ALTER TABLE MODULO_PRE_CADASTRO ADD COLUMN ID_INSTITUICAO BIGINT;

ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_INSTITUICAO)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE MODULO_PRE_CADASTRO ADD COLUMN ID_DRE_CEFAI BIGINT;

ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_DRE_CEFAI)
	REFERENCES DRE_CEFAI (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE MODULO_PRE_CADASTRO ADD COLUMN ID_DIRETORIA_ENSINO BIGINT;

ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_DIRETORIA_ENSINO)
	REFERENCES DIRETORIA_ENSINO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;