ALTER TABLE ESPERA ADD COLUMN ID_PROFISSIONAL_SOLICITADO_POR BIGINT;
ALTER TABLE ESPERA
	ADD FOREIGN KEY (ID_PROFISSIONAL_SOLICITADO_POR)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;