CREATE TABLE ATENDIMENTO_COMUNIDADE
(
	ID BIGSERIAL NOT NULL,
	ID_PRE_CADASTRO BIGINT NOT NULL,
	ID_TIPO_VINCULO BIGINT NOT NULL,
	ID_INFORMACAO_ATENDIMENTO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE ATENDIMENTO_INDIVIDUAL ADD COLUMN PARTICIPACAO VARCHAR(50);

CREATE TABLE ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_COMUNIDADE
(
	ID_ATENDIMENTO_INDIVIDUAL BIGINT NOT NULL,
	ID_ATENDIMENTO_COMUNIDADE BIGINT NOT NULL
) WITHOUT OIDS;

CREATE TABLE TIPO_VINCULO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_COMUNIDADE
	ADD FOREIGN KEY (ID_ATENDIMENTO_COMUNIDADE)
	REFERENCES ATENDIMENTO_COMUNIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_COMUNIDADE
	ADD FOREIGN KEY (ID_ATENDIMENTO_INDIVIDUAL)
	REFERENCES ATENDIMENTO_INDIVIDUAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ATENDIMENTO_COMUNIDADE
	ADD FOREIGN KEY (ID_INFORMACAO_ATENDIMENTO)
	REFERENCES INFORMACAO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ATENDIMENTO_COMUNIDADE
	ADD FOREIGN KEY (ID_PRE_CADASTRO)
	REFERENCES PRE_CADASTRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ATENDIMENTO_COMUNIDADE
	ADD FOREIGN KEY (ID_TIPO_VINCULO)
	REFERENCES TIPO_VINCULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

insert into tipo_vinculo(descricao)values('Fisioterapeuta');	
insert into tipo_vinculo(descricao)values('Fonoaudiólogo');	
insert into tipo_vinculo(descricao)values('Terapeuta Ocupacional');	
insert into tipo_vinculo(descricao)values('Professor');	 
insert into tipo_vinculo(descricao)values('Pedagogo');	
insert into tipo_vinculo(descricao)values('Psicopedagogo');	
insert into tipo_vinculo(descricao)values('Psicólogo');	
insert into tipo_vinculo(descricao)values('Assitente Social');
insert into tipo_vinculo(descricao)values('Representante de Instituição de Ensino');
insert into tipo_vinculo(descricao)values('Representante de Empresa');
insert into tipo_vinculo(descricao)values('Representante de Instituição');
insert into tipo_vinculo(descricao)values('Particular');