insert into modulo (id, nome)values(102, 'Mobiliários adaptados');
insert into modulo (id, nome)values(103, 'Recursos adaptados');
insert into modulo (id, nome)values(104, 'Brinquedos adaptados');
insert into descricao_tipo_atendimento(id, id_tipo_atendimento, nome, sigla, descricao) values (58, 5, 'Centro de Tecnologia Adaptada', 'CTA', '');
insert into descricao_tipo_atendimento_modulo(id_descricao_tipo_atendimento, id_modulo) values(58, 102);
insert into descricao_tipo_atendimento_modulo(id_descricao_tipo_atendimento, id_modulo) values(58, 103);
insert into descricao_tipo_atendimento_modulo(id_descricao_tipo_atendimento, id_modulo) values(58, 104);
insert into tipo_atendimento_descricao_tipo_atendimento(id_tipo_atendimento, id_descricao_tipo_atendimento)values(5, 58);
insert into nome_grupo(id, nome)values(66,'CTA');
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(58, 66);
insert into descricao_tipo_atendimento_setor(id_descricao_tipo_atendimento, id_setor)values(58, 'PROCEJA');
insert into descricao_tipo_atendimento_setor(id_descricao_tipo_atendimento, id_setor)values(58, 'CTO');