CREATE TABLE ETIOLOGIA
(
	ID BIGSERIAL NOT NULL,
	CID VARCHAR(4) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE PERIODO_DEFICIENCIA_ETIOLOGIA
(
	ID_ETIOLOGIA BIGINT NOT NULL,
	ID_PERIODO_DEFICIENCIA BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE ETIOLOGIA
	ADD FOREIGN KEY (CID)
	REFERENCES CID10 (CID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE PERIODO_DEFICIENCIA_ETIOLOGIA
	ADD FOREIGN KEY (ID_ETIOLOGIA)
	REFERENCES ETIOLOGIA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE DEFICIENCIA ADD COLUMN ETIOLOGIA_OBRIGATORIO BOOLEAN DEFAULT 'false' NOT NULL;

UPDATE DEFICIENCIA set etiologia_obrigatorio = true where id in (4, 5, 11);