CREATE TABLE MODULO_PERIODO_PROFISSIONAL_VINCULO
(
	ID_MODULO_PERIODO BIGINT NOT NULL,
	ID_PROFISSIONAL_VINCULO BIGINT NOT NULL
) WITHOUT OIDS;

CREATE TABLE PROFISSIONAL_VINCULO
(
	ID BIGSERIAL NOT NULL,
	ID_PROFISSIONAL BIGINT NOT NULL,
	PARTICIPANTE BOOLEAN DEFAULT 'FALSE',
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE MODULO_PERIODO_PROFISSIONAL_VINCULO
	ADD FOREIGN KEY (ID_MODULO_PERIODO)
	REFERENCES MODULO_PERIODO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE MODULO_PERIODO_PROFISSIONAL_VINCULO
	ADD FOREIGN KEY (ID_PROFISSIONAL_VINCULO)
	REFERENCES PROFISSIONAL_VINCULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

DROP TABLE IF EXISTS modulo_periodo_profissional;

