insert into profissional(nome, habilitado, voluntario, profissional)values('FERNANDO JOSE DE LIMA', true, true, true); 
insert into profissional(nome, habilitado, voluntario, profissional)values('LUIZ CARLOS ROTATORI', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('ELAINE GISELE DA SILVA SOUSA', true, true, true); 
insert into profissional(nome, habilitado, voluntario, profissional)values('FRANCISCA MARINES BEZERRA DA SILVA', true, true, true); 
insert into profissional(nome, habilitado, voluntario, profissional)values('RITA PEREIRA DA SILVA', true, true, true); 
insert into profissional(nome, habilitado, voluntario, profissional)values('ROSALIA MARIA RIBEIRO', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('INES MARIA DE SOUZA', true, true, true); 
insert into profissional(nome, habilitado, voluntario, profissional)values('TERESA MARIA DE JESUS', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('MARINES MARIANO DA SILVA', true, true, true); 
insert into profissional(nome, habilitado, voluntario, profissional)values('ALEXANDRA MARTINS DE MELO', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('FRANCISCO HASHIMOTO', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('SAMANTHA CZYZYNIEWSKI DA SILVA', true, true, true); 
insert into profissional(nome, habilitado, voluntario, profissional)values('VINICIUS DE MORAES OLIVEIRA', true, true, true); 
insert into profissional(nome, habilitado, voluntario, profissional)values('JULIANA APARECIDA FERREIRA ROCCO', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('ROSANGELA CLEMENTINO VALTNER', true, true, true); 