ALTER TABLE pendencia ADD COLUMN ID_GRUPO BIGINT;
ALTER TABLE pendencia ADD COLUMN ID_MODULO_PERIODO BIGINT;
ALTER TABLE pendencia ADD COLUMN DATA DATE;
ALTER TABLE pendencia ADD COLUMN OBS VARCHAR(20000);
ALTER TABLE pendencia ADD COLUMN HORA_INICIO TIME;
ALTER TABLE pendencia ADD COLUMN HORA_TERMINO TIME;

ALTER TABLE PENDENCIA
	ADD FOREIGN KEY (ID_MODULO_PERIODO)
	REFERENCES MODULO_PERIODO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE PENDENCIA
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;