CREATE TABLE ARQUIVO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(1000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE ATENDIMENTO_GRUPO_ARQUIVO
(
	ID_ARQUIVO BIGINT NOT NULL,
	ID_ATENDIMENTO_GRUPO BIGINT NOT NULL
) WITHOUT OIDS;

CREATE TABLE ATENDIMENTO_INDIVIDUAL_ARQUIVO
(
	ID_ARQUIVO BIGINT NOT NULL,
	ID_ATENDIMENTO_INDIVIDUAL BIGINT NOT NULL
) WITHOUT OIDS;

CREATE TABLE ATENDIMENTO_USUARIO_ARQUIVO
(
	ID_ARQUIVO BIGINT NOT NULL,
	ID_ATENDIMENTO_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE ATENDIMENTO_GRUPO_ARQUIVO
	ADD FOREIGN KEY (ID_ARQUIVO)
	REFERENCES ARQUIVO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ATENDIMENTO_INDIVIDUAL_ARQUIVO
	ADD FOREIGN KEY (ID_ARQUIVO)
	REFERENCES ARQUIVO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ATENDIMENTO_USUARIO_ARQUIVO
	ADD FOREIGN KEY (ID_ARQUIVO)
	REFERENCES ARQUIVO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ATENDIMENTO_GRUPO_ARQUIVO
	ADD FOREIGN KEY (ID_ATENDIMENTO_GRUPO)
	REFERENCES ATENDIMENTO_GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ATENDIMENTO_INDIVIDUAL_ARQUIVO
	ADD FOREIGN KEY (ID_ATENDIMENTO_INDIVIDUAL)
	REFERENCES ATENDIMENTO_INDIVIDUAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ATENDIMENTO_USUARIO_ARQUIVO
	ADD FOREIGN KEY (ID_ATENDIMENTO_USUARIO)
	REFERENCES ATENDIMENTO_USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;