package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaEditarEducacional;
import br.laramara.ti.sislaraclient.utilitarios.JOptionPanePersonalizado;
import br.laramara.ti.sislaracommons.dtos.escola.InformacaoEducacionalDTO;
import javax.swing.JDialog;

public class TelaEditarEducacional extends javax.swing.JDialog {

    /** Creates new form TelaEditarEducacional */
    public TelaEditarEducacional(JDialog parent, InformacaoEducacionalDTO informacaoEducacionalDto) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        controlador = new ControladorTelaEditarEducacional(this, informacaoEducacionalDto, jcbInstituicaoEnsino, jcbEscolaridade, jcbSerie, jcbSituacao, jcbPeriodo, jftDataReferencia, jcbAreaFormacao, jtfProfessor);
        controlador.inicializarCombosComDependencia();
        controlador.abrirTela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jpaEditarEducacional = new javax.swing.JPanel();
        jpaTitulo = new javax.swing.JPanel();
        jlaTitulo = new javax.swing.JLabel();
        jbuFecharTitulo = new javax.swing.JButton();
        jlaInstituicaoEnsino = new javax.swing.JLabel();
        jcbInstituicaoEnsino = new javax.swing.JComboBox();
        jbuNovaInstituicao = new javax.swing.JButton();
        jlaEscolaridade = new javax.swing.JLabel();
        jcbEscolaridade = new javax.swing.JComboBox();
        jlaSerie = new javax.swing.JLabel();
        jcbSerie = new javax.swing.JComboBox();
        jlaSituacao = new javax.swing.JLabel();
        jcbSituacao = new javax.swing.JComboBox();
        jlaPeriodo = new javax.swing.JLabel();
        jcbPeriodo = new javax.swing.JComboBox();
        jlaProfessor = new javax.swing.JLabel();
        jtfProfessor = new javax.swing.JTextField();
        jlaAreaFormacao = new javax.swing.JLabel();
        jcbAreaFormacao = new javax.swing.JComboBox();
        jbuSalvar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();
        jlaDataReferencia = new javax.swing.JLabel();
        jftDataReferencia = new javax.swing.JFormattedTextField();
        jbuDataReferencia = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(TelaEditarEducacional.class);
        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setUndecorated(true);

        jpaEditarEducacional.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jpaEditarEducacional.border.lineColor"))); // NOI18N
        jpaEditarEducacional.setName("jpaEditarEducacional"); // NOI18N
        jpaEditarEducacional.setLayout(null);

        jpaTitulo.setBackground(resourceMap.getColor("jpaTitulo.background")); // NOI18N
        jpaTitulo.setName("jpaTitulo"); // NOI18N

        jlaTitulo.setFont(resourceMap.getFont("jlaTitulo.font")); // NOI18N
        jlaTitulo.setForeground(resourceMap.getColor("jlaTitulo.foreground")); // NOI18N
        jlaTitulo.setText(resourceMap.getString("jlaTitulo.text")); // NOI18N
        jlaTitulo.setName("jlaTitulo"); // NOI18N

        jbuFecharTitulo.setBackground(resourceMap.getColor("jbuFecharTitulo.background")); // NOI18N
        jbuFecharTitulo.setIcon(resourceMap.getIcon("jbuFecharTitulo.icon")); // NOI18N
        jbuFecharTitulo.setText(resourceMap.getString("jbuFecharTitulo.text")); // NOI18N
        jbuFecharTitulo.setBorder(null);
        jbuFecharTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFecharTitulo.setFocusable(false);
        jbuFecharTitulo.setName("jbuFecharTitulo"); // NOI18N
        jbuFecharTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharTituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaTituloLayout = new javax.swing.GroupLayout(jpaTitulo);
        jpaTitulo.setLayout(jpaTituloLayout);
        jpaTituloLayout.setHorizontalGroup(
            jpaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 752, Short.MAX_VALUE)
                .addComponent(jbuFecharTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpaTituloLayout.setVerticalGroup(
            jpaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaTituloLayout.createSequentialGroup()
                .addGroup(jpaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuFecharTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpaEditarEducacional.add(jpaTitulo);
        jpaTitulo.setBounds(1, 1, 1024, 26);

        jlaInstituicaoEnsino.setFont(resourceMap.getFont("jlaInstituicaoEnsino.font")); // NOI18N
        jlaInstituicaoEnsino.setText(resourceMap.getString("jlaInstituicaoEnsino.text")); // NOI18N
        jlaInstituicaoEnsino.setToolTipText(resourceMap.getString("jlaInstituicaoEnsino.toolTipText")); // NOI18N
        jlaInstituicaoEnsino.setName("jlaInstituicaoEnsino"); // NOI18N
        jpaEditarEducacional.add(jlaInstituicaoEnsino);
        jlaInstituicaoEnsino.setBounds(10, 40, 180, 17);

        jcbInstituicaoEnsino.setFont(resourceMap.getFont("jcbInstituicaoEnsino.font")); // NOI18N
        jcbInstituicaoEnsino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbInstituicaoEnsino.setName("jcbInstituicaoEnsino"); // NOI18N
        jcbInstituicaoEnsino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbInstituicaoEnsinoActionPerformed(evt);
            }
        });
        jpaEditarEducacional.add(jcbInstituicaoEnsino);
        jcbInstituicaoEnsino.setBounds(10, 60, 850, 25);
        jcbInstituicaoEnsino.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbInstituicaoEnsino.AccessibleContext.accessibleName")); // NOI18N

        jbuNovaInstituicao.setFont(resourceMap.getFont("jbuNovaInstituicao.font")); // NOI18N
        jbuNovaInstituicao.setIcon(resourceMap.getIcon("jbuNovaInstituicao.icon")); // NOI18N
        jbuNovaInstituicao.setMnemonic('N');
        jbuNovaInstituicao.setText(resourceMap.getString("jbuNovaInstituicao.text")); // NOI18N
        jbuNovaInstituicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuNovaInstituicao.setName("jbuNovaInstituicao"); // NOI18N
        jbuNovaInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuNovaInstituicaoActionPerformed(evt);
            }
        });
        jpaEditarEducacional.add(jbuNovaInstituicao);
        jbuNovaInstituicao.setBounds(870, 60, 130, 33);
        jbuNovaInstituicao.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuNovaInstituicao.AccessibleContext.accessibleName")); // NOI18N

        jlaEscolaridade.setFont(resourceMap.getFont("jlaEscolaridade.font")); // NOI18N
        jlaEscolaridade.setText(resourceMap.getString("jlaEscolaridade.text")); // NOI18N
        jlaEscolaridade.setName("jlaEscolaridade"); // NOI18N
        jpaEditarEducacional.add(jlaEscolaridade);
        jlaEscolaridade.setBounds(10, 90, 160, 17);

        jcbEscolaridade.setFont(resourceMap.getFont("jcbSituacao.font")); // NOI18N
        jcbEscolaridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbEscolaridade.setName("jcbEscolaridade"); // NOI18N
        jcbEscolaridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEscolaridadeActionPerformed(evt);
            }
        });
        jpaEditarEducacional.add(jcbEscolaridade);
        jcbEscolaridade.setBounds(10, 110, 206, 25);
        jcbEscolaridade.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbEscolaridade.AccessibleContext.accessibleName")); // NOI18N

        jlaSerie.setFont(resourceMap.getFont("jlaEscolaridade.font")); // NOI18N
        jlaSerie.setText(resourceMap.getString("jlaSerie.text")); // NOI18N
        jlaSerie.setName("jlaSerie"); // NOI18N
        jpaEditarEducacional.add(jlaSerie);
        jlaSerie.setBounds(10, 140, 100, 17);

        jcbSerie.setFont(resourceMap.getFont("jcbSituacao.font")); // NOI18N
        jcbSerie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbSerie.setName("jcbSerie"); // NOI18N
        jpaEditarEducacional.add(jcbSerie);
        jcbSerie.setBounds(10, 160, 206, 25);
        jcbSerie.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbSerie.AccessibleContext.accessibleName")); // NOI18N

        jlaSituacao.setFont(resourceMap.getFont("jlaEscolaridade.font")); // NOI18N
        jlaSituacao.setText(resourceMap.getString("jlaSituacao.text")); // NOI18N
        jlaSituacao.setName("jlaSituacao"); // NOI18N
        jpaEditarEducacional.add(jlaSituacao);
        jlaSituacao.setBounds(10, 190, 110, 17);

        jcbSituacao.setFont(resourceMap.getFont("jcbSituacao.font")); // NOI18N
        jcbSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbSituacao.setName("jcbSituacao"); // NOI18N
        jpaEditarEducacional.add(jcbSituacao);
        jcbSituacao.setBounds(10, 210, 206, 25);
        jcbSituacao.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbSituacao.AccessibleContext.accessibleName")); // NOI18N

        jlaPeriodo.setFont(resourceMap.getFont("jlaEscolaridade.font")); // NOI18N
        jlaPeriodo.setText(resourceMap.getString("jlaPeriodo.text")); // NOI18N
        jlaPeriodo.setName("jlaPeriodo"); // NOI18N
        jpaEditarEducacional.add(jlaPeriodo);
        jlaPeriodo.setBounds(10, 240, 150, 17);

        jcbPeriodo.setFont(resourceMap.getFont("jcbSituacao.font")); // NOI18N
        jcbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbPeriodo.setName("jcbPeriodo"); // NOI18N
        jpaEditarEducacional.add(jcbPeriodo);
        jcbPeriodo.setBounds(10, 260, 206, 25);
        jcbPeriodo.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbPeriodo.AccessibleContext.accessibleName")); // NOI18N

        jlaProfessor.setFont(resourceMap.getFont("jlaEscolaridade.font")); // NOI18N
        jlaProfessor.setText(resourceMap.getString("jlaProfessor.text")); // NOI18N
        jlaProfessor.setName("jlaProfessor"); // NOI18N
        jpaEditarEducacional.add(jlaProfessor);
        jlaProfessor.setBounds(10, 390, 92, 17);

        jtfProfessor.setFont(resourceMap.getFont("jtfProfessor.font")); // NOI18N
        jtfProfessor.setName("jtfProfessor"); // NOI18N
        jpaEditarEducacional.add(jtfProfessor);
        jtfProfessor.setBounds(10, 410, 406, 23);
        jtfProfessor.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfProfessor.AccessibleContext.accessibleName")); // NOI18N

        jlaAreaFormacao.setFont(resourceMap.getFont("jlaAreaFormacao.font")); // NOI18N
        jlaAreaFormacao.setText(resourceMap.getString("jlaAreaFormacao.text")); // NOI18N
        jlaAreaFormacao.setName("jlaAreaFormacao"); // NOI18N
        jpaEditarEducacional.add(jlaAreaFormacao);
        jlaAreaFormacao.setBounds(10, 340, 140, 17);

        jcbAreaFormacao.setFont(resourceMap.getFont("jcbAreaFormacao.font")); // NOI18N
        jcbAreaFormacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbAreaFormacao.setName("jcbAreaFormacao"); // NOI18N
        jpaEditarEducacional.add(jcbAreaFormacao);
        jcbAreaFormacao.setBounds(10, 360, 410, 25);

        jbuSalvar.setFont(resourceMap.getFont("jbuSalvar.font")); // NOI18N
        jbuSalvar.setIcon(resourceMap.getIcon("jbuSalvar.icon")); // NOI18N
        jbuSalvar.setMnemonic('s');
        jbuSalvar.setText(resourceMap.getString("jbuSalvar.text")); // NOI18N
        jbuSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSalvar.setName("jbuSalvar"); // NOI18N
        jbuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSalvarActionPerformed(evt);
            }
        });
        jpaEditarEducacional.add(jbuSalvar);
        jbuSalvar.setBounds(10, 670, 109, 33);

        jbuFechar.setFont(resourceMap.getFont("jbuFechar.font")); // NOI18N
        jbuFechar.setIcon(resourceMap.getIcon("jbuFechar.icon")); // NOI18N
        jbuFechar.setMnemonic('f');
        jbuFechar.setText(resourceMap.getString("jbuFechar.text")); // NOI18N
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });
        jpaEditarEducacional.add(jbuFechar);
        jbuFechar.setBounds(900, 670, 113, 33);

        jlaDataReferencia.setFont(resourceMap.getFont("jlaDataReferencia.font")); // NOI18N
        jlaDataReferencia.setText(resourceMap.getString("jlaDataReferencia.text")); // NOI18N
        jlaDataReferencia.setName("jlaDataReferencia"); // NOI18N
        jpaEditarEducacional.add(jlaDataReferencia);
        jlaDataReferencia.setBounds(10, 290, 150, 17);

        try {
            jftDataReferencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataReferencia.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftDataReferencia.setFont(resourceMap.getFont("jftDataReferencia.font")); // NOI18N
        jftDataReferencia.setName("jftDataReferencia"); // NOI18N
        jpaEditarEducacional.add(jftDataReferencia);
        jftDataReferencia.setBounds(10, 310, 100, 23);

        jbuDataReferencia.setIcon(resourceMap.getIcon("jbuDataReferencia.icon")); // NOI18N
        jbuDataReferencia.setText(resourceMap.getString("jbuDataReferencia.text")); // NOI18N
        jbuDataReferencia.setBorder(null);
        jbuDataReferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuDataReferencia.setName("jbuDataReferencia"); // NOI18N
        jbuDataReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuDataReferenciaActionPerformed(evt);
            }
        });
        jpaEditarEducacional.add(jbuDataReferencia);
        jbuDataReferencia.setBounds(110, 310, 30, 25);
        jbuDataReferencia.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuDataReferencia.AccessibleContext.accessibleName")); // NOI18N
        jbuDataReferencia.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jbuDataReferencia.AccessibleContext.accessibleDescription")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarEducacional, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarEducacional, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuFecharTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharTituloActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharTituloActionPerformed

    private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharActionPerformed

    private void jbuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSalvarActionPerformed
        controlador.salvar();
    }//GEN-LAST:event_jbuSalvarActionPerformed

    private void jbuNovaInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuNovaInstituicaoActionPerformed
        controlador.adicionarInstituicao();
    }//GEN-LAST:event_jbuNovaInstituicaoActionPerformed

    private void jcbInstituicaoEnsinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbInstituicaoEnsinoActionPerformed
        controlador.inicializarEscolaridade();
    }//GEN-LAST:event_jcbInstituicaoEnsinoActionPerformed

    private void jcbEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEscolaridadeActionPerformed
        controlador.inicializarSerie();
    }//GEN-LAST:event_jcbEscolaridadeActionPerformed

    private void jbuDataReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuDataReferenciaActionPerformed
        JOptionPanePersonalizado.mostrarTelaSelecionarData(this, jftDataReferencia);
    }//GEN-LAST:event_jbuDataReferenciaActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbuDataReferencia;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuFecharTitulo;
    private javax.swing.JButton jbuNovaInstituicao;
    private javax.swing.JButton jbuSalvar;
    private javax.swing.JComboBox jcbAreaFormacao;
    private javax.swing.JComboBox jcbEscolaridade;
    private javax.swing.JComboBox jcbInstituicaoEnsino;
    private javax.swing.JComboBox jcbPeriodo;
    private javax.swing.JComboBox jcbSerie;
    private javax.swing.JComboBox jcbSituacao;
    private javax.swing.JFormattedTextField jftDataReferencia;
    private javax.swing.JLabel jlaAreaFormacao;
    private javax.swing.JLabel jlaDataReferencia;
    private javax.swing.JLabel jlaEscolaridade;
    private javax.swing.JLabel jlaInstituicaoEnsino;
    private javax.swing.JLabel jlaPeriodo;
    private javax.swing.JLabel jlaProfessor;
    private javax.swing.JLabel jlaSerie;
    private javax.swing.JLabel jlaSituacao;
    private javax.swing.JLabel jlaTitulo;
    private javax.swing.JPanel jpaEditarEducacional;
    private javax.swing.JPanel jpaTitulo;
    private javax.swing.JTextField jtfProfessor;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaEditarEducacional controlador;
}
