package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaSolicitacaoRelatorioEditar;
import br.laramara.ti.sislaraclient.infra.PermissaoDeTelas;
import br.laramara.ti.sislaracommons.dtos.solicitacao.SolicitacaoRelatorioDTO;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

public class TelaSolicitacaoRelatorioEditar extends javax.swing.JDialog {

    /**
     * Creates new form TelaSolicitacaoRelatorioEditar
     */
    public TelaSolicitacaoRelatorioEditar(JDialog telaPai, SolicitacaoRelatorioDTO solicitacaoRelatorioDto) {
        super(telaPai, true);
        initComponents();
        setLocationRelativeTo(telaPai);
        controlador = new ControladorTelaSolicitacaoRelatorioEditar(this, solicitacaoRelatorioDto, jtfNomeSolicitante, jtfRgSolicitante, jftProntuario, jtfNomeUsuario, jcbTipoRelatorio, jliFinalidadesRelatorios, jcbElaborador, jchEnviarViaCorreio);
        controlador.abrirSomenteSeHouverPermissao(PermissaoDeTelas.SOLICITACAO_RELATORIO_TELA_EDICAO_VISUALIZAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaTelaSolicitacaoRelatorioEditar = new javax.swing.JPanel();
        jpaTitulo = new javax.swing.JPanel();
        jlaTitulo = new javax.swing.JLabel();
        jbuFecharTitulo = new javax.swing.JButton();
        jftProntuario = new javax.swing.JFormattedTextField();
        jlaProntuario = new javax.swing.JLabel();
        jtfNomeUsuario = new javax.swing.JTextField();
        jlaNomeUsuario = new javax.swing.JLabel();
        jbuUtilizarUsuario = new javax.swing.JButton();
        jlaNomeSolicitante = new javax.swing.JLabel();
        jtfNomeSolicitante = new javax.swing.JTextField();
        jlaRgSolicitante = new javax.swing.JLabel();
        jtfRgSolicitante = new javax.swing.JTextField();
        jbuSalvar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();
        jlaTipoRelatorio = new javax.swing.JLabel();
        jcbTipoRelatorio = new javax.swing.JComboBox();
        jbuAdicionar = new javax.swing.JButton();
        jlaFinalidadesRelatorios = new javax.swing.JLabel();
        jcpFinalidadesRelatorios = new javax.swing.JScrollPane();
        jliFinalidadesRelatorios = new javax.swing.JList();
        jbuRemover = new javax.swing.JButton();
        jlaElaborador = new javax.swing.JLabel();
        jcbElaborador = new javax.swing.JComboBox();
        jchEnviarViaCorreio = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setUndecorated(true);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(TelaSolicitacaoRelatorioEditar.class);
        jpaTelaSolicitacaoRelatorioEditar.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jpaTelaSolicitacaoRelatorioEditar.border.lineColor"))); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.setName("jpaTelaSolicitacaoRelatorioEditar"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.setLayout(null);

        jpaTitulo.setBackground(resourceMap.getColor("jpaTitulo.background")); // NOI18N
        jpaTitulo.setName("jpaTitulo"); // NOI18N
        jpaTitulo.setLayout(null);

        jlaTitulo.setFont(resourceMap.getFont("jlaTitulo.font")); // NOI18N
        jlaTitulo.setForeground(resourceMap.getColor("jlaTitulo.foreground")); // NOI18N
        jlaTitulo.setText(resourceMap.getString("jlaTitulo.text")); // NOI18N
        jlaTitulo.setName("jlaTitulo"); // NOI18N
        jpaTitulo.add(jlaTitulo);
        jlaTitulo.setBounds(10, 0, 300, 26);

        jbuFecharTitulo.setBackground(resourceMap.getColor("jbuFecharTitulo.background")); // NOI18N
        jbuFecharTitulo.setIcon(resourceMap.getIcon("jbuFecharTitulo.icon")); // NOI18N
        jbuFecharTitulo.setBorder(null);
        jbuFecharTitulo.setFocusable(false);
        jbuFecharTitulo.setName("jbuFecharTitulo"); // NOI18N
        jbuFecharTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharTituloActionPerformed(evt);
            }
        });
        jpaTitulo.add(jbuFecharTitulo);
        jbuFecharTitulo.setBounds(776, 0, 25, 25);

        jpaTelaSolicitacaoRelatorioEditar.add(jpaTitulo);
        jpaTitulo.setBounds(1, 1, 800, 26);

        try {
            jftProntuario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftProntuario.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftProntuario.setFont(resourceMap.getFont("jftProntuario.font")); // NOI18N
        jftProntuario.setName("jftProntuario"); // NOI18N
        jftProntuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftProntuarioFocusLost(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioEditar.add(jftProntuario);
        jftProntuario.setBounds(10, 100, 80, 22);

        jlaProntuario.setFont(resourceMap.getFont("jlaProntuario.font")); // NOI18N
        jlaProntuario.setText(resourceMap.getString("jlaProntuario.text")); // NOI18N
        jlaProntuario.setName("jlaProntuario"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jlaProntuario);
        jlaProntuario.setBounds(10, 80, 80, 20);

        jtfNomeUsuario.setEditable(false);
        jtfNomeUsuario.setFont(resourceMap.getFont("jtfNomeUsuario.font")); // NOI18N
        jtfNomeUsuario.setName("jtfNomeUsuario"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jtfNomeUsuario);
        jtfNomeUsuario.setBounds(100, 100, 550, 22);

        jlaNomeUsuario.setFont(resourceMap.getFont("jlaProntuario.font")); // NOI18N
        jlaNomeUsuario.setText(resourceMap.getString("jlaNomeUsuario.text")); // NOI18N
        jlaNomeUsuario.setName("jlaNomeUsuario"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jlaNomeUsuario);
        jlaNomeUsuario.setBounds(100, 80, 160, 20);

        jbuUtilizarUsuario.setFont(resourceMap.getFont("jbuUtilizarUsuario.font")); // NOI18N
        jbuUtilizarUsuario.setIcon(resourceMap.getIcon("jbuUtilizarUsuario.icon")); // NOI18N
        jbuUtilizarUsuario.setMnemonic('U');
        jbuUtilizarUsuario.setText(resourceMap.getString("jbuUtilizarUsuario.text")); // NOI18N
        jbuUtilizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuUtilizarUsuario.setName("jbuUtilizarUsuario"); // NOI18N
        jbuUtilizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuUtilizarUsuarioActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioEditar.add(jbuUtilizarUsuario);
        jbuUtilizarUsuario.setBounds(660, 100, 130, 35);

        jlaNomeSolicitante.setFont(resourceMap.getFont("jlaNomeSolicitante.font")); // NOI18N
        jlaNomeSolicitante.setText(resourceMap.getString("jlaNomeSolicitante.text")); // NOI18N
        jlaNomeSolicitante.setName("jlaNomeSolicitante"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jlaNomeSolicitante);
        jlaNomeSolicitante.setBounds(10, 30, 190, 17);

        jtfNomeSolicitante.setFont(resourceMap.getFont("jtfNomeSolicitante.font")); // NOI18N
        jtfNomeSolicitante.setText(resourceMap.getString("jtfNomeSolicitante.text")); // NOI18N
        jtfNomeSolicitante.setName("jtfNomeSolicitante"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jtfNomeSolicitante);
        jtfNomeSolicitante.setBounds(10, 50, 510, 23);

        jlaRgSolicitante.setFont(resourceMap.getFont("jlaRgSolicitante.font")); // NOI18N
        jlaRgSolicitante.setText(resourceMap.getString("jlaRgSolicitante.text")); // NOI18N
        jlaRgSolicitante.setName("jlaRgSolicitante"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jlaRgSolicitante);
        jlaRgSolicitante.setBounds(530, 30, 140, 17);

        jtfRgSolicitante.setFont(resourceMap.getFont("jtfRgSolicitante.font")); // NOI18N
        jtfRgSolicitante.setText(resourceMap.getString("jtfRgSolicitante.text")); // NOI18N
        jtfRgSolicitante.setName("jtfRgSolicitante"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jtfRgSolicitante);
        jtfRgSolicitante.setBounds(530, 50, 120, 23);

        jbuSalvar.setFont(resourceMap.getFont("jbuSalvar.font")); // NOI18N
        jbuSalvar.setIcon(resourceMap.getIcon("jbuSalvar.icon")); // NOI18N
        jbuSalvar.setMnemonic('S');
        jbuSalvar.setText(resourceMap.getString("jbuSalvar.text")); // NOI18N
        jbuSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSalvar.setName("jbuSalvar"); // NOI18N
        jbuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSalvarActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioEditar.add(jbuSalvar);
        jbuSalvar.setBounds(10, 480, 120, 33);

        jbuFechar.setFont(resourceMap.getFont("jbuFechar.font")); // NOI18N
        jbuFechar.setIcon(resourceMap.getIcon("jbuFechar.icon")); // NOI18N
        jbuFechar.setMnemonic('F');
        jbuFechar.setText(resourceMap.getString("jbuFechar.text")); // NOI18N
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioEditar.add(jbuFechar);
        jbuFechar.setBounds(670, 480, 120, 33);

        jlaTipoRelatorio.setFont(resourceMap.getFont("jlaTipoRelatorio.font")); // NOI18N
        jlaTipoRelatorio.setText(resourceMap.getString("jlaTipoRelatorio.text")); // NOI18N
        jlaTipoRelatorio.setName("jlaTipoRelatorio"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jlaTipoRelatorio);
        jlaTipoRelatorio.setBounds(10, 130, 250, 17);

        jcbTipoRelatorio.setFont(resourceMap.getFont("jcbTipoRelatorio.font")); // NOI18N
        jcbTipoRelatorio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbTipoRelatorio.setName("jcbTipoRelatorio"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jcbTipoRelatorio);
        jcbTipoRelatorio.setBounds(10, 150, 450, 25);
        jcbTipoRelatorio.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbTipoRelatorio.AccessibleContext.accessibleName")); // NOI18N
        jcbTipoRelatorio.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jcbTipoRelatorio.AccessibleContext.accessibleDescription")); // NOI18N

        jbuAdicionar.setFont(resourceMap.getFont("jbuAdicionar.font")); // NOI18N
        jbuAdicionar.setIcon(resourceMap.getIcon("jbuAdicionar.icon")); // NOI18N
        jbuAdicionar.setMnemonic('A');
        jbuAdicionar.setText(resourceMap.getString("jbuAdicionar.text")); // NOI18N
        jbuAdicionar.setName("jbuAdicionar"); // NOI18N
        jbuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioEditar.add(jbuAdicionar);
        jbuAdicionar.setBounds(470, 150, 140, 33);

        jlaFinalidadesRelatorios.setFont(resourceMap.getFont("jlaFinalidadesRelatorios.font")); // NOI18N
        jlaFinalidadesRelatorios.setText(resourceMap.getString("jlaFinalidadesRelatorios.text")); // NOI18N
        jlaFinalidadesRelatorios.setName("jlaFinalidadesRelatorios"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jlaFinalidadesRelatorios);
        jlaFinalidadesRelatorios.setBounds(10, 190, 350, 17);

        jcpFinalidadesRelatorios.setName("jcpFinalidadesRelatorios"); // NOI18N

        jliFinalidadesRelatorios.setFont(resourceMap.getFont("jliFinalidadesRelatorios.font")); // NOI18N
        jliFinalidadesRelatorios.setModel(new DefaultListModel());
        jliFinalidadesRelatorios.setName("jliFinalidadesRelatorios"); // NOI18N
        jcpFinalidadesRelatorios.setViewportView(jliFinalidadesRelatorios);
        jliFinalidadesRelatorios.getAccessibleContext().setAccessibleName(resourceMap.getString("jliFinalidadesRelatorios.AccessibleContext.accessibleName")); // NOI18N

        jpaTelaSolicitacaoRelatorioEditar.add(jcpFinalidadesRelatorios);
        jcpFinalidadesRelatorios.setBounds(10, 210, 450, 200);

        jbuRemover.setFont(resourceMap.getFont("jbuRemover.font")); // NOI18N
        jbuRemover.setIcon(resourceMap.getIcon("jbuRemover.icon")); // NOI18N
        jbuRemover.setMnemonic('r');
        jbuRemover.setText(resourceMap.getString("jbuRemover.text")); // NOI18N
        jbuRemover.setName("jbuRemover"); // NOI18N
        jbuRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioEditar.add(jbuRemover);
        jbuRemover.setBounds(470, 210, 140, 30);

        jlaElaborador.setFont(resourceMap.getFont("jlaElaborador.font")); // NOI18N
        jlaElaborador.setText(resourceMap.getString("jlaElaborador.text")); // NOI18N
        jlaElaborador.setName("jlaElaborador"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jlaElaborador);
        jlaElaborador.setBounds(10, 420, 150, 17);

        jcbElaborador.setFont(resourceMap.getFont("jcbElaborador.font")); // NOI18N
        jcbElaborador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbElaborador.setName("jcbElaborador"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jcbElaborador);
        jcbElaborador.setBounds(10, 440, 360, 25);

        jchEnviarViaCorreio.setFont(resourceMap.getFont("jchEnviarViaCorreio.font")); // NOI18N
        jchEnviarViaCorreio.setText(resourceMap.getString("jchEnviarViaCorreio.text")); // NOI18N
        jchEnviarViaCorreio.setName("jchEnviarViaCorreio"); // NOI18N
        jpaTelaSolicitacaoRelatorioEditar.add(jchEnviarViaCorreio);
        jchEnviarViaCorreio.setBounds(380, 440, 170, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaTelaSolicitacaoRelatorioEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaTelaSolicitacaoRelatorioEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuFecharTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharTituloActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharTituloActionPerformed

    private void jftProntuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftProntuarioFocusLost
        controlador.selecionarProntuario();
    }//GEN-LAST:event_jftProntuarioFocusLost

    private void jbuUtilizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuUtilizarUsuarioActionPerformed
        controlador.abrirTelaUtilizarUsuario();
    }//GEN-LAST:event_jbuUtilizarUsuarioActionPerformed

    private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharActionPerformed

    private void jbuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSalvarActionPerformed
        controlador.salvar();
    }//GEN-LAST:event_jbuSalvarActionPerformed

    private void jbuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarActionPerformed
        controlador.adicionarTipoRelatorio();
    }//GEN-LAST:event_jbuAdicionarActionPerformed

    private void jbuRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverActionPerformed
        controlador.removerTipoRelatorioSelecionado();
    }//GEN-LAST:event_jbuRemoverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbuAdicionar;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuFecharTitulo;
    private javax.swing.JButton jbuRemover;
    private javax.swing.JButton jbuSalvar;
    private javax.swing.JButton jbuUtilizarUsuario;
    private javax.swing.JComboBox jcbElaborador;
    private javax.swing.JComboBox jcbTipoRelatorio;
    private javax.swing.JCheckBox jchEnviarViaCorreio;
    private javax.swing.JScrollPane jcpFinalidadesRelatorios;
    private javax.swing.JFormattedTextField jftProntuario;
    private javax.swing.JLabel jlaElaborador;
    private javax.swing.JLabel jlaFinalidadesRelatorios;
    private javax.swing.JLabel jlaNomeSolicitante;
    private javax.swing.JLabel jlaNomeUsuario;
    private javax.swing.JLabel jlaProntuario;
    private javax.swing.JLabel jlaRgSolicitante;
    private javax.swing.JLabel jlaTipoRelatorio;
    private javax.swing.JLabel jlaTitulo;
    private javax.swing.JList jliFinalidadesRelatorios;
    private javax.swing.JPanel jpaTelaSolicitacaoRelatorioEditar;
    private javax.swing.JPanel jpaTitulo;
    private javax.swing.JTextField jtfNomeSolicitante;
    protected javax.swing.JTextField jtfNomeUsuario;
    private javax.swing.JTextField jtfRgSolicitante;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaSolicitacaoRelatorioEditar controlador;
}
