
package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaEditarInstituicao;
import br.laramara.ti.sislaraclient.infra.PermissaoDeTelas;
import br.laramara.ti.sislaracommons.dtos.instituicao.InstituicaoDTO;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

public class TelaEditarInstituicoes extends javax.swing.JDialog {

    /** Creates new form TelaEditarInstituicoes */
    public TelaEditarInstituicoes(JDialog parent, InstituicaoDTO instituicaoDto) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        controlador = new ControladorTelaEditarInstituicao(this, instituicaoDto, jcbTipo, jcbClassificacao, jcbZona, jcbUF, jcbMunicipio, jcbPais, jtfNome, jftCEP, jtfEndereco, jtfNumero, jtfComplemento, jtfBairro, jftRamal, jtfNomeContato, jtfCoordenadorResponsavel, jtfEmail, jcbTipoTelefone, jftTelefone, jliTelefonesAdicionados, jcbNivelEscolar, jliNivelEscolarAdicionados, jcbTipoApoio, jcbTipoEspecialidade, jliTiposEspecialidadeAdicionados, jcbDreCefai, jcbDiretoriaEnsino, jepObservacoes);
        controlador.abrirSomenteSeHouverPermissao(PermissaoDeTelas.INSTITUICAO_TELA_EDICAO_VISUALIZAR);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaEditarInstituicoes = new javax.swing.JPanel();
        jpaSuperior = new javax.swing.JPanel();
        jlabTitulo = new javax.swing.JLabel();
        jbuFecharTitulo = new javax.swing.JButton();
        jpaContatos = new javax.swing.JPanel();
        jlaTelefone = new javax.swing.JLabel();
        jftTelefone = new javax.swing.JFormattedTextField();
        jlaTipoTelefone = new javax.swing.JLabel();
        jcbTipoTelefone = new javax.swing.JComboBox();
        jbuAdicionarTelefone = new javax.swing.JButton();
        jlaTelefonesAdicionados = new javax.swing.JLabel();
        jspTelefonesAdicionados = new javax.swing.JScrollPane();
        jliTelefonesAdicionados = new javax.swing.JList();
        jbuRemoverTelefone = new javax.swing.JButton();
        jftRamal = new javax.swing.JFormattedTextField();
        jlaRamal = new javax.swing.JLabel();
        jlaNomeContato = new javax.swing.JLabel();
        jtfNomeContato = new javax.swing.JTextField();
        jlaEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jpaPrincipal = new javax.swing.JPanel();
        jlaTipo = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox();
        jlaNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlaClassificacao = new javax.swing.JLabel();
        jcbClassificacao = new javax.swing.JComboBox();
        jlaCEP = new javax.swing.JLabel();
        jftCEP = new javax.swing.JFormattedTextField();
        jlaEndereco = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jlaNumero = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jlaComplemento = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jlaPais = new javax.swing.JLabel();
        jcbPais = new javax.swing.JComboBox();
        jlaUF = new javax.swing.JLabel();
        jcbUF = new javax.swing.JComboBox();
        jlaMunicipio = new javax.swing.JLabel();
        jcbMunicipio = new javax.swing.JComboBox();
        jlaZona = new javax.swing.JLabel();
        jcbZona = new javax.swing.JComboBox();
        jlaBairro = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jlaCoordenador = new javax.swing.JLabel();
        jtfCoordenadorResponsavel = new javax.swing.JTextField();
        jlaTipoApoio = new javax.swing.JLabel();
        jcbTipoApoio = new javax.swing.JComboBox();
        jlaTipoEspecialidade = new javax.swing.JLabel();
        jcbTipoEspecialidade = new javax.swing.JComboBox();
        jbuAdicionarTipoSaai = new javax.swing.JButton();
        jlaTiposSaaisAdicionados = new javax.swing.JLabel();
        jspTiposEspecialidadeAdicionados = new javax.swing.JScrollPane();
        jliTiposEspecialidadeAdicionados = new javax.swing.JList();
        jbuRemoverTipoSaai = new javax.swing.JButton();
        jlaObservacoes = new javax.swing.JLabel();
        jspObservacoes = new javax.swing.JScrollPane();
        jepObservacoes = new javax.swing.JEditorPane();
        jlaDreCefai = new javax.swing.JLabel();
        jcbDreCefai = new javax.swing.JComboBox();
        jlaDiretoriaEnsino = new javax.swing.JLabel();
        jcbDiretoriaEnsino = new javax.swing.JComboBox();
        jlaNivelEscolar = new javax.swing.JLabel();
        jcbNivelEscolar = new javax.swing.JComboBox();
        jbuAdicionarNivelEscolar = new javax.swing.JButton();
        jlaNivelEscolarAdicionados = new javax.swing.JLabel();
        jspNivelEscolarAdicionados = new javax.swing.JScrollPane();
        jliNivelEscolarAdicionados = new javax.swing.JList();
        jbuRemoverNivelEscolar = new javax.swing.JButton();
        jbuSalvar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(TelaEditarInstituicoes.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jpaEditarInstituicoes.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jpaEditarInstituicoes.border.lineColor"))); // NOI18N
        jpaEditarInstituicoes.setName("jpaEditarInstituicoes"); // NOI18N
        jpaEditarInstituicoes.setLayout(null);

        jpaSuperior.setBackground(resourceMap.getColor("jpaSuperior.background")); // NOI18N
        jpaSuperior.setName("jpaSuperior"); // NOI18N

        jlabTitulo.setFont(resourceMap.getFont("jlabTitulo.font")); // NOI18N
        jlabTitulo.setForeground(resourceMap.getColor("jlabTitulo.foreground")); // NOI18N
        jlabTitulo.setText(resourceMap.getString("jlabTitulo.text")); // NOI18N
        jlabTitulo.setToolTipText(resourceMap.getString("jlabTitulo.toolTipText")); // NOI18N
        jlabTitulo.setName("jlabTitulo"); // NOI18N

        jbuFecharTitulo.setBackground(resourceMap.getColor("jbuFecharTitulo.background")); // NOI18N
        jbuFecharTitulo.setIcon(resourceMap.getIcon("jbuFecharTitulo.icon")); // NOI18N
        jbuFecharTitulo.setAlignmentY(0.0F);
        jbuFecharTitulo.setBorderPainted(false);
        jbuFecharTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFecharTitulo.setFocusable(false);
        jbuFecharTitulo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbuFecharTitulo.setMaximumSize(new java.awt.Dimension(25, 25));
        jbuFecharTitulo.setMinimumSize(new java.awt.Dimension(25, 25));
        jbuFecharTitulo.setName("jbuFecharTitulo"); // NOI18N
        jbuFecharTitulo.setPreferredSize(new java.awt.Dimension(25, 25));
        jbuFecharTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharTituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaSuperiorLayout = new javax.swing.GroupLayout(jpaSuperior);
        jpaSuperior.setLayout(jpaSuperiorLayout);
        jpaSuperiorLayout.setHorizontalGroup(
            jpaSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 676, Short.MAX_VALUE)
                .addComponent(jbuFecharTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpaSuperiorLayout.setVerticalGroup(
            jpaSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaSuperiorLayout.createSequentialGroup()
                .addGroup(jpaSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbuFecharTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpaEditarInstituicoes.add(jpaSuperior);
        jpaSuperior.setBounds(1, 1, 1018, 27);

        jpaContatos.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jpaContatos.border.lineColor"))); // NOI18N
        jpaContatos.setName("jpaContatos"); // NOI18N
        jpaContatos.setLayout(null);

        jlaTelefone.setFont(resourceMap.getFont("jlaTipoTelefone.font")); // NOI18N
        jlaTelefone.setText(resourceMap.getString("jlaTelefone.text")); // NOI18N
        jlaTelefone.setName("jlaTelefone"); // NOI18N
        jpaContatos.add(jlaTelefone);
        jlaTelefone.setBounds(160, 10, 130, 17);

        try {
            jftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftTelefone.setFont(resourceMap.getFont("jftTelefone.font")); // NOI18N
        jftTelefone.setName("jftTelefone"); // NOI18N
        jpaContatos.add(jftTelefone);
        jftTelefone.setBounds(157, 30, 130, 23);
        jftTelefone.getAccessibleContext().setAccessibleName(resourceMap.getString("jftTelefone.AccessibleContext.accessibleName")); // NOI18N

        jlaTipoTelefone.setFont(resourceMap.getFont("jlaTipoTelefone.font")); // NOI18N
        jlaTipoTelefone.setText(resourceMap.getString("jlaTipoTelefone.text")); // NOI18N
        jlaTipoTelefone.setName("jlaTipoTelefone"); // NOI18N
        jpaContatos.add(jlaTipoTelefone);
        jlaTipoTelefone.setBounds(10, 10, 120, 17);

        jcbTipoTelefone.setFont(resourceMap.getFont("jcbTipoTelefone.font")); // NOI18N
        jcbTipoTelefone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbTipoTelefone.setName("jcbTipoTelefone"); // NOI18N
        jpaContatos.add(jcbTipoTelefone);
        jcbTipoTelefone.setBounds(10, 30, 140, 25);
        jcbTipoTelefone.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbTipoTelefone.AccessibleContext.accessibleName")); // NOI18N

        jbuAdicionarTelefone.setFont(resourceMap.getFont("jbuAdicionarTelefone.font")); // NOI18N
        jbuAdicionarTelefone.setIcon(resourceMap.getIcon("jbuAdicionarTelefone.icon")); // NOI18N
        jbuAdicionarTelefone.setMnemonic('a');
        jbuAdicionarTelefone.setText(resourceMap.getString("jbuAdicionarTelefone.text")); // NOI18N
        jbuAdicionarTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAdicionarTelefone.setName("jbuAdicionarTelefone"); // NOI18N
        jbuAdicionarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarTelefoneActionPerformed(evt);
            }
        });
        jpaContatos.add(jbuAdicionarTelefone);
        jbuAdicionarTelefone.setBounds(300, 25, 130, 33);
        jbuAdicionarTelefone.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAdicionarTelefone.AccessibleContext.accessibleName")); // NOI18N

        jlaTelefonesAdicionados.setFont(resourceMap.getFont("jlaTipoTelefone.font")); // NOI18N
        jlaTelefonesAdicionados.setText(resourceMap.getString("jlaTelefonesAdicionados.text")); // NOI18N
        jlaTelefonesAdicionados.setName("jlaTelefonesAdicionados"); // NOI18N
        jpaContatos.add(jlaTelefonesAdicionados);
        jlaTelefonesAdicionados.setBounds(10, 60, 280, 17);

        jspTelefonesAdicionados.setName("jspTelefonesAdicionados"); // NOI18N

        jliTelefonesAdicionados.setFont(resourceMap.getFont("jliTelefonesAdicionados.font")); // NOI18N
        jliTelefonesAdicionados.setModel(new DefaultListModel());
        jliTelefonesAdicionados.setName("jliTelefonesAdicionados"); // NOI18N
        jspTelefonesAdicionados.setViewportView(jliTelefonesAdicionados);
        jliTelefonesAdicionados.getAccessibleContext().setAccessibleName(resourceMap.getString("jliTelefonesAdicionados.AccessibleContext.accessibleName")); // NOI18N

        jpaContatos.add(jspTelefonesAdicionados);
        jspTelefonesAdicionados.setBounds(10, 80, 280, 105);

        jbuRemoverTelefone.setFont(resourceMap.getFont("jbuRemoverTelefone.font")); // NOI18N
        jbuRemoverTelefone.setIcon(resourceMap.getIcon("jbuRemoverTelefone.icon")); // NOI18N
        jbuRemoverTelefone.setMnemonic('r');
        jbuRemoverTelefone.setText(resourceMap.getString("jbuRemoverTelefone.text")); // NOI18N
        jbuRemoverTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuRemoverTelefone.setName("jbuRemoverTelefone"); // NOI18N
        jbuRemoverTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverTelefoneActionPerformed(evt);
            }
        });
        jpaContatos.add(jbuRemoverTelefone);
        jbuRemoverTelefone.setBounds(300, 80, 130, 33);
        jbuRemoverTelefone.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuRemoverTelefone.AccessibleContext.accessibleName")); // NOI18N

        try {
            jftRamal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftRamal.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftRamal.setFont(resourceMap.getFont("jftRamal.font")); // NOI18N
        jftRamal.setName("jftRamal"); // NOI18N
        jpaContatos.add(jftRamal);
        jftRamal.setBounds(10, 210, 67, 23);
        jftRamal.getAccessibleContext().setAccessibleName(resourceMap.getString("jftFamiliarRamal.AccessibleContext.accessibleName")); // NOI18N

        jlaRamal.setFont(resourceMap.getFont("jlaTipoTelefone.font")); // NOI18N
        jlaRamal.setText(resourceMap.getString("jlaRamal.text")); // NOI18N
        jlaRamal.setName("jlaRamal"); // NOI18N
        jpaContatos.add(jlaRamal);
        jlaRamal.setBounds(10, 190, 67, 17);

        jlaNomeContato.setFont(resourceMap.getFont("jlaTipoTelefone.font")); // NOI18N
        jlaNomeContato.setText(resourceMap.getString("jlaNomeContato.text")); // NOI18N
        jlaNomeContato.setName("jlaNomeContato"); // NOI18N
        jpaContatos.add(jlaNomeContato);
        jlaNomeContato.setBounds(10, 240, 190, 17);

        jtfNomeContato.setFont(resourceMap.getFont("jtfNomeContato.font")); // NOI18N
        jtfNomeContato.setName("jtfNomeContato"); // NOI18N
        jpaContatos.add(jtfNomeContato);
        jtfNomeContato.setBounds(10, 260, 360, 23);
        jtfNomeContato.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfNomeContato.AccessibleContext.accessibleName")); // NOI18N

        jlaEmail.setFont(resourceMap.getFont("jlaTipoTelefone.font")); // NOI18N
        jlaEmail.setText(resourceMap.getString("jlaEmail.text")); // NOI18N
        jlaEmail.setName("jlaEmail"); // NOI18N
        jpaContatos.add(jlaEmail);
        jlaEmail.setBounds(10, 290, 200, 17);

        jtfEmail.setFont(resourceMap.getFont("jtfEmail.font")); // NOI18N
        jtfEmail.setName("jtfEmail"); // NOI18N
        jpaContatos.add(jtfEmail);
        jtfEmail.setBounds(10, 310, 360, 23);
        jtfEmail.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfEmail.AccessibleContext.accessibleName")); // NOI18N

        jpaEditarInstituicoes.add(jpaContatos);
        jpaContatos.setBounds(560, 190, 440, 340);

        jpaPrincipal.setName("jpaPrincipal"); // NOI18N
        jpaPrincipal.setLayout(null);

        jlaTipo.setFont(resourceMap.getFont("jlaTipo.font")); // NOI18N
        jlaTipo.setText(resourceMap.getString("jlaTipo.text")); // NOI18N
        jlaTipo.setName("jlaTipo"); // NOI18N
        jpaPrincipal.add(jlaTipo);
        jlaTipo.setBounds(10, 10, 90, 17);
        jlaTipo.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaTipo.AccessibleContext.accessibleName")); // NOI18N

        jcbTipo.setFont(resourceMap.getFont("jcbTipo.font")); // NOI18N
        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbTipo.setName("jcbTipo"); // NOI18N
        jpaPrincipal.add(jcbTipo);
        jcbTipo.setBounds(10, 30, 195, 25);
        jcbTipo.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbTipo.AccessibleContext.accessibleName")); // NOI18N

        jlaNome.setFont(resourceMap.getFont("jlaNome.font")); // NOI18N
        jlaNome.setText(resourceMap.getString("jlaNome.text")); // NOI18N
        jlaNome.setName("jlaNome"); // NOI18N
        jpaPrincipal.add(jlaNome);
        jlaNome.setBounds(212, 10, 440, 17);

        jtfNome.setFont(resourceMap.getFont("jtfNome.font")); // NOI18N
        jtfNome.setName("jtfNome"); // NOI18N
        jpaPrincipal.add(jtfNome);
        jtfNome.setBounds(212, 30, 570, 23);
        jtfNome.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfInstituicao.AccessibleContext.accessibleName")); // NOI18N

        jlaClassificacao.setFont(resourceMap.getFont("jlaClassificacao.font")); // NOI18N
        jlaClassificacao.setText(resourceMap.getString("jlaClassificacao.text")); // NOI18N
        jlaClassificacao.setName("jlaClassificacao"); // NOI18N
        jpaPrincipal.add(jlaClassificacao);
        jlaClassificacao.setBounds(791, 10, 200, 17);
        jlaClassificacao.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaClassificacao.AccessibleContext.accessibleName")); // NOI18N

        jcbClassificacao.setFont(resourceMap.getFont("jcbClassificacao.font")); // NOI18N
        jcbClassificacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbClassificacao.setName("jcbClassificacao"); // NOI18N
        jpaPrincipal.add(jcbClassificacao);
        jcbClassificacao.setBounds(790, 30, 210, 25);
        jcbClassificacao.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbclassificacao.AccessibleContext.accessibleName")); // NOI18N

        jlaCEP.setFont(resourceMap.getFont("jlaCEP.font")); // NOI18N
        jlaCEP.setText(resourceMap.getString("jlaCEP.text")); // NOI18N
        jlaCEP.setName("jlaCEP"); // NOI18N
        jpaPrincipal.add(jlaCEP);
        jlaCEP.setBounds(11, 60, 28, 17);
        jlaCEP.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaCEP.AccessibleContext.accessibleName")); // NOI18N

        try {
            jftCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCEP.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftCEP.setFont(resourceMap.getFont("jftCEP.font")); // NOI18N
        jftCEP.setName("jftCEP"); // NOI18N
        jftCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftCEPFocusLost(evt);
            }
        });
        jpaPrincipal.add(jftCEP);
        jftCEP.setBounds(11, 80, 100, 23);
        jftCEP.getAccessibleContext().setAccessibleName(resourceMap.getString("jftCEP.AccessibleContext.accessibleName")); // NOI18N

        jlaEndereco.setFont(resourceMap.getFont("jlaCEP.font")); // NOI18N
        jlaEndereco.setText(resourceMap.getString("jlaEndereco.text")); // NOI18N
        jlaEndereco.setName("jlaEndereco"); // NOI18N
        jpaPrincipal.add(jlaEndereco);
        jlaEndereco.setBounds(117, 60, 130, 17);
        jlaEndereco.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaEndereco.AccessibleContext.accessibleName")); // NOI18N

        jtfEndereco.setFont(resourceMap.getFont("jtfNumero.font")); // NOI18N
        jtfEndereco.setName("jtfEndereco"); // NOI18N
        jpaPrincipal.add(jtfEndereco);
        jtfEndereco.setBounds(117, 80, 420, 23);
        jtfEndereco.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfEndereco.AccessibleContext.accessibleName")); // NOI18N

        jlaNumero.setFont(resourceMap.getFont("jlaCEP.font")); // NOI18N
        jlaNumero.setText(resourceMap.getString("jlaNumero.text")); // NOI18N
        jlaNumero.setName("jlaNumero"); // NOI18N
        jpaPrincipal.add(jlaNumero);
        jlaNumero.setBounds(543, 60, 120, 17);
        jlaNumero.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaNumero.AccessibleContext.accessibleName")); // NOI18N

        jtfNumero.setFont(resourceMap.getFont("jtfNumero.font")); // NOI18N
        jtfNumero.setName("jtfNumero"); // NOI18N
        jpaPrincipal.add(jtfNumero);
        jtfNumero.setBounds(543, 80, 122, 23);
        jtfNumero.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfNumero.AccessibleContext.accessibleName")); // NOI18N

        jlaComplemento.setFont(resourceMap.getFont("jlaCEP.font")); // NOI18N
        jlaComplemento.setText(resourceMap.getString("jlaComplemento.text")); // NOI18N
        jlaComplemento.setName("jlaComplemento"); // NOI18N
        jpaPrincipal.add(jlaComplemento);
        jlaComplemento.setBounds(672, 60, 102, 17);
        jlaComplemento.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaComplemento.AccessibleContext.accessibleName")); // NOI18N

        jtfComplemento.setFont(resourceMap.getFont("jtfNumero.font")); // NOI18N
        jtfComplemento.setName("jtfComplemento"); // NOI18N
        jpaPrincipal.add(jtfComplemento);
        jtfComplemento.setBounds(671, 80, 156, 23);
        jtfComplemento.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfComplemento.AccessibleContext.accessibleName")); // NOI18N

        jlaPais.setFont(resourceMap.getFont("jlaPais.font")); // NOI18N
        jlaPais.setText(resourceMap.getString("jlaPais.text")); // NOI18N
        jlaPais.setName("jlaPais"); // NOI18N
        jpaPrincipal.add(jlaPais);
        jlaPais.setBounds(833, 60, 120, 17);
        jlaPais.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaPais.AccessibleContext.accessibleName")); // NOI18N

        jcbPais.setFont(resourceMap.getFont("jcbPais.font")); // NOI18N
        jcbPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbPais.setName("jcbPais"); // NOI18N
        jcbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPaisActionPerformed(evt);
            }
        });
        jpaPrincipal.add(jcbPais);
        jcbPais.setBounds(833, 80, 169, 25);
        jcbPais.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbUF1.AccessibleContext.accessibleName")); // NOI18N

        jlaUF.setFont(resourceMap.getFont("jlaMunicipio.font")); // NOI18N
        jlaUF.setText(resourceMap.getString("jlaUF.text")); // NOI18N
        jlaUF.setName("jlaUF"); // NOI18N
        jpaPrincipal.add(jlaUF);
        jlaUF.setBounds(10, 110, 90, 17);
        jlaUF.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaUF.AccessibleContext.accessibleName")); // NOI18N

        jcbUF.setFont(resourceMap.getFont("jlaMunicipio.font")); // NOI18N
        jcbUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbUF.setName("jcbUF"); // NOI18N
        jcbUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUFActionPerformed(evt);
            }
        });
        jpaPrincipal.add(jcbUF);
        jcbUF.setBounds(10, 130, 140, 25);
        jcbUF.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbUF.AccessibleContext.accessibleName")); // NOI18N

        jlaMunicipio.setFont(resourceMap.getFont("jlaMunicipio.font")); // NOI18N
        jlaMunicipio.setText(resourceMap.getString("jlaMunicipio.text")); // NOI18N
        jlaMunicipio.setName("jlaMunicipio"); // NOI18N
        jpaPrincipal.add(jlaMunicipio);
        jlaMunicipio.setBounds(156, 110, 240, 17);
        jlaMunicipio.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaMunicipio.AccessibleContext.accessibleName")); // NOI18N

        jcbMunicipio.setFont(resourceMap.getFont("jlaMunicipio.font")); // NOI18N
        jcbMunicipio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbMunicipio.setLightWeightPopupEnabled(false);
        jcbMunicipio.setName("jcbMunicipio"); // NOI18N
        jpaPrincipal.add(jcbMunicipio);
        jcbMunicipio.setBounds(156, 130, 451, 25);
        jcbMunicipio.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbMunicipio.AccessibleContext.accessibleName")); // NOI18N

        jlaZona.setFont(resourceMap.getFont("jlaZona.font")); // NOI18N
        jlaZona.setText(resourceMap.getString("jlaZona.text")); // NOI18N
        jlaZona.setName("jlaZona"); // NOI18N
        jpaPrincipal.add(jlaZona);
        jlaZona.setBounds(614, 110, 80, 17);
        jlaZona.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaZona.AccessibleContext.accessibleName")); // NOI18N

        jcbZona.setFont(resourceMap.getFont("jlaZona.font")); // NOI18N
        jcbZona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbZona.setName("jcbZona"); // NOI18N
        jpaPrincipal.add(jcbZona);
        jcbZona.setBounds(614, 130, 164, 25);
        jcbZona.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbZona.AccessibleContext.accessibleName")); // NOI18N

        jlaBairro.setFont(resourceMap.getFont("jlaBairro.font")); // NOI18N
        jlaBairro.setText(resourceMap.getString("jlaBairro.text")); // NOI18N
        jlaBairro.setName("jlaBairro"); // NOI18N
        jpaPrincipal.add(jlaBairro);
        jlaBairro.setBounds(785, 110, 80, 17);
        jlaBairro.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaBairro.AccessibleContext.accessibleName")); // NOI18N

        jtfBairro.setFont(resourceMap.getFont("jlaBairro.font")); // NOI18N
        jtfBairro.setName("jtfBairro"); // NOI18N
        jpaPrincipal.add(jtfBairro);
        jtfBairro.setBounds(785, 130, 218, 23);
        jtfBairro.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfBairro.AccessibleContext.accessibleName")); // NOI18N

        jlaCoordenador.setFont(resourceMap.getFont("jlaCoordenador.font")); // NOI18N
        jlaCoordenador.setText(resourceMap.getString("jlaCoordenador.text")); // NOI18N
        jlaCoordenador.setName("jlaCoordenador"); // NOI18N
        jpaPrincipal.add(jlaCoordenador);
        jlaCoordenador.setBounds(10, 160, 203, 17);
        jlaCoordenador.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaCoordenador.AccessibleContext.accessibleName")); // NOI18N

        jtfCoordenadorResponsavel.setFont(resourceMap.getFont("jtfCoordenadorResponsavel.font")); // NOI18N
        jtfCoordenadorResponsavel.setText(resourceMap.getString("jtfCoordenadorResponsavel.text")); // NOI18N
        jtfCoordenadorResponsavel.setName("jtfCoordenadorResponsavel"); // NOI18N
        jpaPrincipal.add(jtfCoordenadorResponsavel);
        jtfCoordenadorResponsavel.setBounds(10, 180, 450, 23);
        jtfCoordenadorResponsavel.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfCoordenadorResponsavel.AccessibleContext.accessibleName")); // NOI18N

        jlaTipoApoio.setFont(resourceMap.getFont("jlaTipoApoio.font")); // NOI18N
        jlaTipoApoio.setText(resourceMap.getString("jlaTipoApoio.text")); // NOI18N
        jlaTipoApoio.setName("jlaTipoApoio"); // NOI18N
        jpaPrincipal.add(jlaTipoApoio);
        jlaTipoApoio.setBounds(10, 350, 350, 17);

        jcbTipoApoio.setFont(resourceMap.getFont("jcbTipoApoio.font")); // NOI18N
        jcbTipoApoio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbTipoApoio.setName("jcbTipoApoio"); // NOI18N
        jpaPrincipal.add(jcbTipoApoio);
        jcbTipoApoio.setBounds(10, 370, 260, 25);
        jcbTipoApoio.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbTipoApoio.AccessibleContext.accessibleName")); // NOI18N

        jlaTipoEspecialidade.setFont(resourceMap.getFont("jlaSaais.font")); // NOI18N
        jlaTipoEspecialidade.setText(resourceMap.getString("jlaSaais.text")); // NOI18N
        jlaTipoEspecialidade.setName("jlaSaais"); // NOI18N
        jpaPrincipal.add(jlaTipoEspecialidade);
        jlaTipoEspecialidade.setBounds(10, 400, 210, 17);

        jcbTipoEspecialidade.setFont(resourceMap.getFont("jcbSaais.font")); // NOI18N
        jcbTipoEspecialidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbTipoEspecialidade.setName("jcbSaais"); // NOI18N
        jpaPrincipal.add(jcbTipoEspecialidade);
        jcbTipoEspecialidade.setBounds(10, 420, 260, 25);
        jcbTipoEspecialidade.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbSaais.AccessibleContext.accessibleName")); // NOI18N

        jbuAdicionarTipoSaai.setFont(resourceMap.getFont("jbuAdicionarTipoSaai.font")); // NOI18N
        jbuAdicionarTipoSaai.setIcon(resourceMap.getIcon("jbuAdicionarTipoSaai.icon")); // NOI18N
        jbuAdicionarTipoSaai.setText(resourceMap.getString("jbuAdicionarTipoSaai.text")); // NOI18N
        jbuAdicionarTipoSaai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAdicionarTipoSaai.setName("jbuAdicionarTipoSaai"); // NOI18N
        jbuAdicionarTipoSaai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarTipoSaaiActionPerformed(evt);
            }
        });
        jpaPrincipal.add(jbuAdicionarTipoSaai);
        jbuAdicionarTipoSaai.setBounds(280, 420, 140, 33);
        jbuAdicionarTipoSaai.getAccessibleContext().setAccessibleName(resourceMap.getString("jButton1.AccessibleContext.accessibleName")); // NOI18N

        jlaTiposSaaisAdicionados.setFont(resourceMap.getFont("jlaSaaisAdicionados.font")); // NOI18N
        jlaTiposSaaisAdicionados.setText(resourceMap.getString("jlaSaaisAdicionados.text")); // NOI18N
        jlaTiposSaaisAdicionados.setName("jlaSaaisAdicionados"); // NOI18N
        jpaPrincipal.add(jlaTiposSaaisAdicionados);
        jlaTiposSaaisAdicionados.setBounds(10, 450, 260, 17);

        jspTiposEspecialidadeAdicionados.setName("jspTiposEspecialidadeAdicionados"); // NOI18N

        jliTiposEspecialidadeAdicionados.setFont(resourceMap.getFont("jliSaaisAdicionados.font")); // NOI18N
        jliTiposEspecialidadeAdicionados.setModel(new DefaultListModel());
        jliTiposEspecialidadeAdicionados.setName("jliSaaisAdicionados"); // NOI18N
        jspTiposEspecialidadeAdicionados.setViewportView(jliTiposEspecialidadeAdicionados);
        jliTiposEspecialidadeAdicionados.getAccessibleContext().setAccessibleName(resourceMap.getString("jliSaaisAdicionados.AccessibleContext.accessibleName")); // NOI18N

        jpaPrincipal.add(jspTiposEspecialidadeAdicionados);
        jspTiposEspecialidadeAdicionados.setBounds(10, 470, 260, 60);

        jbuRemoverTipoSaai.setFont(resourceMap.getFont("jbuRemoverTipoSaai.font")); // NOI18N
        jbuRemoverTipoSaai.setIcon(resourceMap.getIcon("jbuRemoverTipoSaai.icon")); // NOI18N
        jbuRemoverTipoSaai.setText(resourceMap.getString("jbuRemoverTipoSaai.text")); // NOI18N
        jbuRemoverTipoSaai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuRemoverTipoSaai.setName("jbuRemoverTipoSaai"); // NOI18N
        jbuRemoverTipoSaai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverTipoSaaiActionPerformed(evt);
            }
        });
        jpaPrincipal.add(jbuRemoverTipoSaai);
        jbuRemoverTipoSaai.setBounds(280, 470, 140, 33);
        jbuRemoverTipoSaai.getAccessibleContext().setAccessibleName(resourceMap.getString("jButton2.AccessibleContext.accessibleName")); // NOI18N

        jlaObservacoes.setFont(resourceMap.getFont("jlaObservacoes.font")); // NOI18N
        jlaObservacoes.setText(resourceMap.getString("jlaObservacoes.text")); // NOI18N
        jlaObservacoes.setName("jlaObservacoes"); // NOI18N
        jpaPrincipal.add(jlaObservacoes);
        jlaObservacoes.setBounds(570, 510, 95, 17);
        jlaObservacoes.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaObservacoes.AccessibleContext.accessibleName")); // NOI18N

        jspObservacoes.setName("jspObservacoes"); // NOI18N

        jepObservacoes.setFont(resourceMap.getFont("jepObservacoes.font")); // NOI18N
        jepObservacoes.setName("jepObservacoes"); // NOI18N
        jspObservacoes.setViewportView(jepObservacoes);
        jepObservacoes.getAccessibleContext().setAccessibleName(resourceMap.getString("jEditorPane1.AccessibleContext.accessibleName")); // NOI18N
        jepObservacoes.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jepObservacoes.AccessibleContext.accessibleDescription")); // NOI18N

        jpaPrincipal.add(jspObservacoes);
        jspObservacoes.setBounds(570, 530, 430, 90);

        jlaDreCefai.setFont(resourceMap.getFont("jlaDreCefai.font")); // NOI18N
        jlaDreCefai.setText(resourceMap.getString("jlaDreCefai.text")); // NOI18N
        jlaDreCefai.setName("jlaDreCefai"); // NOI18N
        jpaPrincipal.add(jlaDreCefai);
        jlaDreCefai.setBounds(10, 530, 500, 17);

        jcbDreCefai.setFont(resourceMap.getFont("jcbDreCefai.font")); // NOI18N
        jcbDreCefai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbDreCefai.setName("jcbDreCefai"); // NOI18N
        jpaPrincipal.add(jcbDreCefai);
        jcbDreCefai.setBounds(10, 550, 540, 25);
        jcbDreCefai.getAccessibleContext().setAccessibleName(resourceMap.getString("jComboBox1.AccessibleContext.accessibleName")); // NOI18N

        jlaDiretoriaEnsino.setFont(resourceMap.getFont("jlaDiretoriaEnsino.font")); // NOI18N
        jlaDiretoriaEnsino.setText(resourceMap.getString("jlaDiretoriaEnsino.text")); // NOI18N
        jlaDiretoriaEnsino.setName("jlaDiretoriaEnsino"); // NOI18N
        jpaPrincipal.add(jlaDiretoriaEnsino);
        jlaDiretoriaEnsino.setBounds(10, 580, 500, 17);

        jcbDiretoriaEnsino.setFont(resourceMap.getFont("jcbDiretoriaEnsino.font")); // NOI18N
        jcbDiretoriaEnsino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbDiretoriaEnsino.setName("jcbDiretoriaEnsino"); // NOI18N
        jpaPrincipal.add(jcbDiretoriaEnsino);
        jcbDiretoriaEnsino.setBounds(10, 600, 540, 25);
        jcbDiretoriaEnsino.getAccessibleContext().setAccessibleName(resourceMap.getString("jComboBox1.AccessibleContext.accessibleName")); // NOI18N

        jlaNivelEscolar.setFont(resourceMap.getFont("jlaNivelEscolar.font")); // NOI18N
        jlaNivelEscolar.setText(resourceMap.getString("jlaNivelEscolar.text")); // NOI18N
        jlaNivelEscolar.setName("jlaNivelEscolar"); // NOI18N
        jpaPrincipal.add(jlaNivelEscolar);
        jlaNivelEscolar.setBounds(10, 210, 390, 17);

        jcbNivelEscolar.setFont(resourceMap.getFont("jcbNivelEscolar.font")); // NOI18N
        jcbNivelEscolar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbNivelEscolar.setName("jcbNivelEscolar"); // NOI18N
        jpaPrincipal.add(jcbNivelEscolar);
        jcbNivelEscolar.setBounds(10, 230, 210, 25);
        jcbNivelEscolar.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbNivelEscolar.AccessibleContext.accessibleName")); // NOI18N

        jbuAdicionarNivelEscolar.setFont(resourceMap.getFont("jbuAdicionarNivelEscolar.font")); // NOI18N
        jbuAdicionarNivelEscolar.setIcon(resourceMap.getIcon("jbuAdicionarNivelEscolar.icon")); // NOI18N
        jbuAdicionarNivelEscolar.setText(resourceMap.getString("jbuAdicionarNivelEscolar.text")); // NOI18N
        jbuAdicionarNivelEscolar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAdicionarNivelEscolar.setName("jbuAdicionarNivelEscolar"); // NOI18N
        jbuAdicionarNivelEscolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarNivelEscolarActionPerformed(evt);
            }
        });
        jpaPrincipal.add(jbuAdicionarNivelEscolar);
        jbuAdicionarNivelEscolar.setBounds(230, 230, 140, 33);
        jbuAdicionarNivelEscolar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAdicionarNivelEscolar.AccessibleContext.accessibleName")); // NOI18N

        jlaNivelEscolarAdicionados.setFont(resourceMap.getFont("jlaNivelEscolarAdicionados.font")); // NOI18N
        jlaNivelEscolarAdicionados.setText(resourceMap.getString("jlaNivelEscolarAdicionados.text")); // NOI18N
        jlaNivelEscolarAdicionados.setName("jlaNivelEscolarAdicionados"); // NOI18N
        jpaPrincipal.add(jlaNivelEscolarAdicionados);
        jlaNivelEscolarAdicionados.setBounds(10, 260, 230, 17);

        jspNivelEscolarAdicionados.setName("jspNivelEscolarAdicionados"); // NOI18N

        jliNivelEscolarAdicionados.setFont(resourceMap.getFont("jliNivelEscolarAdicionados.font")); // NOI18N
        jliNivelEscolarAdicionados.setModel(new DefaultListModel());
        jliNivelEscolarAdicionados.setName("jliNivelEscolarAdicionados"); // NOI18N
        jspNivelEscolarAdicionados.setViewportView(jliNivelEscolarAdicionados);
        jliNivelEscolarAdicionados.getAccessibleContext().setAccessibleName(resourceMap.getString("jliNivelEscolarAdicionados.AccessibleContext.accessibleName")); // NOI18N

        jpaPrincipal.add(jspNivelEscolarAdicionados);
        jspNivelEscolarAdicionados.setBounds(10, 280, 210, 60);

        jbuRemoverNivelEscolar.setFont(resourceMap.getFont("jbuRemoverNivelEscolar.font")); // NOI18N
        jbuRemoverNivelEscolar.setIcon(resourceMap.getIcon("jbuRemoverNivelEscolar.icon")); // NOI18N
        jbuRemoverNivelEscolar.setText(resourceMap.getString("jbuRemoverNivelEscolar.text")); // NOI18N
        jbuRemoverNivelEscolar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuRemoverNivelEscolar.setName("jbuRemoverNivelEscolar"); // NOI18N
        jbuRemoverNivelEscolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverNivelEscolarActionPerformed(evt);
            }
        });
        jpaPrincipal.add(jbuRemoverNivelEscolar);
        jbuRemoverNivelEscolar.setBounds(230, 280, 140, 33);
        jbuRemoverNivelEscolar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuRemoverNivelEscolar.AccessibleContext.accessibleName")); // NOI18N

        jpaEditarInstituicoes.add(jpaPrincipal);
        jpaPrincipal.setBounds(4, 30, 1010, 630);

        jbuSalvar.setFont(resourceMap.getFont("jbuFechar.font")); // NOI18N
        jbuSalvar.setIcon(resourceMap.getIcon("jbuSalvar.icon")); // NOI18N
        jbuSalvar.setMnemonic('S');
        jbuSalvar.setText(resourceMap.getString("jbuSalvar.text")); // NOI18N
        jbuSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSalvar.setName("jbuSalvar"); // NOI18N
        jbuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSalvarActionPerformed(evt);
            }
        });
        jpaEditarInstituicoes.add(jbuSalvar);
        jbuSalvar.setBounds(11, 667, 120, 33);

        jbuFechar.setFont(resourceMap.getFont("jbuFechar.font")); // NOI18N
        jbuFechar.setIcon(resourceMap.getIcon("jbuFechar.icon")); // NOI18N
        jbuFechar.setMnemonic('F');
        jbuFechar.setText(resourceMap.getString("jbuFechar.text")); // NOI18N
        jbuFechar.setToolTipText(resourceMap.getString("jbuFechar.toolTipText")); // NOI18N
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });
        jpaEditarInstituicoes.add(jbuFechar);
        jbuFechar.setBounds(879, 667, 130, 33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarInstituicoes, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarInstituicoes, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUFActionPerformed
        if (controlador != null) {
            controlador.inicializarCampoMunicipio(jcbUF, jcbMunicipio);
        }
}//GEN-LAST:event_jcbUFActionPerformed

    private void jbuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSalvarActionPerformed
       controlador.salvar();        // TODO add your handling code here:
}//GEN-LAST:event_jbuSalvarActionPerformed

    private void jcbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPaisActionPerformed

    private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
        controlador.fecharTela();      
}//GEN-LAST:event_jbuFecharActionPerformed

    private void jbuFecharTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharTituloActionPerformed
        controlador.fecharTela();      
}//GEN-LAST:event_jbuFecharTituloActionPerformed

    private void jbuAdicionarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarTelefoneActionPerformed
        controlador.adicionarTelefone();
    }//GEN-LAST:event_jbuAdicionarTelefoneActionPerformed

    private void jbuRemoverTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverTelefoneActionPerformed
        controlador.removerTelefoneSelecionado();
    }//GEN-LAST:event_jbuRemoverTelefoneActionPerformed

    private void jbuAdicionarTipoSaaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarTipoSaaiActionPerformed
        controlador.adicionarTipoSaai();
    }//GEN-LAST:event_jbuAdicionarTipoSaaiActionPerformed

    private void jbuRemoverTipoSaaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverTipoSaaiActionPerformed
        controlador.removerTipoSaaiSelecionado();        // TODO add your handling code here:
    }//GEN-LAST:event_jbuRemoverTipoSaaiActionPerformed

    private void jbuAdicionarNivelEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarNivelEscolarActionPerformed
        controlador.adicionarNivelEscolarSelecionado();
    }//GEN-LAST:event_jbuAdicionarNivelEscolarActionPerformed

    private void jbuRemoverNivelEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverNivelEscolarActionPerformed
        controlador.removerNivelEscolarSelecionado();
    }//GEN-LAST:event_jbuRemoverNivelEscolarActionPerformed

    private void jftCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftCEPFocusLost
         controlador.carregarEndereco();
    }//GEN-LAST:event_jftCEPFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbuAdicionarNivelEscolar;
    private javax.swing.JButton jbuAdicionarTelefone;
    private javax.swing.JButton jbuAdicionarTipoSaai;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuFecharTitulo;
    private javax.swing.JButton jbuRemoverNivelEscolar;
    private javax.swing.JButton jbuRemoverTelefone;
    private javax.swing.JButton jbuRemoverTipoSaai;
    private javax.swing.JButton jbuSalvar;
    private javax.swing.JComboBox jcbClassificacao;
    private javax.swing.JComboBox jcbDiretoriaEnsino;
    private javax.swing.JComboBox jcbDreCefai;
    private javax.swing.JComboBox jcbMunicipio;
    private javax.swing.JComboBox jcbNivelEscolar;
    private javax.swing.JComboBox jcbPais;
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JComboBox jcbTipoApoio;
    private javax.swing.JComboBox jcbTipoEspecialidade;
    private javax.swing.JComboBox jcbTipoTelefone;
    private javax.swing.JComboBox jcbUF;
    private javax.swing.JComboBox jcbZona;
    private javax.swing.JEditorPane jepObservacoes;
    private javax.swing.JFormattedTextField jftCEP;
    private javax.swing.JFormattedTextField jftRamal;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JLabel jlaBairro;
    private javax.swing.JLabel jlaCEP;
    private javax.swing.JLabel jlaClassificacao;
    private javax.swing.JLabel jlaComplemento;
    private javax.swing.JLabel jlaCoordenador;
    private javax.swing.JLabel jlaDiretoriaEnsino;
    private javax.swing.JLabel jlaDreCefai;
    private javax.swing.JLabel jlaEmail;
    private javax.swing.JLabel jlaEndereco;
    private javax.swing.JLabel jlaMunicipio;
    private javax.swing.JLabel jlaNivelEscolar;
    private javax.swing.JLabel jlaNivelEscolarAdicionados;
    private javax.swing.JLabel jlaNome;
    private javax.swing.JLabel jlaNomeContato;
    private javax.swing.JLabel jlaNumero;
    private javax.swing.JLabel jlaObservacoes;
    private javax.swing.JLabel jlaPais;
    private javax.swing.JLabel jlaRamal;
    private javax.swing.JLabel jlaTelefone;
    private javax.swing.JLabel jlaTelefonesAdicionados;
    private javax.swing.JLabel jlaTipo;
    private javax.swing.JLabel jlaTipoApoio;
    private javax.swing.JLabel jlaTipoEspecialidade;
    private javax.swing.JLabel jlaTipoTelefone;
    private javax.swing.JLabel jlaTiposSaaisAdicionados;
    private javax.swing.JLabel jlaUF;
    private javax.swing.JLabel jlaZona;
    private javax.swing.JLabel jlabTitulo;
    private javax.swing.JList jliNivelEscolarAdicionados;
    private javax.swing.JList jliTelefonesAdicionados;
    private javax.swing.JList jliTiposEspecialidadeAdicionados;
    private javax.swing.JPanel jpaContatos;
    private javax.swing.JPanel jpaEditarInstituicoes;
    private javax.swing.JPanel jpaPrincipal;
    private javax.swing.JPanel jpaSuperior;
    private javax.swing.JScrollPane jspNivelEscolarAdicionados;
    private javax.swing.JScrollPane jspObservacoes;
    private javax.swing.JScrollPane jspTelefonesAdicionados;
    private javax.swing.JScrollPane jspTiposEspecialidadeAdicionados;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfCoordenadorResponsavel;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNomeContato;
    private javax.swing.JTextField jtfNumero;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaEditarInstituicao controlador;
}
