package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaEditarContribuicoes;
import br.laramara.ti.sislaracommons.dtos.contribuicao.ContribuinteDTO;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

public class TelaEditarContribuintes extends javax.swing.JDialog {

    /**
     * Creates new form TelaEditarContribuintes
     */
    public TelaEditarContribuintes(JDialog parent, ContribuinteDTO contribuinteDto) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        controlador = new ControladorTelaEditarContribuicoes(this, contribuinteDto, jtfCodigo, jtfDataCadastro, jtfNomeEmpresa, jftCpf, jftCEP, jtfEndereco, jtfNumero, jtfComplemento, jtfBairro, jcbMunicipio, jcbUF, jcbPais, jcbTipoTelefone, jftTelefone, jliTelefonesAdicionados, jftRamal, jtfNomeContato, jtfEmail, jcbStatus, jtfValorContribuicao, jcbMotivoDesativacao);
        controlador.abrirTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaEditarContribuintes = new javax.swing.JPanel();
        jpaPrincipal = new javax.swing.JPanel();
        jlaCodigo = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jlaDataCadastro = new javax.swing.JLabel();
        jtfDataCadastro = new javax.swing.JTextField();
        jlaNome = new javax.swing.JLabel();
        jtfNomeEmpresa = new javax.swing.JTextField();
        jlaCEP = new javax.swing.JLabel();
        jftCEP = new javax.swing.JFormattedTextField();
        jtfEndereco = new javax.swing.JTextField();
        jlaEndereco = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jlaNumero = new javax.swing.JLabel();
        jcbPais = new javax.swing.JComboBox();
        jcbUF = new javax.swing.JComboBox();
        jlaUF = new javax.swing.JLabel();
        jlaPais = new javax.swing.JLabel();
        jlaMunicipio = new javax.swing.JLabel();
        jcbMunicipio = new javax.swing.JComboBox();
        jlaBairro = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jtfComplemento = new javax.swing.JTextField();
        jlaComplemento = new javax.swing.JLabel();
        jpaContatos = new javax.swing.JPanel();
        jlaTelefone = new javax.swing.JLabel();
        jftTelefone = new javax.swing.JFormattedTextField();
        jlaTipoTelefone = new javax.swing.JLabel();
        jcbTipoTelefone = new javax.swing.JComboBox();
        jbuAdicionarTelefone = new javax.swing.JButton();
        jlaTelefonesAdicionados = new javax.swing.JLabel();
        jspTelefonesAdicionados = new javax.swing.JScrollPane();
        jliTelefonesAdicionados = new javax.swing.JList();
        jbuRemoverTelefone = new javax.swing.JButton();
        jlaRamal = new javax.swing.JLabel();
        jftRamal = new javax.swing.JFormattedTextField();
        jlaNomeContato = new javax.swing.JLabel();
        jtfNomeContato = new javax.swing.JTextField();
        jlaEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jpaInformacoes = new javax.swing.JPanel();
        jlaIndicadoPor = new javax.swing.JLabel();
        jtfIndicadoPor = new javax.swing.JTextField();
        jlaStatus = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox();
        jlaValorContribuicao = new javax.swing.JLabel();
        jtfValorContribuicao = new javax.swing.JTextField();
        jlaMotivoDesativacao = new javax.swing.JLabel();
        jcbMotivoDesativacao = new javax.swing.JComboBox();
        jlaCpf = new javax.swing.JLabel();
        jftCpf = new javax.swing.JFormattedTextField();
        jbuSalvar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Contribuinte");

        jpaEditarContribuintes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jpaEditarContribuintes.setName("jpaEditarContribuintes"); // NOI18N
        jpaEditarContribuintes.setLayout(null);

        jpaPrincipal.setName("jpaPrincipal"); // NOI18N
        jpaPrincipal.setOpaque(false);

        jlaCodigo.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaCodigo.setText("Código");
        jlaCodigo.setName("jlaCodigo"); // NOI18N

        jtfCodigo.setEditable(false);
        jtfCodigo.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfCodigo.setToolTipText("");
        jtfCodigo.setName("jtfCodigo"); // NOI18N

        jlaDataCadastro.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaDataCadastro.setText("Data de Cadastro");
        jlaDataCadastro.setName("jlaDataCadastro"); // NOI18N

        jtfDataCadastro.setEditable(false);
        jtfDataCadastro.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfDataCadastro.setToolTipText("");
        jtfDataCadastro.setName("jtfDataCadastro"); // NOI18N

        jlaNome.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaNome.setText("Nome/Empresa");
        jlaNome.setName("jlaNome"); // NOI18N

        jtfNomeEmpresa.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfNomeEmpresa.setToolTipText("");
        jtfNomeEmpresa.setName("jtfNomeEmpresa"); // NOI18N

        jlaCEP.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaCEP.setText("CEP");
        jlaCEP.setName("jlaCEP"); // NOI18N

        try {
            jftCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCEP.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftCEP.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jftCEP.setName("jftCEP"); // NOI18N
        jftCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftCEPFocusLost(evt);
            }
        });

        jtfEndereco.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfEndereco.setName("jtfEndereco"); // NOI18N

        jlaEndereco.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaEndereco.setText("Endereço*");
        jlaEndereco.setName("jlaEndereco"); // NOI18N

        jtfNumero.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfNumero.setName("jtfNumero"); // NOI18N

        jlaNumero.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaNumero.setText("Número*");
        jlaNumero.setName("jlaNumero"); // NOI18N

        jcbPais.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jcbPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbPais.setName("jcbPais"); // NOI18N

        jcbUF.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jcbUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbUF.setName("jcbUF"); // NOI18N
        jcbUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUFActionPerformed(evt);
            }
        });

        jlaUF.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaUF.setText("UF*");
        jlaUF.setName("jlaUF"); // NOI18N

        jlaPais.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaPais.setText("País*");
        jlaPais.setName("jlaPais"); // NOI18N

        jlaMunicipio.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaMunicipio.setText("Município*");
        jlaMunicipio.setName("jlaMunicipio"); // NOI18N

        jcbMunicipio.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jcbMunicipio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbMunicipio.setLightWeightPopupEnabled(false);
        jcbMunicipio.setName("jcbMunicipio"); // NOI18N

        jlaBairro.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaBairro.setText("Bairro*");
        jlaBairro.setName("jlaBairro"); // NOI18N

        jtfBairro.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfBairro.setName("jtfBairro"); // NOI18N

        jtfComplemento.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfComplemento.setName("jtfComplemento"); // NOI18N

        jlaComplemento.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaComplemento.setText("Complemento");
        jlaComplemento.setName("jlaComplemento"); // NOI18N

        jpaContatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 84, 160)));
        jpaContatos.setName("jpaContatos"); // NOI18N
        jpaContatos.setLayout(null);

        jlaTelefone.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaTelefone.setText("Telefone");
        jlaTelefone.setName("jlaTelefone"); // NOI18N
        jpaContatos.add(jlaTelefone);
        jlaTelefone.setBounds(155, 10, 62, 17);

        try {
            jftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftTelefone.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jftTelefone.setName("jftTelefone"); // NOI18N
        jpaContatos.add(jftTelefone);
        jftTelefone.setBounds(155, 30, 132, 23);

        jlaTipoTelefone.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaTipoTelefone.setText("Tipo de Telefone");
        jlaTipoTelefone.setName("jlaTipoTelefone"); // NOI18N
        jpaContatos.add(jlaTipoTelefone);
        jlaTipoTelefone.setBounds(10, 10, 118, 17);

        jcbTipoTelefone.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jcbTipoTelefone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbTipoTelefone.setName("jcbTipoTelefone"); // NOI18N
        jpaContatos.add(jcbTipoTelefone);
        jcbTipoTelefone.setBounds(10, 30, 140, 23);

        jbuAdicionarTelefone.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuAdicionarTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Adicionar.png"))); // NOI18N
        jbuAdicionarTelefone.setMnemonic('a');
        jbuAdicionarTelefone.setText("Adicionar");
        jbuAdicionarTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAdicionarTelefone.setName("jbuAdicionarTelefone"); // NOI18N
        jbuAdicionarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarTelefoneActionPerformed(evt);
            }
        });
        jpaContatos.add(jbuAdicionarTelefone);
        jbuAdicionarTelefone.setBounds(300, 25, 130, 33);

        jlaTelefonesAdicionados.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaTelefonesAdicionados.setText("Telefones Adicionados*");
        jlaTelefonesAdicionados.setName("jlaTelefonesAdicionados"); // NOI18N
        jpaContatos.add(jlaTelefonesAdicionados);
        jlaTelefonesAdicionados.setBounds(10, 60, 200, 17);

        jspTelefonesAdicionados.setName("jspTelefonesAdicionados"); // NOI18N

        jliTelefonesAdicionados.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jliTelefonesAdicionados.setModel(new DefaultListModel());
        jliTelefonesAdicionados.setName("jliTelefonesAdicionados"); // NOI18N
        jspTelefonesAdicionados.setViewportView(jliTelefonesAdicionados);

        jpaContatos.add(jspTelefonesAdicionados);
        jspTelefonesAdicionados.setBounds(10, 80, 280, 105);

        jbuRemoverTelefone.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuRemoverTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Remover.png"))); // NOI18N
        jbuRemoverTelefone.setMnemonic('r');
        jbuRemoverTelefone.setText("Remover");
        jbuRemoverTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuRemoverTelefone.setName("jbuRemoverTelefone"); // NOI18N
        jbuRemoverTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverTelefoneActionPerformed(evt);
            }
        });
        jpaContatos.add(jbuRemoverTelefone);
        jbuRemoverTelefone.setBounds(300, 80, 130, 33);

        jlaRamal.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaRamal.setText("Ramal");
        jlaRamal.setName("jlaRamal"); // NOI18N
        jpaContatos.add(jlaRamal);
        jlaRamal.setBounds(10, 190, 45, 17);

        try {
            jftRamal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftRamal.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftRamal.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jftRamal.setName("jftRamal"); // NOI18N
        jpaContatos.add(jftRamal);
        jftRamal.setBounds(10, 210, 70, 23);

        jlaNomeContato.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaNomeContato.setText("Nome para Contato");
        jlaNomeContato.setName("jlaNomeContato"); // NOI18N
        jpaContatos.add(jlaNomeContato);
        jlaNomeContato.setBounds(10, 240, 141, 17);

        jtfNomeContato.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfNomeContato.setName("jtfNomeContato"); // NOI18N
        jpaContatos.add(jtfNomeContato);
        jtfNomeContato.setBounds(10, 260, 360, 23);

        jlaEmail.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaEmail.setText("Email");
        jlaEmail.setName("jlaEmail"); // NOI18N
        jpaContatos.add(jlaEmail);
        jlaEmail.setBounds(10, 290, 200, 17);

        jtfEmail.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfEmail.setName("jtfEmail"); // NOI18N
        jpaContatos.add(jtfEmail);
        jtfEmail.setBounds(10, 310, 360, 23);

        jpaInformacoes.setName("jpaInformacoes"); // NOI18N

        jlaIndicadoPor.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaIndicadoPor.setText("Indicado por");
        jlaIndicadoPor.setName("jlaIndicadoPor"); // NOI18N

        jtfIndicadoPor.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfIndicadoPor.setToolTipText("");
        jtfIndicadoPor.setName("jtfIndicadoPor"); // NOI18N

        jlaStatus.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaStatus.setText("Status");
        jlaStatus.setName("jlaStatus"); // NOI18N

        jcbStatus.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbStatus.setName("jcbStatus"); // NOI18N

        jlaValorContribuicao.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaValorContribuicao.setText("Valor de contribuição (ex. 75,50)");
        jlaValorContribuicao.setName("jlaValorContribuicao"); // NOI18N

        jtfValorContribuicao.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jtfValorContribuicao.setName("jtfValorContribuicao"); // NOI18N

        jlaMotivoDesativacao.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaMotivoDesativacao.setText("Motivo de desativação");
        jlaMotivoDesativacao.setName("jlaMotivoDesativacao"); // NOI18N

        jcbMotivoDesativacao.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jcbMotivoDesativacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbMotivoDesativacao.setName("jcbMotivoDesativacao"); // NOI18N

        javax.swing.GroupLayout jpaInformacoesLayout = new javax.swing.GroupLayout(jpaInformacoes);
        jpaInformacoes.setLayout(jpaInformacoesLayout);
        jpaInformacoesLayout.setHorizontalGroup(
            jpaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfIndicadoPor)
            .addGroup(jpaInformacoesLayout.createSequentialGroup()
                .addComponent(jlaIndicadoPor)
                .addGap(0, 463, Short.MAX_VALUE))
            .addGroup(jpaInformacoesLayout.createSequentialGroup()
                .addGroup(jpaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbMotivoDesativacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpaInformacoesLayout.createSequentialGroup()
                        .addGroup(jpaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaInformacoesLayout.createSequentialGroup()
                                .addGroup(jpaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlaStatus)
                                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlaValorContribuicao)
                                    .addComponent(jtfValorContribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlaMotivoDesativacao))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpaInformacoesLayout.setVerticalGroup(
            jpaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaInformacoesLayout.createSequentialGroup()
                .addComponent(jlaIndicadoPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpaInformacoesLayout.createSequentialGroup()
                        .addComponent(jtfIndicadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlaStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpaInformacoesLayout.createSequentialGroup()
                        .addComponent(jlaValorContribuicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfValorContribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlaMotivoDesativacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbMotivoDesativacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
        );

        jlaCpf.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaCpf.setText("CPF");
        jlaCpf.setName("jlaCpf"); // NOI18N

        try {
            jftCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCpf.setToolTipText("");
        jftCpf.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftCpf.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jftCpf.setName("jftCpf"); // NOI18N

        javax.swing.GroupLayout jpaPrincipalLayout = new javax.swing.GroupLayout(jpaPrincipal);
        jpaPrincipal.setLayout(jpaPrincipalLayout);
        jpaPrincipalLayout.setHorizontalGroup(
            jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaPrincipalLayout.createSequentialGroup()
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                                .addComponent(jlaPais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(jlaUF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                                .addComponent(jcbPais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jcbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jlaMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfBairro))))
                    .addGroup(jpaPrincipalLayout.createSequentialGroup()
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                                .addComponent(jftCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                                .addComponent(jlaCEP)
                                .addGap(84, 84, 84)
                                .addComponent(jlaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaComplemento)
                            .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpaPrincipalLayout.createSequentialGroup()
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaCodigo)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDataCadastro)
                            .addComponent(jlaDataCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaNome)
                            .addComponent(jtfNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftCpf)
                            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                                .addComponent(jlaCpf)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaPrincipalLayout.createSequentialGroup()
                        .addComponent(jpaInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpaContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpaPrincipalLayout.setVerticalGroup(
            jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlaCodigo)
                        .addComponent(jlaNome)
                        .addComponent(jlaDataCadastro))
                    .addComponent(jlaCpf, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpaPrincipalLayout.createSequentialGroup()
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlaCEP)
                                .addComponent(jlaEndereco))
                            .addComponent(jlaNumero))
                        .addGap(3, 3, 3)
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpaPrincipalLayout.createSequentialGroup()
                        .addComponent(jlaComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlaPais)
                    .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlaUF)
                        .addComponent(jlaMunicipio)
                        .addComponent(jlaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpaContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpaInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpaEditarContribuintes.add(jpaPrincipal);
        jpaPrincipal.setBounds(0, 0, 1020, 540);

        jbuSalvar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Salvar.png"))); // NOI18N
        jbuSalvar.setMnemonic('S');
        jbuSalvar.setText("Salvar");
        jbuSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSalvar.setName("jbuSalvar"); // NOI18N
        jbuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSalvarActionPerformed(evt);
            }
        });
        jpaEditarContribuintes.add(jbuSalvar);
        jbuSalvar.setBounds(11, 667, 120, 33);

        jbuFechar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Fechar.png"))); // NOI18N
        jbuFechar.setMnemonic('F');
        jbuFechar.setText("Fechar");
        jbuFechar.setToolTipText("");
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });
        jpaEditarContribuintes.add(jbuFechar);
        jbuFechar.setBounds(879, 667, 130, 33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarContribuintes, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarContribuintes, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jftCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftCEPFocusLost
        controlador.carregarEndereco();
    }//GEN-LAST:event_jftCEPFocusLost

    private void jcbUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUFActionPerformed
        if (controlador != null) {
            controlador.inicializarCampoMunicipio(jcbUF, jcbMunicipio);
        }
    }//GEN-LAST:event_jcbUFActionPerformed

    private void jbuAdicionarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarTelefoneActionPerformed
        controlador.adicionarTelefone();
    }//GEN-LAST:event_jbuAdicionarTelefoneActionPerformed

    private void jbuRemoverTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverTelefoneActionPerformed
        controlador.removerTelefoneSelecionado();
    }//GEN-LAST:event_jbuRemoverTelefoneActionPerformed

    private void jbuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSalvarActionPerformed
        controlador.salvar();        // TODO add your handling code here:
    }//GEN-LAST:event_jbuSalvarActionPerformed

    private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbuAdicionarTelefone;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuRemoverTelefone;
    private javax.swing.JButton jbuSalvar;
    private javax.swing.JComboBox jcbMotivoDesativacao;
    private javax.swing.JComboBox jcbMunicipio;
    private javax.swing.JComboBox jcbPais;
    private javax.swing.JComboBox jcbStatus;
    private javax.swing.JComboBox jcbTipoTelefone;
    private javax.swing.JComboBox jcbUF;
    private javax.swing.JFormattedTextField jftCEP;
    private javax.swing.JFormattedTextField jftCpf;
    private javax.swing.JFormattedTextField jftRamal;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JLabel jlaBairro;
    private javax.swing.JLabel jlaCEP;
    private javax.swing.JLabel jlaCodigo;
    private javax.swing.JLabel jlaComplemento;
    private javax.swing.JLabel jlaCpf;
    private javax.swing.JLabel jlaDataCadastro;
    private javax.swing.JLabel jlaEmail;
    private javax.swing.JLabel jlaEndereco;
    private javax.swing.JLabel jlaIndicadoPor;
    private javax.swing.JLabel jlaMotivoDesativacao;
    private javax.swing.JLabel jlaMunicipio;
    private javax.swing.JLabel jlaNome;
    private javax.swing.JLabel jlaNomeContato;
    private javax.swing.JLabel jlaNumero;
    private javax.swing.JLabel jlaPais;
    private javax.swing.JLabel jlaRamal;
    private javax.swing.JLabel jlaStatus;
    private javax.swing.JLabel jlaTelefone;
    private javax.swing.JLabel jlaTelefonesAdicionados;
    private javax.swing.JLabel jlaTipoTelefone;
    private javax.swing.JLabel jlaUF;
    private javax.swing.JLabel jlaValorContribuicao;
    private javax.swing.JList jliTelefonesAdicionados;
    private javax.swing.JPanel jpaContatos;
    private javax.swing.JPanel jpaEditarContribuintes;
    private javax.swing.JPanel jpaInformacoes;
    private javax.swing.JPanel jpaPrincipal;
    private javax.swing.JScrollPane jspTelefonesAdicionados;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfDataCadastro;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfIndicadoPor;
    private javax.swing.JTextField jtfNomeContato;
    private javax.swing.JTextField jtfNomeEmpresa;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfValorContribuicao;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaEditarContribuicoes controlador;
}
