package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaAtendimentoIndividualEditar;
import br.laramara.ti.sislaraclient.infra.PermissaoDeTelas;
import br.laramara.ti.sislaraclient.modelos.ModeloTabelaAtendimentoAcompanhante;
import br.laramara.ti.sislaraclient.modelos.ModeloTabelaAtendimentoProfissional;
import br.laramara.ti.sislaraclient.utilitarios.JOptionPanePersonalizado;
import br.laramara.ti.sislaraclient.utilitarios.WordUtils;
import br.laramara.ti.sislaracommons.dtos.atendimento.AtendimentoIndividualDTO;
import java.awt.Window;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

public class TelaAtendimentoIndividualEditar extends javax.swing.JDialog {

    public TelaAtendimentoIndividualEditar(JDialog parent, AtendimentoIndividualDTO atendimentoIndividualDTO) {
        this(parent, false, atendimentoIndividualDTO);
    }
    
    public TelaAtendimentoIndividualEditar(Window parent, boolean forcarCarregamentoAtendimentoIndividualDTO, AtendimentoIndividualDTO atendimentoIndividualDTO) {
        super(parent, ModalityType.APPLICATION_MODAL);
        initComponents();
        setLocationRelativeTo(parent);
        controlador = new ControladorTelaAtendimentoIndividualEditar(this, forcarCarregamentoAtendimentoIndividualDTO, atendimentoIndividualDTO, jbuUtilizarUsuario, jbuUtilizarPreCadastro, jftProntuario, jtfNomeUsuario, jtfNomePreCadastro, jftData, jftHoraInicio, jftHoraTermino, jcbTipoAtendimento, jcbDescricaoTipoAtendimento, jcbModuloAtividade, jcbPrimeiraVez, jcbSetor, jcbLocalAtendimento, jatDescricao, jatInterdisciplinar, jtaProfissionais, jcbFrequencia, jatJustificativa, jcbParticipacao, jtfQuantidadePessoas, jliParticipacoesAdicionadas, jtaAcompanhante, jliArquivos, jcbTipoAcaoConduta, jftDataExpectativa, jcbGrupoConduta, jtaObs, jepInformacoesModuloAEE, jliCondutasSolicitadas, jcbIntegracao, jtaMotivoNaoIntegracao, jtaResumoIntegracao, jcbDiscussaoCaso);
        controlador.inicializarCombosComDependencia();
        controlador.abrirSomenteSeHouverPermissao(PermissaoDeTelas.ATENDIMENTO_INDIVIDUAL_TELA_EDICAO_VISUALIZAR);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jpaEditarAtendimentoIndividual = new javax.swing.JPanel();
        jtpIntegrante = new javax.swing.JTabbedPane();
        jpaUsuario = new javax.swing.JPanel();
        jlaProntuario = new javax.swing.JLabel();
        jlaNomeUsuario = new javax.swing.JLabel();
        jtfNomeUsuario = new javax.swing.JTextField();
        jbuUtilizarUsuario = new javax.swing.JButton();
        jftProntuario = new javax.swing.JFormattedTextField();
        jpaPreCadastro = new javax.swing.JPanel();
        jlaNomePreCadastro = new javax.swing.JLabel();
        jtfNomePreCadastro = new javax.swing.JTextField();
        jbuUtilizarPreCadastro = new javax.swing.JButton();
        jpaDataHora = new javax.swing.JPanel();
        jlaData = new javax.swing.JLabel();
        jftData = new javax.swing.JFormattedTextField();
        jbuSelecionarData = new javax.swing.JButton();
        jlaHoraInicio = new javax.swing.JLabel();
        jftHoraInicio = new javax.swing.JFormattedTextField();
        jlaHoraTermino = new javax.swing.JLabel();
        jftHoraTermino = new javax.swing.JFormattedTextField();
        jlaTipoAtendimento = new javax.swing.JLabel();
        jcbTipoAtendimento = new javax.swing.JComboBox();
        jlaDescricaoTipoAtendimento = new javax.swing.JLabel();
        jcbDescricaoTipoAtendimento = new javax.swing.JComboBox();
        jlaSetor = new javax.swing.JLabel();
        jcbSetor = new javax.swing.JComboBox();
        jlaModuloAtividade = new javax.swing.JLabel();
        jcbModuloAtividade = new javax.swing.JComboBox();
        jlaLocalAtendimento = new javax.swing.JLabel();
        jcbLocalAtendimento = new javax.swing.JComboBox();
        jtpRegistros = new javax.swing.JTabbedPane();
        jpaDescricaoAtendimento = new javax.swing.JPanel();
        jlaDescricao = new javax.swing.JLabel();
        jspDescricao = new javax.swing.JScrollPane();
        jatDescricao = new javax.swing.JTextArea();
        jlaInterdisciplinar = new javax.swing.JLabel();
        jspInterdisciplinar = new javax.swing.JScrollPane();
        jatInterdisciplinar = new javax.swing.JTextArea();
        jpaProfissionais = new javax.swing.JPanel();
        jlaProfissionais = new javax.swing.JLabel();
        jspProfissionais = new javax.swing.JScrollPane();
        jtaProfissionais = new javax.swing.JTable();
        jbuAdicionar = new javax.swing.JButton();
        jbuAlterar = new javax.swing.JButton();
        jbuRemover = new javax.swing.JButton();
        jpaFrequencia = new javax.swing.JPanel();
        jlaFrequencia = new javax.swing.JLabel();
        jcbFrequencia = new javax.swing.JComboBox();
        jlaJustificativa = new javax.swing.JLabel();
        jspJustificativa = new javax.swing.JScrollPane();
        jatJustificativa = new javax.swing.JTextArea();
        jpaParticipacao = new javax.swing.JPanel();
        jlaParticipacao = new javax.swing.JLabel();
        jcbParticipacao = new javax.swing.JComboBox();
        jlaQuantidadePessoas = new javax.swing.JLabel();
        jtfQuantidadePessoas = new javax.swing.JTextField();
        jbuAdicionarParticipacaoDetalhada = new javax.swing.JButton();
        jluParticipacaoDetalhasAdiconadas = new javax.swing.JLabel();
        jspParticipacoesAdicionadas = new javax.swing.JScrollPane();
        jliParticipacoesAdicionadas = new javax.swing.JList();
        jbuRemoverParticipacaoDetalhada = new javax.swing.JButton();
        jpaAcompanhante = new javax.swing.JPanel();
        jlaAcompanhante = new javax.swing.JLabel();
        jspAcompanhante = new javax.swing.JScrollPane();
        jtaAcompanhante = new javax.swing.JTable();
        jbuAdicionarAcompanhante = new javax.swing.JButton();
        jbuAlterarAcompanhante = new javax.swing.JButton();
        jbuRemoverAcompanhante = new javax.swing.JButton();
        jpaArquivos = new javax.swing.JPanel();
        jspArquivos = new javax.swing.JScrollPane();
        jliArquivos = new javax.swing.JList();
        jlaArquivos = new javax.swing.JLabel();
        jbuAdicionarArquivo = new javax.swing.JButton();
        jbuAbrirAquivo = new javax.swing.JButton();
        jbuRemoverArquivo = new javax.swing.JButton();
        jpaTriagem = new javax.swing.JPanel();
        jpaIntegracao = new javax.swing.JLabel();
        jcbIntegracao = new javax.swing.JComboBox();
        jlaMotivoNaoIntegracao = new javax.swing.JLabel();
        jspMotivoNaoIntegracao = new javax.swing.JScrollPane();
        jtaMotivoNaoIntegracao = new javax.swing.JTextArea();
        jlaDiscussaoDeCaso = new javax.swing.JLabel();
        jcbDiscussaoCaso = new javax.swing.JComboBox();
        jlaResumoIntegracao = new javax.swing.JLabel();
        jspResumoIntegracao = new javax.swing.JScrollPane();
        jtaResumoIntegracao = new javax.swing.JTextArea();
        jpaConduta = new javax.swing.JPanel();
        jlaTipoAcaoConduta = new javax.swing.JLabel();
        jcbTipoAcaoConduta = new javax.swing.JComboBox();
        jlaGrupoConduta = new javax.swing.JLabel();
        jcbGrupoConduta = new javax.swing.JComboBox();
        jlaInformacaoModuloAEE = new javax.swing.JLabel();
        jspInformacoesModuloAEE = new javax.swing.JScrollPane();
        jepInformacoesModuloAEE = new javax.swing.JEditorPane();
        jbuAdicionarConduta = new javax.swing.JButton();
        jlaCondutasSolicitadas = new javax.swing.JLabel();
        jspCondutasSolicitadas = new javax.swing.JScrollPane();
        jliCondutasSolicitadas = new javax.swing.JList();
        jbuCancelarConduta = new javax.swing.JButton();
        jlaDataExpectativa = new javax.swing.JLabel();
        jftDataExpectativa = new javax.swing.JFormattedTextField();
        jbuDataExpectativa = new javax.swing.JButton();
        jlaObs = new javax.swing.JLabel();
        jspObs = new javax.swing.JScrollPane();
        jtaObs = new javax.swing.JTextArea();
        jbuSalvar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();
        jlaPrimeiraVez = new javax.swing.JLabel();
        jcbPrimeiraVez = new javax.swing.JComboBox();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(TelaAtendimentoIndividualEditar.class);
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jpaEditarAtendimentoIndividual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpaEditarAtendimentoIndividual.setName("jpaEditarAtendimentoIndividual"); // NOI18N
        jpaEditarAtendimentoIndividual.setLayout(null);

        jtpIntegrante.setFont(resourceMap.getFont("jtpIntegrante.font")); // NOI18N
        jtpIntegrante.setName("jtpIntegrante"); // NOI18N

        jpaUsuario.setName("jpaUsuario"); // NOI18N
        jpaUsuario.setLayout(null);

        jlaProntuario.setFont(resourceMap.getFont("jlaProntuario.font")); // NOI18N
        jlaProntuario.setText(resourceMap.getString("jlaProntuario.text")); // NOI18N
        jlaProntuario.setName("jlaProntuario"); // NOI18N
        jpaUsuario.add(jlaProntuario);
        jlaProntuario.setBounds(10, 11, 80, 17);

        jlaNomeUsuario.setFont(resourceMap.getFont("jlaProntuario.font")); // NOI18N
        jlaNomeUsuario.setText(resourceMap.getString("jlaNomeUsuario.text")); // NOI18N
        jlaNomeUsuario.setName("jlaNomeUsuario"); // NOI18N
        jpaUsuario.add(jlaNomeUsuario);
        jlaNomeUsuario.setBounds(99, 11, 42, 17);

        jtfNomeUsuario.setEditable(false);
        jtfNomeUsuario.setFont(resourceMap.getFont("jlaProntuario.font")); // NOI18N
        jtfNomeUsuario.setText(resourceMap.getString("jtfNomeUsuario.text")); // NOI18N
        jtfNomeUsuario.setName("jtfNomeUsuario"); // NOI18N
        jpaUsuario.add(jtfNomeUsuario);
        jtfNomeUsuario.setBounds(99, 31, 450, 23);
        jtfNomeUsuario.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfNomeUsuario.AccessibleContext.accessibleName")); // NOI18N

        jbuUtilizarUsuario.setFont(resourceMap.getFont("jbuUtilizarUsuario.font")); // NOI18N
        jbuUtilizarUsuario.setIcon(resourceMap.getIcon("jbuUtilizarUsuario.icon")); // NOI18N
        jbuUtilizarUsuario.setMnemonic('U');
        jbuUtilizarUsuario.setText(resourceMap.getString("jbuUtilizarUsuario.text")); // NOI18N
        jbuUtilizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuUtilizarUsuario.setName("jbuUtilizarUsuario"); // NOI18N
        jbuUtilizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuUtilizarUsuarioActionPerformed(evt);
            }
        });
        jpaUsuario.add(jbuUtilizarUsuario);
        jbuUtilizarUsuario.setBounds(555, 26, 120, 33);
        jbuUtilizarUsuario.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuUtilizarUsuario.AccessibleContext.accessibleName")); // NOI18N

        try {
            jftProntuario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftProntuario.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftProntuario.setFont(resourceMap.getFont("jftProntuario.font")); // NOI18N
        jftProntuario.setName("jftProntuario"); // NOI18N
        jftProntuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftProntuarioFocusLost(evt);
            }
        });
        jpaUsuario.add(jftProntuario);
        jftProntuario.setBounds(10, 31, 80, 23);
        jftProntuario.getAccessibleContext().setAccessibleName(resourceMap.getString("jftProntuario.AccessibleContext.accessibleName")); // NOI18N

        jtpIntegrante.addTab(resourceMap.getString("jpaUsuario.TabConstraints.tabTitle"), jpaUsuario); // NOI18N

        jpaPreCadastro.setName("jpaPreCadastro"); // NOI18N
        jpaPreCadastro.setLayout(null);

        jlaNomePreCadastro.setFont(resourceMap.getFont("jtfNomePreCadastro.font")); // NOI18N
        jlaNomePreCadastro.setText(resourceMap.getString("jlaNomePreCadastro.text")); // NOI18N
        jlaNomePreCadastro.setName("jlaNomePreCadastro"); // NOI18N
        jpaPreCadastro.add(jlaNomePreCadastro);
        jlaNomePreCadastro.setBounds(10, 11, 42, 17);

        jtfNomePreCadastro.setEditable(false);
        jtfNomePreCadastro.setFont(resourceMap.getFont("jtfNomePreCadastro.font")); // NOI18N
        jtfNomePreCadastro.setText(resourceMap.getString("jtfNomePreCadastro.text")); // NOI18N
        jtfNomePreCadastro.setName("jtfNomePreCadastro"); // NOI18N
        jpaPreCadastro.add(jtfNomePreCadastro);
        jtfNomePreCadastro.setBounds(10, 30, 540, 23);
        jtfNomePreCadastro.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfNomePreCadastro.AccessibleContext.accessibleName")); // NOI18N

        jbuUtilizarPreCadastro.setFont(resourceMap.getFont("jbuUtilizarPreCadastro.font")); // NOI18N
        jbuUtilizarPreCadastro.setIcon(resourceMap.getIcon("jbuUtilizarPreCadastro.icon")); // NOI18N
        jbuUtilizarPreCadastro.setMnemonic('U');
        jbuUtilizarPreCadastro.setText(resourceMap.getString("jbuUtilizarPreCadastro.text")); // NOI18N
        jbuUtilizarPreCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuUtilizarPreCadastro.setName("jbuUtilizarPreCadastro"); // NOI18N
        jbuUtilizarPreCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuUtilizarPreCadastroActionPerformed(evt);
            }
        });
        jpaPreCadastro.add(jbuUtilizarPreCadastro);
        jbuUtilizarPreCadastro.setBounds(555, 26, 120, 33);
        jbuUtilizarPreCadastro.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuUtilizarPreCadastro.AccessibleContext.accessibleName")); // NOI18N

        jtpIntegrante.addTab(resourceMap.getString("jpaPreCadastro.TabConstraints.tabTitle"), jpaPreCadastro); // NOI18N

        jpaEditarAtendimentoIndividual.add(jtpIntegrante);
        jtpIntegrante.setBounds(10, 10, 690, 120);

        jpaDataHora.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jpaDataHora.border.lineColor"))); // NOI18N
        jpaDataHora.setName("jpaDataHora"); // NOI18N
        jpaDataHora.setLayout(null);

        jlaData.setFont(resourceMap.getFont("jlaHoraTermino.font")); // NOI18N
        jlaData.setText(resourceMap.getString("jlaData.text")); // NOI18N
        jlaData.setName("jlaData"); // NOI18N
        jpaDataHora.add(jlaData);
        jlaData.setBounds(10, 5, 50, 17);

        try {
            jftData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftData.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftData.setFont(resourceMap.getFont("jftData.font")); // NOI18N
        jftData.setName("jftData"); // NOI18N
        jpaDataHora.add(jftData);
        jftData.setBounds(10, 25, 100, 23);
        jftData.getAccessibleContext().setAccessibleName(resourceMap.getString("jFormattedTextField1.AccessibleContext.accessibleName")); // NOI18N
        jftData.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jFormattedTextField1.AccessibleContext.accessibleDescription")); // NOI18N

        jbuSelecionarData.setIcon(resourceMap.getIcon("jbuSelecionarData.icon")); // NOI18N
        jbuSelecionarData.setText(resourceMap.getString("jbuSelecionarData.text")); // NOI18N
        jbuSelecionarData.setBorderPainted(false);
        jbuSelecionarData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSelecionarData.setName("jbuSelecionarData"); // NOI18N
        jbuSelecionarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSelecionarDataActionPerformed(evt);
            }
        });
        jpaDataHora.add(jbuSelecionarData);
        jbuSelecionarData.setBounds(114, 24, 25, 25);
        jbuSelecionarData.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuSelecionarData.AccessibleContext.accessibleName")); // NOI18N
        jbuSelecionarData.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jbuSelecionarData.AccessibleContext.accessibleDescription")); // NOI18N

        jlaHoraInicio.setFont(resourceMap.getFont("jlaHoraTermino.font")); // NOI18N
        jlaHoraInicio.setText(resourceMap.getString("jlaHoraInicio.text")); // NOI18N
        jlaHoraInicio.setName("jlaHoraInicio"); // NOI18N
        jpaDataHora.add(jlaHoraInicio);
        jlaHoraInicio.setBounds(10, 60, 80, 17);

        try {
            jftHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftHoraInicio.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftHoraInicio.setFont(resourceMap.getFont("jftHoraInicio.font")); // NOI18N
        jftHoraInicio.setName("jftHoraInicio"); // NOI18N
        jpaDataHora.add(jftHoraInicio);
        jftHoraInicio.setBounds(10, 80, 100, 23);
        jftHoraInicio.getAccessibleContext().setAccessibleName(resourceMap.getString("jFormattedTextField2.AccessibleContext.accessibleName")); // NOI18N
        jftHoraInicio.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jFormattedTextField2.AccessibleContext.accessibleDescription")); // NOI18N

        jlaHoraTermino.setFont(resourceMap.getFont("jlaHoraTermino.font")); // NOI18N
        jlaHoraTermino.setText(resourceMap.getString("jlaHoraTermino.text")); // NOI18N
        jlaHoraTermino.setName("jlaHoraTermino"); // NOI18N
        jpaDataHora.add(jlaHoraTermino);
        jlaHoraTermino.setBounds(10, 110, 100, 16);

        try {
            jftHoraTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftHoraTermino.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftHoraTermino.setFont(resourceMap.getFont("jftHoraTermino.font")); // NOI18N
        jftHoraTermino.setName("jftHoraTermino"); // NOI18N
        jpaDataHora.add(jftHoraTermino);
        jftHoraTermino.setBounds(10, 130, 100, 23);
        jftHoraTermino.getAccessibleContext().setAccessibleName(resourceMap.getString("jftHoraTermino.AccessibleContext.accessibleName")); // NOI18N
        jftHoraTermino.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jftHoraTermino.AccessibleContext.accessibleDescription")); // NOI18N

        jpaEditarAtendimentoIndividual.add(jpaDataHora);
        jpaDataHora.setBounds(710, 10, 155, 170);

        jlaTipoAtendimento.setFont(resourceMap.getFont("jlaTipoAtendimento.font")); // NOI18N
        jlaTipoAtendimento.setText(resourceMap.getString("jlaTipoAtendimento.text")); // NOI18N
        jlaTipoAtendimento.setName("jlaTipoAtendimento"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaTipoAtendimento);
        jlaTipoAtendimento.setBounds(10, 140, 290, 17);

        jcbTipoAtendimento.setFont(resourceMap.getFont("jcbTipoAtendimento.font")); // NOI18N
        jcbTipoAtendimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbTipoAtendimento.setName("jcbTipoAtendimento"); // NOI18N
        jcbTipoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoAtendimentoActionPerformed(evt);
            }
        });
        jpaEditarAtendimentoIndividual.add(jcbTipoAtendimento);
        jcbTipoAtendimento.setBounds(10, 160, 690, 23);
        jcbTipoAtendimento.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbTipoAtendimento.AccessibleContext.accessibleName")); // NOI18N

        jlaDescricaoTipoAtendimento.setFont(resourceMap.getFont("jlaDescricaoTipoAtendimento.font")); // NOI18N
        jlaDescricaoTipoAtendimento.setText(resourceMap.getString("jlaDescricaoTipoAtendimento.text")); // NOI18N
        jlaDescricaoTipoAtendimento.setName("jlaDescricaoTipoAtendimento"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaDescricaoTipoAtendimento);
        jlaDescricaoTipoAtendimento.setBounds(10, 190, 270, 17);

        jcbDescricaoTipoAtendimento.setFont(resourceMap.getFont("jcbDescricaoTipoAtendimento.font")); // NOI18N
        jcbDescricaoTipoAtendimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbDescricaoTipoAtendimento.setName("jcbDescricaoTipoAtendimento"); // NOI18N
        jcbDescricaoTipoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDescricaoTipoAtendimentoActionPerformed(evt);
            }
        });
        jpaEditarAtendimentoIndividual.add(jcbDescricaoTipoAtendimento);
        jcbDescricaoTipoAtendimento.setBounds(10, 210, 690, 23);
        jcbDescricaoTipoAtendimento.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbDescricaoTipoAtendimento.AccessibleContext.accessibleName")); // NOI18N

        jlaSetor.setFont(resourceMap.getFont("jlaSetor.font")); // NOI18N
        jlaSetor.setText(resourceMap.getString("jlaSetor.text")); // NOI18N
        jlaSetor.setName("jlaSetor"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaSetor);
        jlaSetor.setBounds(710, 190, 60, 17);

        jcbSetor.setFont(resourceMap.getFont("jcbSetor.font")); // NOI18N
        jcbSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbSetor.setName("jcbSetor"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jcbSetor);
        jcbSetor.setBounds(710, 210, 170, 23);
        jcbSetor.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbSetor.AccessibleContext.accessibleName")); // NOI18N

        jlaModuloAtividade.setFont(resourceMap.getFont("jlaModuloAtividade.font")); // NOI18N
        jlaModuloAtividade.setText(resourceMap.getString("jlaModuloAtividade.text")); // NOI18N
        jlaModuloAtividade.setName("jlaModuloAtividade"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaModuloAtividade);
        jlaModuloAtividade.setBounds(10, 240, 150, 17);

        jcbModuloAtividade.setFont(resourceMap.getFont("jcbModuloAtividade.font")); // NOI18N
        jcbModuloAtividade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbModuloAtividade.setName("jcbModuloAtividade"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jcbModuloAtividade);
        jcbModuloAtividade.setBounds(10, 260, 690, 23);
        jcbModuloAtividade.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbModuloAtividade.AccessibleContext.accessibleName")); // NOI18N

        jlaLocalAtendimento.setFont(resourceMap.getFont("jlaLocalAtendimento.font")); // NOI18N
        jlaLocalAtendimento.setText(resourceMap.getString("jlaLocalAtendimento.text")); // NOI18N
        jlaLocalAtendimento.setName("jlaLocalAtendimento"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaLocalAtendimento);
        jlaLocalAtendimento.setBounds(10, 290, 240, 17);

        jcbLocalAtendimento.setFont(resourceMap.getFont("jcbLocalAtendimento.font")); // NOI18N
        jcbLocalAtendimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbLocalAtendimento.setName("jcbLocalAtendimento"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jcbLocalAtendimento);
        jcbLocalAtendimento.setBounds(10, 310, 690, 23);
        jcbLocalAtendimento.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbLocalAtendimento.AccessibleContext.accessibleName")); // NOI18N

        jtpRegistros.setAutoscrolls(true);
        jtpRegistros.setFont(resourceMap.getFont("jtpRegistros.font")); // NOI18N
        jtpRegistros.setName("jtpRegistros"); // NOI18N

        jpaDescricaoAtendimento.setName("jpaDescricaoAtendimento"); // NOI18N
        jpaDescricaoAtendimento.setLayout(null);

        jlaDescricao.setFont(resourceMap.getFont("jlaDescricao.font")); // NOI18N
        jlaDescricao.setText(resourceMap.getString("jlaDescricao.text")); // NOI18N
        jlaDescricao.setName("jlaDescricao"); // NOI18N
        jpaDescricaoAtendimento.add(jlaDescricao);
        jlaDescricao.setBounds(10, 10, 210, 17);

        jspDescricao.setName("jspDescricao"); // NOI18N

        jatDescricao.setColumns(20);
        jatDescricao.setFont(resourceMap.getFont("jatDescricao.font")); // NOI18N
        jatDescricao.setLineWrap(true);
        jatDescricao.setRows(5);
        jatDescricao.setWrapStyleWord(true);
        jatDescricao.setName("jatDescricao"); // NOI18N
        jatDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jatDescricaoKeyPressed(evt);
            }
        });
        jspDescricao.setViewportView(jatDescricao);
        jatDescricao.getAccessibleContext().setAccessibleName(resourceMap.getString("jatDescricao.AccessibleContext.accessibleName")); // NOI18N
        jatDescricao.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jatDescricao.AccessibleContext.accessibleDescription")); // NOI18N

        jpaDescricaoAtendimento.add(jspDescricao);
        jspDescricao.setBounds(10, 30, 490, 200);

        jlaInterdisciplinar.setFont(resourceMap.getFont("jlaDescricao.font")); // NOI18N
        jlaInterdisciplinar.setText(resourceMap.getString("jlaInterdisciplinar.text")); // NOI18N
        jlaInterdisciplinar.setName("jlaInterdisciplinar"); // NOI18N
        jpaDescricaoAtendimento.add(jlaInterdisciplinar);
        jlaInterdisciplinar.setBounds(510, 10, 130, 17);

        jspInterdisciplinar.setName("jspInterdisciplinar"); // NOI18N

        jatInterdisciplinar.setColumns(20);
        jatInterdisciplinar.setFont(resourceMap.getFont("jatInterdisciplinar.font")); // NOI18N
        jatInterdisciplinar.setLineWrap(true);
        jatInterdisciplinar.setRows(5);
        jatInterdisciplinar.setWrapStyleWord(true);
        jatInterdisciplinar.setName("jatInterdisciplinar"); // NOI18N
        jatInterdisciplinar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jatInterdisciplinarKeyPressed(evt);
            }
        });
        jspInterdisciplinar.setViewportView(jatInterdisciplinar);
        jatInterdisciplinar.getAccessibleContext().setAccessibleName(resourceMap.getString("jatInterdisciplinar.AccessibleContext.accessibleName")); // NOI18N
        jatInterdisciplinar.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jatInterdisciplinar.AccessibleContext.accessibleDescription")); // NOI18N

        jpaDescricaoAtendimento.add(jspInterdisciplinar);
        jspInterdisciplinar.setBounds(510, 30, 490, 200);

        jtpRegistros.addTab(resourceMap.getString("jpaDescricaoAtendimento.TabConstraints.tabTitle"), jpaDescricaoAtendimento); // NOI18N

        jpaProfissionais.setName("jpaProfissionais"); // NOI18N
        jpaProfissionais.setLayout(null);

        jlaProfissionais.setFont(resourceMap.getFont("jlaProfissionais.font")); // NOI18N
        jlaProfissionais.setText(resourceMap.getString("jlaProfissionais.text")); // NOI18N
        jlaProfissionais.setToolTipText(resourceMap.getString("jlaProfissionais.toolTipText")); // NOI18N
        jlaProfissionais.setName("jlaProfissionais"); // NOI18N
        jpaProfissionais.add(jlaProfissionais);
        jlaProfissionais.setBounds(10, 10, 180, 17);

        jspProfissionais.setName("jspProfissionais"); // NOI18N

        jtaProfissionais.setAutoCreateRowSorter(true);
        jtaProfissionais.setFont(resourceMap.getFont("jtaProfissionais.font")); // NOI18N
        jtaProfissionais.setModel(new ModeloTabelaAtendimentoProfissional());
        jtaProfissionais.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtaProfissionais.setName("jtaProfissionais"); // NOI18N
        jtaProfissionais.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtaProfissionais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaProfissionaisKeyPressed(evt);
            }
        });
        jspProfissionais.setViewportView(jtaProfissionais);
        jtaProfissionais.getAccessibleContext().setAccessibleName(resourceMap.getString("jtaProfissionais.AccessibleContext.accessibleName")); // NOI18N

        jpaProfissionais.add(jspProfissionais);
        jspProfissionais.setBounds(10, 30, 850, 210);

        jbuAdicionar.setFont(resourceMap.getFont("jbuAdicionar.font")); // NOI18N
        jbuAdicionar.setIcon(resourceMap.getIcon("jbuAdicionar.icon")); // NOI18N
        jbuAdicionar.setMnemonic('A');
        jbuAdicionar.setText(resourceMap.getString("jbuAdicionar.text")); // NOI18N
        jbuAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAdicionar.setName("jbuAdicionar"); // NOI18N
        jbuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarActionPerformed(evt);
            }
        });
        jpaProfissionais.add(jbuAdicionar);
        jbuAdicionar.setBounds(870, 30, 130, 33);
        jbuAdicionar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAdicionar.AccessibleContext.accessibleName")); // NOI18N

        jbuAlterar.setFont(resourceMap.getFont("jbuAlterar.font")); // NOI18N
        jbuAlterar.setIcon(resourceMap.getIcon("jbuAlterar.icon")); // NOI18N
        jbuAlterar.setMnemonic('e');
        jbuAlterar.setText(resourceMap.getString("jbuAlterar.text")); // NOI18N
        jbuAlterar.setToolTipText(resourceMap.getString("jbuAlterar.toolTipText")); // NOI18N
        jbuAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAlterar.setName("jbuAlterar"); // NOI18N
        jbuAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAlterarActionPerformed(evt);
            }
        });
        jpaProfissionais.add(jbuAlterar);
        jbuAlterar.setBounds(870, 70, 130, 33);
        jbuAlterar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAlterar.AccessibleContext.accessibleName")); // NOI18N

        jbuRemover.setFont(resourceMap.getFont("jbuRemover.font")); // NOI18N
        jbuRemover.setIcon(resourceMap.getIcon("jbuRemover.icon")); // NOI18N
        jbuRemover.setMnemonic('R');
        jbuRemover.setText(resourceMap.getString("jbuRemover.text")); // NOI18N
        jbuRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuRemover.setName("jbuRemover"); // NOI18N
        jbuRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverActionPerformed(evt);
            }
        });
        jpaProfissionais.add(jbuRemover);
        jbuRemover.setBounds(870, 110, 130, 33);
        jbuRemover.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuRemover.AccessibleContext.accessibleName")); // NOI18N

        jtpRegistros.addTab(resourceMap.getString("jpaProfissionais.TabConstraints.tabTitle"), jpaProfissionais); // NOI18N

        jpaFrequencia.setName("jpaFrequencia"); // NOI18N
        jpaFrequencia.setLayout(null);

        jlaFrequencia.setFont(resourceMap.getFont("jlaJustificativa.font")); // NOI18N
        jlaFrequencia.setText(resourceMap.getString("jlaFrequencia.text")); // NOI18N
        jlaFrequencia.setName("jlaFrequencia"); // NOI18N
        jpaFrequencia.add(jlaFrequencia);
        jlaFrequencia.setBounds(10, 10, 110, 17);

        jcbFrequencia.setFont(resourceMap.getFont("jcbFrequencia.font")); // NOI18N
        jcbFrequencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbFrequencia.setName("jcbFrequencia"); // NOI18N
        jpaFrequencia.add(jcbFrequencia);
        jcbFrequencia.setBounds(10, 30, 130, 23);
        jcbFrequencia.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbFrequencia.AccessibleContext.accessibleName")); // NOI18N

        jlaJustificativa.setFont(resourceMap.getFont("jlaJustificativa.font")); // NOI18N
        jlaJustificativa.setText(resourceMap.getString("jlaJustificativa.text")); // NOI18N
        jlaJustificativa.setName("jlaJustificativa"); // NOI18N
        jpaFrequencia.add(jlaJustificativa);
        jlaJustificativa.setBounds(10, 60, 150, 17);

        jspJustificativa.setName("jspJustificativa"); // NOI18N

        jatJustificativa.setFont(resourceMap.getFont("jatJustificativa.font")); // NOI18N
        jatJustificativa.setLineWrap(true);
        jatJustificativa.setRows(5);
        jatJustificativa.setWrapStyleWord(true);
        jatJustificativa.setName("jatJustificativa"); // NOI18N
        jatJustificativa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jatJustificativaKeyPressed(evt);
            }
        });
        jspJustificativa.setViewportView(jatJustificativa);

        jpaFrequencia.add(jspJustificativa);
        jspJustificativa.setBounds(10, 80, 990, 160);

        jtpRegistros.addTab(resourceMap.getString("jpaFrequencia.TabConstraints.tabTitle"), jpaFrequencia); // NOI18N

        jpaParticipacao.setName("jpaParticipacao"); // NOI18N

        jlaParticipacao.setFont(resourceMap.getFont("jlaParticipacao.font")); // NOI18N
        jlaParticipacao.setText(resourceMap.getString("jlaParticipacao.text")); // NOI18N
        jlaParticipacao.setToolTipText(resourceMap.getString("jlaParticipacao.toolTipText")); // NOI18N
        jlaParticipacao.setName("jlaParticipacao"); // NOI18N

        jcbParticipacao.setFont(resourceMap.getFont("jcbParticipacao.font")); // NOI18N
        jcbParticipacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbParticipacao.setName("jcbParticipacao"); // NOI18N
        jcbParticipacao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbParticipacaoItemStateChanged(evt);
            }
        });

        jlaQuantidadePessoas.setFont(resourceMap.getFont("jlaQuantidadePessoas.font")); // NOI18N
        jlaQuantidadePessoas.setText(resourceMap.getString("jlaQuantidadePessoas.text")); // NOI18N
        jlaQuantidadePessoas.setName("jlaQuantidadePessoas"); // NOI18N

        jtfQuantidadePessoas.setFont(resourceMap.getFont("jtfQuantidadePessoas.font")); // NOI18N
        jtfQuantidadePessoas.setText(resourceMap.getString("jtfQuantidadePessoas.text")); // NOI18N
        jtfQuantidadePessoas.setToolTipText(resourceMap.getString("jtfQuantidadePessoas.toolTipText")); // NOI18N
        jtfQuantidadePessoas.setName("jtfQuantidadePessoas"); // NOI18N

        jbuAdicionarParticipacaoDetalhada.setFont(resourceMap.getFont("jbuAdicionarParticipacaoDetalhada.font")); // NOI18N
        jbuAdicionarParticipacaoDetalhada.setIcon(resourceMap.getIcon("jbuAdicionarParticipacaoDetalhada.icon")); // NOI18N
        jbuAdicionarParticipacaoDetalhada.setMnemonic('A');
        jbuAdicionarParticipacaoDetalhada.setText(resourceMap.getString("jbuAdicionarParticipacaoDetalhada.text")); // NOI18N
        jbuAdicionarParticipacaoDetalhada.setToolTipText(resourceMap.getString("jbuAdicionarParticipacaoDetalhada.toolTipText")); // NOI18N
        jbuAdicionarParticipacaoDetalhada.setName("jbuAdicionarParticipacaoDetalhada"); // NOI18N
        jbuAdicionarParticipacaoDetalhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarParticipacaoDetalhadaActionPerformed(evt);
            }
        });

        jluParticipacaoDetalhasAdiconadas.setFont(resourceMap.getFont("jluParticipacaoDetalhasAdiconadas.font")); // NOI18N
        jluParticipacaoDetalhasAdiconadas.setText(resourceMap.getString("jluParticipacaoDetalhasAdiconadas.text")); // NOI18N
        jluParticipacaoDetalhasAdiconadas.setName("jluParticipacaoDetalhasAdiconadas"); // NOI18N

        jspParticipacoesAdicionadas.setName("jspParticipacoesAdicionadas"); // NOI18N

        jliParticipacoesAdicionadas.setFont(resourceMap.getFont("jliParticipacoesAdicionadas.font")); // NOI18N
        jliParticipacoesAdicionadas.setModel(new DefaultListModel());
        jliParticipacoesAdicionadas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jliParticipacoesAdicionadas.setName("jliParticipacoesAdicionadas"); // NOI18N
        jspParticipacoesAdicionadas.setViewportView(jliParticipacoesAdicionadas);
        jliParticipacoesAdicionadas.getAccessibleContext().setAccessibleName(resourceMap.getString("jliParticipacoesAdicionadas.AccessibleContext.accessibleName")); // NOI18N

        jbuRemoverParticipacaoDetalhada.setFont(resourceMap.getFont("jbuRemoverParticipacaoDetalhada.font")); // NOI18N
        jbuRemoverParticipacaoDetalhada.setIcon(resourceMap.getIcon("jbuRemoverParticipacaoDetalhada.icon")); // NOI18N
        jbuRemoverParticipacaoDetalhada.setMnemonic('R');
        jbuRemoverParticipacaoDetalhada.setText(resourceMap.getString("jbuRemoverParticipacaoDetalhada.text")); // NOI18N
        jbuRemoverParticipacaoDetalhada.setToolTipText(resourceMap.getString("jbuRemoverParticipacaoDetalhada.toolTipText")); // NOI18N
        jbuRemoverParticipacaoDetalhada.setName("jbuRemoverParticipacaoDetalhada"); // NOI18N
        jbuRemoverParticipacaoDetalhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverParticipacaoDetalhadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaParticipacaoLayout = new javax.swing.GroupLayout(jpaParticipacao);
        jpaParticipacao.setLayout(jpaParticipacaoLayout);
        jpaParticipacaoLayout.setHorizontalGroup(
            jpaParticipacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaParticipacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaParticipacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jluParticipacaoDetalhasAdiconadas)
                    .addGroup(jpaParticipacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jspParticipacoesAdicionadas, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpaParticipacaoLayout.createSequentialGroup()
                            .addGroup(jpaParticipacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbParticipacao, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlaParticipacao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jpaParticipacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlaQuantidadePessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfQuantidadePessoas)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaParticipacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuRemoverParticipacaoDetalhada)
                    .addComponent(jbuAdicionarParticipacaoDetalhada))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jpaParticipacaoLayout.setVerticalGroup(
            jpaParticipacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaParticipacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaParticipacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlaParticipacao)
                    .addComponent(jlaQuantidadePessoas))
                .addGap(8, 8, 8)
                .addGroup(jpaParticipacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaParticipacaoLayout.createSequentialGroup()
                        .addComponent(jbuAdicionarParticipacaoDetalhada)
                        .addGap(19, 19, 19)
                        .addComponent(jbuRemoverParticipacaoDetalhada))
                    .addGroup(jpaParticipacaoLayout.createSequentialGroup()
                        .addGroup(jpaParticipacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbParticipacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfQuantidadePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jluParticipacaoDetalhasAdiconadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspParticipacoesAdicionadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jcbParticipacao.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbParticipacao.AccessibleContext.accessibleName")); // NOI18N
        jtfQuantidadePessoas.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfQuantidadePessoas.AccessibleContext.accessibleName")); // NOI18N
        jbuAdicionarParticipacaoDetalhada.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAdicionarParticipacaoDetalhada.AccessibleContext.accessibleName")); // NOI18N
        jbuRemoverParticipacaoDetalhada.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuRemoverParticipacaoDetalhada.AccessibleContext.accessibleName")); // NOI18N

        jtpRegistros.addTab(resourceMap.getString("jpaParticipacao.TabConstraints.tabTitle"), jpaParticipacao); // NOI18N

        jpaAcompanhante.setName("jpaAcompanhante"); // NOI18N

        jlaAcompanhante.setFont(resourceMap.getFont("jlaAcompanhante.font")); // NOI18N
        jlaAcompanhante.setText(resourceMap.getString("jlaAcompanhante.text")); // NOI18N
        jlaAcompanhante.setName("jlaAcompanhante"); // NOI18N

        jspAcompanhante.setName("jspAcompanhante"); // NOI18N

        jtaAcompanhante.setAutoCreateRowSorter(true);
        jtaAcompanhante.setFont(resourceMap.getFont("jtaAcompanhante.font")); // NOI18N
        jtaAcompanhante.setModel(new ModeloTabelaAtendimentoAcompanhante());
        jtaAcompanhante.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtaAcompanhante.setName("jtaAcompanhante"); // NOI18N
        jtaAcompanhante.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtaAcompanhante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaAcompanhanteKeyPressed(evt);
            }
        });
        jspAcompanhante.setViewportView(jtaAcompanhante);
        jtaAcompanhante.getAccessibleContext().setAccessibleName(resourceMap.getString("jtaAcompanhante.AccessibleContext.accessibleName")); // NOI18N

        jbuAdicionarAcompanhante.setFont(resourceMap.getFont("jbuAdicionarAcompanhante.font")); // NOI18N
        jbuAdicionarAcompanhante.setIcon(resourceMap.getIcon("jbuAdicionarAcompanhante.icon")); // NOI18N
        jbuAdicionarAcompanhante.setMnemonic('A');
        jbuAdicionarAcompanhante.setText(resourceMap.getString("jbuAdicionarAcompanhante.text")); // NOI18N
        jbuAdicionarAcompanhante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAdicionarAcompanhante.setName("jbuAdicionarAcompanhante"); // NOI18N
        jbuAdicionarAcompanhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarAcompanhanteActionPerformed(evt);
            }
        });

        jbuAlterarAcompanhante.setFont(resourceMap.getFont("jbuAlterarAcompanhante.font")); // NOI18N
        jbuAlterarAcompanhante.setIcon(resourceMap.getIcon("jbuAlterarAcompanhante.icon")); // NOI18N
        jbuAlterarAcompanhante.setMnemonic('e');
        jbuAlterarAcompanhante.setText(resourceMap.getString("jbuAlterarAcompanhante.text")); // NOI18N
        jbuAlterarAcompanhante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAlterarAcompanhante.setName("jbuAlterarAcompanhante"); // NOI18N
        jbuAlterarAcompanhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAlterarAcompanhanteActionPerformed(evt);
            }
        });

        jbuRemoverAcompanhante.setFont(resourceMap.getFont("jbuRemoverAcompanhante.font")); // NOI18N
        jbuRemoverAcompanhante.setIcon(resourceMap.getIcon("jbuRemoverAcompanhante.icon")); // NOI18N
        jbuRemoverAcompanhante.setMnemonic('r');
        jbuRemoverAcompanhante.setText(resourceMap.getString("jbuRemoverAcompanhante.text")); // NOI18N
        jbuRemoverAcompanhante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuRemoverAcompanhante.setName("jbuRemoverAcompanhante"); // NOI18N
        jbuRemoverAcompanhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverAcompanhanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaAcompanhanteLayout = new javax.swing.GroupLayout(jpaAcompanhante);
        jpaAcompanhante.setLayout(jpaAcompanhanteLayout);
        jpaAcompanhanteLayout.setHorizontalGroup(
            jpaAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaAcompanhanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaAcompanhanteLayout.createSequentialGroup()
                        .addComponent(jlaAcompanhante)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpaAcompanhanteLayout.createSequentialGroup()
                        .addComponent(jspAcompanhante, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpaAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbuAlterarAcompanhante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuRemoverAcompanhante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuAdicionarAcompanhante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpaAcompanhanteLayout.setVerticalGroup(
            jpaAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaAcompanhanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlaAcompanhante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaAcompanhanteLayout.createSequentialGroup()
                        .addComponent(jbuAdicionarAcompanhante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuAlterarAcompanhante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuRemoverAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jspAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbuAdicionarAcompanhante.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAdicionarAcompanhante.AccessibleContext.accessibleName")); // NOI18N
        jbuAlterarAcompanhante.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAlterarAcompanhante.AccessibleContext.accessibleName")); // NOI18N
        jbuRemoverAcompanhante.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuRemoverAcompanhante.AccessibleContext.accessibleName")); // NOI18N
        jbuRemoverAcompanhante.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jbuRemoverAcompanhante.AccessibleContext.accessibleDescription")); // NOI18N

        jtpRegistros.addTab(resourceMap.getString("jpaAcompanhante.TabConstraints.tabTitle"), jpaAcompanhante); // NOI18N

        jpaArquivos.setFont(resourceMap.getFont("jpaArquivos.font")); // NOI18N
        jpaArquivos.setName("jpaArquivos"); // NOI18N

        jspArquivos.setName("jspArquivos"); // NOI18N

        jliArquivos.setFont(resourceMap.getFont("jliArquivos.font")); // NOI18N
        jliArquivos.setModel(new DefaultListModel());
        jliArquivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jliArquivos.setName("jliArquivos"); // NOI18N
        jspArquivos.setViewportView(jliArquivos);
        jliArquivos.getAccessibleContext().setAccessibleName(resourceMap.getString("jliArquivos.AccessibleContext.accessibleName")); // NOI18N

        jlaArquivos.setFont(resourceMap.getFont("jlaArquivos.font")); // NOI18N
        jlaArquivos.setText(resourceMap.getString("jlaArquivos.text")); // NOI18N
        jlaArquivos.setName("jlaArquivos"); // NOI18N

        jbuAdicionarArquivo.setFont(resourceMap.getFont("jbuAdicionarArquivo.font")); // NOI18N
        jbuAdicionarArquivo.setIcon(resourceMap.getIcon("jbuAdicionarArquivo.icon")); // NOI18N
        jbuAdicionarArquivo.setMnemonic('d');
        jbuAdicionarArquivo.setText(resourceMap.getString("jbuAdicionarArquivo.text")); // NOI18N
        jbuAdicionarArquivo.setToolTipText(resourceMap.getString("jbuAdicionarArquivo.toolTipText")); // NOI18N
        jbuAdicionarArquivo.setName("jbuAdicionarArquivo"); // NOI18N
        jbuAdicionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarArquivoActionPerformed(evt);
            }
        });

        jbuAbrirAquivo.setFont(resourceMap.getFont("jbuAbrirAquivo.font")); // NOI18N
        jbuAbrirAquivo.setIcon(resourceMap.getIcon("jbuAbrirAquivo.icon")); // NOI18N
        jbuAbrirAquivo.setMnemonic('A');
        jbuAbrirAquivo.setText(resourceMap.getString("jbuAbrirAquivo.text")); // NOI18N
        jbuAbrirAquivo.setName("jbuAbrirAquivo"); // NOI18N
        jbuAbrirAquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAbrirAquivoActionPerformed(evt);
            }
        });

        jbuRemoverArquivo.setFont(resourceMap.getFont("jbuRemoverArquivo.font")); // NOI18N
        jbuRemoverArquivo.setIcon(resourceMap.getIcon("jbuRemoverArquivo.icon")); // NOI18N
        jbuRemoverArquivo.setMnemonic('R');
        jbuRemoverArquivo.setText(resourceMap.getString("jbuRemoverArquivo.text")); // NOI18N
        jbuRemoverArquivo.setName("jbuRemoverArquivo"); // NOI18N
        jbuRemoverArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaArquivosLayout = new javax.swing.GroupLayout(jpaArquivos);
        jpaArquivos.setLayout(jpaArquivosLayout);
        jpaArquivosLayout.setHorizontalGroup(
            jpaArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaArquivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlaArquivos)
                    .addGroup(jpaArquivosLayout.createSequentialGroup()
                        .addComponent(jspArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpaArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbuAdicionarArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuAbrirAquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuRemoverArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(474, Short.MAX_VALUE))
        );
        jpaArquivosLayout.setVerticalGroup(
            jpaArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaArquivosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlaArquivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpaArquivosLayout.createSequentialGroup()
                        .addComponent(jbuAbrirAquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuAdicionarArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuRemoverArquivo)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jbuAdicionarArquivo.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAdicionarArquivo.AccessibleContext.accessibleName")); // NOI18N
        jbuAbrirAquivo.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAbrirAquivo.AccessibleContext.accessibleName")); // NOI18N
        jbuRemoverArquivo.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuRemoverArquivo.AccessibleContext.accessibleName")); // NOI18N

        jtpRegistros.addTab(resourceMap.getString("jpaArquivos.TabConstraints.tabTitle"), jpaArquivos); // NOI18N

        jpaTriagem.setToolTipText(resourceMap.getString("jpaTriagem.toolTipText")); // NOI18N
        jpaTriagem.setName("jpaTriagem"); // NOI18N
        jpaTriagem.setLayout(null);

        jpaIntegracao.setFont(resourceMap.getFont("jpaIntegracao.font")); // NOI18N
        jpaIntegracao.setText(resourceMap.getString("jpaIntegracao.text")); // NOI18N
        jpaIntegracao.setName("jpaIntegracao"); // NOI18N
        jpaTriagem.add(jpaIntegracao);
        jpaIntegracao.setBounds(10, 11, 80, 17);

        jcbIntegracao.setFont(resourceMap.getFont("jcbIntegracao.font")); // NOI18N
        jcbIntegracao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbIntegracao.setName("jcbIntegracao"); // NOI18N
        jpaTriagem.add(jcbIntegracao);
        jcbIntegracao.setBounds(10, 34, 210, 23);

        jlaMotivoNaoIntegracao.setFont(resourceMap.getFont("jlaMotivoNaoIntegracao.font")); // NOI18N
        jlaMotivoNaoIntegracao.setText(resourceMap.getString("jlaMotivoNaoIntegracao.text")); // NOI18N
        jlaMotivoNaoIntegracao.setName("jlaMotivoNaoIntegracao"); // NOI18N
        jpaTriagem.add(jlaMotivoNaoIntegracao);
        jlaMotivoNaoIntegracao.setBounds(230, 10, 270, 17);

        jspMotivoNaoIntegracao.setName("jspMotivoNaoIntegracao"); // NOI18N

        jtaMotivoNaoIntegracao.setColumns(20);
        jtaMotivoNaoIntegracao.setFont(resourceMap.getFont("jtaMotivoNaoIntegracao.font")); // NOI18N
        jtaMotivoNaoIntegracao.setLineWrap(true);
        jtaMotivoNaoIntegracao.setRows(5);
        jtaMotivoNaoIntegracao.setWrapStyleWord(true);
        jtaMotivoNaoIntegracao.setName("jtaMotivoNaoIntegracao"); // NOI18N
        jspMotivoNaoIntegracao.setViewportView(jtaMotivoNaoIntegracao);

        jpaTriagem.add(jspMotivoNaoIntegracao);
        jspMotivoNaoIntegracao.setBounds(230, 30, 280, 110);

        jlaDiscussaoDeCaso.setFont(resourceMap.getFont("jlaDiscussaoDeCaso.font")); // NOI18N
        jlaDiscussaoDeCaso.setText(resourceMap.getString("jlaDiscussaoDeCaso.text")); // NOI18N
        jlaDiscussaoDeCaso.setName("jlaDiscussaoDeCaso"); // NOI18N
        jpaTriagem.add(jlaDiscussaoDeCaso);
        jlaDiscussaoDeCaso.setBounds(10, 149, 133, 17);

        jcbDiscussaoCaso.setFont(resourceMap.getFont("jcbDiscussaoCaso.font")); // NOI18N
        jcbDiscussaoCaso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbDiscussaoCaso.setName("jcbDiscussaoCaso"); // NOI18N
        jpaTriagem.add(jcbDiscussaoCaso);
        jcbDiscussaoCaso.setBounds(10, 172, 210, 23);

        jlaResumoIntegracao.setFont(resourceMap.getFont("jlaResumoIntegracao.font")); // NOI18N
        jlaResumoIntegracao.setText(resourceMap.getString("jlaResumoIntegracao.text")); // NOI18N
        jlaResumoIntegracao.setName("jlaResumoIntegracao"); // NOI18N
        jpaTriagem.add(jlaResumoIntegracao);
        jlaResumoIntegracao.setBounds(520, 10, 250, 17);

        jspResumoIntegracao.setName("jspResumoIntegracao"); // NOI18N

        jtaResumoIntegracao.setEditable(false);
        jtaResumoIntegracao.setBackground(resourceMap.getColor("jtaResumoIntegracao.background")); // NOI18N
        jtaResumoIntegracao.setColumns(20);
        jtaResumoIntegracao.setFont(resourceMap.getFont("jtaResumoIntegracao.font")); // NOI18N
        jtaResumoIntegracao.setLineWrap(true);
        jtaResumoIntegracao.setRows(5);
        jtaResumoIntegracao.setWrapStyleWord(true);
        jtaResumoIntegracao.setName("jtaResumoIntegracao"); // NOI18N
        jspResumoIntegracao.setViewportView(jtaResumoIntegracao);

        jpaTriagem.add(jspResumoIntegracao);
        jspResumoIntegracao.setBounds(520, 30, 470, 110);

        jtpRegistros.addTab(resourceMap.getString("jpaTriagem.TabConstraints.tabTitle"), jpaTriagem); // NOI18N

        jpaConduta.setName("jpaConduta"); // NOI18N
        jpaConduta.setLayout(null);

        jlaTipoAcaoConduta.setFont(resourceMap.getFont("jlaTipoAcaoConduta.font")); // NOI18N
        jlaTipoAcaoConduta.setText(resourceMap.getString("jlaTipoAcaoConduta.text")); // NOI18N
        jlaTipoAcaoConduta.setName("jlaTipoAcaoConduta"); // NOI18N
        jpaConduta.add(jlaTipoAcaoConduta);
        jlaTipoAcaoConduta.setBounds(10, 0, 80, 17);

        jcbTipoAcaoConduta.setFont(resourceMap.getFont("jcbTipoAcaoConduta.font")); // NOI18N
        jcbTipoAcaoConduta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbTipoAcaoConduta.setName("jcbTipoAcaoConduta"); // NOI18N
        jpaConduta.add(jcbTipoAcaoConduta);
        jcbTipoAcaoConduta.setBounds(10, 20, 190, 23);

        jlaGrupoConduta.setFont(resourceMap.getFont("jlaGrupoConduta.font")); // NOI18N
        jlaGrupoConduta.setText(resourceMap.getString("jlaGrupoConduta.text")); // NOI18N
        jlaGrupoConduta.setName("jlaGrupoConduta"); // NOI18N
        jpaConduta.add(jlaGrupoConduta);
        jlaGrupoConduta.setBounds(10, 40, 50, 17);

        jcbGrupoConduta.setFont(resourceMap.getFont("jcbTipoAcaoConduta.font")); // NOI18N
        jcbGrupoConduta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbGrupoConduta.setName("jcbGrupoConduta"); // NOI18N
        jcbGrupoConduta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbGrupoCondutaItemStateChanged(evt);
            }
        });
        jcbGrupoConduta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcbGrupoCondutaFocusGained(evt);
            }
        });
        jpaConduta.add(jcbGrupoConduta);
        jcbGrupoConduta.setBounds(10, 60, 330, 23);

        jlaInformacaoModuloAEE.setFont(resourceMap.getFont("jlaInformacaoModuloAEE.font")); // NOI18N
        jlaInformacaoModuloAEE.setText(resourceMap.getString("jlaInformacaoModuloAEE.text")); // NOI18N
        jlaInformacaoModuloAEE.setName("jlaInformacaoModuloAEE"); // NOI18N
        jpaConduta.add(jlaInformacaoModuloAEE);
        jlaInformacaoModuloAEE.setBounds(360, 0, 350, 17);

        jspInformacoesModuloAEE.setName("jspInformacoesModuloAEE"); // NOI18N

        jepInformacoesModuloAEE.setEditable(false);
        jepInformacoesModuloAEE.setBackground(resourceMap.getColor("jepInformacoesModuloAEE.background")); // NOI18N
        jepInformacoesModuloAEE.setFont(resourceMap.getFont("jcbTipoAcaoConduta.font")); // NOI18N
        jepInformacoesModuloAEE.setName("jepInformacoesModuloAEE"); // NOI18N
        jspInformacoesModuloAEE.setViewportView(jepInformacoesModuloAEE);

        jpaConduta.add(jspInformacoesModuloAEE);
        jspInformacoesModuloAEE.setBounds(360, 20, 600, 130);

        jbuAdicionarConduta.setFont(resourceMap.getFont("jbuAdicionarConduta.font")); // NOI18N
        jbuAdicionarConduta.setIcon(resourceMap.getIcon("jbuAdicionarConduta.icon")); // NOI18N
        jbuAdicionarConduta.setMnemonic('A');
        jbuAdicionarConduta.setText(resourceMap.getString("jbuAdicionarConduta.text")); // NOI18N
        jbuAdicionarConduta.setName("jbuAdicionarConduta"); // NOI18N
        jbuAdicionarConduta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarCondutaActionPerformed(evt);
            }
        });
        jpaConduta.add(jbuAdicionarConduta);
        jbuAdicionarConduta.setBounds(10, 190, 290, 33);

        jlaCondutasSolicitadas.setFont(resourceMap.getFont("jlaCondutasSolicitadas.font")); // NOI18N
        jlaCondutasSolicitadas.setText(resourceMap.getString("jlaCondutasSolicitadas.text")); // NOI18N
        jlaCondutasSolicitadas.setName("jlaCondutasSolicitadas"); // NOI18N
        jpaConduta.add(jlaCondutasSolicitadas);
        jlaCondutasSolicitadas.setBounds(355, 155, 500, 17);

        jspCondutasSolicitadas.setName("jspCondutasSolicitadas"); // NOI18N

        jliCondutasSolicitadas.setFont(resourceMap.getFont("jcbTipoAcaoConduta.font")); // NOI18N
        jliCondutasSolicitadas.setModel(new DefaultListModel());
        jliCondutasSolicitadas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jliCondutasSolicitadas.setToolTipText(resourceMap.getString("jliCondutasSolicitadas.toolTipText")); // NOI18N
        jliCondutasSolicitadas.setName("jliCondutasSolicitadas"); // NOI18N
        jspCondutasSolicitadas.setViewportView(jliCondutasSolicitadas);

        jpaConduta.add(jspCondutasSolicitadas);
        jspCondutasSolicitadas.setBounds(355, 175, 500, 54);

        jbuCancelarConduta.setFont(resourceMap.getFont("jbuCancelarConduta.font")); // NOI18N
        jbuCancelarConduta.setIcon(resourceMap.getIcon("jbuCancelarConduta.icon")); // NOI18N
        jbuCancelarConduta.setMnemonic('C');
        jbuCancelarConduta.setText(resourceMap.getString("jbuCancelarConduta.text")); // NOI18N
        jbuCancelarConduta.setName("jbuCancelarConduta"); // NOI18N
        jbuCancelarConduta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuCancelarCondutaActionPerformed(evt);
            }
        });
        jpaConduta.add(jbuCancelarConduta);
        jbuCancelarConduta.setBounds(865, 175, 129, 33);

        jlaDataExpectativa.setFont(resourceMap.getFont("jlaDataExpectativa.font")); // NOI18N
        jlaDataExpectativa.setText(resourceMap.getString("jlaDataExpectativa.text")); // NOI18N
        jlaDataExpectativa.setName("jlaDataExpectativa"); // NOI18N
        jpaConduta.add(jlaDataExpectativa);
        jlaDataExpectativa.setBounds(210, 0, 130, 17);

        try {
            jftDataExpectativa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataExpectativa.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftDataExpectativa.setFont(resourceMap.getFont("jftDataExpectativa.font")); // NOI18N
        jftDataExpectativa.setName("jftDataExpectativa"); // NOI18N
        jpaConduta.add(jftDataExpectativa);
        jftDataExpectativa.setBounds(210, 20, 100, 23);

        jbuDataExpectativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Calendario.png"))); // NOI18N
        jbuDataExpectativa.setBorder(null);
        jbuDataExpectativa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuDataExpectativa.setName("jbuDataExpectativa"); // NOI18N
        jbuDataExpectativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuDataExpectativaActionPerformed(evt);
            }
        });
        jpaConduta.add(jbuDataExpectativa);
        jbuDataExpectativa.setBounds(310, 20, 25, 25);

        jlaObs.setFont(resourceMap.getFont("jlaObs.font")); // NOI18N
        jlaObs.setText(resourceMap.getString("jlaObs.text")); // NOI18N
        jlaObs.setName("jlaObs"); // NOI18N
        jpaConduta.add(jlaObs);
        jlaObs.setBounds(10, 80, 50, 20);

        jspObs.setName("jspObs"); // NOI18N

        jtaObs.setColumns(20);
        jtaObs.setFont(resourceMap.getFont("jtaObs.font")); // NOI18N
        jtaObs.setLineWrap(true);
        jtaObs.setRows(5);
        jtaObs.setWrapStyleWord(true);
        jtaObs.setName("jtaObs"); // NOI18N
        jspObs.setViewportView(jtaObs);

        jpaConduta.add(jspObs);
        jspObs.setBounds(10, 100, 330, 80);

        jtpRegistros.addTab(resourceMap.getString("jpaConduta.TabConstraints.tabTitle"), jpaConduta); // NOI18N

        jpaEditarAtendimentoIndividual.add(jtpRegistros);
        jtpRegistros.setBounds(10, 340, 1010, 290);

        jbuSalvar.setFont(resourceMap.getFont("jbuSalvar.font")); // NOI18N
        jbuSalvar.setIcon(resourceMap.getIcon("jbuSalvar.icon")); // NOI18N
        jbuSalvar.setMnemonic('S');
        jbuSalvar.setText(resourceMap.getString("jbuSalvar.text")); // NOI18N
        jbuSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSalvar.setName("jbuSalvar"); // NOI18N
        jbuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSalvarActionPerformed(evt);
            }
        });
        jpaEditarAtendimentoIndividual.add(jbuSalvar);
        jbuSalvar.setBounds(10, 630, 120, 33);
        jbuSalvar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuSalvar.AccessibleContext.accessibleName")); // NOI18N

        jbuFechar.setFont(resourceMap.getFont("jbuFechar.font")); // NOI18N
        jbuFechar.setIcon(resourceMap.getIcon("jbuFechar.icon")); // NOI18N
        jbuFechar.setMnemonic('F');
        jbuFechar.setText(resourceMap.getString("jbuFechar.text")); // NOI18N
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });
        jpaEditarAtendimentoIndividual.add(jbuFechar);
        jbuFechar.setBounds(900, 630, 120, 33);
        jbuFechar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuFechar.AccessibleContext.accessibleName")); // NOI18N

        jlaPrimeiraVez.setFont(resourceMap.getFont("jlaPrimeiraVez.font")); // NOI18N
        jlaPrimeiraVez.setText(resourceMap.getString("jlaPrimeiraVez.text")); // NOI18N
        jlaPrimeiraVez.setName("jlaPrimeiraVez"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaPrimeiraVez);
        jlaPrimeiraVez.setBounds(710, 240, 190, 17);

        jcbPrimeiraVez.setFont(resourceMap.getFont("jcbPrimeiraVez.font")); // NOI18N
        jcbPrimeiraVez.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbPrimeiraVez.setName("jcbPrimeiraVez"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jcbPrimeiraVez);
        jcbPrimeiraVez.setBounds(710, 260, 170, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarAtendimentoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarAtendimentoIndividual, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoAtendimentoActionPerformed
        controlador.inicializarDescricaoTipoAtendimento();
}//GEN-LAST:event_jcbTipoAtendimentoActionPerformed

    private void jcbDescricaoTipoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDescricaoTipoAtendimentoActionPerformed
        controlador.inicializarModuloAtividadeESetor();
}//GEN-LAST:event_jcbDescricaoTipoAtendimentoActionPerformed

    private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharActionPerformed

    private void jbuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSalvarActionPerformed
        controlador.salvar();
    }//GEN-LAST:event_jbuSalvarActionPerformed

    private void jbuUtilizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuUtilizarUsuarioActionPerformed
        controlador.abrirTelaUtilizarUsuario();
    }//GEN-LAST:event_jbuUtilizarUsuarioActionPerformed

    private void jbuUtilizarPreCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuUtilizarPreCadastroActionPerformed
        controlador.abrirTelaUtilizarPreCadastro();
    }//GEN-LAST:event_jbuUtilizarPreCadastroActionPerformed

    private void jbuSelecionarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSelecionarDataActionPerformed
        JOptionPanePersonalizado.mostrarTelaSelecionarData(this, jftData);
    }//GEN-LAST:event_jbuSelecionarDataActionPerformed

    private void jbuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarActionPerformed
        controlador.adicionarDetalheProfissional();
    }//GEN-LAST:event_jbuAdicionarActionPerformed

    private void jbuAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAlterarActionPerformed
        controlador.editarAtendimentoProfissional();
    }//GEN-LAST:event_jbuAlterarActionPerformed

    private void jbuRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverActionPerformed
        controlador.removerAtendimentoProfissionalSelecionado();
    }//GEN-LAST:event_jbuRemoverActionPerformed

    private void jtaProfissionaisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaProfissionaisKeyPressed
        controlador.moverFocoOuAbrirTelaDeAlteracaoProfissional(evt);
    }//GEN-LAST:event_jtaProfissionaisKeyPressed

    private void jftProntuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftProntuarioFocusLost
        controlador.selecionarProntuario();
    }//GEN-LAST:event_jftProntuarioFocusLost

    private void jbuAdicionarAcompanhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarAcompanhanteActionPerformed
        controlador.adicionarAcompanhante();
    }//GEN-LAST:event_jbuAdicionarAcompanhanteActionPerformed

    private void jbuAlterarAcompanhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAlterarAcompanhanteActionPerformed
        controlador.editarAcompanhanteSelecionado();
    }//GEN-LAST:event_jbuAlterarAcompanhanteActionPerformed

    private void jbuRemoverAcompanhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverAcompanhanteActionPerformed
        controlador.removerAcompanhanteSelecionado();
    }//GEN-LAST:event_jbuRemoverAcompanhanteActionPerformed

    private void jtaAcompanhanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaAcompanhanteKeyPressed
        controlador.moverFocoOuAbrirTelaDeAlteracaoComunidade(evt);
    }//GEN-LAST:event_jtaAcompanhanteKeyPressed

    private void jatDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jatDescricaoKeyPressed
        WordUtils.abrirWord(evt, jatDescricao);
    }//GEN-LAST:event_jatDescricaoKeyPressed

    private void jatInterdisciplinarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jatInterdisciplinarKeyPressed
        WordUtils.abrirWord(evt, jatInterdisciplinar);
    }//GEN-LAST:event_jatInterdisciplinarKeyPressed

    private void jatJustificativaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jatJustificativaKeyPressed
        WordUtils.abrirWord(evt, jatJustificativa);
    }//GEN-LAST:event_jatJustificativaKeyPressed

    private void jbuAdicionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarArquivoActionPerformed
        controlador.adicionarArquivo();
    }//GEN-LAST:event_jbuAdicionarArquivoActionPerformed

    private void jbuAbrirAquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAbrirAquivoActionPerformed
        controlador.abrirArquivo();
    }//GEN-LAST:event_jbuAbrirAquivoActionPerformed

    private void jbuRemoverArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverArquivoActionPerformed
        controlador.removerArquivoSelecionado();
    }//GEN-LAST:event_jbuRemoverArquivoActionPerformed

    private void jbuAdicionarParticipacaoDetalhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarParticipacaoDetalhadaActionPerformed
        controlador.adicionarParticipacaoDetalhada();
    }//GEN-LAST:event_jbuAdicionarParticipacaoDetalhadaActionPerformed

    private void jbuRemoverParticipacaoDetalhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverParticipacaoDetalhadaActionPerformed
        controlador.removerParticipacaoDetalhadaSelecionada();
    }//GEN-LAST:event_jbuRemoverParticipacaoDetalhadaActionPerformed

    private void jcbParticipacaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbParticipacaoItemStateChanged
        controlador.inicializarQuantidadePessoasPadrao();
    }//GEN-LAST:event_jcbParticipacaoItemStateChanged

    private void jcbGrupoCondutaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbGrupoCondutaItemStateChanged
        controlador.carregarInformacoesDoModuloAEESelecionado();
    }//GEN-LAST:event_jcbGrupoCondutaItemStateChanged

    private void jbuAdicionarCondutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarCondutaActionPerformed
        controlador.adicionarAcaoConduta();
    }//GEN-LAST:event_jbuAdicionarCondutaActionPerformed

    private void jbuCancelarCondutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuCancelarCondutaActionPerformed
        controlador.cancelarAcaoConduta();
    }//GEN-LAST:event_jbuCancelarCondutaActionPerformed

    private void jcbGrupoCondutaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbGrupoCondutaFocusGained
        controlador.carregarComboGrupos();
    }//GEN-LAST:event_jcbGrupoCondutaFocusGained

    private void jbuDataExpectativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuDataExpectativaActionPerformed
        JOptionPanePersonalizado.mostrarTelaSelecionarData(this, jftDataExpectativa);
    }//GEN-LAST:event_jbuDataExpectativaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JTextArea jatDescricao;
    private javax.swing.JTextArea jatInterdisciplinar;
    private javax.swing.JTextArea jatJustificativa;
    private javax.swing.JButton jbuAbrirAquivo;
    private javax.swing.JButton jbuAdicionar;
    private javax.swing.JButton jbuAdicionarAcompanhante;
    private javax.swing.JButton jbuAdicionarArquivo;
    private javax.swing.JButton jbuAdicionarConduta;
    private javax.swing.JButton jbuAdicionarParticipacaoDetalhada;
    private javax.swing.JButton jbuAlterar;
    private javax.swing.JButton jbuAlterarAcompanhante;
    private javax.swing.JButton jbuCancelarConduta;
    private javax.swing.JButton jbuDataExpectativa;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuRemover;
    private javax.swing.JButton jbuRemoverAcompanhante;
    private javax.swing.JButton jbuRemoverArquivo;
    private javax.swing.JButton jbuRemoverParticipacaoDetalhada;
    private javax.swing.JButton jbuSalvar;
    private javax.swing.JButton jbuSelecionarData;
    private javax.swing.JButton jbuUtilizarPreCadastro;
    private javax.swing.JButton jbuUtilizarUsuario;
    protected javax.swing.JComboBox jcbDescricaoTipoAtendimento;
    private javax.swing.JComboBox jcbDiscussaoCaso;
    protected javax.swing.JComboBox jcbFrequencia;
    private javax.swing.JComboBox jcbGrupoConduta;
    private javax.swing.JComboBox jcbIntegracao;
    protected javax.swing.JComboBox jcbLocalAtendimento;
    protected javax.swing.JComboBox jcbModuloAtividade;
    private javax.swing.JComboBox jcbParticipacao;
    private javax.swing.JComboBox jcbPrimeiraVez;
    protected javax.swing.JComboBox jcbSetor;
    private javax.swing.JComboBox jcbTipoAcaoConduta;
    protected javax.swing.JComboBox jcbTipoAtendimento;
    private javax.swing.JEditorPane jepInformacoesModuloAEE;
    private javax.swing.JFormattedTextField jftData;
    private javax.swing.JFormattedTextField jftDataExpectativa;
    private javax.swing.JFormattedTextField jftHoraInicio;
    private javax.swing.JFormattedTextField jftHoraTermino;
    private javax.swing.JFormattedTextField jftProntuario;
    private javax.swing.JLabel jlaAcompanhante;
    private javax.swing.JLabel jlaArquivos;
    private javax.swing.JLabel jlaCondutasSolicitadas;
    private javax.swing.JLabel jlaData;
    private javax.swing.JLabel jlaDataExpectativa;
    private javax.swing.JLabel jlaDescricao;
    private javax.swing.JLabel jlaDescricaoTipoAtendimento;
    private javax.swing.JLabel jlaDiscussaoDeCaso;
    private javax.swing.JLabel jlaFrequencia;
    private javax.swing.JLabel jlaGrupoConduta;
    private javax.swing.JLabel jlaHoraInicio;
    private javax.swing.JLabel jlaHoraTermino;
    private javax.swing.JLabel jlaInformacaoModuloAEE;
    private javax.swing.JLabel jlaInterdisciplinar;
    private javax.swing.JLabel jlaJustificativa;
    private javax.swing.JLabel jlaLocalAtendimento;
    private javax.swing.JLabel jlaModuloAtividade;
    private javax.swing.JLabel jlaMotivoNaoIntegracao;
    private javax.swing.JLabel jlaNomePreCadastro;
    private javax.swing.JLabel jlaNomeUsuario;
    private javax.swing.JLabel jlaObs;
    private javax.swing.JLabel jlaParticipacao;
    private javax.swing.JLabel jlaPrimeiraVez;
    private javax.swing.JLabel jlaProfissionais;
    private javax.swing.JLabel jlaProntuario;
    private javax.swing.JLabel jlaQuantidadePessoas;
    private javax.swing.JLabel jlaResumoIntegracao;
    private javax.swing.JLabel jlaSetor;
    private javax.swing.JLabel jlaTipoAcaoConduta;
    private javax.swing.JLabel jlaTipoAtendimento;
    private javax.swing.JList jliArquivos;
    private javax.swing.JList jliCondutasSolicitadas;
    private javax.swing.JList jliParticipacoesAdicionadas;
    private javax.swing.JLabel jluParticipacaoDetalhasAdiconadas;
    private javax.swing.JPanel jpaAcompanhante;
    private javax.swing.JPanel jpaArquivos;
    private javax.swing.JPanel jpaConduta;
    private javax.swing.JPanel jpaDataHora;
    private javax.swing.JPanel jpaDescricaoAtendimento;
    private javax.swing.JPanel jpaEditarAtendimentoIndividual;
    private javax.swing.JPanel jpaFrequencia;
    private javax.swing.JLabel jpaIntegracao;
    private javax.swing.JPanel jpaParticipacao;
    private javax.swing.JPanel jpaPreCadastro;
    private javax.swing.JPanel jpaProfissionais;
    private javax.swing.JPanel jpaTriagem;
    private javax.swing.JPanel jpaUsuario;
    private javax.swing.JScrollPane jspAcompanhante;
    private javax.swing.JScrollPane jspArquivos;
    private javax.swing.JScrollPane jspCondutasSolicitadas;
    private javax.swing.JScrollPane jspDescricao;
    private javax.swing.JScrollPane jspInformacoesModuloAEE;
    private javax.swing.JScrollPane jspInterdisciplinar;
    private javax.swing.JScrollPane jspJustificativa;
    private javax.swing.JScrollPane jspMotivoNaoIntegracao;
    private javax.swing.JScrollPane jspObs;
    private javax.swing.JScrollPane jspParticipacoesAdicionadas;
    private javax.swing.JScrollPane jspProfissionais;
    private javax.swing.JScrollPane jspResumoIntegracao;
    private javax.swing.JTable jtaAcompanhante;
    private javax.swing.JTextArea jtaMotivoNaoIntegracao;
    private javax.swing.JTextArea jtaObs;
    private javax.swing.JTable jtaProfissionais;
    private javax.swing.JTextArea jtaResumoIntegracao;
    private javax.swing.JTextField jtfNomePreCadastro;
    private javax.swing.JTextField jtfNomeUsuario;
    private javax.swing.JTextField jtfQuantidadePessoas;
    private javax.swing.JTabbedPane jtpIntegrante;
    private javax.swing.JTabbedPane jtpRegistros;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaAtendimentoIndividualEditar controlador;
}
