package br.laramara.ti.sislaraserver.dominio;

public class TamanhoMaximoGenerico {
	public static final int NOME = 100;
	public static final int ARQUIVO = 1000;
	public static final int EMAIL = 100;
	public static final int OBS = 20000;
	public static final int DDD = 2;
	public static final int TIPO_TELEFONE = 20;
	public static final int TELEFONE_MINIMO = 8;
	public static final int TELEFONE_MAXIMO = 9;
	public static final int RAMAL = 6;
	public static final int DISPONIBILIDADE = 20;
	public static final int CPF = 11;
	public static final int DESCRICAO = 50;
	public static final int RENDA = 2;
	public static final int ESTADO_CIVIL = 20;
	public static final int TIPO_ESPECIALIDADE = 10;
	public static final int TIPO_APOIO = 40;
	public static final int TIPO_PENDENCIA = 50;
	public static final int SETOR = 10;
	public static final int STATUS = 25;
	public static final int CHAPA = 10;
	public static final int FREQUENCIA = 2;
	public static final int TEXTO_GRANDE = 20000;
	public static final int ORIGEM = 25;
	public static final int CURSO = 100;
	public static final int QUANTIDADE_RECURSO_MINIMO = 1;
	public static final int VALOR = 25;
	public static final int SEQUENCIA_CRIACAO = 50;
	public static final int TOKEN = 36;
	public static final int TAMANHO_FONTE = 100;
	public static final int TIPO_LEITURA = 25;
	public static final int FINALIDADE_RELATORIO = 50;
	public static final int SIM_NAO = 5;
	public static final int AREA = 50;
	public static final int ESPECIALIDADE = 50;
	public static final int FREQUENCIA_CONTRIBUICAO = 50;
	public static final int CHAVE = 1000;
	public static final int QUANTIDADE = 5;
	public static final int NOME_DOCUMENTO = 250;
	public static final int CNPJ = 14;
	public static final int TIPO_ACAO_CONDUTA = 50;
	public static final int INTEGRACAO = 50;
}