
/* Drop Tables */

DROP TABLE IF EXISTS ATENDIMENTO_INDIVIDUAL_ACAO_CONDUTA;
DROP TABLE IF EXISTS ACAO_CONDUTA;
DROP TABLE IF EXISTS AGENDAMENTO_GRUPO;
DROP TABLE IF EXISTS AGENDAMENTO_HISTORICO_STATUS_AGENDAMENTO;
DROP TABLE IF EXISTS PENDENCIA_PROFISSIONAL;
DROP TABLE IF EXISTS PENDENCIA;
DROP TABLE IF EXISTS AGENDAMENTO;
DROP TABLE IF EXISTS FAMILIAR_INFORMACAO_EDUCACIONAL;
DROP TABLE IF EXISTS USUARIO_INFORMACAO_EDUCACIONAL;
DROP TABLE IF EXISTS INFORMACAO_EDUCACIONAL;
DROP TABLE IF EXISTS AREA_FORMACAO;
DROP TABLE IF EXISTS ATENDIMENTO_GRUPO_ARQUIVO;
DROP TABLE IF EXISTS ATENDIMENTO_INDIVIDUAL_ARQUIVO;
DROP TABLE IF EXISTS ATENDIMENTO_USUARIO_ARQUIVO;
DROP TABLE IF EXISTS DEMANDA_DOCUMENTO_SOLICITACAO_DOACAO;
DROP TABLE IF EXISTS DOCUMENTO_SOLICITACAO_DOACAO;
DROP TABLE IF EXISTS PROJETO_ARQUIVO;
DROP TABLE IF EXISTS ARQUIVO;
DROP TABLE IF EXISTS ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_COMUNIDADE;
DROP TABLE IF EXISTS ATENDIMENTO_COMUNIDADE;
DROP TABLE IF EXISTS ATENDIMENTO_GRUPO_ATENDIMENTO_PRE_CADASTRO;
DROP TABLE IF EXISTS ATENDIMENTO_GRUPO_ATENDIMENTO_PROFISSIONAL;
DROP TABLE IF EXISTS ATENDIMENTO_GRUPO_ATENDIMENTO_USUARIO;
DROP TABLE IF EXISTS MODULO_PERIODO_ATENDIMENTO_GRUPO;
DROP TABLE IF EXISTS ATENDIMENTO_GRUPO;
DROP TABLE IF EXISTS ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_PROFISSIONAL;
DROP TABLE IF EXISTS ATENDIMENTO_INDIVIDUAL;
DROP TABLE IF EXISTS ATENDIMENTO_PRE_CADASTRO;
DROP TABLE IF EXISTS ATENDIMENTO_PROFISSIONAL;
DROP TABLE IF EXISTS ATENDIMENTO_USUARIO;
DROP TABLE IF EXISTS FAMILIAR_PERIODO_BENEFICIO;
DROP TABLE IF EXISTS USUARIO_PERIODO_BENEFICIO;
DROP TABLE IF EXISTS PERIODO_BENEFICIO;
DROP TABLE IF EXISTS BENEFICIO;
DROP TABLE IF EXISTS BLOQUEIO;
DROP TABLE IF EXISTS DEMANDA_CAPTACAO;
DROP TABLE IF EXISTS CAPTACAO;
DROP TABLE IF EXISTS FAMILIAR_VULNERABILIDADE;
DROP TABLE IF EXISTS USUARIO_FAMILIAR;
DROP TABLE IF EXISTS FAMILIAR;
DROP TABLE IF EXISTS INFORMACAO_TRABALHO;
DROP TABLE IF EXISTS USUARIO_INFORMACAO_TRABALHO_COMPLETA;
DROP TABLE IF EXISTS INFORMACAO_TRABALHO_COMPLETA;
DROP TABLE IF EXISTS CARGO;
DROP TABLE IF EXISTS USUARIO_CERTIDAO;
DROP TABLE IF EXISTS CERTIDAO;
DROP TABLE IF EXISTS PERIODO_DEFICIENCIA_ETIOLOGIA;
DROP TABLE IF EXISTS ETIOLOGIA;
DROP TABLE IF EXISTS USUARIO_PERIODO_DEFICIENCIA;
DROP TABLE IF EXISTS PERIODO_DEFICIENCIA;
DROP TABLE IF EXISTS CID10;
DROP TABLE IF EXISTS USUARIO_PERIODO_COMPROMETIMENTO;
DROP TABLE IF EXISTS PERIODO_COMPROMETIMENTO;
DROP TABLE IF EXISTS COMPROMETIMENTO;
DROP TABLE IF EXISTS DEMANDA_HISTORICO_STATUS_DEMANDA;
DROP TABLE IF EXISTS PROJETO_RESERVA;
DROP TABLE IF EXISTS RESERVA;
DROP TABLE IF EXISTS DEMANDA;
DROP TABLE IF EXISTS ESPERA_HISTORICO_STATUS_ESPERA;
DROP TABLE IF EXISTS ESPERA;
DROP TABLE IF EXISTS MODULO_PERIODO_MODULO_PRE_CADASTRO;
DROP TABLE IF EXISTS MODULO_PRE_CADASTRO;
DROP TABLE IF EXISTS MODULO_PERIODO_MODULO_USUARIO;
DROP TABLE IF EXISTS MODULO_USUARIO;
DROP TABLE IF EXISTS SOLICITACAO_RELATORIO_FINALIDADE_RELATORIO;
DROP TABLE IF EXISTS SOLICITACAO_RELATORIO_HISTORICO_STATUS_SOLICITACAO_RELATORIO;
DROP TABLE IF EXISTS SOLICITACAO_RELATORIO;
DROP TABLE IF EXISTS USUARIO_CONVENIO;
DROP TABLE IF EXISTS USUARIO_CUSTO_DEFICIENCIA;
DROP TABLE IF EXISTS USUARIO_CUSTO_DOENCA;
DROP TABLE IF EXISTS USUARIO_ENCAMINHAMENTO;
DROP TABLE IF EXISTS USUARIO_EXPECTATIVA;
DROP TABLE IF EXISTS USUARIO_HISTORICO_CLASSIFICACAO_SOCIAL;
DROP TABLE IF EXISTS USUARIO_HISTORICO_INSTITUICAO_OUTROS_AEE;
DROP TABLE IF EXISTS USUARIO_HISTORICO_INSTITUICAO_SALA_RECURSO;
DROP TABLE IF EXISTS USUARIO_HISTORICO_INSTITUICAO_SRMS;
DROP TABLE IF EXISTS USUARIO_HISTORICO_SETOR;
DROP TABLE IF EXISTS USUARIO_HISTORICO_STATUS;
DROP TABLE IF EXISTS USUARIO_HISTORICO_STATUS_USUARIO;
DROP TABLE IF EXISTS USUARIO_INFRAESTRUTURA_BASICA;
DROP TABLE IF EXISTS USUARIO_NECESSIDADE;
DROP TABLE IF EXISTS USUARIO_ORIGEM_ENCAMINHAMENTO_DETALHADO;
DROP TABLE IF EXISTS USUARIO_PERIODO_DOENCA;
DROP TABLE IF EXISTS USUARIO_RECURSO;
DROP TABLE IF EXISTS USUARIO_RECURSO_MORADIA;
DROP TABLE IF EXISTS USUARIO_RECURSO_RELACIONAMENTO;
DROP TABLE IF EXISTS USUARIO_SERVICO;
DROP TABLE IF EXISTS USUARIO_SITUACAO_GUARDA;
DROP TABLE IF EXISTS USUARIO_VULNERABILIDADE_FAMILIA;
DROP TABLE IF EXISTS USUARIO_VULNERABILIDADE_USUARIO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS CONDICAO_MORADIA;
DROP TABLE IF EXISTS CONTRIBUINTE_HISTORICO_STATUS_CONTRIBUINTE;
DROP TABLE IF EXISTS CONTRIBUINTE;
DROP TABLE IF EXISTS INFORMACAO_ESSENCIAL_ENDERECO;
DROP TABLE IF EXISTS INFORMACAO_ESSENCIAL_HISTORICO_RG;
DROP TABLE IF EXISTS PRE_CADASTRO;
DROP TABLE IF EXISTS INFORMACAO_ESSENCIAL;
DROP TABLE IF EXISTS GRUPO_DESCRICAO_EVENTO;
DROP TABLE IF EXISTS GRUPO_LOTE_RECURSO;
DROP TABLE IF EXISTS GRUPO_MODULO_PERIODO;
DROP TABLE IF EXISTS GRUPO_TIPIFICACAO_SERVICO;
DROP TABLE IF EXISTS INSCRICAO;
DROP TABLE IF EXISTS GRUPO;
DROP TABLE IF EXISTS HISTORICO_INSTITUICAO;
DROP TABLE IF EXISTS INSTITUICAO_ESCOLARIDADE;
DROP TABLE IF EXISTS INSTITUICAO_TIPO_ESPECIALIDADE;
DROP TABLE IF EXISTS INSTITUICAO;
DROP TABLE IF EXISTS TELEFONE;
DROP TABLE IF EXISTS CONTATO;
DROP TABLE IF EXISTS CONTA_ACESSO_PERMISSOES;
DROP TABLE IF EXISTS CONTA_ACESSO_PROFISSIONAL_EQUIVALENTE;
DROP TABLE IF EXISTS HISTORICO_STATUS_AGENDAMENTO;
DROP TABLE IF EXISTS HISTORICO_STATUS_DEMANDA;
DROP TABLE IF EXISTS HISTORICO_STATUS_ESPERA;
DROP TABLE IF EXISTS RECIBO_HISTORICO_STATUS_RECIBO;
DROP TABLE IF EXISTS HISTORICO_STATUS_RECIBO;
DROP TABLE IF EXISTS RETIRADA_HISTORICO_STATUS_RETIRADA;
DROP TABLE IF EXISTS HISTORICO_STATUS_RETIRADA;
DROP TABLE IF EXISTS HISTORICO_STATUS_SOLICITACAO_RELATORIO;
DROP TABLE IF EXISTS CONTA_ACESSO;
DROP TABLE IF EXISTS CONVENIO;
DROP TABLE IF EXISTS CUSTO;
DROP TABLE IF EXISTS DEFICIENCIA;
DROP TABLE IF EXISTS DESCRICAO_EVENTO;
DROP TABLE IF EXISTS RECURSO_DESCRICAO_RECURSO;
DROP TABLE IF EXISTS DESCRICAO_RECURSO;
DROP TABLE IF EXISTS DESCRICAO_TIPO_ATENDIMENTO_MODULO;
DROP TABLE IF EXISTS DESCRICAO_TIPO_ATENDIMENTO_NOME_GRUPO;
DROP TABLE IF EXISTS DESCRICAO_TIPO_ATENDIMENTO_SETOR;
DROP TABLE IF EXISTS TIPO_ATENDIMENTO_DESCRICAO_TIPO_ATENDIMENTO;
DROP TABLE IF EXISTS DESCRICAO_TIPO_ATENDIMENTO;
DROP TABLE IF EXISTS MODULO_PERIODO_DIA_SEMANA_E_HORARIO;
DROP TABLE IF EXISTS DIA_SEMANA_E_HORARIO;
DROP TABLE IF EXISTS DIRETORIA_ENSINO;
DROP TABLE IF EXISTS DOACOES_LEGADO;
DROP TABLE IF EXISTS PERIODO_DOENCA;
DROP TABLE IF EXISTS DOENCA;
DROP TABLE IF EXISTS DRE_CEFAI;
DROP TABLE IF EXISTS PROJETO_PATROCINIO;
DROP TABLE IF EXISTS PATROCINIO;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS ENCAMINHAMENTO;
DROP TABLE IF EXISTS USUARIO_EXTERNO;
DROP TABLE IF EXISTS ENDERECO;
DROP TABLE IF EXISTS ESCOLARIDADE_SERIE;
DROP TABLE IF EXISTS ESCOLARIDADE;
DROP TABLE IF EXISTS ESTADO_CIVIL;
DROP TABLE IF EXISTS EXPECTATIVA;
DROP TABLE IF EXISTS FERIADO_PONTE;
DROP TABLE IF EXISTS RECIBO;
DROP TABLE IF EXISTS FILIAL;
DROP TABLE IF EXISTS HABITACAO;
DROP TABLE IF EXISTS HISTORICO_CLASSIFICACAO_SOCIAL;
DROP TABLE IF EXISTS HISTORICO_RG;
DROP TABLE IF EXISTS HISTORICO_SETOR;
DROP TABLE IF EXISTS HISTORICO_STATUS;
DROP TABLE IF EXISTS HISTORICO_STATUS_CONTRIBUINTE;
DROP TABLE IF EXISTS HISTORICO_STATUS_USUARIO;
DROP TABLE IF EXISTS INFORMACAO_ATENDIMENTO_PARTICIPACAO_DETALHADA;
DROP TABLE IF EXISTS INFORMACAO_ATENDIMENTO;
DROP TABLE IF EXISTS INFRAESTRUTURA_BASICA;
DROP TABLE IF EXISTS ITEM_CUSTO;
DROP TABLE IF EXISTS MODULO_PERIODO_PROFISSIONAL_VINCULO;
DROP TABLE IF EXISTS MODULO_PERIODO_PROGRAMACAO;
DROP TABLE IF EXISTS MODULO_PERIODO;
DROP TABLE IF EXISTS PROGRAMACAO;
DROP TABLE IF EXISTS LOCAL_ATENDIMENTO;
DROP TABLE IF EXISTS LOCAL_TRABALHO;
DROP TABLE IF EXISTS LOTE_RECURSO;
DROP TABLE IF EXISTS MODULO;
DROP TABLE IF EXISTS MOTIVO_CANCELAMENTO;
DROP TABLE IF EXISTS MOTIVO_DESATIVACAO;
DROP TABLE IF EXISTS MUNICIPIO;
DROP TABLE IF EXISTS NECESSIDADE;
DROP TABLE IF EXISTS NOME_GRUPO;
DROP TABLE IF EXISTS ORIGEM_ENCAMINHAMENTO_DETALHADO;
DROP TABLE IF EXISTS ORIGEM_ENCAMINHAMENTO;
DROP TABLE IF EXISTS PAIS;
DROP TABLE IF EXISTS PARENTESCO;
DROP TABLE IF EXISTS PARTICIPACAO_DETALHADA;
DROP TABLE IF EXISTS PERFIL_PERMISSOES;
DROP TABLE IF EXISTS PERFIL;
DROP TABLE IF EXISTS PROFISSIONAL_VINCULO;
DROP TABLE IF EXISTS PROJETO_RECURSO_DISPONIVEL;
DROP TABLE IF EXISTS PROJETO_RESPONSAVEL_TECNICO;
DROP TABLE IF EXISTS PROJETO;
DROP TABLE IF EXISTS RESPONSAVEL_TECNICO;
DROP TABLE IF EXISTS RETIRADA;
DROP TABLE IF EXISTS PROFISSIONAL;
DROP TABLE IF EXISTS RECURSO_DISPONIVEL;
DROP TABLE IF EXISTS RECURSO_RELACIONAMENTO;
DROP TABLE IF EXISTS RECURSO;
DROP TABLE IF EXISTS RECURSO_MORADIA;
DROP TABLE IF EXISTS SERIE;
DROP TABLE IF EXISTS SERVICO;
DROP TABLE IF EXISTS SETOR;
DROP TABLE IF EXISTS SITUACAO_GUARDA;
DROP TABLE IF EXISTS SITUACAO_HABITACIONAL;
DROP TABLE IF EXISTS TIPIFICACAO_SERVICO;
DROP TABLE IF EXISTS TIPO_ATENDIMENTO;
DROP TABLE IF EXISTS TIPO_CONSTRUCAO;
DROP TABLE IF EXISTS TIPO_VINCULO;
DROP TABLE IF EXISTS VULNERABILIDADE;



/* Drop Sequences */

DROP SEQUENCE IF EXISTS NOSSO_NUMERO_SEQ;




/* Create Sequences */

CREATE SEQUENCE NOSSO_NUMERO_SEQ INCREMENT 1 START 1;



/* Create Tables */

CREATE TABLE ACAO_CONDUTA
(
	ID BIGSERIAL NOT NULL,
	TIPO_ACAO_CONDUTA VARCHAR(50) NOT NULL,
	ID_GRUPO BIGINT,
	ID_USUARIO BIGINT NOT NULL,
	ID_SETOR VARCHAR(10),
	DATA_EXPECTATIVA DATE,
	DATA_PROCESSAMENTO TIMESTAMP,
	RESULTADO_PROCESSAMENTO VARCHAR(20000),
	OBS VARCHAR(20000),
	CANCELADA BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE AGENDAMENTO
(
	ID BIGSERIAL NOT NULL,
	ID_USUARIO BIGINT,
	ID_PRE_CADASTRO BIGINT,
	ID_PROFISSIONAL BIGINT NOT NULL,
	ID_DESCRICAO_TIPO_ATENDIMENTO BIGINT NOT NULL,
	ID_MODULO BIGINT NOT NULL,
	ID_SETOR VARCHAR(10) NOT NULL,
	ID_LOCAL_ATENDIMENTO BIGINT NOT NULL,
	ID_MOTIVO_CANCELAMENTO BIGINT,
	JUSTIFICATIVA_CANCELAMENTO VARCHAR(20000),
	DATA DATE NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_TERMINO TIME NOT NULL,
	RESERVA_PARA VARCHAR(25) NOT NULL,
	OBS VARCHAR(20000),
	ORIGINADO_POR_EXCESSO_DE_FALTAS BOOLEAN DEFAULT 'false',
	INFORMACAO_ADICIONAL VARCHAR(20000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE AGENDAMENTO_GRUPO
(
	ID_AGENDAMENTO BIGINT NOT NULL,
	ID_GRUPO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE AGENDAMENTO_HISTORICO_STATUS_AGENDAMENTO
(
	ID_AGENDAMENTO BIGINT NOT NULL,
	ID_HISTORICO_STATUS_AGENDAMENTO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE AREA_FORMACAO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ARQUIVO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(1000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_COMUNIDADE
(
	ID BIGSERIAL NOT NULL,
	ID_PRE_CADASTRO BIGINT NOT NULL,
	ID_TIPO_VINCULO BIGINT NOT NULL,
	ID_INFORMACAO_ATENDIMENTO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_GRUPO
(
	ID BIGSERIAL NOT NULL,
	CATEGORIA VARCHAR(25) NOT NULL,
	DATA DATE NOT NULL,
	STATUS VARCHAR(10) NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_TERMINO TIME NOT NULL,
	DESCRICAO VARCHAR(20000),
	INTERDISCIPLINAR VARCHAR(20000),
	TOTAL_HORAS TIME NOT NULL,
	PESSOAS_SEM_CADASTRO INT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_GRUPO_ARQUIVO
(
	ID_ARQUIVO BIGINT NOT NULL,
	ID_ATENDIMENTO_GRUPO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_GRUPO_ATENDIMENTO_PRE_CADASTRO
(
	ID_ATENDIMENTO_GRUPO BIGINT NOT NULL,
	ID_ATENDIMENTO_PRE_CADASTRO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_GRUPO_ATENDIMENTO_PROFISSIONAL
(
	ID_ATENDIMENTO_GRUPO BIGINT NOT NULL,
	ID_ATENDIMENTO_PROFISSIONAL BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_GRUPO_ATENDIMENTO_USUARIO
(
	ID_ATENDIMENTO_GRUPO BIGINT NOT NULL,
	ID_ATENDIMENTO_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_INDIVIDUAL
(
	ID BIGSERIAL NOT NULL,
	ID_USUARIO BIGINT,
	ID_PRE_CADASTRO BIGINT,
	ID_INFORMACAO_ATENDIMENTO BIGINT NOT NULL,
	ID_DESCRICAO_TIPO_ATENDIMENTO BIGINT NOT NULL,
	ID_MODULO BIGINT NOT NULL,
	ID_SETOR VARCHAR(10) NOT NULL,
	ID_LOCAL_ATENDIMENTO BIGINT NOT NULL,
	CATEGORIA VARCHAR(25) NOT NULL,
	DATA DATE NOT NULL,
	STATUS VARCHAR(10) NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_TERMINO TIME NOT NULL,
	TOTAL_HORAS TIME NOT NULL,
	INTERDISCIPLINAR VARCHAR(20000),
	PRIMEIRA_VEZ_OU_RETORNO VARCHAR(25),
	INTEGRACAO VARCHAR(50),
	MOTIVO_NAO_INTEGRACAO VARCHAR(20000),
	DISCUSSAO_CASO VARCHAR(5),
	RELATORIO_AVFUN_NAO_CONFECCIONADO BOOLEAN DEFAULT 'false',
	MOTIVO_NAO_CONFECCAO_RELATORIO_AVFUN VARCHAR(20000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_INDIVIDUAL_ACAO_CONDUTA
(
	ID_ACAO_CONDUTA BIGINT NOT NULL,
	ID_ATENDIMENTO_INDIVIDUAL BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_INDIVIDUAL_ARQUIVO
(
	ID_ARQUIVO BIGINT NOT NULL,
	ID_ATENDIMENTO_INDIVIDUAL BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_COMUNIDADE
(
	ID_ATENDIMENTO_INDIVIDUAL BIGINT NOT NULL,
	ID_ATENDIMENTO_COMUNIDADE BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_PROFISSIONAL
(
	ID_ATENDIMENTO_INDIVIDUAL BIGINT NOT NULL,
	ID_ATENDIMENTO_PROFISSIONAL BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_PRE_CADASTRO
(
	ID BIGSERIAL NOT NULL,
	ID_PRE_CADASTRO BIGINT NOT NULL,
	ID_INFORMACAO_ATENDIMENTO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_PROFISSIONAL
(
	ID BIGSERIAL NOT NULL,
	ID_PROFISSIONAL BIGINT NOT NULL,
	ID_INFORMACAO_ATENDIMENTO BIGINT NOT NULL,
	HORA_INICIO TIME,
	HORA_TERMINO TIME,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_USUARIO
(
	ID BIGSERIAL NOT NULL,
	ID_USUARIO BIGINT NOT NULL,
	ID_INFORMACAO_ATENDIMENTO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ATENDIMENTO_USUARIO_ARQUIVO
(
	ID_ARQUIVO BIGINT NOT NULL,
	ID_ATENDIMENTO_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE BENEFICIO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE BLOQUEIO
(
	ID BIGSERIAL NOT NULL,
	ID_DESCRICAO_TIPO_ATENDIMENTO BIGINT NOT NULL,
	ID_MODULO BIGINT NOT NULL,
	AREA VARCHAR(200),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CAPTACAO
(
	ID BIGSERIAL NOT NULL,
	VALOR DECIMAL NOT NULL,
	ID_RECIBO BIGINT NOT NULL,
	DATA TIMESTAMP NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	CANCELADA BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CARGO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CERTIDAO
(
	ID BIGSERIAL NOT NULL,
	TIPO_CERTIDAO VARCHAR(25) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	LIVRO VARCHAR(10) NOT NULL,
	FOLHA VARCHAR(10) NOT NULL,
	DISTRITO VARCHAR(100) NOT NULL,
	UF VARCHAR(10) NOT NULL,
	ID_MUNICIPIO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CID10
(
	CID VARCHAR(4) NOT NULL,
	OPC VARCHAR(1),
	CAT VARCHAR(1),
	SUBCAT VARCHAR(1),
	DESCRICAO VARCHAR(100),
	RESTRSEXO VARCHAR(1),
	PRIMARY KEY (CID)
) WITHOUT OIDS;


CREATE TABLE COMPROMETIMENTO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(250) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CONDICAO_MORADIA
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CONTATO
(
	ID BIGSERIAL NOT NULL,
	RAMAL VARCHAR(6),
	NOME_CONTATO VARCHAR(100),
	EMAIL VARCHAR(100),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CONTA_ACESSO
(
	ID BIGSERIAL NOT NULL,
	ID_PERFIL BIGINT NOT NULL,
	LOGIN VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	BLOQUEADO BOOLEAN NOT NULL,
	EXTENSAO_RELATORIOS VARCHAR(3) NOT NULL,
	FILTRO_GRUPO BOOLEAN DEFAULT 'false' NOT NULL,
	ID_PROFISSIONAL BIGINT,
	TOKEN VARCHAR(36),
	PALAVRA_CHAVE_GRUPO VARCHAR(20000),
	CONSTRAINT conta_acesso_pkey PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CONTA_ACESSO_PERMISSOES
(
	ID_CONTA_ACESSO BIGINT NOT NULL,
	PERMISSAO VARCHAR(100)
) WITHOUT OIDS;


CREATE TABLE CONTA_ACESSO_PROFISSIONAL_EQUIVALENTE
(
	ID_PROFISSIONAL BIGINT NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE CONTRIBUINTE
(
	ID BIGSERIAL NOT NULL,
	DATA_CADASTRO TIMESTAMP NOT NULL,
	NOME_EMPRESA VARCHAR(100) NOT NULL,
	PRONTUARIO INT,
	ID_ENDERECO BIGINT NOT NULL,
	INDICADO_POR VARCHAR(100),
	FREQUENCIA_CONTRIBUICAO VARCHAR(50),
	VALOR_CONTRIBUICAO DECIMAL DEFAULT 0.00,
	ID_CONTATO BIGINT NOT NULL,
	ID_MOTIVO_DESATIVACAO BIGINT,
	CPF VARCHAR(11),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CONTRIBUINTE_HISTORICO_STATUS_CONTRIBUINTE
(
	ID_CONTRIBUINTE BIGINT NOT NULL,
	ID_HISTORICO_STATUS_CONTRIBUINTE BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE CONVENIO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CUSTO
(
	ID BIGSERIAL NOT NULL,
	ID_ITEM_CUSTO BIGINT NOT NULL,
	VALOR DECIMAL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DEFICIENCIA
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	ETIOLOGIA_OBRIGATORIO BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DEMANDA
(
	ID BIGSERIAL NOT NULL,
	DATA_PRAZO_CAPTACAO DATE,
	SEQUENCIA_CRIACAO VARCHAR(50) NOT NULL,
	ID_USUARIO BIGINT,
	ID_PRE_CADASTRO BIGINT,
	ID_GRUPO BIGINT,
	ID_RECURSO BIGINT NOT NULL,
	ID_DESCRICAO_RECURSO BIGINT,
	DATA_EXPECTATIVA DATE,
	OBS VARCHAR(20000),
	CARTELA_DE_SELOS BOOLEAN DEFAULT 'false',
	VALOR DECIMAL,
	ID_MOTIVO_CANCELAMENTO BIGINT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DEMANDA_CAPTACAO
(
	ID_CAPTACAO BIGINT NOT NULL,
	ID_DEMANDA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE DEMANDA_DOCUMENTO_SOLICITACAO_DOACAO
(
	ID_DOCUMENTO_SOLICITACAO_DOACAO BIGINT NOT NULL,
	ID_DEMANDA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE DEMANDA_HISTORICO_STATUS_DEMANDA
(
	ID_DEMANDA BIGINT NOT NULL,
	ID_HISTORICO_STATUS_DEMANDA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE DESCRICAO_EVENTO
(
	ID BIGSERIAL NOT NULL,
	TIPO_DESCRICAO_EVENTO VARCHAR(100),
	CONTEUDO VARCHAR(20000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DESCRICAO_RECURSO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DESCRICAO_TIPO_ATENDIMENTO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	SIGLA VARCHAR(15) NOT NULL,
	DESCRICAO VARCHAR(1000),
	ID_TIPO_ATENDIMENTO BIGINT NOT NULL,
	INATIVO BOOLEAN DEFAULT 'false' NOT NULL,
	BLOQUEADO_LISTA_ESPERA BOOLEAN DEFAULT 'FALSE',
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DESCRICAO_TIPO_ATENDIMENTO_MODULO
(
	ID_DESCRICAO_TIPO_ATENDIMENTO BIGINT NOT NULL,
	ID_MODULO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE DESCRICAO_TIPO_ATENDIMENTO_NOME_GRUPO
(
	ID_DESCRICAO_TIPO_ATENDIMENTO BIGINT NOT NULL,
	ID_NOME_GRUPO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE DESCRICAO_TIPO_ATENDIMENTO_SETOR
(
	ID_DESCRICAO_TIPO_ATENDIMENTO BIGINT NOT NULL,
	ID_SETOR VARCHAR(10) NOT NULL
) WITHOUT OIDS;


CREATE TABLE DIA_SEMANA_E_HORARIO
(
	ID BIGSERIAL NOT NULL,
	DIA_SEMANA VARCHAR(10) NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_TERMINO TIME NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DIRETORIA_ENSINO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DOACOES_LEGADO
(
	CPF VARCHAR(14) NOT NULL,
	TIPO VARCHAR(255) NOT NULL,
	PRIMARY KEY (CPF)
) WITHOUT OIDS;


CREATE TABLE DOCUMENTO_SOLICITACAO_DOACAO
(
	ID BIGSERIAL NOT NULL,
	ID_ARQUIVO BIGINT NOT NULL,
	NOME_DOCUMENTO VARCHAR(250) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DOENCA
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DRE_CEFAI
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE EMPRESA
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ENCAMINHAMENTO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ENDERECO
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	UF VARCHAR(5),
	ID_MUNICIPIO BIGINT,
	CEP VARCHAR(8),
	ENDERECO VARCHAR(60),
	NUMERO VARCHAR(10),
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(50),
	ZONA VARCHAR(10),
	ID_PAIS BIGINT,
	TIPO_ENDERECO VARCHAR(11),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ESCOLARIDADE
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ESCOLARIDADE_SERIE
(
	ID_ESCOLARIDADE BIGINT NOT NULL,
	ID_SERIE BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ESPERA
(
	ID BIGSERIAL NOT NULL,
	ID_USUARIO BIGINT,
	ID_PRE_CADASTRO BIGINT,
	DATA DATE,
	ID_DESCRICAO_TIPO_ATENDIMENTO BIGINT NOT NULL,
	ID_MODULO BIGINT,
	ID_SETOR VARCHAR(10) NOT NULL,
	ID_NOME_GRUPO BIGINT,
	ID_PROFISSIONAL_SOLICITADO_POR BIGINT,
	TIPO_ESPERA VARCHAR(25),
	OBS VARCHAR(20000),
	JUSTIFICATIVA_CANCELAMENTO VARCHAR(20000),
	INTERESSE BOOLEAN DEFAULT 'false',
	LM_LIGOU BOOLEAN DEFAULT 'false',
	PENDENCIAS BOOLEAN DEFAULT 'false',
	CHAVE_ATENDIMENTO_ACARRETOU_INCLUSAO VARCHAR(1000),
	DATA_ULTIMA_LIGACAO_INTERESSE DATE,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ESPERA_HISTORICO_STATUS_ESPERA
(
	ID_ESPERA BIGINT NOT NULL,
	ID_HISTORICO_STATUS_ESPERA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ESTADO_CIVIL
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ETIOLOGIA
(
	ID BIGSERIAL NOT NULL,
	CID VARCHAR(4) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE EXPECTATIVA
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE FAMILIAR
(
	ID BIGSERIAL NOT NULL,
	ID_PARENTESCO BIGINT NOT NULL,
	CPF VARCHAR(11),
	DATA_NASCIMENTO DATE,
	ID_INFORMACAO_TRABALHO BIGINT NOT NULL,
	ID_ESTADO_CIVIL BIGINT,
	NAO_ALFABETIZADO BOOLEAN DEFAULT 'false',
	ID_INFORMACAO_ESSENCIAL BIGINT NOT NULL,
	RENDA DECIMAL,
	PRINCIPAL_RESPONSAVEL BOOLEAN NOT NULL,
	STATUS VARCHAR(25),
	MORA_NA_CASA BOOLEAN DEFAULT 'false',
	GENERO VARCHAR(20),
	RESPONSAVEL_PELA_AVALIACAO_SOCIAL BOOLEAN DEFAULT 'false',
	ACOMPANHANTE BOOLEAN DEFAULT 'false',
	RESPONSAVEL_PELO_USUARIO BOOLEAN DEFAULT 'false',
	PARADEIRO_IGNORADO BOOLEAN DEFAULT 'false',
	OBS VARCHAR(20000),
	FALECIDO BOOLEAN DEFAULT 'false',
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE FAMILIAR_INFORMACAO_EDUCACIONAL
(
	ID_FAMILIAR BIGINT NOT NULL,
	ID_INFORMACAO_EDUCACIONAL BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE FAMILIAR_PERIODO_BENEFICIO
(
	ID_FAMILIAR BIGINT NOT NULL,
	ID_PERIODO_BENEFICIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE FAMILIAR_VULNERABILIDADE
(
	ID_FAMILIAR BIGINT NOT NULL,
	ID_VULNERABILIDADE BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE FERIADO_PONTE
(
	DATA DATE NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_TERMINO TIME NOT NULL,
	PRIMARY KEY (DATA)
) WITHOUT OIDS;


CREATE TABLE FILIAL
(
	ID BIGINT NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	ENDERECO VARCHAR(60) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE GRUPO
(
	ID BIGSERIAL NOT NULL,
	ATIVO BOOLEAN NOT NULL,
	ID_NOME_GRUPO BIGINT NOT NULL,
	ID_SETOR VARCHAR(10) NOT NULL,
	ID_DESCRICAO_TIPO_ATENDIMENTO BIGINT NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_TERMINO DATE NOT NULL,
	TURMA VARCHAR(2) NOT NULL,
	NIVEL INT,
	DESCRICAO VARCHAR(20000),
	ID_INSTITUICAO BIGINT,
	EXCLUIDO BOOLEAN DEFAULT 'false' NOT NULL,
	NOME_CURSO VARCHAR(100),
	DATA_INICIO_PRE_INSCRICAO DATE,
	DATA_TERMINO_PRE_INSCRICAO DATE,
	VALOR_TOTAL_ALMOCO DECIMAL,
	INVESTIMENTO DECIMAL,
	PUBLICADO BOOLEAN DEFAULT 'false',
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE GRUPO_DESCRICAO_EVENTO
(
	ID_DESCRICAO_EVENTO BIGINT NOT NULL,
	ID_GRUPO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE GRUPO_LOTE_RECURSO
(
	ID_GRUPO BIGINT NOT NULL,
	ID_LOTE_RECURSO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE GRUPO_MODULO_PERIODO
(
	ID_GRUPO BIGINT NOT NULL,
	ID_MODULO_PERIODO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE GRUPO_TIPIFICACAO_SERVICO
(
	ID_GRUPO BIGINT NOT NULL,
	ID_TIPIFICACAO_SERVICO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE HABITACAO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_CLASSIFICACAO_SOCIAL
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	CLASSIFICACAO_SOCIAL VARCHAR(20),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_INSTITUICAO
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	ID_INSTITUICAO BIGINT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_RG
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	RG VARCHAR(15),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_SETOR
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	ID_SETOR VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_STATUS
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_STATUS_AGENDAMENTO
(
	ID BIGSERIAL NOT NULL,
	ID_CONTA_ACESSO BIGINT,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_STATUS_CONTRIBUINTE
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_STATUS_DEMANDA
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25) NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_STATUS_ESPERA
(
	ID BIGSERIAL NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_STATUS_RECIBO
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25) NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_STATUS_RETIRADA
(
	ID BIGSERIAL NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_STATUS_SOLICITACAO_RELATORIO
(
	ID BIGSERIAL NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS_SOLICITACAO_RELATORIO VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_STATUS_USUARIO
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25) NOT NULL,
	OBS VARCHAR(20000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE INFORMACAO_ATENDIMENTO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(20000),
	FREQUENCIA VARCHAR(2) NOT NULL,
	JUSTIFICATIVA VARCHAR(20000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE INFORMACAO_ATENDIMENTO_PARTICIPACAO_DETALHADA
(
	ID_INFORMACAO_ATENDIMENTO BIGINT NOT NULL,
	ID_PARTICIPACAO_DETALHADA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE INFORMACAO_EDUCACIONAL
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	ID_INSTITUICAO BIGINT,
	SITUACAO VARCHAR(20),
	PERIODO VARCHAR(20),
	ID_SERIE BIGINT,
	ID_ESCOLARIDADE BIGINT,
	NOME_PROFESSOR VARCHAR(100),
	EXCLUIDO BOOLEAN NOT NULL,
	ID_AREA_FORMACAO BIGINT,
	DATA_REFERENCIA TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE INFORMACAO_ESSENCIAL
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE,
	ID_CONTATO BIGINT NOT NULL,
	CPF VARCHAR(11),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE INFORMACAO_ESSENCIAL_ENDERECO
(
	ID_INFORMACAO_ESSENCIAL BIGINT NOT NULL,
	ID_ENDERECO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE INFORMACAO_ESSENCIAL_HISTORICO_RG
(
	ID_INFORMACAO_ESSENCIAL BIGINT NOT NULL,
	ID_HISTORICO_RG BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE INFORMACAO_TRABALHO
(
	ID BIGSERIAL NOT NULL,
	EMPRESA VARCHAR(150),
	FUNCAO VARCHAR(150),
	ID_CARGO BIGINT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE INFORMACAO_TRABALHO_COMPLETA
(
	ID BIGSERIAL NOT NULL,
	ID_LOCAL_TRABALHO BIGINT NOT NULL,
	ID_CARGO BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	VOLUNTARIO VARCHAR(5),
	ESTAGIARIO VARCHAR(5),
	ENCAMINHADO_POR_LARAMARA VARCHAR(5),
	OBS VARCHAR(20000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE INFRAESTRUTURA_BASICA
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE INSCRICAO
(
	ID BIGSERIAL NOT NULL,
	ID_USUARIO_EXTERNO BIGINT NOT NULL,
	ID_ENDERECO BIGINT NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL,
	OBSERVACOES VARCHAR(20000),
	NOME_PARA_CRACHA VARCHAR(16),
	AREA_FORMACAO VARCHAR(100),
	LOCAL_TRABALHO VARCHAR(100),
	CARGO_OU_FUNCAO VARCHAR(100),
	USUARIO_EXTERNO_POSSUI_CADEIRA_DE_RODAS BOOLEAN,
	USUARIO_EXTERNO_POSSUI_CAO_GUIA BOOLEAN,
	ID_GRUPO BIGINT NOT NULL,
	VALOR_TOTAL_ALMOCO_INCLUSO BOOLEAN,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE INSTITUICAO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	ID_ENDERECO BIGINT NOT NULL,
	ID_CONTATO BIGINT NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	RAMAL VARCHAR(6),
	NOME_COORDENADOR_RESPONSAVEL VARCHAR(100),
	CLASSIFICACAO VARCHAR(20) NOT NULL,
	OBS VARCHAR(20000),
	ID_DRE_CEFAI BIGINT,
	ID_DIRETORIA_ENSINO BIGINT,
	TIPO_APOIO VARCHAR(40),
	CONSTRAINT instituicao_pkey PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE INSTITUICAO_ESCOLARIDADE
(
	ID_INSTITUICAO BIGINT NOT NULL,
	ID_ESCOLARIDADE BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE INSTITUICAO_TIPO_ESPECIALIDADE
(
	ID_INSTITUICAO BIGINT NOT NULL,
	TIPO_ESPECIALIDADE VARCHAR(10) NOT NULL
) WITHOUT OIDS;


CREATE TABLE ITEM_CUSTO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	DEFICIENCIA BOOLEAN DEFAULT 'false',
	DOENCA BOOLEAN DEFAULT 'false',
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE LOCAL_ATENDIMENTO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE LOCAL_TRABALHO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE LOTE_RECURSO
(
	ID BIGSERIAL NOT NULL,
	ID_RECURSO BIGINT NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR NUMERIC,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MODULO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	BLOQUEADO_LISTA_ESPERA BOOLEAN DEFAULT 'FALSE',
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MODULO_PERIODO
(
	ID BIGSERIAL NOT NULL,
	ID_MODULO BIGINT NOT NULL,
	ID_LOCAL_ATENDIMENTO BIGINT NOT NULL,
	VAGAS INT NOT NULL,
	CARGA_HORARIA VARCHAR(13) NOT NULL,
	CARGA_HORARIA_MINIMA VARCHAR(13) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MODULO_PERIODO_ATENDIMENTO_GRUPO
(
	ID_ATENDIMENTO_GRUPO BIGINT NOT NULL,
	ID_MODULO_PERIODO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE MODULO_PERIODO_DIA_SEMANA_E_HORARIO
(
	ID_DIA_SEMANA_E_HORARIO BIGINT NOT NULL,
	ID_MODULO_PERIODO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE MODULO_PERIODO_MODULO_PRE_CADASTRO
(
	ID_MODULO_PRE_CADASTRO BIGINT NOT NULL,
	ID_MODULO_PERIODO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE MODULO_PERIODO_MODULO_USUARIO
(
	ID_MODULO_PERIODO BIGINT NOT NULL,
	ID_MODULO_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE MODULO_PERIODO_PROFISSIONAL_VINCULO
(
	ID_MODULO_PERIODO BIGINT NOT NULL,
	ID_PROFISSIONAL_VINCULO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE MODULO_PERIODO_PROGRAMACAO
(
	ID_MODULO_PERIODO BIGINT NOT NULL,
	ID_PROGRAMACAO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE MODULO_PRE_CADASTRO
(
	ID BIGSERIAL NOT NULL,
	ID_PRE_CADASTRO BIGINT NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_OCORRENCIA DATE,
	STATUS VARCHAR(25) NOT NULL,
	OBS VARCHAR(20000),
	APROVADO BOOLEAN,
	ID_TIPO_VINCULO BIGINT NOT NULL,
	NOME_ORIGEM_COMUNIDADE VARCHAR(100),
	CURSO VARCHAR(100),
	ID_DRE_CEFAI BIGINT,
	ID_DIRETORIA_ENSINO BIGINT,
	ID_INSTITUICAO BIGINT,
	ID_INSTITUICAO_COM_SRMS BIGINT,
	ID_INSTITUICAO_COM_SALA_RECURSO BIGINT,
	ID_INSTITUICAO_COM_OUTROS_AEE BIGINT,
	ID_USUARIO_VINCULADO BIGINT,
	QUANTIDADE_CRIANCAS INT,
	QUANTIDADE_ADULTOS INT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MODULO_USUARIO
(
	ID BIGSERIAL NOT NULL,
	ID_USUARIO BIGINT NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_OCORRENCIA DATE,
	STATUS VARCHAR(25) NOT NULL,
	OBS VARCHAR(20000),
	APROVADO BOOLEAN DEFAULT 'false',
	IGNORAR_REGRA_REUNIAO_DE_INTEGRACAO BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MOTIVO_CANCELAMENTO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	AGENDAMENTO BOOLEAN DEFAULT 'false',
	DEMANDA BOOLEAN DEFAULT 'false',
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MOTIVO_DESATIVACAO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE MUNICIPIO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	UF VARCHAR(5) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE NECESSIDADE
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE NOME_GRUPO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ORIGEM_ENCAMINHAMENTO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE ORIGEM_ENCAMINHAMENTO_DETALHADO
(
	ID BIGSERIAL NOT NULL,
	ID_ORIGEM_ENCAMINHAMENTO BIGINT,
	PROFISSIONAL_LIBERAL VARCHAR(100),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PAIS
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CONSTRAINT pais_pkey PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PARENTESCO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PARTICIPACAO_DETALHADA
(
	ID BIGSERIAL NOT NULL,
	PARTICIPACAO VARCHAR(50) NOT NULL,
	QUANTIDADE BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PATROCINIO
(
	ID BIGSERIAL NOT NULL,
	ID_EMPRESA BIGINT NOT NULL,
	VALOR DECIMAL NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PENDENCIA
(
	ID BIGSERIAL NOT NULL,
	TIPO VARCHAR(50) NOT NULL,
	PRONTUARIO BIGINT,
	RESOLVIDA BOOLEAN DEFAULT 'false' NOT NULL,
	ID_AGENDAMENTO BIGINT,
	ID_GRUPO BIGINT,
	ID_MODULO_PERIODO BIGINT,
	DATA DATE,
	HORA_INICIO TIME,
	HORA_TERMINO TIME,
	OBS VARCHAR(20000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PENDENCIA_PROFISSIONAL
(
	ID_PENDENCIA BIGINT NOT NULL,
	ID_PROFISSIONAL BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE PERFIL
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100),
	CONSTRAINT perfil_pkey PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PERFIL_PERMISSOES
(
	ID_PERFIL BIGINT NOT NULL,
	PERMISSAO VARCHAR(100)
) WITHOUT OIDS;


CREATE TABLE PERIODO_BENEFICIO
(
	ID BIGSERIAL NOT NULL,
	ID_BENEFICIO BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PERIODO_COMPROMETIMENTO
(
	ID BIGSERIAL NOT NULL,
	ID_COMPROMETIMENTO BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	EPOCA_INCIDENCIA VARCHAR(25),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PERIODO_DEFICIENCIA
(
	ID BIGSERIAL NOT NULL,
	ID_DEFICIENCIA BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	CID VARCHAR(4),
	EPOCA_INCIDENCIA VARCHAR(25),
	EXCLUIDO BOOLEAN DEFAULT 'FALSE',
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PERIODO_DEFICIENCIA_ETIOLOGIA
(
	ID_ETIOLOGIA BIGINT NOT NULL,
	ID_PERIODO_DEFICIENCIA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE PERIODO_DOENCA
(
	ID BIGSERIAL NOT NULL,
	ID_DOENCA BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	OBS VARCHAR(20000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PRE_CADASTRO
(
	ID BIGSERIAL NOT NULL,
	DATA_CADASTRO TIMESTAMP NOT NULL,
	ID_INFORMACAO_ESSENCIAL BIGINT NOT NULL,
	OBS VARCHAR(20000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PROFISSIONAL
(
	ID BIGSERIAL NOT NULL,
	CHAPA VARCHAR(10),
	NOME VARCHAR(100) NOT NULL,
	HABILITADO BOOLEAN DEFAULT 'true' NOT NULL,
	VOLUNTARIO BOOLEAN DEFAULT 'false' NOT NULL,
	PROFISSIONAL BOOLEAN DEFAULT 'false' NOT NULL,
	ESPECIALIDADE VARCHAR(50),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PROFISSIONAL_VINCULO
(
	ID BIGSERIAL NOT NULL,
	ID_PROFISSIONAL BIGINT NOT NULL,
	PARTICIPANTE BOOLEAN DEFAULT 'FALSE',
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PROGRAMACAO
(
	ID BIGSERIAL NOT NULL,
	AULA INT NOT NULL,
	DATA DATE NOT NULL,
	TEMA_CONTEUDO VARCHAR(20000),
	ESTRATEGIAS VARCHAR(20000),
	RECADO_FAMILIA VARCHAR(20000),
	ID_LOCAL_ATENDIMENTO BIGINT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PROJETO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_INICIAL_VIGENCIA DATE NOT NULL,
	VALOR VARCHAR(25),
	ATIVO BOOLEAN NOT NULL,
	VALOR_PRODUTOS DECIMAL NOT NULL,
	VALOR_OUTROS DECIMAL NOT NULL,
	EDITAL_INVESTIMENTO VARCHAR(100),
	ORGAO_PARCEIRO_FINANCIADOR VARCHAR(100),
	LEI VARCHAR(100),
	OBJETIVO_GERAL VARCHAR(20000),
	PUBLICO_ALVO VARCHAR(20000),
	NUMERO_TERMO_FOMENTO_PARCERIA VARCHAR(100),
	INCENTIVADO VARCHAR(5),
	CLASSIFICACAO VARCHAR(20),
	ID_PROFISSIONAL_ADMINISTRATIVO_RESPONSAVEL BIGINT,
	PRESTACAO_CONTAS VARCHAR(20),
	DURACAO INT,
	ADITAMENTO INT,
	IDADE_MINIMA INT,
	IDADE_MAXIMA INT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE PROJETO_ARQUIVO
(
	ID_ARQUIVO BIGINT NOT NULL,
	ID_PROJETO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE PROJETO_PATROCINIO
(
	ID_PROJETO BIGINT NOT NULL,
	ID_PATROCINIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE PROJETO_RECURSO_DISPONIVEL
(
	ID_PROJETO BIGINT NOT NULL,
	ID_RECURSO_DISPONIVEL BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE PROJETO_RESERVA
(
	ID_RESERVA BIGINT NOT NULL,
	ID_PROJETO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE PROJETO_RESPONSAVEL_TECNICO
(
	ID_PROJETO BIGINT NOT NULL,
	ID_RESPONSAVEL_TECNICO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE RECIBO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CPF_CNPJ VARCHAR(14) NOT NULL,
	VALOR NUMERIC NOT NULL,
	DATA_DO_REGISTRO TIMESTAMP NOT NULL,
	DATA DATE NOT NULL,
	DESCRICAO VARCHAR(20000),
	MOTIVO_DO_CANCELAMENTO VARCHAR(20000),
	ID_FILIAL BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE RECIBO_HISTORICO_STATUS_RECIBO
(
	ID_RECIBO BIGINT NOT NULL,
	ID_HISTORICO_STATUS_RECIBO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE RECURSO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	CARTELA_DE_SELOS BOOLEAN DEFAULT 'false',
	VALOR DECIMAL,
	DISPONIVEL_PARA_DEMANDA BOOLEAN DEFAULT 'false',
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE RECURSO_DESCRICAO_RECURSO
(
	ID_DESCRICAO_RECURSO BIGINT NOT NULL,
	ID_RECURSO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE RECURSO_DISPONIVEL
(
	ID BIGSERIAL NOT NULL,
	ID_RECURSO BIGINT NOT NULL,
	VALOR_UNITARIO DECIMAL NOT NULL,
	QUANTIDADE INT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE RECURSO_MORADIA
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE RECURSO_RELACIONAMENTO
(
	ID BIGSERIAL NOT NULL,
	ID_RECURSO BIGINT NOT NULL,
	POSSUI_NECESSITA VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE RESERVA
(
	ID BIGSERIAL NOT NULL,
	DATA TIMESTAMP NOT NULL,
	ID_DEMANDA BIGINT NOT NULL,
	VALOR DECIMAL NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE RESPONSAVEL_TECNICO
(
	ID BIGSERIAL NOT NULL,
	ID_PROFISSIONAL BIGINT NOT NULL,
	PRINCIPAL BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE RETIRADA
(
	ID BIGSERIAL NOT NULL,
	PRONTUARIO BIGINT NOT NULL,
	ID_PROFISSIONAL BIGINT NOT NULL,
	ID_VOLUNTARIO BIGINT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE RETIRADA_HISTORICO_STATUS_RETIRADA
(
	ID_RETIRADA BIGINT NOT NULL,
	ID_HISTORICO_STATUS_RETIRADA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE SERIE
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE SERVICO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE SETOR
(
	ID VARCHAR(10) NOT NULL,
	DESCRICAO VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE SITUACAO_GUARDA
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE SITUACAO_HABITACIONAL
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE SOLICITACAO_RELATORIO
(
	ID BIGSERIAL NOT NULL,
	NOME_SOLICITANTE VARCHAR(100) NOT NULL,
	RG_SOLICITANTE VARCHAR(15) NOT NULL,
	ID_USUARIO BIGINT NOT NULL,
	QUANTIDADE_RELATORIOS_EMITIDOS INT,
	QUANTIDADE_RELATORIOS_ENTREGUES INT,
	OBS VARCHAR(20000),
	ELABORADOR VARCHAR(50) NOT NULL,
	ENVIAR_PELO_CORREIO BOOLEAN,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE SOLICITACAO_RELATORIO_FINALIDADE_RELATORIO
(
	ID_SOLICITACAO_RELATORIO BIGINT NOT NULL,
	FINALIDADE_RELATORIO VARCHAR(50) NOT NULL
) WITHOUT OIDS;


CREATE TABLE SOLICITACAO_RELATORIO_HISTORICO_STATUS_SOLICITACAO_RELATORIO
(
	ID_SOLICITACAO_RELATORIO BIGINT NOT NULL,
	ID_HISTORICO_STATUS_SOLICITACAO_RELATORIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE TELEFONE
(
	TIPO VARCHAR(20) NOT NULL,
	DDD VARCHAR(2) NOT NULL,
	TELEFONE VARCHAR(10) NOT NULL,
	ID_CONTATO BIGINT NOT NULL,
	RAMAL VARCHAR(6),
	NOME_CONTATO VARCHAR(100)
) WITHOUT OIDS;


CREATE TABLE TIPIFICACAO_SERVICO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TIPO_ATENDIMENTO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	INATIVO BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TIPO_ATENDIMENTO_DESCRICAO_TIPO_ATENDIMENTO
(
	ID_TIPO_ATENDIMENTO BIGINT NOT NULL,
	ID_DESCRICAO_TIPO_ATENDIMENTO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE TIPO_CONSTRUCAO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TIPO_VINCULO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE USUARIO
(
	ID BIGSERIAL NOT NULL,
	VERSAO VARCHAR(36) DEFAULT ' ',
	DATA_CADASTRO TIMESTAMP NOT NULL,
	ID_INFORMACAO_ESSENCIAL BIGINT NOT NULL,
	GENERO VARCHAR(20) NOT NULL,
	NATURALIDADE VARCHAR(30) NOT NULL,
	NACIONALIDADE VARCHAR(30) NOT NULL,
	RG_UF VARCHAR(5),
	RG_DATA_EXPEDICAO DATE,
	RG_ORGAO_EMISSOR VARCHAR(25),
	ID_ESTADO_CIVIL BIGINT NOT NULL,
	RESPONSAVEL_POR_SI_MESMO BOOLEAN DEFAULT 'false',
	GRUPO_ETNICO VARCHAR(20),
	CADEIRA_DE_RODAS BOOLEAN DEFAULT 'FALSE',
	OBS VARCHAR(20000),
	OUTROS_APOIOS_SERVICOS VARCHAR(100),
	TIPO_LEITURA VARCHAR(25),
	TAMANHO_FONTE VARCHAR(100),
	ATUALMENTE_TRABALHANDO VARCHAR(5),
	RENDA DECIMAL,
	CIRURGIAS VARCHAR(20000),
	MEDICAMENTOS VARCHAR(20000),
	POSSUI_CONSANGUINIDADE VARCHAR(5),
	CONSANGUINIDADE VARCHAR(20000),
	FALECIDO BOOLEAN DEFAULT 'false',
	ID_CONDICAO_MORADIA BIGINT,
	ID_SITUACAO_HABITACIONAL BIGINT,
	ID_HABITACAO BIGINT,
	ID_TIPO_CONSTRUCAO BIGINT,
	HISTORICO VARCHAR(20000),
	FUNCIONALIDADE VARCHAR(20000),
	REACAO_FRENTE_A_DEFICIENCIA VARCHAR(20000),
	REACAO_FRENTE_A_DEFICIENCIA_FAMILIA VARCHAR(20000),
	REDE_DE_APOIO VARCHAR(20000),
	REDE_DE_AMIGOS VARCHAR(20000),
	NAMORO_CASAMENTO_SEXUALIDADE VARCHAR(20000),
	NECESSIDADES_EXPECTATIVAS_QUEIXAS VARCHAR(20000),
	EDUCACIONAL VARCHAR(20000),
	COMUNICACAO VARCHAR(20000),
	RELIGIAO_LAZER_CULTURA_ROTINA VARCHAR(20000),
	PARECER VARCHAR(20000),
	CONSTRAINT usuario_pkey PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE USUARIO_CERTIDAO
(
	ID_CERTIDAO BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_CONVENIO
(
	ID_USUARIO BIGINT NOT NULL,
	ID_CONVENIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_CUSTO_DEFICIENCIA
(
	ID_USUARIO BIGINT NOT NULL,
	ID_CUSTO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_CUSTO_DOENCA
(
	ID_USUARIO BIGINT NOT NULL,
	ID_CUSTO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_ENCAMINHAMENTO
(
	ID_USUARIO BIGINT NOT NULL,
	ID_ENCAMINHAMENTO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_EXPECTATIVA
(
	ID_USUARIO BIGINT NOT NULL,
	ID_EXPECTATIVA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_EXTERNO
(
	ID BIGSERIAL NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	NOME_COMPLETO VARCHAR(100) NOT NULL,
	DDD VARCHAR(2) NOT NULL,
	TELEFONE_CELULAR VARCHAR(9) NOT NULL,
	OUTRO_TELEFONE VARCHAR(11),
	SENHA VARCHAR(100),
	AUTORIZO_RECEBIMENTO_INFORMATIVO BOOLEAN,
	BLOQUEADO BOOLEAN,
	TOKEN VARCHAR(36),
	CPF VARCHAR(11),
	DATA_NASCIMENTO DATE,
	RG_RNE VARCHAR(15),
	ID_ENDERECO_RESIDENCIAL BIGINT,
	E_PESSOA_COM_DEFICIENCIA BOOLEAN,
	POSSUI_BAIXA_VISAO BOOLEAN,
	POSSUI_CEGUEIRA BOOLEAN,
	OUTRA_DEFICIENCIA VARCHAR(100),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE USUARIO_FAMILIAR
(
	ID_USUARIO BIGINT NOT NULL,
	ID_FAMILIAR BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_HISTORICO_CLASSIFICACAO_SOCIAL
(
	ID_USUARIO BIGINT NOT NULL,
	ID_HISTORICO_CLASSIFICACAO_SOCIAL BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_HISTORICO_INSTITUICAO_OUTROS_AEE
(
	ID_USUARIO BIGINT NOT NULL,
	ID_HISTORICO_INSTITUICAO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_HISTORICO_INSTITUICAO_SALA_RECURSO
(
	ID_USUARIO BIGINT NOT NULL,
	ID_HISTORICO_INSTITUICAO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_HISTORICO_INSTITUICAO_SRMS
(
	ID_USUARIO BIGINT NOT NULL,
	ID_HISTORICO_INSTITUICAO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_HISTORICO_SETOR
(
	ID_USUARIO BIGINT NOT NULL,
	ID_HISTORICO_SETOR BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_HISTORICO_STATUS
(
	ID_USUARIO BIGINT NOT NULL,
	ID_HISTORICO_STATUS BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_HISTORICO_STATUS_USUARIO
(
	ID_USUARIO BIGINT NOT NULL,
	ID_HISTORICO_STATUS_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_INFORMACAO_EDUCACIONAL
(
	ID_USUARIO BIGINT NOT NULL,
	ID_INFORMACAO_EDUCACIONAL BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_INFORMACAO_TRABALHO_COMPLETA
(
	ID_INFORMACAO_TRABALHO_COMPLETA BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_INFRAESTRUTURA_BASICA
(
	ID_INFRAESTRUTURA_BASICA BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_NECESSIDADE
(
	ID_NECESSIDADE BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_ORIGEM_ENCAMINHAMENTO_DETALHADO
(
	ID_USUARIO BIGINT NOT NULL,
	ID_ORIGEM_ENCAMINHAMENTO_DETALHADO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_PERIODO_BENEFICIO
(
	ID_PERIODO_BENEFICIO BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_PERIODO_COMPROMETIMENTO
(
	ID_PERIODO_COMPROMETIMENTO BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_PERIODO_DEFICIENCIA
(
	ID_PERIODO_DEFICIENCIA BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_PERIODO_DOENCA
(
	ID_PERIODO_DOENCA BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_RECURSO
(
	ID_RECURSO BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_RECURSO_MORADIA
(
	ID_USUARIO BIGINT NOT NULL,
	ID_RECURSO_MORADIA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_RECURSO_RELACIONAMENTO
(
	ID_RECURSO_RELACIONAMENTO BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_SERVICO
(
	ID_USUARIO BIGINT NOT NULL,
	ID_SERVICO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_SITUACAO_GUARDA
(
	ID_USUARIO BIGINT NOT NULL,
	ID_SITUACAO_GUARDA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_VULNERABILIDADE_FAMILIA
(
	ID_USUARIO BIGINT NOT NULL,
	ID_VULNERABILIDADE BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE USUARIO_VULNERABILIDADE_USUARIO
(
	ID_USUARIO BIGINT NOT NULL,
	ID_VULNERABILIDADE BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE VULNERABILIDADE
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	DISPONIVEL_PARA_USUARIO BOOLEAN DEFAULT 'false' NOT NULL,
	DISPONIVEL_PARA_FAMILIA BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE ATENDIMENTO_INDIVIDUAL_ACAO_CONDUTA
	ADD FOREIGN KEY (ID_ACAO_CONDUTA)
	REFERENCES ACAO_CONDUTA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO_GRUPO
	ADD FOREIGN KEY (ID_AGENDAMENTO)
	REFERENCES AGENDAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO_HISTORICO_STATUS_AGENDAMENTO
	ADD FOREIGN KEY (ID_AGENDAMENTO)
	REFERENCES AGENDAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PENDENCIA
	ADD FOREIGN KEY (ID_AGENDAMENTO)
	REFERENCES AGENDAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_EDUCACIONAL
	ADD FOREIGN KEY (ID_AREA_FORMACAO)
	REFERENCES AREA_FORMACAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_GRUPO_ARQUIVO
	ADD FOREIGN KEY (ID_ARQUIVO)
	REFERENCES ARQUIVO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL_ARQUIVO
	ADD FOREIGN KEY (ID_ARQUIVO)
	REFERENCES ARQUIVO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_USUARIO_ARQUIVO
	ADD FOREIGN KEY (ID_ARQUIVO)
	REFERENCES ARQUIVO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DOCUMENTO_SOLICITACAO_DOACAO
	ADD FOREIGN KEY (ID_ARQUIVO)
	REFERENCES ARQUIVO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO_ARQUIVO
	ADD FOREIGN KEY (ID_ARQUIVO)
	REFERENCES ARQUIVO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_COMUNIDADE
	ADD FOREIGN KEY (ID_ATENDIMENTO_COMUNIDADE)
	REFERENCES ATENDIMENTO_COMUNIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_GRUPO_ARQUIVO
	ADD FOREIGN KEY (ID_ATENDIMENTO_GRUPO)
	REFERENCES ATENDIMENTO_GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_GRUPO_ATENDIMENTO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_ATENDIMENTO_GRUPO)
	REFERENCES ATENDIMENTO_GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_GRUPO_ATENDIMENTO_PROFISSIONAL
	ADD FOREIGN KEY (ID_ATENDIMENTO_GRUPO)
	REFERENCES ATENDIMENTO_GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_GRUPO_ATENDIMENTO_USUARIO
	ADD FOREIGN KEY (ID_ATENDIMENTO_GRUPO)
	REFERENCES ATENDIMENTO_GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_ATENDIMENTO_GRUPO
	ADD FOREIGN KEY (ID_ATENDIMENTO_GRUPO)
	REFERENCES ATENDIMENTO_GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL_ACAO_CONDUTA
	ADD FOREIGN KEY (ID_ATENDIMENTO_INDIVIDUAL)
	REFERENCES ATENDIMENTO_INDIVIDUAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL_ARQUIVO
	ADD FOREIGN KEY (ID_ATENDIMENTO_INDIVIDUAL)
	REFERENCES ATENDIMENTO_INDIVIDUAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_COMUNIDADE
	ADD FOREIGN KEY (ID_ATENDIMENTO_INDIVIDUAL)
	REFERENCES ATENDIMENTO_INDIVIDUAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_PROFISSIONAL
	ADD FOREIGN KEY (ID_ATENDIMENTO_INDIVIDUAL)
	REFERENCES ATENDIMENTO_INDIVIDUAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_GRUPO_ATENDIMENTO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_ATENDIMENTO_PRE_CADASTRO)
	REFERENCES ATENDIMENTO_PRE_CADASTRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_GRUPO_ATENDIMENTO_PROFISSIONAL
	ADD FOREIGN KEY (ID_ATENDIMENTO_PROFISSIONAL)
	REFERENCES ATENDIMENTO_PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL_ATENDIMENTO_PROFISSIONAL
	ADD FOREIGN KEY (ID_ATENDIMENTO_PROFISSIONAL)
	REFERENCES ATENDIMENTO_PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_GRUPO_ATENDIMENTO_USUARIO
	ADD FOREIGN KEY (ID_ATENDIMENTO_USUARIO)
	REFERENCES ATENDIMENTO_USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_USUARIO_ARQUIVO
	ADD FOREIGN KEY (ID_ATENDIMENTO_USUARIO)
	REFERENCES ATENDIMENTO_USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PERIODO_BENEFICIO
	ADD FOREIGN KEY (ID_BENEFICIO)
	REFERENCES BENEFICIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA_CAPTACAO
	ADD FOREIGN KEY (ID_CAPTACAO)
	REFERENCES CAPTACAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_TRABALHO
	ADD FOREIGN KEY (ID_CARGO)
	REFERENCES CARGO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_TRABALHO_COMPLETA
	ADD FOREIGN KEY (ID_CARGO)
	REFERENCES CARGO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_CERTIDAO
	ADD FOREIGN KEY (ID_CERTIDAO)
	REFERENCES CERTIDAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ETIOLOGIA
	ADD FOREIGN KEY (CID)
	REFERENCES CID10 (CID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PERIODO_DEFICIENCIA
	ADD FOREIGN KEY (CID)
	REFERENCES CID10 (CID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PERIODO_COMPROMETIMENTO
	ADD FOREIGN KEY (ID_COMPROMETIMENTO)
	REFERENCES COMPROMETIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO
	ADD FOREIGN KEY (ID_CONDICAO_MORADIA)
	REFERENCES CONDICAO_MORADIA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTRIBUINTE
	ADD FOREIGN KEY (ID_CONTATO)
	REFERENCES CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_ESSENCIAL
	ADD FOREIGN KEY (ID_CONTATO)
	REFERENCES CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSTITUICAO
	ADD FOREIGN KEY (ID_CONTATO)
	REFERENCES CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TELEFONE
	ADD FOREIGN KEY (ID_CONTATO)
	REFERENCES CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CAPTACAO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTA_ACESSO_PERMISSOES
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTA_ACESSO_PROFISSIONAL_EQUIVALENTE
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HISTORICO_STATUS_AGENDAMENTO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HISTORICO_STATUS_DEMANDA
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HISTORICO_STATUS_ESPERA
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HISTORICO_STATUS_RECIBO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HISTORICO_STATUS_RETIRADA
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HISTORICO_STATUS_SOLICITACAO_RELATORIO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTRIBUINTE_HISTORICO_STATUS_CONTRIBUINTE
	ADD FOREIGN KEY (ID_CONTRIBUINTE)
	REFERENCES CONTRIBUINTE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_CONVENIO
	ADD FOREIGN KEY (ID_CONVENIO)
	REFERENCES CONVENIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_CUSTO_DEFICIENCIA
	ADD FOREIGN KEY (ID_CUSTO)
	REFERENCES CUSTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_CUSTO_DOENCA
	ADD FOREIGN KEY (ID_CUSTO)
	REFERENCES CUSTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PERIODO_DEFICIENCIA
	ADD FOREIGN KEY (ID_DEFICIENCIA)
	REFERENCES DEFICIENCIA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA_CAPTACAO
	ADD FOREIGN KEY (ID_DEMANDA)
	REFERENCES DEMANDA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA_DOCUMENTO_SOLICITACAO_DOACAO
	ADD FOREIGN KEY (ID_DEMANDA)
	REFERENCES DEMANDA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA_HISTORICO_STATUS_DEMANDA
	ADD FOREIGN KEY (ID_DEMANDA)
	REFERENCES DEMANDA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESERVA
	ADD FOREIGN KEY (ID_DEMANDA)
	REFERENCES DEMANDA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO_DESCRICAO_EVENTO
	ADD FOREIGN KEY (ID_DESCRICAO_EVENTO)
	REFERENCES DESCRICAO_EVENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA
	ADD FOREIGN KEY (ID_DESCRICAO_RECURSO)
	REFERENCES DESCRICAO_RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RECURSO_DESCRICAO_RECURSO
	ADD FOREIGN KEY (ID_DESCRICAO_RECURSO)
	REFERENCES DESCRICAO_RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO
	ADD FOREIGN KEY (ID_DESCRICAO_TIPO_ATENDIMENTO)
	REFERENCES DESCRICAO_TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL
	ADD FOREIGN KEY (ID_DESCRICAO_TIPO_ATENDIMENTO)
	REFERENCES DESCRICAO_TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BLOQUEIO
	ADD FOREIGN KEY (ID_DESCRICAO_TIPO_ATENDIMENTO)
	REFERENCES DESCRICAO_TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DESCRICAO_TIPO_ATENDIMENTO_MODULO
	ADD FOREIGN KEY (ID_DESCRICAO_TIPO_ATENDIMENTO)
	REFERENCES DESCRICAO_TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DESCRICAO_TIPO_ATENDIMENTO_NOME_GRUPO
	ADD FOREIGN KEY (ID_DESCRICAO_TIPO_ATENDIMENTO)
	REFERENCES DESCRICAO_TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DESCRICAO_TIPO_ATENDIMENTO_SETOR
	ADD FOREIGN KEY (ID_DESCRICAO_TIPO_ATENDIMENTO)
	REFERENCES DESCRICAO_TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESPERA
	ADD FOREIGN KEY (ID_DESCRICAO_TIPO_ATENDIMENTO)
	REFERENCES DESCRICAO_TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO
	ADD FOREIGN KEY (ID_DESCRICAO_TIPO_ATENDIMENTO)
	REFERENCES DESCRICAO_TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TIPO_ATENDIMENTO_DESCRICAO_TIPO_ATENDIMENTO
	ADD FOREIGN KEY (ID_DESCRICAO_TIPO_ATENDIMENTO)
	REFERENCES DESCRICAO_TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_DIA_SEMANA_E_HORARIO
	ADD FOREIGN KEY (ID_DIA_SEMANA_E_HORARIO)
	REFERENCES DIA_SEMANA_E_HORARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSTITUICAO
	ADD FOREIGN KEY (ID_DIRETORIA_ENSINO)
	REFERENCES DIRETORIA_ENSINO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_DIRETORIA_ENSINO)
	REFERENCES DIRETORIA_ENSINO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA_DOCUMENTO_SOLICITACAO_DOACAO
	ADD FOREIGN KEY (ID_DOCUMENTO_SOLICITACAO_DOACAO)
	REFERENCES DOCUMENTO_SOLICITACAO_DOACAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PERIODO_DOENCA
	ADD FOREIGN KEY (ID_DOENCA)
	REFERENCES DOENCA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSTITUICAO
	ADD FOREIGN KEY (ID_DRE_CEFAI)
	REFERENCES DRE_CEFAI (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_DRE_CEFAI)
	REFERENCES DRE_CEFAI (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PATROCINIO
	ADD FOREIGN KEY (ID_EMPRESA)
	REFERENCES EMPRESA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_ENCAMINHAMENTO
	ADD FOREIGN KEY (ID_ENCAMINHAMENTO)
	REFERENCES ENCAMINHAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTRIBUINTE
	ADD FOREIGN KEY (ID_ENDERECO)
	REFERENCES ENDERECO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_ESSENCIAL_ENDERECO
	ADD FOREIGN KEY (ID_ENDERECO)
	REFERENCES ENDERECO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSCRICAO
	ADD FOREIGN KEY (ID_ENDERECO)
	REFERENCES ENDERECO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSTITUICAO
	ADD FOREIGN KEY (ID_ENDERECO)
	REFERENCES ENDERECO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_EXTERNO
	ADD FOREIGN KEY (ID_ENDERECO_RESIDENCIAL)
	REFERENCES ENDERECO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESCOLARIDADE_SERIE
	ADD FOREIGN KEY (ID_ESCOLARIDADE)
	REFERENCES ESCOLARIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_EDUCACIONAL
	ADD FOREIGN KEY (ID_ESCOLARIDADE)
	REFERENCES ESCOLARIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSTITUICAO_ESCOLARIDADE
	ADD FOREIGN KEY (ID_ESCOLARIDADE)
	REFERENCES ESCOLARIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESPERA_HISTORICO_STATUS_ESPERA
	ADD FOREIGN KEY (ID_ESPERA)
	REFERENCES ESPERA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAMILIAR
	ADD FOREIGN KEY (ID_ESTADO_CIVIL)
	REFERENCES ESTADO_CIVIL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO
	ADD FOREIGN KEY (ID_ESTADO_CIVIL)
	REFERENCES ESTADO_CIVIL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PERIODO_DEFICIENCIA_ETIOLOGIA
	ADD FOREIGN KEY (ID_ETIOLOGIA)
	REFERENCES ETIOLOGIA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_EXPECTATIVA
	ADD FOREIGN KEY (ID_EXPECTATIVA)
	REFERENCES EXPECTATIVA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAMILIAR_INFORMACAO_EDUCACIONAL
	ADD FOREIGN KEY (ID_FAMILIAR)
	REFERENCES FAMILIAR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAMILIAR_PERIODO_BENEFICIO
	ADD FOREIGN KEY (ID_FAMILIAR)
	REFERENCES FAMILIAR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAMILIAR_VULNERABILIDADE
	ADD FOREIGN KEY (ID_FAMILIAR)
	REFERENCES FAMILIAR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_FAMILIAR
	ADD FOREIGN KEY (ID_FAMILIAR)
	REFERENCES FAMILIAR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RECIBO
	ADD FOREIGN KEY (ID_FILIAL)
	REFERENCES FILIAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ACAO_CONDUTA
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO_GRUPO
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO_DESCRICAO_EVENTO
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO_LOTE_RECURSO
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO_MODULO_PERIODO
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO_TIPIFICACAO_SERVICO
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSCRICAO
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PENDENCIA
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO
	ADD FOREIGN KEY (ID_HABITACAO)
	REFERENCES HABITACAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_CLASSIFICACAO_SOCIAL
	ADD FOREIGN KEY (ID_HISTORICO_CLASSIFICACAO_SOCIAL)
	REFERENCES HISTORICO_CLASSIFICACAO_SOCIAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_OUTROS_AEE
	ADD FOREIGN KEY (ID_HISTORICO_INSTITUICAO)
	REFERENCES HISTORICO_INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_SALA_RECURSO
	ADD FOREIGN KEY (ID_HISTORICO_INSTITUICAO)
	REFERENCES HISTORICO_INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_SRMS
	ADD FOREIGN KEY (ID_HISTORICO_INSTITUICAO)
	REFERENCES HISTORICO_INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_ESSENCIAL_HISTORICO_RG
	ADD FOREIGN KEY (ID_HISTORICO_RG)
	REFERENCES HISTORICO_RG (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_SETOR
	ADD FOREIGN KEY (ID_HISTORICO_SETOR)
	REFERENCES HISTORICO_SETOR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_STATUS
	ADD FOREIGN KEY (ID_HISTORICO_STATUS)
	REFERENCES HISTORICO_STATUS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO_HISTORICO_STATUS_AGENDAMENTO
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_AGENDAMENTO)
	REFERENCES HISTORICO_STATUS_AGENDAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTRIBUINTE_HISTORICO_STATUS_CONTRIBUINTE
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_CONTRIBUINTE)
	REFERENCES HISTORICO_STATUS_CONTRIBUINTE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA_HISTORICO_STATUS_DEMANDA
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_DEMANDA)
	REFERENCES HISTORICO_STATUS_DEMANDA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESPERA_HISTORICO_STATUS_ESPERA
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_ESPERA)
	REFERENCES HISTORICO_STATUS_ESPERA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RECIBO_HISTORICO_STATUS_RECIBO
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_RECIBO)
	REFERENCES HISTORICO_STATUS_RECIBO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RETIRADA_HISTORICO_STATUS_RETIRADA
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_RETIRADA)
	REFERENCES HISTORICO_STATUS_RETIRADA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SOLICITACAO_RELATORIO_HISTORICO_STATUS_SOLICITACAO_RELATORIO
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_SOLICITACAO_RELATORIO)
	REFERENCES HISTORICO_STATUS_SOLICITACAO_RELATORIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_STATUS_USUARIO
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_USUARIO)
	REFERENCES HISTORICO_STATUS_USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_COMUNIDADE
	ADD FOREIGN KEY (ID_INFORMACAO_ATENDIMENTO)
	REFERENCES INFORMACAO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL
	ADD FOREIGN KEY (ID_INFORMACAO_ATENDIMENTO)
	REFERENCES INFORMACAO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_INFORMACAO_ATENDIMENTO)
	REFERENCES INFORMACAO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_PROFISSIONAL
	ADD FOREIGN KEY (ID_INFORMACAO_ATENDIMENTO)
	REFERENCES INFORMACAO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_USUARIO
	ADD FOREIGN KEY (ID_INFORMACAO_ATENDIMENTO)
	REFERENCES INFORMACAO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_ATENDIMENTO_PARTICIPACAO_DETALHADA
	ADD FOREIGN KEY (ID_INFORMACAO_ATENDIMENTO)
	REFERENCES INFORMACAO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAMILIAR_INFORMACAO_EDUCACIONAL
	ADD FOREIGN KEY (ID_INFORMACAO_EDUCACIONAL)
	REFERENCES INFORMACAO_EDUCACIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_INFORMACAO_EDUCACIONAL
	ADD FOREIGN KEY (ID_INFORMACAO_EDUCACIONAL)
	REFERENCES INFORMACAO_EDUCACIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAMILIAR
	ADD FOREIGN KEY (ID_INFORMACAO_ESSENCIAL)
	REFERENCES INFORMACAO_ESSENCIAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_ESSENCIAL_ENDERECO
	ADD FOREIGN KEY (ID_INFORMACAO_ESSENCIAL)
	REFERENCES INFORMACAO_ESSENCIAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_ESSENCIAL_HISTORICO_RG
	ADD FOREIGN KEY (ID_INFORMACAO_ESSENCIAL)
	REFERENCES INFORMACAO_ESSENCIAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PRE_CADASTRO
	ADD FOREIGN KEY (ID_INFORMACAO_ESSENCIAL)
	REFERENCES INFORMACAO_ESSENCIAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO
	ADD FOREIGN KEY (ID_INFORMACAO_ESSENCIAL)
	REFERENCES INFORMACAO_ESSENCIAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAMILIAR
	ADD FOREIGN KEY (ID_INFORMACAO_TRABALHO)
	REFERENCES INFORMACAO_TRABALHO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_INFORMACAO_TRABALHO_COMPLETA
	ADD FOREIGN KEY (ID_INFORMACAO_TRABALHO_COMPLETA)
	REFERENCES INFORMACAO_TRABALHO_COMPLETA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_INFRAESTRUTURA_BASICA
	ADD FOREIGN KEY (ID_INFRAESTRUTURA_BASICA)
	REFERENCES INFRAESTRUTURA_BASICA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO
	ADD FOREIGN KEY (ID_INSTITUICAO)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HISTORICO_INSTITUICAO
	ADD FOREIGN KEY (ID_INSTITUICAO)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_EDUCACIONAL
	ADD FOREIGN KEY (ID_INSTITUICAO)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSTITUICAO_ESCOLARIDADE
	ADD FOREIGN KEY (ID_INSTITUICAO)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSTITUICAO_TIPO_ESPECIALIDADE
	ADD FOREIGN KEY (ID_INSTITUICAO)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_INSTITUICAO_COM_SALA_RECURSO)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_INSTITUICAO_COM_OUTROS_AEE)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_INSTITUICAO)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_INSTITUICAO_COM_SRMS)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CUSTO
	ADD FOREIGN KEY (ID_ITEM_CUSTO)
	REFERENCES ITEM_CUSTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO
	ADD FOREIGN KEY (ID_LOCAL_ATENDIMENTO)
	REFERENCES LOCAL_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL
	ADD FOREIGN KEY (ID_LOCAL_ATENDIMENTO)
	REFERENCES LOCAL_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO
	ADD FOREIGN KEY (ID_LOCAL_ATENDIMENTO)
	REFERENCES LOCAL_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROGRAMACAO
	ADD FOREIGN KEY (ID_LOCAL_ATENDIMENTO)
	REFERENCES LOCAL_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_TRABALHO_COMPLETA
	ADD FOREIGN KEY (ID_LOCAL_TRABALHO)
	REFERENCES LOCAL_TRABALHO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO_LOTE_RECURSO
	ADD FOREIGN KEY (ID_LOTE_RECURSO)
	REFERENCES LOTE_RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO
	ADD FOREIGN KEY (ID_MODULO)
	REFERENCES MODULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL
	ADD FOREIGN KEY (ID_MODULO)
	REFERENCES MODULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BLOQUEIO
	ADD FOREIGN KEY (ID_MODULO)
	REFERENCES MODULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DESCRICAO_TIPO_ATENDIMENTO_MODULO
	ADD FOREIGN KEY (ID_MODULO)
	REFERENCES MODULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESPERA
	ADD FOREIGN KEY (ID_MODULO)
	REFERENCES MODULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO
	ADD FOREIGN KEY (ID_MODULO)
	REFERENCES MODULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO_MODULO_PERIODO
	ADD FOREIGN KEY (ID_MODULO_PERIODO)
	REFERENCES MODULO_PERIODO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_ATENDIMENTO_GRUPO
	ADD FOREIGN KEY (ID_MODULO_PERIODO)
	REFERENCES MODULO_PERIODO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_DIA_SEMANA_E_HORARIO
	ADD FOREIGN KEY (ID_MODULO_PERIODO)
	REFERENCES MODULO_PERIODO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_MODULO_PERIODO)
	REFERENCES MODULO_PERIODO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_MODULO_USUARIO
	ADD FOREIGN KEY (ID_MODULO_PERIODO)
	REFERENCES MODULO_PERIODO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_PROFISSIONAL_VINCULO
	ADD FOREIGN KEY (ID_MODULO_PERIODO)
	REFERENCES MODULO_PERIODO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_PROGRAMACAO
	ADD FOREIGN KEY (ID_MODULO_PERIODO)
	REFERENCES MODULO_PERIODO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PENDENCIA
	ADD FOREIGN KEY (ID_MODULO_PERIODO)
	REFERENCES MODULO_PERIODO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_MODULO_PRE_CADASTRO)
	REFERENCES MODULO_PRE_CADASTRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_MODULO_USUARIO
	ADD FOREIGN KEY (ID_MODULO_USUARIO)
	REFERENCES MODULO_USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO
	ADD FOREIGN KEY (ID_MOTIVO_CANCELAMENTO)
	REFERENCES MOTIVO_CANCELAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA
	ADD FOREIGN KEY (ID_MOTIVO_CANCELAMENTO)
	REFERENCES MOTIVO_CANCELAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTRIBUINTE
	ADD FOREIGN KEY (ID_MOTIVO_DESATIVACAO)
	REFERENCES MOTIVO_DESATIVACAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CERTIDAO
	ADD FOREIGN KEY (ID_MUNICIPIO)
	REFERENCES MUNICIPIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ENDERECO
	ADD FOREIGN KEY (ID_MUNICIPIO)
	REFERENCES MUNICIPIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_NECESSIDADE
	ADD FOREIGN KEY (ID_NECESSIDADE)
	REFERENCES NECESSIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DESCRICAO_TIPO_ATENDIMENTO_NOME_GRUPO
	ADD FOREIGN KEY (ID_NOME_GRUPO)
	REFERENCES NOME_GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESPERA
	ADD FOREIGN KEY (ID_NOME_GRUPO)
	REFERENCES NOME_GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO
	ADD FOREIGN KEY (ID_NOME_GRUPO)
	REFERENCES NOME_GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORIGEM_ENCAMINHAMENTO_DETALHADO
	ADD FOREIGN KEY (ID_ORIGEM_ENCAMINHAMENTO)
	REFERENCES ORIGEM_ENCAMINHAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_ORIGEM_ENCAMINHAMENTO_DETALHADO
	ADD FOREIGN KEY (ID_ORIGEM_ENCAMINHAMENTO_DETALHADO)
	REFERENCES ORIGEM_ENCAMINHAMENTO_DETALHADO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ENDERECO
	ADD FOREIGN KEY (ID_PAIS)
	REFERENCES PAIS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAMILIAR
	ADD FOREIGN KEY (ID_PARENTESCO)
	REFERENCES PARENTESCO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_ATENDIMENTO_PARTICIPACAO_DETALHADA
	ADD FOREIGN KEY (ID_PARTICIPACAO_DETALHADA)
	REFERENCES PARTICIPACAO_DETALHADA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO_PATROCINIO
	ADD FOREIGN KEY (ID_PATROCINIO)
	REFERENCES PATROCINIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PENDENCIA_PROFISSIONAL
	ADD FOREIGN KEY (ID_PENDENCIA)
	REFERENCES PENDENCIA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTA_ACESSO
	ADD FOREIGN KEY (ID_PERFIL)
	REFERENCES PERFIL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PERFIL_PERMISSOES
	ADD FOREIGN KEY (ID_PERFIL)
	REFERENCES PERFIL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAMILIAR_PERIODO_BENEFICIO
	ADD FOREIGN KEY (ID_PERIODO_BENEFICIO)
	REFERENCES PERIODO_BENEFICIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_PERIODO_BENEFICIO
	ADD FOREIGN KEY (ID_PERIODO_BENEFICIO)
	REFERENCES PERIODO_BENEFICIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_PERIODO_COMPROMETIMENTO
	ADD FOREIGN KEY (ID_PERIODO_COMPROMETIMENTO)
	REFERENCES PERIODO_COMPROMETIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PERIODO_DEFICIENCIA_ETIOLOGIA
	ADD FOREIGN KEY (ID_PERIODO_DEFICIENCIA)
	REFERENCES PERIODO_DEFICIENCIA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_PERIODO_DEFICIENCIA
	ADD FOREIGN KEY (ID_PERIODO_DEFICIENCIA)
	REFERENCES PERIODO_DEFICIENCIA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_PERIODO_DOENCA
	ADD FOREIGN KEY (ID_PERIODO_DOENCA)
	REFERENCES PERIODO_DOENCA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO
	ADD FOREIGN KEY (ID_PRE_CADASTRO)
	REFERENCES PRE_CADASTRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_COMUNIDADE
	ADD FOREIGN KEY (ID_PRE_CADASTRO)
	REFERENCES PRE_CADASTRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL
	ADD FOREIGN KEY (ID_PRE_CADASTRO)
	REFERENCES PRE_CADASTRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_PRE_CADASTRO)
	REFERENCES PRE_CADASTRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA
	ADD FOREIGN KEY (ID_PRE_CADASTRO)
	REFERENCES PRE_CADASTRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESPERA
	ADD FOREIGN KEY (ID_PRE_CADASTRO)
	REFERENCES PRE_CADASTRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_PRE_CADASTRO)
	REFERENCES PRE_CADASTRO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_PROFISSIONAL
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTA_ACESSO
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTA_ACESSO_PROFISSIONAL_EQUIVALENTE
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESPERA
	ADD FOREIGN KEY (ID_PROFISSIONAL_SOLICITADO_POR)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PENDENCIA_PROFISSIONAL
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROFISSIONAL_VINCULO
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO
	ADD FOREIGN KEY (ID_PROFISSIONAL_ADMINISTRATIVO_RESPONSAVEL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESPONSAVEL_TECNICO
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RETIRADA
	ADD FOREIGN KEY (ID_VOLUNTARIO)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RETIRADA
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_PROFISSIONAL_VINCULO
	ADD FOREIGN KEY (ID_PROFISSIONAL_VINCULO)
	REFERENCES PROFISSIONAL_VINCULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PERIODO_PROGRAMACAO
	ADD FOREIGN KEY (ID_PROGRAMACAO)
	REFERENCES PROGRAMACAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO_ARQUIVO
	ADD FOREIGN KEY (ID_PROJETO)
	REFERENCES PROJETO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO_PATROCINIO
	ADD FOREIGN KEY (ID_PROJETO)
	REFERENCES PROJETO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO_RECURSO_DISPONIVEL
	ADD FOREIGN KEY (ID_PROJETO)
	REFERENCES PROJETO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO_RESERVA
	ADD FOREIGN KEY (ID_PROJETO)
	REFERENCES PROJETO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO_RESPONSAVEL_TECNICO
	ADD FOREIGN KEY (ID_PROJETO)
	REFERENCES PROJETO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CAPTACAO
	ADD FOREIGN KEY (ID_RECIBO)
	REFERENCES RECIBO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RECIBO_HISTORICO_STATUS_RECIBO
	ADD FOREIGN KEY (ID_RECIBO)
	REFERENCES RECIBO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA
	ADD FOREIGN KEY (ID_RECURSO)
	REFERENCES RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOTE_RECURSO
	ADD FOREIGN KEY (ID_RECURSO)
	REFERENCES RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RECURSO_DESCRICAO_RECURSO
	ADD FOREIGN KEY (ID_RECURSO)
	REFERENCES RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RECURSO_DISPONIVEL
	ADD FOREIGN KEY (ID_RECURSO)
	REFERENCES RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RECURSO_RELACIONAMENTO
	ADD FOREIGN KEY (ID_RECURSO)
	REFERENCES RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_RECURSO
	ADD FOREIGN KEY (ID_RECURSO)
	REFERENCES RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO_RECURSO_DISPONIVEL
	ADD FOREIGN KEY (ID_RECURSO_DISPONIVEL)
	REFERENCES RECURSO_DISPONIVEL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_RECURSO_MORADIA
	ADD FOREIGN KEY (ID_RECURSO_MORADIA)
	REFERENCES RECURSO_MORADIA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_RECURSO_RELACIONAMENTO
	ADD FOREIGN KEY (ID_RECURSO_RELACIONAMENTO)
	REFERENCES RECURSO_RELACIONAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO_RESERVA
	ADD FOREIGN KEY (ID_RESERVA)
	REFERENCES RESERVA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROJETO_RESPONSAVEL_TECNICO
	ADD FOREIGN KEY (ID_RESPONSAVEL_TECNICO)
	REFERENCES RESPONSAVEL_TECNICO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RETIRADA_HISTORICO_STATUS_RETIRADA
	ADD FOREIGN KEY (ID_RETIRADA)
	REFERENCES RETIRADA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESCOLARIDADE_SERIE
	ADD FOREIGN KEY (ID_SERIE)
	REFERENCES SERIE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INFORMACAO_EDUCACIONAL
	ADD FOREIGN KEY (ID_SERIE)
	REFERENCES SERIE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_SERVICO
	ADD FOREIGN KEY (ID_SERVICO)
	REFERENCES SERVICO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ACAO_CONDUTA
	ADD FOREIGN KEY (ID_SETOR)
	REFERENCES SETOR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO
	ADD FOREIGN KEY (ID_SETOR)
	REFERENCES SETOR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL
	ADD FOREIGN KEY (ID_SETOR)
	REFERENCES SETOR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DESCRICAO_TIPO_ATENDIMENTO_SETOR
	ADD FOREIGN KEY (ID_SETOR)
	REFERENCES SETOR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESPERA
	ADD FOREIGN KEY (ID_SETOR)
	REFERENCES SETOR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO
	ADD FOREIGN KEY (ID_SETOR)
	REFERENCES SETOR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HISTORICO_SETOR
	ADD FOREIGN KEY (ID_SETOR)
	REFERENCES SETOR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_SITUACAO_GUARDA
	ADD FOREIGN KEY (ID_SITUACAO_GUARDA)
	REFERENCES SITUACAO_GUARDA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO
	ADD FOREIGN KEY (ID_SITUACAO_HABITACIONAL)
	REFERENCES SITUACAO_HABITACIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SOLICITACAO_RELATORIO_FINALIDADE_RELATORIO
	ADD FOREIGN KEY (ID_SOLICITACAO_RELATORIO)
	REFERENCES SOLICITACAO_RELATORIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SOLICITACAO_RELATORIO_HISTORICO_STATUS_SOLICITACAO_RELATORIO
	ADD FOREIGN KEY (ID_SOLICITACAO_RELATORIO)
	REFERENCES SOLICITACAO_RELATORIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRUPO_TIPIFICACAO_SERVICO
	ADD FOREIGN KEY (ID_TIPIFICACAO_SERVICO)
	REFERENCES TIPIFICACAO_SERVICO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DESCRICAO_TIPO_ATENDIMENTO
	ADD FOREIGN KEY (ID_TIPO_ATENDIMENTO)
	REFERENCES TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TIPO_ATENDIMENTO_DESCRICAO_TIPO_ATENDIMENTO
	ADD FOREIGN KEY (ID_TIPO_ATENDIMENTO)
	REFERENCES TIPO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO
	ADD FOREIGN KEY (ID_TIPO_CONSTRUCAO)
	REFERENCES TIPO_CONSTRUCAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_COMUNIDADE
	ADD FOREIGN KEY (ID_TIPO_VINCULO)
	REFERENCES TIPO_VINCULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_TIPO_VINCULO)
	REFERENCES TIPO_VINCULO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ACAO_CONDUTA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AGENDAMENTO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_INDIVIDUAL
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ATENDIMENTO_USUARIO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEMANDA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ESPERA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_USUARIO_VINCULADO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MODULO_USUARIO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SOLICITACAO_RELATORIO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_CERTIDAO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_CONVENIO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_CUSTO_DEFICIENCIA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_CUSTO_DOENCA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_ENCAMINHAMENTO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_EXPECTATIVA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_FAMILIAR
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_CLASSIFICACAO_SOCIAL
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_OUTROS_AEE
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_SALA_RECURSO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_SRMS
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_SETOR
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_STATUS
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_HISTORICO_STATUS_USUARIO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_INFORMACAO_EDUCACIONAL
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_INFORMACAO_TRABALHO_COMPLETA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_INFRAESTRUTURA_BASICA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_NECESSIDADE
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_ORIGEM_ENCAMINHAMENTO_DETALHADO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_PERIODO_BENEFICIO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_PERIODO_COMPROMETIMENTO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_PERIODO_DEFICIENCIA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_PERIODO_DOENCA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_RECURSO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_RECURSO_MORADIA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_RECURSO_RELACIONAMENTO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_SERVICO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_SITUACAO_GUARDA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_VULNERABILIDADE_FAMILIA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_VULNERABILIDADE_USUARIO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INSCRICAO
	ADD FOREIGN KEY (ID_USUARIO_EXTERNO)
	REFERENCES USUARIO_EXTERNO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FAMILIAR_VULNERABILIDADE
	ADD FOREIGN KEY (ID_VULNERABILIDADE)
	REFERENCES VULNERABILIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_VULNERABILIDADE_FAMILIA
	ADD FOREIGN KEY (ID_VULNERABILIDADE)
	REFERENCES VULNERABILIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_VULNERABILIDADE_USUARIO
	ADD FOREIGN KEY (ID_VULNERABILIDADE)
	REFERENCES VULNERABILIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



