package br.laramara.ti.sislaraserver.dominio.doacao;

public enum NomeDocumento {
	FOTO_RECENTE, 
	RG_CPF, 
	FORMULARIO_DE_CADASTRO_DO_PROJETO_CARTELA_DE_SELOS,
	COMPROVANTE_DE_ENDERECO, 
	HISTORICO_DO_SOLICITANTE, 
	DECLARACAO_DE_MATRICULA,
	AUTODECLARACAO_COMO_USUARIO_DO_SISTEMA_BRAILLE, 
	INDICACAO_PARA_USO_PREFERENCIAL_DO_SISTEMA_BRAILLE,
	TERMO_DE_RESPONSABILIDADE
}
