SELECT pg_catalog.setval('pais_id_seq', 244, true);
insert into pais(id, nome)values(0,'Nenhum');
insert into pais(id, nome)values(1,'Afeganistão');
insert into pais(id, nome)values(2,'África do Sul');
insert into pais(id, nome)values(3,'Aland, Ilhas');
insert into pais(id, nome)values(4,'Albânia');
insert into pais(id, nome)values(5,'Alemanha');
insert into pais(id, nome)values(6,'Andorra');
insert into pais(id, nome)values(7,'Angola');
insert into pais(id, nome)values(8,'Anguilla');
insert into pais(id, nome)values(9,'Antárctida');
insert into pais(id, nome)values(10,'Antigua e Barbuda');
insert into pais(id, nome)values(11,'Antilhas Holandesas');
insert into pais(id, nome)values(12,'Arábia Saudita');
insert into pais(id, nome)values(13,'Argélia');
insert into pais(id, nome)values(14,'Argentina');
insert into pais(id, nome)values(15,'Arménia');
insert into pais(id, nome)values(16,'Aruba');
insert into pais(id, nome)values(17,'Austrália');
insert into pais(id, nome)values(18,'Áustria');
insert into pais(id, nome)values(19,'Azerbeijão');
insert into pais(id, nome)values(20,'Bahamas');
insert into pais(id, nome)values(21,'Bahrain');
insert into pais(id, nome)values(22,'Bangladesh');
insert into pais(id, nome)values(23,'Barbados');
insert into pais(id, nome)values(24,'Bélgica');
insert into pais(id, nome)values(25,'Belize');
insert into pais(id, nome)values(26,'Benin');
insert into pais(id, nome)values(27,'Bermuda');
insert into pais(id, nome)values(28,'Bielo-Rússia');
insert into pais(id, nome)values(29,'Bolívia');
insert into pais(id, nome)values(30,'Bósnia-Herzegovina');
insert into pais(id, nome)values(31,'Botswana');
insert into pais(id, nome)values(32,'Bouvet, Ilha');
insert into pais(id, nome)values(33,'Brasil');
insert into pais(id, nome)values(34,'Brunei');
insert into pais(id, nome)values(35,'Bulgária');
insert into pais(id, nome)values(36,'Burkina Faso');
insert into pais(id, nome)values(37,'Burundi');
insert into pais(id, nome)values(38,'Butão');
insert into pais(id, nome)values(39,'Cabo Verde');
insert into pais(id, nome)values(40,'Cambodja');
insert into pais(id, nome)values(41,'Camarões');
insert into pais(id, nome)values(42,'Canadá');
insert into pais(id, nome)values(43,'Cayman, Ilhas');
insert into pais(id, nome)values(44,'Cazaquistão');
insert into pais(id, nome)values(45,'Centro-africana, República');
insert into pais(id, nome)values(46,'Chade');
insert into pais(id, nome)values(47,'Checa, República');
insert into pais(id, nome)values(48,'Chile');
insert into pais(id, nome)values(49,'China');
insert into pais(id, nome)values(50,'Chipre');
insert into pais(id, nome)values(51,'Christmas, Ilha');
insert into pais(id, nome)values(52,'Cocos, Ilhas');
insert into pais(id, nome)values(53,'Colômbia');
insert into pais(id, nome)values(54,'Comores');
insert into pais(id, nome)values(55,'Congo, República do');
insert into pais(id, nome)values(56,'Congo, República Democrática do (antigo Zaire)');
insert into pais(id, nome)values(57,'Cook, Ilhas');
insert into pais(id, nome)values(58,'Coreia do Sul');
insert into pais(id, nome)values(59,'Coreia, República Democrática da (Coreia do Norte)');
insert into pais(id, nome)values(60,'Costa do Marfim');
insert into pais(id, nome)values(61,'Costa Rica');
insert into pais(id, nome)values(62,'Croácia');
insert into pais(id, nome)values(63,'Cuba');
insert into pais(id, nome)values(64,'Dinamarca');
insert into pais(id, nome)values(65,'Djibouti');
insert into pais(id, nome)values(66,'Dominica');
insert into pais(id, nome)values(67,'Dominicana, República');
insert into pais(id, nome)values(68,'Egipto');
insert into pais(id, nome)values(69,'El Salvador');
insert into pais(id, nome)values(70,'Emiratos Árabes Unidos');
insert into pais(id, nome)values(71,'Equador');
insert into pais(id, nome)values(72,'Eritreia');
insert into pais(id, nome)values(73,'Eslováquia');
insert into pais(id, nome)values(74,'Eslovénia');
insert into pais(id, nome)values(75,'Espanha');
insert into pais(id, nome)values(76,'Estados Unidos da América');
insert into pais(id, nome)values(77,'Estónia');
insert into pais(id, nome)values(78,'Etiópia');
insert into pais(id, nome)values(79,'Faroe, Ilhas');
insert into pais(id, nome)values(80,'Fiji');
insert into pais(id, nome)values(81,'Filipinas');
insert into pais(id, nome)values(82,'Finlândia');
insert into pais(id, nome)values(83,'França');
insert into pais(id, nome)values(84,'Gabão');
insert into pais(id, nome)values(85,'Gâmbia');
insert into pais(id, nome)values(86,'Gana');
insert into pais(id, nome)values(87,'Geórgia');
insert into pais(id, nome)values(88,'Geórgia do Sul e Sandwich do Sul, Ilhas');
insert into pais(id, nome)values(89,'Gibraltar');
insert into pais(id, nome)values(90,'Grécia');
insert into pais(id, nome)values(91,'Grenada');
insert into pais(id, nome)values(92,'Gronelândia');
insert into pais(id, nome)values(93,'Guadeloupe');
insert into pais(id, nome)values(94,'Guam');
insert into pais(id, nome)values(95,'Guatemala');
insert into pais(id, nome)values(96,'Guernsey');
insert into pais(id, nome)values(97,'Guiana');
insert into pais(id, nome)values(98,'Guiana Francesa');
insert into pais(id, nome)values(99,'Guiné-Bissau');
insert into pais(id, nome)values(100,'Guiné-Conacri');
insert into pais(id, nome)values(101,'Guiné Equatorial');
insert into pais(id, nome)values(102,'Haiti');
insert into pais(id, nome)values(103,'Heard e Ilhas McDonald, Ilha');
insert into pais(id, nome)values(104,'Honduras');
insert into pais(id, nome)values(105,'Hong Kong');
insert into pais(id, nome)values(106,'Hungria');
insert into pais(id, nome)values(107,'Iémen');
insert into pais(id, nome)values(108,'Índia');
insert into pais(id, nome)values(109,'Indonésia');
insert into pais(id, nome)values(110,'Iraque');
insert into pais(id, nome)values(111,'Irã');
insert into pais(id, nome)values(112,'Irlanda');
insert into pais(id, nome)values(113,'Islândia');
insert into pais(id, nome)values(114,'Israel');
insert into pais(id, nome)values(115,'Itália');
insert into pais(id, nome)values(116,'Jamaica');
insert into pais(id, nome)values(117,'Japão');
insert into pais(id, nome)values(118,'Jersey');
insert into pais(id, nome)values(119,'Jordânia');
insert into pais(id, nome)values(120,'Kiribati');
insert into pais(id, nome)values(121,'Kuwait');
insert into pais(id, nome)values(122,'Laos');
insert into pais(id, nome)values(123,'Lesoto');
insert into pais(id, nome)values(124,'Letónia');
insert into pais(id, nome)values(125,'Líbano');
insert into pais(id, nome)values(126,'Libéria');
insert into pais(id, nome)values(127,'Líbia');
insert into pais(id, nome)values(128,'Liechtenstein');
insert into pais(id, nome)values(129,'Lituânia');
insert into pais(id, nome)values(130,'Luxemburgo');
insert into pais(id, nome)values(131,'Macau');
insert into pais(id, nome)values(132,'Macedónia, República da');
insert into pais(id, nome)values(133,'Madagáscar');
insert into pais(id, nome)values(134,'Malásia');
insert into pais(id, nome)values(135,'Malawi');
insert into pais(id, nome)values(136,'Maldivas');
insert into pais(id, nome)values(137,'Mali');
insert into pais(id, nome)values(138,'Malta');
insert into pais(id, nome)values(139,'Malvinas, Ilhas (Falkland)');
insert into pais(id, nome)values(140,'Man, Ilha de');
insert into pais(id, nome)values(141,'Marianas Setentrionais');
insert into pais(id, nome)values(142,'Marrocos');
insert into pais(id, nome)values(143,'Marshall, Ilhas');
insert into pais(id, nome)values(144,'Martinica');
insert into pais(id, nome)values(145,'Maurícia');
insert into pais(id, nome)values(146,'Mauritânia');
insert into pais(id, nome)values(147,'Mayotte');
insert into pais(id, nome)values(148,'Menores Distantes dos Estados Unidos, Ilhas');
insert into pais(id, nome)values(149,'México');
insert into pais(id, nome)values(150,'Myanmar (antiga Birmânia)');
insert into pais(id, nome)values(151,'Micronésia, Estados Federados da');
insert into pais(id, nome)values(152,'Moçambique');
insert into pais(id, nome)values(153,'Moldávia');
insert into pais(id, nome)values(154,'Mónaco');
insert into pais(id, nome)values(155,'Mongólia');
insert into pais(id, nome)values(156,'Montenegro');
insert into pais(id, nome)values(157,'Montserrat');
insert into pais(id, nome)values(158,'Namíbia');
insert into pais(id, nome)values(159,'Nauru');
insert into pais(id, nome)values(160,'Nepal');
insert into pais(id, nome)values(161,'Nicarágua');
insert into pais(id, nome)values(162,'Níger');
insert into pais(id, nome)values(163,'Nigéria');
insert into pais(id, nome)values(164,'Niue');
insert into pais(id, nome)values(165,'Norfolk, Ilha');
insert into pais(id, nome)values(166,'Noruega');
insert into pais(id, nome)values(167,'Nova Caledónia');
insert into pais(id, nome)values(168,'Nova Zelândia (Aotearoa)');
insert into pais(id, nome)values(169,'Oman');
insert into pais(id, nome)values(170,'Países Baixos (Holanda)');
insert into pais(id, nome)values(171,'Palau');
insert into pais(id, nome)values(172,'Palestina');
insert into pais(id, nome)values(173,'Panamá');
insert into pais(id, nome)values(174,'Papua-Nova Guiné');
insert into pais(id, nome)values(175,'Paquistão');
insert into pais(id, nome)values(176,'Paraguai');
insert into pais(id, nome)values(177,'Peru');
insert into pais(id, nome)values(178,'Pitcairn');
insert into pais(id, nome)values(179,'Polinésia Francesa');
insert into pais(id, nome)values(180,'Polónia');
insert into pais(id, nome)values(181,'Porto Rico');
insert into pais(id, nome)values(182,'Portugal');
insert into pais(id, nome)values(183,'Qatar');
insert into pais(id, nome)values(184,'Quénia');
insert into pais(id, nome)values(185,'Quirguistão');
insert into pais(id, nome)values(186,'Reino Unido da Grã-Bretanha e Irlanda do Norte');
insert into pais(id, nome)values(187,'Reunião');
insert into pais(id, nome)values(188,'Roménia');
insert into pais(id, nome)values(189,'Ruanda');
insert into pais(id, nome)values(190,'Rússia');
insert into pais(id, nome)values(191,'Saara Ocidental');
insert into pais(id, nome)values(192,'Samoa Americana');
insert into pais(id, nome)values(193,'Samoa (Samoa Ocidental)');
insert into pais(id, nome)values(194,'Saint Pierre et Miquelon');
insert into pais(id, nome)values(195,'Salomão, Ilhas');
insert into pais(id, nome)values(196,'São Cristóvão e Névis (Saint Kitts e Nevis)');
insert into pais(id, nome)values(197,'San Marino');
insert into pais(id, nome)values(198,'São Tomé e Príncipe');
insert into pais(id, nome)values(199,'São Vicente e Granadinas');
insert into pais(id, nome)values(200,'Santa Helena');
insert into pais(id, nome)values(201,'Santa Lúcia');
insert into pais(id, nome)values(202,'Senegal');
insert into pais(id, nome)values(203,'Serra Leoa');
insert into pais(id, nome)values(204,'Sérvia');
insert into pais(id, nome)values(205,'Seychelles');
insert into pais(id, nome)values(206,'Singapura');
insert into pais(id, nome)values(207,'Síria');
insert into pais(id, nome)values(208,'Somália');
insert into pais(id, nome)values(209,'Sri Lanka');
insert into pais(id, nome)values(210,'Suazilândia');
insert into pais(id, nome)values(211,'Sudão');
insert into pais(id, nome)values(212,'Suécia');
insert into pais(id, nome)values(213,'Suíça');
insert into pais(id, nome)values(214,'Suriname');
insert into pais(id, nome)values(215,'Svalbard e Jan Mayen');
insert into pais(id, nome)values(216,'Tailândia');
insert into pais(id, nome)values(217,'Taiwan');
insert into pais(id, nome)values(218,'Tajiquistão');
insert into pais(id, nome)values(219,'Tanzânia');
insert into pais(id, nome)values(220,'Terras Austrais e Antárticas Francesas (TAAF)');
insert into pais(id, nome)values(221,'Território Britânico do Oceano Índico');
insert into pais(id, nome)values(222,'Timor-Leste');
insert into pais(id, nome)values(223,'Togo');
insert into pais(id, nome)values(224,'Toquelau');
insert into pais(id, nome)values(225,'Tonga');
insert into pais(id, nome)values(226,'Trindade e Tobago');
insert into pais(id, nome)values(227,'Tunísia');
insert into pais(id, nome)values(228,'Turks e Caicos');
insert into pais(id, nome)values(229,'Turquemenistão');
insert into pais(id, nome)values(230,'Turquia');
insert into pais(id, nome)values(231,'Tuvalu');
insert into pais(id, nome)values(232,'Ucrânia');
insert into pais(id, nome)values(233,'Uganda');
insert into pais(id, nome)values(234,'Uruguai');
insert into pais(id, nome)values(235,'Usbequistão');
insert into pais(id, nome)values(236,'Vanuatu');
insert into pais(id, nome)values(237,'Vaticano');
insert into pais(id, nome)values(238,'Venezuela');
insert into pais(id, nome)values(239,'Vietname');
insert into pais(id, nome)values(240,'Virgens Americanas, Ilhas');
insert into pais(id, nome)values(241,'Virgens Britânicas, Ilhas');
insert into pais(id, nome)values(242,'Wallis e Futuna');
insert into pais(id, nome)values(243,'Zâmbia');
insert into pais(id, nome)values(244,'Zimbabwe');