
package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaSolicitacaoRelatorioGeren;
import br.laramara.ti.sislaraclient.modelos.ModeloTabelaSolicitacaoRelatorio;
import javax.swing.JFrame;

public class TelaSolicitacaoRelatorioGeren extends javax.swing.JDialog {

    /**
     * Creates new form TelaSolicitacaoRelatorioGeren
     */
    public TelaSolicitacaoRelatorioGeren(JFrame telaPai) {
        super(telaPai, true);
        initComponents();
        setLocationRelativeTo(telaPai);
        controlador = new ControladorTelaSolicitacaoRelatorioGeren(this, jcbStatus, jtfProtocolo, jtfProntuario, jtaSolicitacaoRelatorios);
        controlador.abrirTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaTelaSolicitacaoRelatorioGeren = new javax.swing.JPanel();
        jpaTitulo = new javax.swing.JPanel();
        jlaTitulo = new javax.swing.JLabel();
        jbuFecharTitulo = new javax.swing.JButton();
        jlaStatusRelatorios = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox();
        jlaProtocolo = new javax.swing.JLabel();
        jtfProtocolo = new javax.swing.JTextField();
        jlaProntuario = new javax.swing.JLabel();
        jtfProntuario = new javax.swing.JTextField();
        jcpListaSolicitacoes = new javax.swing.JScrollPane();
        jtaSolicitacaoRelatorios = new javax.swing.JTable();
        jlaListaSolicitacoes = new javax.swing.JLabel();
        jbuPesquisar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();
        jbuNovo = new javax.swing.JButton();
        jbuSaidaRecepcao = new javax.swing.JButton();
        jbuCancelar = new javax.swing.JButton();
        jbuEmissaoProfissional = new javax.swing.JButton();
        jbuEntrega = new javax.swing.JButton();
        jbuImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setUndecorated(true);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(br.laramara.ti.sislaraclient.telas.SisLaraClient.class).getContext().getResourceMap(TelaSolicitacaoRelatorioGeren.class);
        jpaTelaSolicitacaoRelatorioGeren.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jpaTelaSolicitacaoRelatorioGeren.border.lineColor"))); // NOI18N
        jpaTelaSolicitacaoRelatorioGeren.setName("jpaTelaSolicitacaoRelatorioGeren"); // NOI18N
        jpaTelaSolicitacaoRelatorioGeren.setLayout(null);

        jpaTitulo.setBackground(resourceMap.getColor("jpaTitulo.background")); // NOI18N
        jpaTitulo.setName("jpaTitulo"); // NOI18N
        jpaTitulo.setLayout(null);

        jlaTitulo.setFont(resourceMap.getFont("jlaTitulo.font")); // NOI18N
        jlaTitulo.setForeground(resourceMap.getColor("jlaTitulo.foreground")); // NOI18N
        jlaTitulo.setText(resourceMap.getString("jlaTitulo.text")); // NOI18N
        jlaTitulo.setName("jlaTitulo"); // NOI18N
        jpaTitulo.add(jlaTitulo);
        jlaTitulo.setBounds(10, 0, 300, 26);

        jbuFecharTitulo.setBackground(resourceMap.getColor("jbuFecharTitulo.background")); // NOI18N
        jbuFecharTitulo.setIcon(resourceMap.getIcon("jbuFecharTitulo.icon")); // NOI18N
        jbuFecharTitulo.setBorder(null);
        jbuFecharTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFecharTitulo.setFocusable(false);
        jbuFecharTitulo.setName("jbuFecharTitulo"); // NOI18N
        jbuFecharTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharTituloActionPerformed(evt);
            }
        });
        jpaTitulo.add(jbuFecharTitulo);
        jbuFecharTitulo.setBounds(1003, 0, 25, 25);

        jpaTelaSolicitacaoRelatorioGeren.add(jpaTitulo);
        jpaTitulo.setBounds(1, 1, 1028, 26);

        jlaStatusRelatorios.setFont(resourceMap.getFont("jlaStatusRelatorios.font")); // NOI18N
        jlaStatusRelatorios.setText(resourceMap.getString("jlaStatusRelatorios.text")); // NOI18N
        jlaStatusRelatorios.setName("jlaStatusRelatorios"); // NOI18N
        jpaTelaSolicitacaoRelatorioGeren.add(jlaStatusRelatorios);
        jlaStatusRelatorios.setBounds(10, 30, 47, 17);

        jcbStatus.setFont(resourceMap.getFont("jcbStatus.font")); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbStatus.setName("jcbStatus"); // NOI18N
        jpaTelaSolicitacaoRelatorioGeren.add(jcbStatus);
        jcbStatus.setBounds(10, 50, 350, 25);
        jcbStatus.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbStatus.AccessibleContext.accessibleName")); // NOI18N

        jlaProtocolo.setFont(resourceMap.getFont("jlaProtocolo.font")); // NOI18N
        jlaProtocolo.setText(resourceMap.getString("jlaProtocolo.text")); // NOI18N
        jlaProtocolo.setName("jlaProtocolo"); // NOI18N
        jpaTelaSolicitacaoRelatorioGeren.add(jlaProtocolo);
        jlaProtocolo.setBounds(10, 80, 70, 17);

        jtfProtocolo.setFont(resourceMap.getFont("jtfProtocolo.font")); // NOI18N
        jtfProtocolo.setText(resourceMap.getString("jtfProtocolo.text")); // NOI18N
        jtfProtocolo.setToolTipText(resourceMap.getString("jtfProtocolo.toolTipText")); // NOI18N
        jtfProtocolo.setName("jtfProtocolo"); // NOI18N
        jpaTelaSolicitacaoRelatorioGeren.add(jtfProtocolo);
        jtfProtocolo.setBounds(10, 100, 100, 23);
        jtfProtocolo.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfProtocolo.AccessibleContext.accessibleName")); // NOI18N

        jlaProntuario.setFont(resourceMap.getFont("jlaProntuario.font")); // NOI18N
        jlaProntuario.setText(resourceMap.getString("jlaProntuario.text")); // NOI18N
        jlaProntuario.setName("jlaProntuario"); // NOI18N
        jpaTelaSolicitacaoRelatorioGeren.add(jlaProntuario);
        jlaProntuario.setBounds(120, 80, 80, 17);

        jtfProntuario.setFont(resourceMap.getFont("jtfProntuario.font")); // NOI18N
        jtfProntuario.setText(resourceMap.getString("jtfProntuario.text")); // NOI18N
        jtfProntuario.setToolTipText(resourceMap.getString("jtfProntuario.toolTipText")); // NOI18N
        jtfProntuario.setName("jtfProntuario"); // NOI18N
        jpaTelaSolicitacaoRelatorioGeren.add(jtfProntuario);
        jtfProntuario.setBounds(120, 100, 90, 23);

        jcpListaSolicitacoes.setName("jcpListaSolicitacoes"); // NOI18N

        jtaSolicitacaoRelatorios.setAutoCreateRowSorter(true);
        jtaSolicitacaoRelatorios.setFont(resourceMap.getFont("jtaSolicitacaoRelatorios.font")); // NOI18N
        jtaSolicitacaoRelatorios.setModel(new ModeloTabelaSolicitacaoRelatorio());
        jtaSolicitacaoRelatorios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtaSolicitacaoRelatorios.setName("jtaSolicitacaoRelatorios"); // NOI18N
        jtaSolicitacaoRelatorios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtaSolicitacaoRelatorios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaSolicitacaoRelatoriosKeyPressed(evt);
            }
        });
        jcpListaSolicitacoes.setViewportView(jtaSolicitacaoRelatorios);

        jpaTelaSolicitacaoRelatorioGeren.add(jcpListaSolicitacoes);
        jcpListaSolicitacoes.setBounds(10, 160, 1010, 500);

        jlaListaSolicitacoes.setFont(resourceMap.getFont("jlaListaSolicitacoes.font")); // NOI18N
        jlaListaSolicitacoes.setText(resourceMap.getString("jlaListaSolicitacoes.text")); // NOI18N
        jlaListaSolicitacoes.setName("jlaListaSolicitacoes"); // NOI18N
        jpaTelaSolicitacaoRelatorioGeren.add(jlaListaSolicitacoes);
        jlaListaSolicitacoes.setBounds(10, 140, 240, 17);

        jbuPesquisar.setFont(resourceMap.getFont("jbuPesquisar.font")); // NOI18N
        jbuPesquisar.setIcon(resourceMap.getIcon("jbuPesquisar.icon")); // NOI18N
        jbuPesquisar.setMnemonic('P');
        jbuPesquisar.setText(resourceMap.getString("jbuPesquisar.text")); // NOI18N
        jbuPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuPesquisar.setName("jbuPesquisar"); // NOI18N
        jbuPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuPesquisarActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioGeren.add(jbuPesquisar);
        jbuPesquisar.setBounds(220, 100, 140, 33);

        jbuFechar.setFont(resourceMap.getFont("jbuNovo.font")); // NOI18N
        jbuFechar.setIcon(resourceMap.getIcon("jbuFechar.icon")); // NOI18N
        jbuFechar.setMnemonic('f');
        jbuFechar.setText(resourceMap.getString("jbuFechar.text")); // NOI18N
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioGeren.add(jbuFechar);
        jbuFechar.setBounds(900, 670, 120, 35);

        jbuNovo.setFont(resourceMap.getFont("jbuNovo.font")); // NOI18N
        jbuNovo.setIcon(resourceMap.getIcon("jbuNovo.icon")); // NOI18N
        jbuNovo.setMnemonic('N');
        jbuNovo.setText(resourceMap.getString("jbuNovo.text")); // NOI18N
        jbuNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuNovo.setName("jbuNovo"); // NOI18N
        jbuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuNovoActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioGeren.add(jbuNovo);
        jbuNovo.setBounds(10, 670, 110, 35);

        jbuSaidaRecepcao.setFont(resourceMap.getFont("jbuSaidaRecepcao.font")); // NOI18N
        jbuSaidaRecepcao.setIcon(resourceMap.getIcon("jbuSaidaRecepcao.icon")); // NOI18N
        jbuSaidaRecepcao.setText(resourceMap.getString("jbuSaidaRecepcao.text")); // NOI18N
        jbuSaidaRecepcao.setName("jbuSaidaRecepcao"); // NOI18N
        jbuSaidaRecepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSaidaRecepcaoActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioGeren.add(jbuSaidaRecepcao);
        jbuSaidaRecepcao.setBounds(130, 670, 200, 35);

        jbuCancelar.setFont(resourceMap.getFont("jbuCancelar.font")); // NOI18N
        jbuCancelar.setIcon(resourceMap.getIcon("jbuCancelar.icon")); // NOI18N
        jbuCancelar.setMnemonic('C');
        jbuCancelar.setText(resourceMap.getString("jbuCancelar.text")); // NOI18N
        jbuCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuCancelar.setName("jbuCancelar"); // NOI18N
        jbuCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuCancelarActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioGeren.add(jbuCancelar);
        jbuCancelar.setBounds(730, 670, 130, 35);

        jbuEmissaoProfissional.setFont(resourceMap.getFont("jbuEmissaoProfissional.font")); // NOI18N
        jbuEmissaoProfissional.setIcon(resourceMap.getIcon("jbuEmissaoProfissional.icon")); // NOI18N
        jbuEmissaoProfissional.setText(resourceMap.getString("jbuEmissaoProfissional.text")); // NOI18N
        jbuEmissaoProfissional.setName("jbuEmissaoProfissional"); // NOI18N
        jbuEmissaoProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuEmissaoProfissionalActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioGeren.add(jbuEmissaoProfissional);
        jbuEmissaoProfissional.setBounds(340, 670, 247, 35);

        jbuEntrega.setFont(resourceMap.getFont("jbuEntrega.font")); // NOI18N
        jbuEntrega.setIcon(resourceMap.getIcon("jbuEntrega.icon")); // NOI18N
        jbuEntrega.setText(resourceMap.getString("jbuEntrega.text")); // NOI18N
        jbuEntrega.setName("jbuEntrega"); // NOI18N
        jbuEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuEntregaActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioGeren.add(jbuEntrega);
        jbuEntrega.setBounds(600, 670, 120, 35);

        jbuImprimir.setFont(resourceMap.getFont("jbuImprimir.font")); // NOI18N
        jbuImprimir.setIcon(resourceMap.getIcon("jbuImprimir.icon")); // NOI18N
        jbuImprimir.setMnemonic('I');
        jbuImprimir.setText(resourceMap.getString("jbuImprimir.text")); // NOI18N
        jbuImprimir.setName("jbuImprimir"); // NOI18N
        jbuImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuImprimirActionPerformed(evt);
            }
        });
        jpaTelaSolicitacaoRelatorioGeren.add(jbuImprimir);
        jbuImprimir.setBounds(880, 110, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaTelaSolicitacaoRelatorioGeren, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpaTelaSolicitacaoRelatorioGeren, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuFecharTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharTituloActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharTituloActionPerformed

    private void jbuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuPesquisarActionPerformed
        controlador.efetuarPesquisa();
    }//GEN-LAST:event_jbuPesquisarActionPerformed

    private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharActionPerformed

    private void jbuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuNovoActionPerformed
        controlador.novaSolicitacaoRelatorio();
    }//GEN-LAST:event_jbuNovoActionPerformed

    private void jbuCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuCancelarActionPerformed
        controlador.cancelar();
    }//GEN-LAST:event_jbuCancelarActionPerformed

    private void jtaSolicitacaoRelatoriosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaSolicitacaoRelatoriosKeyPressed
        controlador.transferirFocoNaTabulacao(evt);
    }//GEN-LAST:event_jtaSolicitacaoRelatoriosKeyPressed

    private void jbuSaidaRecepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSaidaRecepcaoActionPerformed
        controlador.efetuarEncaminhamentoRecepcao();
    }//GEN-LAST:event_jbuSaidaRecepcaoActionPerformed

    private void jbuEmissaoProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuEmissaoProfissionalActionPerformed
        controlador.efetuarEmissaoProfissional();
    }//GEN-LAST:event_jbuEmissaoProfissionalActionPerformed

    private void jbuEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuEntregaActionPerformed
        controlador.efetuarEntrega();
    }//GEN-LAST:event_jbuEntregaActionPerformed

    private void jbuImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuImprimirActionPerformed
        controlador.imprimir();
    }//GEN-LAST:event_jbuImprimirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbuCancelar;
    private javax.swing.JButton jbuEmissaoProfissional;
    private javax.swing.JButton jbuEntrega;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuFecharTitulo;
    private javax.swing.JButton jbuImprimir;
    private javax.swing.JButton jbuNovo;
    private javax.swing.JButton jbuPesquisar;
    private javax.swing.JButton jbuSaidaRecepcao;
    private javax.swing.JComboBox jcbStatus;
    private javax.swing.JScrollPane jcpListaSolicitacoes;
    private javax.swing.JLabel jlaListaSolicitacoes;
    private javax.swing.JLabel jlaProntuario;
    private javax.swing.JLabel jlaProtocolo;
    private javax.swing.JLabel jlaStatusRelatorios;
    private javax.swing.JLabel jlaTitulo;
    private javax.swing.JPanel jpaTelaSolicitacaoRelatorioGeren;
    private javax.swing.JPanel jpaTitulo;
    private javax.swing.JTable jtaSolicitacaoRelatorios;
    private javax.swing.JTextField jtfProntuario;
    private javax.swing.JTextField jtfProtocolo;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaSolicitacaoRelatorioGeren controlador;
}
