package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaDemandaGeren;
import br.laramara.ti.sislaraclient.modelos.ModeloTabelaDemanda;
import javax.swing.JFrame;

public class TelaDemandaGeren extends javax.swing.JDialog {

    public TelaDemandaGeren(JFrame telaPai) {
        super(telaPai, true);
        initComponents();
        setLocationRelativeTo(telaPai);
        controlador = new ControladorTelaDemandaGeren(this, jcbStatus, jcbRecurso, jtfProntuario, jftCpf, jtaDemandas);
        controlador.abrirTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaTelaDemandaGeren = new javax.swing.JPanel();
        jlaStatus = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox();
        jlaRecurso = new javax.swing.JLabel();
        jcbRecurso = new javax.swing.JComboBox();
        jlaProntuario = new javax.swing.JLabel();
        jtfProntuario = new javax.swing.JTextField();
        jbuUtilizarUsuario = new javax.swing.JButton();
        jlaCpf = new javax.swing.JLabel();
        jftCpf = new javax.swing.JFormattedTextField();
        jbuUtilizarPreCadastro = new javax.swing.JButton();
        jbuPesquisar = new javax.swing.JButton();
        jlaDemandas = new javax.swing.JLabel();
        jspDemandas = new javax.swing.JScrollPane();
        jtaDemandas = new javax.swing.JTable();
        jbuNovo = new javax.swing.JButton();
        jbuDocumentos = new javax.swing.JButton();
        jbuProrrogar = new javax.swing.JButton();
        jbuCaptar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(TelaDemandaGeren.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jpaTelaDemandaGeren.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpaTelaDemandaGeren.setName("jpaTelaDemandaGeren"); // NOI18N
        jpaTelaDemandaGeren.setLayout(null);

        jlaStatus.setFont(resourceMap.getFont("jlaStatus.font")); // NOI18N
        jlaStatus.setText(resourceMap.getString("jlaStatus.text")); // NOI18N
        jlaStatus.setName("jlaStatus"); // NOI18N
        jpaTelaDemandaGeren.add(jlaStatus);
        jlaStatus.setBounds(800, 10, 60, 17);

        jcbStatus.setFont(resourceMap.getFont("jcbStatus.font")); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbStatus.setName("jcbStatus"); // NOI18N
        jpaTelaDemandaGeren.add(jcbStatus);
        jcbStatus.setBounds(800, 30, 210, 25);
        jcbStatus.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbStatus.AccessibleContext.accessibleName")); // NOI18N

        jlaRecurso.setFont(resourceMap.getFont("jlaRecurso.font")); // NOI18N
        jlaRecurso.setText(resourceMap.getString("jlaRecurso.text")); // NOI18N
        jlaRecurso.setName("jlaRecurso"); // NOI18N
        jpaTelaDemandaGeren.add(jlaRecurso);
        jlaRecurso.setBounds(10, 10, 130, 17);

        jcbRecurso.setFont(resourceMap.getFont("jcbRecurso.font")); // NOI18N
        jcbRecurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbRecurso.setName("jcbRecurso"); // NOI18N
        jpaTelaDemandaGeren.add(jcbRecurso);
        jcbRecurso.setBounds(10, 30, 780, 25);
        jcbRecurso.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbRecurso.AccessibleContext.accessibleName")); // NOI18N

        jlaProntuario.setFont(resourceMap.getFont("jlaProntuario.font")); // NOI18N
        jlaProntuario.setText(resourceMap.getString("jlaProntuario.text")); // NOI18N
        jlaProntuario.setName("jlaProntuario"); // NOI18N
        jpaTelaDemandaGeren.add(jlaProntuario);
        jlaProntuario.setBounds(10, 60, 90, 17);

        jtfProntuario.setFont(resourceMap.getFont("jtfProntuario.font")); // NOI18N
        jtfProntuario.setText(resourceMap.getString("jtfProntuario.text")); // NOI18N
        jtfProntuario.setName("jtfProntuario"); // NOI18N
        jtfProntuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfProntuarioFocusLost(evt);
            }
        });
        jpaTelaDemandaGeren.add(jtfProntuario);
        jtfProntuario.setBounds(10, 80, 90, 23);
        jtfProntuario.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfProntuario.AccessibleContext.accessibleName")); // NOI18N

        jbuUtilizarUsuario.setFont(resourceMap.getFont("jbuUtilizarUsuario.font")); // NOI18N
        jbuUtilizarUsuario.setIcon(resourceMap.getIcon("jbuUtilizarUsuario.icon")); // NOI18N
        jbuUtilizarUsuario.setText(resourceMap.getString("jbuUtilizarUsuario.text")); // NOI18N
        jbuUtilizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuUtilizarUsuario.setName("jbuUtilizarUsuario"); // NOI18N
        jbuUtilizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuUtilizarUsuarioActionPerformed(evt);
            }
        });
        jpaTelaDemandaGeren.add(jbuUtilizarUsuario);
        jbuUtilizarUsuario.setBounds(110, 80, 120, 33);
        jbuUtilizarUsuario.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuUtilizarUsuario.AccessibleContext.accessibleName")); // NOI18N

        jlaCpf.setFont(resourceMap.getFont("jlaCpf.font")); // NOI18N
        jlaCpf.setText(resourceMap.getString("jlaCpf.text")); // NOI18N
        jlaCpf.setName("jlaCpf"); // NOI18N
        jpaTelaDemandaGeren.add(jlaCpf);
        jlaCpf.setBounds(240, 60, 28, 17);

        try {
            jftCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCpf.setToolTipText(resourceMap.getString("jftCpf.toolTipText")); // NOI18N
        jftCpf.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftCpf.setFont(resourceMap.getFont("jftCpf.font")); // NOI18N
        jftCpf.setName("jftCpf"); // NOI18N
        jpaTelaDemandaGeren.add(jftCpf);
        jftCpf.setBounds(240, 80, 130, 23);

        jbuUtilizarPreCadastro.setFont(resourceMap.getFont("jbuUtilizarPreCadastro.font")); // NOI18N
        jbuUtilizarPreCadastro.setIcon(resourceMap.getIcon("jbuUtilizarPreCadastro.icon")); // NOI18N
        jbuUtilizarPreCadastro.setMnemonic('U');
        jbuUtilizarPreCadastro.setText(resourceMap.getString("jbuUtilizarPreCadastro.text")); // NOI18N
        jbuUtilizarPreCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuUtilizarPreCadastro.setName("jbuUtilizarPreCadastro"); // NOI18N
        jbuUtilizarPreCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuUtilizarPreCadastroActionPerformed(evt);
            }
        });
        jpaTelaDemandaGeren.add(jbuUtilizarPreCadastro);
        jbuUtilizarPreCadastro.setBounds(380, 80, 120, 33);
        jbuUtilizarPreCadastro.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuUtilizarPreCadastro.AccessibleContext.accessibleName")); // NOI18N

        jbuPesquisar.setFont(resourceMap.getFont("jbuPesquisar.font")); // NOI18N
        jbuPesquisar.setIcon(resourceMap.getIcon("jbuPesquisar.icon")); // NOI18N
        jbuPesquisar.setMnemonic('P');
        jbuPesquisar.setText(resourceMap.getString("jbuPesquisar.text")); // NOI18N
        jbuPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuPesquisar.setName("jbuPesquisar"); // NOI18N
        jbuPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuPesquisarActionPerformed(evt);
            }
        });
        jpaTelaDemandaGeren.add(jbuPesquisar);
        jbuPesquisar.setBounds(870, 110, 140, 33);

        jlaDemandas.setFont(resourceMap.getFont("jlaDemandas.font")); // NOI18N
        jlaDemandas.setText(resourceMap.getString("jlaDemandas.text")); // NOI18N
        jlaDemandas.setName("jlaDemandas"); // NOI18N
        jpaTelaDemandaGeren.add(jlaDemandas);
        jlaDemandas.setBounds(10, 130, 100, 17);

        jspDemandas.setName("jspDemandas"); // NOI18N

        jtaDemandas.setAutoCreateRowSorter(true);
        jtaDemandas.setFont(resourceMap.getFont("jtaDemandas.font")); // NOI18N
        jtaDemandas.setModel(new ModeloTabelaDemanda());
        jtaDemandas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtaDemandas.setName("jtaDemandas"); // NOI18N
        jtaDemandas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaDemandasKeyPressed(evt);
            }
        });
        jspDemandas.setViewportView(jtaDemandas);
        jtaDemandas.getAccessibleContext().setAccessibleName(resourceMap.getString("jtaDemandas.AccessibleContext.accessibleName")); // NOI18N

        jpaTelaDemandaGeren.add(jspDemandas);
        jspDemandas.setBounds(10, 160, 1005, 470);

        jbuNovo.setFont(resourceMap.getFont("jbuNovo.font")); // NOI18N
        jbuNovo.setIcon(resourceMap.getIcon("jbuNovo.icon")); // NOI18N
        jbuNovo.setMnemonic('N');
        jbuNovo.setText(resourceMap.getString("jbuNovo.text")); // NOI18N
        jbuNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuNovo.setName("jbuNovo"); // NOI18N
        jbuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuNovoActionPerformed(evt);
            }
        });
        jpaTelaDemandaGeren.add(jbuNovo);
        jbuNovo.setBounds(10, 640, 99, 33);
        jbuNovo.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuNovo.AccessibleContext.accessibleName")); // NOI18N

        jbuDocumentos.setFont(resourceMap.getFont("jbuDocumentos.font")); // NOI18N
        jbuDocumentos.setIcon(resourceMap.getIcon("jbuDocumentos.icon")); // NOI18N
        jbuDocumentos.setMnemonic('D');
        jbuDocumentos.setText(resourceMap.getString("jbuDocumentos.text")); // NOI18N
        jbuDocumentos.setName("jbuDocumentos"); // NOI18N
        jbuDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuDocumentosActionPerformed(evt);
            }
        });
        jpaTelaDemandaGeren.add(jbuDocumentos);
        jbuDocumentos.setBounds(120, 640, 160, 33);

        jbuProrrogar.setFont(resourceMap.getFont("jbuProrrogar.font")); // NOI18N
        jbuProrrogar.setIcon(resourceMap.getIcon("jbuProrrogar.icon")); // NOI18N
        jbuProrrogar.setMnemonic('O');
        jbuProrrogar.setText(resourceMap.getString("jbuProrrogar.text")); // NOI18N
        jbuProrrogar.setToolTipText(resourceMap.getString("jbuProrrogar.toolTipText")); // NOI18N
        jbuProrrogar.setName("jbuProrrogar"); // NOI18N
        jbuProrrogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuProrrogarActionPerformed(evt);
            }
        });
        jpaTelaDemandaGeren.add(jbuProrrogar);
        jbuProrrogar.setBounds(290, 640, 140, 33);

        jbuCaptar.setFont(resourceMap.getFont("jbuCaptar.font")); // NOI18N
        jbuCaptar.setIcon(resourceMap.getIcon("jbuCaptar.icon")); // NOI18N
        jbuCaptar.setMnemonic('C');
        jbuCaptar.setText(resourceMap.getString("jbuCaptar.text")); // NOI18N
        jbuCaptar.setName("jbuCaptar"); // NOI18N
        jbuCaptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuCaptarActionPerformed(evt);
            }
        });
        jpaTelaDemandaGeren.add(jbuCaptar);
        jbuCaptar.setBounds(440, 640, 111, 33);

        jbuFechar.setFont(resourceMap.getFont("jbuNovo.font")); // NOI18N
        jbuFechar.setIcon(resourceMap.getIcon("jbuFechar.icon")); // NOI18N
        jbuFechar.setMnemonic('F');
        jbuFechar.setText(resourceMap.getString("jbuFechar.text")); // NOI18N
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });
        jpaTelaDemandaGeren.add(jbuFechar);
        jbuFechar.setBounds(900, 640, 113, 33);
        jbuFechar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuFechar.AccessibleContext.accessibleName")); // NOI18N

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setMnemonic('S');
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpaTelaDemandaGeren.add(jButton1);
        jButton1.setBounds(560, 640, 117, 33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaTelaDemandaGeren, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaTelaDemandaGeren, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuPesquisarActionPerformed
        controlador.efetuarPesquisa();
    }//GEN-LAST:event_jbuPesquisarActionPerformed

    private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharActionPerformed

    private void jbuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuNovoActionPerformed
        controlador.novaDemanda();
    }//GEN-LAST:event_jbuNovoActionPerformed

    private void jbuUtilizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuUtilizarUsuarioActionPerformed
        controlador.localizarUsuario();
    }//GEN-LAST:event_jbuUtilizarUsuarioActionPerformed

    private void jbuUtilizarPreCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuUtilizarPreCadastroActionPerformed
        controlador.localizarPreCadastro();
    }//GEN-LAST:event_jbuUtilizarPreCadastroActionPerformed

    private void jtfProntuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfProntuarioFocusLost
        controlador.selecionarProntuario();
    }//GEN-LAST:event_jtfProntuarioFocusLost

    private void jtaDemandasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaDemandasKeyPressed
        controlador.transferirFocoNaTabulacao(evt);
    }//GEN-LAST:event_jtaDemandasKeyPressed

    private void jbuDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuDocumentosActionPerformed
        controlador.abrirTelaVisualizacaoDocumento();
    }//GEN-LAST:event_jbuDocumentosActionPerformed

    private void jbuProrrogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuProrrogarActionPerformed
        controlador.prorrogar();
    }//GEN-LAST:event_jbuProrrogarActionPerformed

    private void jbuCaptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuCaptarActionPerformed
        controlador.captar();
    }//GEN-LAST:event_jbuCaptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controlador.alterarStatus();
    }//GEN-LAST:event_jButton1ActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbuCaptar;
    private javax.swing.JButton jbuDocumentos;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuNovo;
    private javax.swing.JButton jbuPesquisar;
    private javax.swing.JButton jbuProrrogar;
    private javax.swing.JButton jbuUtilizarPreCadastro;
    private javax.swing.JButton jbuUtilizarUsuario;
    private javax.swing.JComboBox jcbRecurso;
    private javax.swing.JComboBox jcbStatus;
    private javax.swing.JFormattedTextField jftCpf;
    private javax.swing.JLabel jlaCpf;
    private javax.swing.JLabel jlaDemandas;
    private javax.swing.JLabel jlaProntuario;
    private javax.swing.JLabel jlaRecurso;
    private javax.swing.JLabel jlaStatus;
    private javax.swing.JPanel jpaTelaDemandaGeren;
    private javax.swing.JScrollPane jspDemandas;
    private javax.swing.JTable jtaDemandas;
    private javax.swing.JTextField jtfProntuario;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaDemandaGeren controlador;
}
