package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaGruposGerenAtendimentos;
import br.laramara.ti.sislaraclient.modelos.ModeloTabelaAtendimentos;
import javax.swing.JFrame;

public class TelaGruposGerenAtedimentos extends javax.swing.JDialog {

    /** Creates new form TelaGruposGerenAtedimentos */
    public TelaGruposGerenAtedimentos(JFrame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        controlador = new ControladorTelaGruposGerenAtendimentos(this, jtfGrupo, jcbModuloAtividade, jtaListagemAtendimentos);
        controlador.abrirTela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaGerenAtendimentos = new javax.swing.JPanel();
        jpaGerarAtendimento = new javax.swing.JPanel();
        jlaGrupo = new javax.swing.JLabel();
        jtfGrupo = new javax.swing.JTextField();
        jlaModuloAtividade = new javax.swing.JLabel();
        jcbModuloAtividade = new javax.swing.JComboBox();
        jlaListagemAtendimentos = new javax.swing.JLabel();
        jspListagemAtendimentos = new javax.swing.JScrollPane();
        jtaListagemAtendimentos = new javax.swing.JTable();
        jbuVerAlterar = new javax.swing.JButton();
        jbuCancelar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();
        jbuGerarAtendimento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(TelaGruposGerenAtedimentos.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jpaGerenAtendimentos.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jpaGerenAtendimentos.border.lineColor"))); // NOI18N
        jpaGerenAtendimentos.setName("jpaGerenAtendimentos"); // NOI18N
        jpaGerenAtendimentos.setLayout(null);

        jpaGerarAtendimento.setName("jpaGerarAtendimento"); // NOI18N
        jpaGerarAtendimento.setLayout(null);

        jlaGrupo.setFont(resourceMap.getFont("jlaGrupo.font")); // NOI18N
        jlaGrupo.setText(resourceMap.getString("jlaGrupo.text")); // NOI18N
        jlaGrupo.setName("jlaGrupo"); // NOI18N
        jpaGerarAtendimento.add(jlaGrupo);
        jlaGrupo.setBounds(10, 10, 210, 17);
        jlaGrupo.getAccessibleContext().setAccessibleName(resourceMap.getString("jlaGrupo.AccessibleContext.accessibleName")); // NOI18N
        jlaGrupo.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jlaGrupo.AccessibleContext.accessibleDescription")); // NOI18N

        jtfGrupo.setFont(resourceMap.getFont("jtfGrupo.font")); // NOI18N
        jtfGrupo.setText(resourceMap.getString("jtfGrupo.text")); // NOI18N
        jtfGrupo.setName("jtfGrupo"); // NOI18N
        jtfGrupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfGrupoFocusLost(evt);
            }
        });
        jpaGerarAtendimento.add(jtfGrupo);
        jtfGrupo.setBounds(10, 30, 220, 23);
        jtfGrupo.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfGrupo.AccessibleContext.accessibleName")); // NOI18N
        jtfGrupo.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jtfGrupo.AccessibleContext.accessibleDescription")); // NOI18N

        jlaModuloAtividade.setFont(resourceMap.getFont("jlaModuloAtividade.font")); // NOI18N
        jlaModuloAtividade.setText(resourceMap.getString("jlaModuloAtividade.text")); // NOI18N
        jlaModuloAtividade.setName("jlaModuloAtividade"); // NOI18N
        jpaGerarAtendimento.add(jlaModuloAtividade);
        jlaModuloAtividade.setBounds(10, 60, 138, 17);

        jcbModuloAtividade.setFont(resourceMap.getFont("jcbModuloAtividade.font")); // NOI18N
        jcbModuloAtividade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbModuloAtividade.setName("jcbModuloAtividade"); // NOI18N
        jcbModuloAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbModuloAtividadeActionPerformed(evt);
            }
        });
        jpaGerarAtendimento.add(jcbModuloAtividade);
        jcbModuloAtividade.setBounds(10, 80, 789, 25);
        jcbModuloAtividade.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbModuloAtividade.AccessibleContext.accessibleName")); // NOI18N

        jpaGerenAtendimentos.add(jpaGerarAtendimento);
        jpaGerarAtendimento.setBounds(2, 30, 800, 110);

        jlaListagemAtendimentos.setFont(resourceMap.getFont("jlaListagemAtendimentos.font")); // NOI18N
        jlaListagemAtendimentos.setText(resourceMap.getString("jlaListagemAtendimentos.text")); // NOI18N
        jlaListagemAtendimentos.setName("jlaListagemAtendimentos"); // NOI18N
        jpaGerenAtendimentos.add(jlaListagemAtendimentos);
        jlaListagemAtendimentos.setBounds(10, 150, 195, 17);

        jspListagemAtendimentos.setName("jspListagemAtendimentos"); // NOI18N

        jtaListagemAtendimentos.setAutoCreateRowSorter(true);
        jtaListagemAtendimentos.setFont(resourceMap.getFont("jtaListagemAtendimentos.font")); // NOI18N
        jtaListagemAtendimentos.setModel(new ModeloTabelaAtendimentos());
        jtaListagemAtendimentos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtaListagemAtendimentos.setName("jtaListagemAtendimentos"); // NOI18N
        jtaListagemAtendimentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtaListagemAtendimentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaListagemAtendimentosKeyPressed(evt);
            }
        });
        jspListagemAtendimentos.setViewportView(jtaListagemAtendimentos);
        jtaListagemAtendimentos.getAccessibleContext().setAccessibleName(resourceMap.getString("jtaListagemAtendimentos.AccessibleContext.accessibleName")); // NOI18N

        jpaGerenAtendimentos.add(jspListagemAtendimentos);
        jspListagemAtendimentos.setBounds(10, 170, 1000, 480);

        jbuVerAlterar.setFont(resourceMap.getFont("jbuVerAlterar.font")); // NOI18N
        jbuVerAlterar.setIcon(resourceMap.getIcon("jbuVerAlterar.icon")); // NOI18N
        jbuVerAlterar.setMnemonic('e');
        jbuVerAlterar.setText(resourceMap.getString("jbuVerAlterar.text")); // NOI18N
        jbuVerAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuVerAlterar.setName("jbuVerAlterar"); // NOI18N
        jbuVerAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuVerAlterarActionPerformed(evt);
            }
        });
        jpaGerenAtendimentos.add(jbuVerAlterar);
        jbuVerAlterar.setBounds(10, 670, 160, 33);
        jbuVerAlterar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuVerAlterar.AccessibleContext.accessibleName")); // NOI18N

        jbuCancelar.setFont(resourceMap.getFont("jbuCancelar.font")); // NOI18N
        jbuCancelar.setIcon(resourceMap.getIcon("jbuCancelar.icon")); // NOI18N
        jbuCancelar.setMnemonic('C');
        jbuCancelar.setText(resourceMap.getString("jbuCancelar.text")); // NOI18N
        jbuCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuCancelar.setName("jbuCancelar"); // NOI18N
        jbuCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuCancelarActionPerformed(evt);
            }
        });
        jpaGerenAtendimentos.add(jbuCancelar);
        jbuCancelar.setBounds(430, 670, 130, 33);
        jbuCancelar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuCancelar.AccessibleContext.accessibleName")); // NOI18N

        jbuFechar.setFont(resourceMap.getFont("jbuFechar.font")); // NOI18N
        jbuFechar.setIcon(resourceMap.getIcon("jbuFechar.icon")); // NOI18N
        jbuFechar.setMnemonic('f');
        jbuFechar.setText(resourceMap.getString("jbuFechar.text")); // NOI18N
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });
        jpaGerenAtendimentos.add(jbuFechar);
        jbuFechar.setBounds(893, 670, 120, 33);
        jbuFechar.getAccessibleContext().setAccessibleName(resourceMap.getString("jButton1.AccessibleContext.accessibleName")); // NOI18N

        jbuGerarAtendimento.setFont(resourceMap.getFont("jbuGerarAtendimento.font")); // NOI18N
        jbuGerarAtendimento.setIcon(resourceMap.getIcon("jbuGerarAtendimento.icon")); // NOI18N
        jbuGerarAtendimento.setMnemonic('G');
        jbuGerarAtendimento.setText(resourceMap.getString("jbuGerarAtendimento.text")); // NOI18N
        jbuGerarAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuGerarAtendimento.setName("jbuGerarAtendimento"); // NOI18N
        jbuGerarAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuGerarAtendimentoActionPerformed(evt);
            }
        });
        jpaGerenAtendimentos.add(jbuGerarAtendimento);
        jbuGerarAtendimento.setBounds(810, 70, 170, 60);
        jbuGerarAtendimento.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuGerarAtendimento.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaGerenAtendimentos, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaGerenAtendimentos, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName(resourceMap.getString("Form.AccessibleContext.accessibleName")); // NOI18N
        getAccessibleContext().setAccessibleDescription(resourceMap.getString("Form.AccessibleContext.accessibleDescription")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
        controlador.desbloquearDTOeFecharTela();
    }//GEN-LAST:event_jbuFecharActionPerformed

    private void jbuGerarAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuGerarAtendimentoActionPerformed
        controlador.gerarAtendimento();
    }//GEN-LAST:event_jbuGerarAtendimentoActionPerformed

    private void jcbModuloAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbModuloAtividadeActionPerformed
        controlador.inicializarAtendimentos();
    }//GEN-LAST:event_jcbModuloAtividadeActionPerformed

    private void jtaListagemAtendimentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaListagemAtendimentosKeyPressed
        controlador.transferirFocoNaTabulacao(evt);
        controlador.abrirTelaDeAlteracaoAtendimento(evt);
    }//GEN-LAST:event_jtaListagemAtendimentosKeyPressed

    private void jbuVerAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuVerAlterarActionPerformed
        controlador.alterarAtendimento();
    }//GEN-LAST:event_jbuVerAlterarActionPerformed

    private void jbuCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuCancelarActionPerformed
        controlador.cancelarAtemdimento();
    }//GEN-LAST:event_jbuCancelarActionPerformed

    private void jtfGrupoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfGrupoFocusLost
        controlador.inicializarModuloAtividade();
    }//GEN-LAST:event_jtfGrupoFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controlador.desbloquearDTOeFecharTela();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbuCancelar;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuGerarAtendimento;
    private javax.swing.JButton jbuVerAlterar;
    private javax.swing.JComboBox jcbModuloAtividade;
    private javax.swing.JLabel jlaGrupo;
    private javax.swing.JLabel jlaListagemAtendimentos;
    private javax.swing.JLabel jlaModuloAtividade;
    private javax.swing.JPanel jpaGerarAtendimento;
    private javax.swing.JPanel jpaGerenAtendimentos;
    private javax.swing.JScrollPane jspListagemAtendimentos;
    private javax.swing.JTable jtaListagemAtendimentos;
    protected javax.swing.JTextField jtfGrupo;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaGruposGerenAtendimentos controlador;
}
