package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaEditar;
import br.laramara.ti.sislaraclient.controladores.ControladorTelaEditarPeriodoDeficiencia;
import br.laramara.ti.sislaraclient.utilitarios.JOptionPanePersonalizado;
import br.laramara.ti.sislaracommons.dtos.ModeloDTO;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

public abstract class TelaEditarComboEDataInicioFinal extends javax.swing.JDialog {

    /** Creates new form TelaEditarComboEDataInicioFinal */
    public TelaEditarComboEDataInicioFinal(String titulo, JDialog parent, ModeloDTO modeloDTO, boolean exibirDeficienciaCID, boolean exibirStatus, boolean exibirObservacao) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        configurarTituloEBotoes(titulo);
        jpaDeficienciaCID.setVisible(exibirDeficienciaCID);
        jpaStatus.setVisible(exibirStatus);
        jpaObservacao.setVisible(exibirObservacao);
        controlador = obterControlador(modeloDTO);
        controlador.abrirTela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaTelaEditarBeneficios = new javax.swing.JPanel();
        jpaTitulo = new javax.swing.JPanel();
        jlaTitulo = new javax.swing.JLabel();
        jbuFecharTitulo = new javax.swing.JButton();
        jpaPrincipal = new javax.swing.JPanel();
        jlaObjetos = new javax.swing.JLabel();
        jcbObjetos = new javax.swing.JComboBox();
        jlaDataInicial = new javax.swing.JLabel();
        jftDataIncial = new javax.swing.JFormattedTextField();
        jbuSelecionarDataInicial = new javax.swing.JButton();
        jlaDataFinal = new javax.swing.JLabel();
        jftDataFinal = new javax.swing.JFormattedTextField();
        jbuSelecionarDataFinal = new javax.swing.JButton();
        jpaStatus = new javax.swing.JPanel();
        jlaStatus = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox();
        jpaDeficienciaCID = new javax.swing.JPanel();
        jlaDeficienciaEtiologia = new javax.swing.JLabel();
        jtfCidEtiologia = new javax.swing.JTextField();
        jlaCidEtiologia = new javax.swing.JLabel();
        jbuAdicionarEtiologiaSelecionada = new javax.swing.JButton();
        jlaEtiologias = new javax.swing.JLabel();
        jspEtiologiasAdicionadas = new javax.swing.JScrollPane();
        jliEtiologiasAdicionadas = new javax.swing.JList();
        jbuRemoverEtiologiaSelecionada = new javax.swing.JButton();
        jlaDeficienciaCID = new javax.swing.JLabel();
        jtfCID = new javax.swing.JTextField();
        jlaCid = new javax.swing.JLabel();
        jlaEpocaIncidencia = new javax.swing.JLabel();
        jcbEpocaIncidencia = new javax.swing.JComboBox();
        jpaObservacao = new javax.swing.JPanel();
        jlaObservacao = new javax.swing.JLabel();
        jspObservacao = new javax.swing.JScrollPane();
        jepObservacao = new javax.swing.JEditorPane();
        jpaBotoes = new javax.swing.JPanel();
        jbuSalvar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(br.laramara.ti.sislaraclient.telas.SisLaraClient.class).getContext().getResourceMap(TelaEditarComboEDataInicioFinal.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jpaTelaEditarBeneficios.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jpaTelaEditarBeneficios.border.lineColor"))); // NOI18N
        jpaTelaEditarBeneficios.setName("jpaTelaEditarBeneficios"); // NOI18N

        jpaTitulo.setBackground(resourceMap.getColor("jpaTitulo.background")); // NOI18N
        jpaTitulo.setName("jpaTitulo"); // NOI18N

        jlaTitulo.setFont(resourceMap.getFont("jlaTitulo.font")); // NOI18N
        jlaTitulo.setForeground(resourceMap.getColor("jlaTitulo.foreground")); // NOI18N
        jlaTitulo.setText(resourceMap.getString("jlaTitulo.text")); // NOI18N
        jlaTitulo.setName("jlaTitulo"); // NOI18N

        jbuFecharTitulo.setBackground(resourceMap.getColor("jbuFecharTitulo.background")); // NOI18N
        jbuFecharTitulo.setIcon(resourceMap.getIcon("jbuFecharTitulo.icon")); // NOI18N
        jbuFecharTitulo.setText(resourceMap.getString("jbuFecharTitulo.text")); // NOI18N
        jbuFecharTitulo.setBorder(null);
        jbuFecharTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFecharTitulo.setFocusable(false);
        jbuFecharTitulo.setName("jbuFecharTitulo"); // NOI18N
        jbuFecharTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharTituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaTituloLayout = new javax.swing.GroupLayout(jpaTitulo);
        jpaTitulo.setLayout(jpaTituloLayout);
        jpaTituloLayout.setHorizontalGroup(
            jpaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 373, Short.MAX_VALUE)
                .addComponent(jbuFecharTitulo))
        );
        jpaTituloLayout.setVerticalGroup(
            jpaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaTituloLayout.createSequentialGroup()
                .addGroup(jpaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbuFecharTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        jpaPrincipal.setName("jpaPrincipal"); // NOI18N

        jlaObjetos.setFont(resourceMap.getFont("jlaObjetos.font")); // NOI18N
        jlaObjetos.setText(resourceMap.getString("jlaObjetos.text")); // NOI18N
        jlaObjetos.setName("jlaObjetos"); // NOI18N

        jcbObjetos.setFont(resourceMap.getFont("jcbObjetos.font")); // NOI18N
        jcbObjetos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbObjetos.setName("jcbObjetos"); // NOI18N

        jlaDataInicial.setFont(resourceMap.getFont("jlaDataInicial.font")); // NOI18N
        jlaDataInicial.setText(resourceMap.getString("jlaDataInicial.text")); // NOI18N
        jlaDataInicial.setName("jlaDataInicial"); // NOI18N

        try {
            jftDataIncial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataIncial.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftDataIncial.setFont(resourceMap.getFont("jftDataIncial.font")); // NOI18N
        jftDataIncial.setName("jftDataIncial"); // NOI18N

        jbuSelecionarDataInicial.setIcon(resourceMap.getIcon("jbuSelecionarDataInicial.icon")); // NOI18N
        jbuSelecionarDataInicial.setText(resourceMap.getString("jbuSelecionarDataInicial.text")); // NOI18N
        jbuSelecionarDataInicial.setBorderPainted(false);
        jbuSelecionarDataInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSelecionarDataInicial.setName("jbuSelecionarDataInicial"); // NOI18N
        jbuSelecionarDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSelecionarDataInicialActionPerformed(evt);
            }
        });

        jlaDataFinal.setFont(resourceMap.getFont("jlaDataInicial.font")); // NOI18N
        jlaDataFinal.setText(resourceMap.getString("jlaDataFinal.text")); // NOI18N
        jlaDataFinal.setName("jlaDataFinal"); // NOI18N

        try {
            jftDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataFinal.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftDataFinal.setFont(resourceMap.getFont("jftDataFinal.font")); // NOI18N
        jftDataFinal.setName("jftDataFinal"); // NOI18N

        jbuSelecionarDataFinal.setIcon(resourceMap.getIcon("jbuSelecionarDataFinal.icon")); // NOI18N
        jbuSelecionarDataFinal.setText(resourceMap.getString("jbuSelecionarDataFinal.text")); // NOI18N
        jbuSelecionarDataFinal.setBorderPainted(false);
        jbuSelecionarDataFinal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSelecionarDataFinal.setName("jbuSelecionarDataFinal"); // NOI18N
        jbuSelecionarDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSelecionarDataFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaPrincipalLayout = new javax.swing.GroupLayout(jpaPrincipal);
        jpaPrincipal.setLayout(jpaPrincipalLayout);
        jpaPrincipalLayout.setHorizontalGroup(
            jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbObjetos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpaPrincipalLayout.createSequentialGroup()
                        .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                                .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlaDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jftDataIncial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlaDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jftDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbuSelecionarDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuSelecionarDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpaPrincipalLayout.setVerticalGroup(
            jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaPrincipalLayout.createSequentialGroup()
                .addComponent(jlaObjetos)
                .addGap(3, 3, 3)
                .addComponent(jcbObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jpaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaPrincipalLayout.createSequentialGroup()
                        .addComponent(jlaDataInicial)
                        .addGap(3, 3, 3)
                        .addComponent(jftDataIncial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jlaDataFinal)
                        .addGap(3, 3, 3)
                        .addComponent(jftDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpaPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbuSelecionarDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jbuSelecionarDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jcbObjetos.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbBeneficios.AccessibleContext.accessibleName")); // NOI18N
        jftDataIncial.getAccessibleContext().setAccessibleName(resourceMap.getString("jftDataIncial.AccessibleContext.accessibleName")); // NOI18N
        jftDataIncial.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jftDataIncial.AccessibleContext.accessibleDescription")); // NOI18N
        jbuSelecionarDataInicial.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuSelecionarDataInicial.AccessibleContext.accessibleName")); // NOI18N
        jbuSelecionarDataInicial.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jbuSelecionarDataInicial.AccessibleContext.accessibleDescription")); // NOI18N
        jftDataFinal.getAccessibleContext().setAccessibleName(resourceMap.getString("jftDataFinal.AccessibleContext.accessibleName")); // NOI18N
        jftDataFinal.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jftDataFinal.AccessibleContext.accessibleDescription")); // NOI18N
        jbuSelecionarDataFinal.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuSelecionarDataFinal.AccessibleContext.accessibleName")); // NOI18N
        jbuSelecionarDataFinal.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jbuSelecionarDataFinal.AccessibleContext.accessibleDescription")); // NOI18N

        jpaStatus.setName("jpaStatus"); // NOI18N
        jpaStatus.setOpaque(false);
        jpaStatus.setLayout(null);

        jlaStatus.setFont(resourceMap.getFont("jlaStatus.font")); // NOI18N
        jlaStatus.setText(resourceMap.getString("jlaStatus.text")); // NOI18N
        jlaStatus.setName("jlaStatus"); // NOI18N
        jpaStatus.add(jlaStatus);
        jlaStatus.setBounds(10, 0, 47, 17);

        jcbStatus.setFont(resourceMap.getFont("jcbStatus.font")); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbStatus.setName("jcbStatus"); // NOI18N
        jpaStatus.add(jcbStatus);
        jcbStatus.setBounds(10, 20, 220, 25);
        jcbStatus.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbStatus.AccessibleContext.accessibleName")); // NOI18N

        jpaDeficienciaCID.setToolTipText(resourceMap.getString("jpaDeficienciaCID.toolTipText")); // NOI18N
        jpaDeficienciaCID.setName("jpaDeficienciaCID"); // NOI18N
        jpaDeficienciaCID.setOpaque(false);

        jlaDeficienciaEtiologia.setFont(resourceMap.getFont("jlaDeficienciaEtiologia.font")); // NOI18N
        jlaDeficienciaEtiologia.setText(resourceMap.getString("jlaDeficienciaEtiologia.text")); // NOI18N
        jlaDeficienciaEtiologia.setName("jlaDeficienciaEtiologia"); // NOI18N

        jtfCidEtiologia.setFont(resourceMap.getFont("jtfCidEtiologia.font")); // NOI18N
        jtfCidEtiologia.setText(resourceMap.getString("jtfCidEtiologia.text")); // NOI18N
        jtfCidEtiologia.setToolTipText(resourceMap.getString("jtfCidEtiologia.toolTipText")); // NOI18N
        jtfCidEtiologia.setName("jtfCidEtiologia"); // NOI18N
        jtfCidEtiologia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCidEtiologiaFocusLost(evt);
            }
        });

        jlaCidEtiologia.setFont(resourceMap.getFont("jlaCidEtiologia.font")); // NOI18N
        jlaCidEtiologia.setText(resourceMap.getString("jlaCidEtiologia.text")); // NOI18N
        jlaCidEtiologia.setToolTipText(resourceMap.getString("jlaCidEtiologia.toolTipText")); // NOI18N
        jlaCidEtiologia.setName("jlaCidEtiologia"); // NOI18N

        jbuAdicionarEtiologiaSelecionada.setFont(resourceMap.getFont("jbuAdicionarEtiologiaSelecionada.font")); // NOI18N
        jbuAdicionarEtiologiaSelecionada.setIcon(resourceMap.getIcon("jbuAdicionarEtiologiaSelecionada.icon")); // NOI18N
        jbuAdicionarEtiologiaSelecionada.setMnemonic('A');
        jbuAdicionarEtiologiaSelecionada.setText(resourceMap.getString("jbuAdicionarEtiologiaSelecionada.text")); // NOI18N
        jbuAdicionarEtiologiaSelecionada.setName("jbuAdicionarEtiologiaSelecionada"); // NOI18N
        jbuAdicionarEtiologiaSelecionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarEtiologiaSelecionadaActionPerformed(evt);
            }
        });

        jlaEtiologias.setFont(resourceMap.getFont("jlaEtiologias.font")); // NOI18N
        jlaEtiologias.setText(resourceMap.getString("jlaEtiologias.text")); // NOI18N
        jlaEtiologias.setName("jlaEtiologias"); // NOI18N

        jspEtiologiasAdicionadas.setFont(resourceMap.getFont("jspEtiologiasAdicionadas.font")); // NOI18N
        jspEtiologiasAdicionadas.setName("jspEtiologiasAdicionadas"); // NOI18N

        jliEtiologiasAdicionadas.setFont(resourceMap.getFont("jliEtiologiasAdicionadas.font")); // NOI18N
        jliEtiologiasAdicionadas.setModel(new DefaultListModel());
        jliEtiologiasAdicionadas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jliEtiologiasAdicionadas.setName("jliEtiologiasAdicionadas"); // NOI18N
        jspEtiologiasAdicionadas.setViewportView(jliEtiologiasAdicionadas);
        jliEtiologiasAdicionadas.getAccessibleContext().setAccessibleName(resourceMap.getString("jliEtiologiasAdicionadas.AccessibleContext.accessibleName")); // NOI18N

        jbuRemoverEtiologiaSelecionada.setFont(resourceMap.getFont("jbuRemoverEtiologiaSelecionada.font")); // NOI18N
        jbuRemoverEtiologiaSelecionada.setIcon(resourceMap.getIcon("jbuRemoverEtiologiaSelecionada.icon")); // NOI18N
        jbuRemoverEtiologiaSelecionada.setMnemonic('r');
        jbuRemoverEtiologiaSelecionada.setText(resourceMap.getString("jbuRemoverEtiologiaSelecionada.text")); // NOI18N
        jbuRemoverEtiologiaSelecionada.setName("jbuRemoverEtiologiaSelecionada"); // NOI18N
        jbuRemoverEtiologiaSelecionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverEtiologiaSelecionadaActionPerformed(evt);
            }
        });

        jlaDeficienciaCID.setFont(resourceMap.getFont("jlaDeficienciaCID.font")); // NOI18N
        jlaDeficienciaCID.setText(resourceMap.getString("jlaDeficienciaCID.text")); // NOI18N
        jlaDeficienciaCID.setName("jlaDeficienciaCID"); // NOI18N

        jtfCID.setFont(resourceMap.getFont("jtfCID.font")); // NOI18N
        jtfCID.setText(resourceMap.getString("jtfCID.text")); // NOI18N
        jtfCID.setName("jtfCID"); // NOI18N
        jtfCID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCIDFocusLost(evt);
            }
        });

        jlaCid.setFont(resourceMap.getFont("jlaCid.font")); // NOI18N
        jlaCid.setText(resourceMap.getString("jlaCid.text")); // NOI18N
        jlaCid.setToolTipText(resourceMap.getString("jlaCid.toolTipText")); // NOI18N
        jlaCid.setName("jlaCid"); // NOI18N

        jlaEpocaIncidencia.setFont(resourceMap.getFont("jlaEpocaIncidencia.font")); // NOI18N
        jlaEpocaIncidencia.setText(resourceMap.getString("jlaEpocaIncidencia.text")); // NOI18N
        jlaEpocaIncidencia.setToolTipText(resourceMap.getString("jlaEpocaIncidencia.toolTipText")); // NOI18N
        jlaEpocaIncidencia.setName("jlaEpocaIncidencia"); // NOI18N

        jcbEpocaIncidencia.setFont(resourceMap.getFont("jcbEpocaIncidencia.font")); // NOI18N
        jcbEpocaIncidencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  " }));
        jcbEpocaIncidencia.setName("jcbEpocaIncidencia"); // NOI18N

        javax.swing.GroupLayout jpaDeficienciaCIDLayout = new javax.swing.GroupLayout(jpaDeficienciaCID);
        jpaDeficienciaCID.setLayout(jpaDeficienciaCIDLayout);
        jpaDeficienciaCIDLayout.setHorizontalGroup(
            jpaDeficienciaCIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaDeficienciaCIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaDeficienciaCIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlaDeficienciaCID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlaDeficienciaEtiologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpaDeficienciaCIDLayout.createSequentialGroup()
                        .addComponent(jtfCidEtiologia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlaCidEtiologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpaDeficienciaCIDLayout.createSequentialGroup()
                        .addComponent(jtfCID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlaCid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlaEtiologias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlaEpocaIncidencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpaDeficienciaCIDLayout.createSequentialGroup()
                        .addGroup(jpaDeficienciaCIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuAdicionarEtiologiaSelecionada)
                            .addComponent(jcbEpocaIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpaDeficienciaCIDLayout.createSequentialGroup()
                        .addComponent(jspEtiologiasAdicionadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuRemoverEtiologiaSelecionada)))
                .addContainerGap())
        );
        jpaDeficienciaCIDLayout.setVerticalGroup(
            jpaDeficienciaCIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaDeficienciaCIDLayout.createSequentialGroup()
                .addComponent(jlaDeficienciaEtiologia, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaDeficienciaCIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCidEtiologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlaCidEtiologia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbuAdicionarEtiologiaSelecionada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlaEtiologias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaDeficienciaCIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaDeficienciaCIDLayout.createSequentialGroup()
                        .addComponent(jspEtiologiasAdicionadas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlaDeficienciaCID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpaDeficienciaCIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfCID)
                            .addComponent(jlaCid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlaEpocaIncidencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbEpocaIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbuRemoverEtiologiaSelecionada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbuRemoverEtiologiaSelecionada.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jbuRemoverEtiologiaSelecionada.AccessibleContext.accessibleDescription")); // NOI18N

        jpaObservacao.setName("jpaObservacao"); // NOI18N
        jpaObservacao.setOpaque(false);

        jlaObservacao.setFont(resourceMap.getFont("jlaObservacao.font")); // NOI18N
        jlaObservacao.setText(resourceMap.getString("jlaObservacao.text")); // NOI18N
        jlaObservacao.setName("jlaObservacao"); // NOI18N

        jspObservacao.setName("jspObservacao"); // NOI18N

        jepObservacao.setFont(resourceMap.getFont("jepObservacao.font")); // NOI18N
        jepObservacao.setName("jepObservacao"); // NOI18N
        jspObservacao.setViewportView(jepObservacao);

        javax.swing.GroupLayout jpaObservacaoLayout = new javax.swing.GroupLayout(jpaObservacao);
        jpaObservacao.setLayout(jpaObservacaoLayout);
        jpaObservacaoLayout.setHorizontalGroup(
            jpaObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaObservacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspObservacao)
                    .addGroup(jpaObservacaoLayout.createSequentialGroup()
                        .addComponent(jlaObservacao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpaObservacaoLayout.setVerticalGroup(
            jpaObservacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaObservacaoLayout.createSequentialGroup()
                .addComponent(jlaObservacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpaBotoes.setName("jpaBotoes"); // NOI18N
        jpaBotoes.setOpaque(false);

        jbuSalvar.setFont(resourceMap.getFont("jbuSalvar.font")); // NOI18N
        jbuSalvar.setIcon(resourceMap.getIcon("jbuSalvar.icon")); // NOI18N
        jbuSalvar.setMnemonic('s');
        jbuSalvar.setText(resourceMap.getString("jbuSalvar.text")); // NOI18N
        jbuSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSalvar.setName("jbuSalvar"); // NOI18N
        jbuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSalvarActionPerformed(evt);
            }
        });

        jbuFechar.setFont(resourceMap.getFont("jbuFechar.font")); // NOI18N
        jbuFechar.setIcon(resourceMap.getIcon("jbuFechar.icon")); // NOI18N
        jbuFechar.setMnemonic('f');
        jbuFechar.setText(resourceMap.getString("jbuFechar.text")); // NOI18N
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaBotoesLayout = new javax.swing.GroupLayout(jpaBotoes);
        jpaBotoes.setLayout(jpaBotoesLayout);
        jpaBotoesLayout.setHorizontalGroup(
            jpaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbuSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbuFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpaBotoesLayout.setVerticalGroup(
            jpaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpaBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuFechar)
                    .addComponent(jbuSalvar))
                .addContainerGap())
        );

        jbuSalvar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuSalvar.AccessibleContext.accessibleName")); // NOI18N
        jbuFechar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuFechar.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout jpaTelaEditarBeneficiosLayout = new javax.swing.GroupLayout(jpaTelaEditarBeneficios);
        jpaTelaEditarBeneficios.setLayout(jpaTelaEditarBeneficiosLayout);
        jpaTelaEditarBeneficiosLayout.setHorizontalGroup(
            jpaTelaEditarBeneficiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaDeficienciaCID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpaTelaEditarBeneficiosLayout.setVerticalGroup(
            jpaTelaEditarBeneficiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaTelaEditarBeneficiosLayout.createSequentialGroup()
                .addComponent(jpaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpaDeficienciaCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpaObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpaBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaTelaEditarBeneficios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaTelaEditarBeneficios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSalvarActionPerformed
    controlador.salvar();
}//GEN-LAST:event_jbuSalvarActionPerformed

private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
    controlador.fecharTela();
}//GEN-LAST:event_jbuFecharActionPerformed

private void jbuSelecionarDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSelecionarDataInicialActionPerformed
    JOptionPanePersonalizado.mostrarTelaSelecionarData(this, jftDataIncial);
}//GEN-LAST:event_jbuSelecionarDataInicialActionPerformed

private void jbuSelecionarDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSelecionarDataFinalActionPerformed
    JOptionPanePersonalizado.mostrarTelaSelecionarData(this, jftDataFinal);
}//GEN-LAST:event_jbuSelecionarDataFinalActionPerformed

private void jbuFecharTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharTituloActionPerformed
    controlador.fecharTela();
}//GEN-LAST:event_jbuFecharTituloActionPerformed

    private void jtfCIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCIDFocusLost
        ((ControladorTelaEditarPeriodoDeficiencia)controlador).consultarCid();
    }//GEN-LAST:event_jtfCIDFocusLost

    private void jtfCidEtiologiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCidEtiologiaFocusLost
        ((ControladorTelaEditarPeriodoDeficiencia)controlador).consultarEtiologia();
    }//GEN-LAST:event_jtfCidEtiologiaFocusLost

    private void jbuAdicionarEtiologiaSelecionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarEtiologiaSelecionadaActionPerformed
        ((ControladorTelaEditarPeriodoDeficiencia)controlador).adicionarEtiologiaSelecinada();
    }//GEN-LAST:event_jbuAdicionarEtiologiaSelecionadaActionPerformed

    private void jbuRemoverEtiologiaSelecionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverEtiologiaSelecionadaActionPerformed
        ((ControladorTelaEditarPeriodoDeficiencia)controlador).removerEtiologiaSelecinada();
    }//GEN-LAST:event_jbuRemoverEtiologiaSelecionadaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbuAdicionarEtiologiaSelecionada;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuFecharTitulo;
    private javax.swing.JButton jbuRemoverEtiologiaSelecionada;
    private javax.swing.JButton jbuSalvar;
    private javax.swing.JButton jbuSelecionarDataFinal;
    private javax.swing.JButton jbuSelecionarDataInicial;
    protected javax.swing.JComboBox jcbEpocaIncidencia;
    protected javax.swing.JComboBox jcbObjetos;
    protected javax.swing.JComboBox jcbStatus;
    protected javax.swing.JEditorPane jepObservacao;
    protected javax.swing.JFormattedTextField jftDataFinal;
    protected javax.swing.JFormattedTextField jftDataIncial;
    protected javax.swing.JLabel jlaCid;
    protected javax.swing.JLabel jlaCidEtiologia;
    private javax.swing.JLabel jlaDataFinal;
    private javax.swing.JLabel jlaDataInicial;
    private javax.swing.JLabel jlaDeficienciaCID;
    private javax.swing.JLabel jlaDeficienciaEtiologia;
    private javax.swing.JLabel jlaEpocaIncidencia;
    private javax.swing.JLabel jlaEtiologias;
    private javax.swing.JLabel jlaObjetos;
    private javax.swing.JLabel jlaObservacao;
    private javax.swing.JLabel jlaStatus;
    private javax.swing.JLabel jlaTitulo;
    protected javax.swing.JList jliEtiologiasAdicionadas;
    private javax.swing.JPanel jpaBotoes;
    protected javax.swing.JPanel jpaDeficienciaCID;
    private javax.swing.JPanel jpaObservacao;
    private javax.swing.JPanel jpaPrincipal;
    private javax.swing.JPanel jpaStatus;
    private javax.swing.JPanel jpaTelaEditarBeneficios;
    private javax.swing.JPanel jpaTitulo;
    private javax.swing.JScrollPane jspEtiologiasAdicionadas;
    private javax.swing.JScrollPane jspObservacao;
    protected javax.swing.JTextField jtfCID;
    protected javax.swing.JTextField jtfCidEtiologia;
    // End of variables declaration//GEN-END:variables
    protected ControladorTelaEditar controlador;
    
    protected abstract ControladorTelaEditar obterControlador(ModeloDTO modeloDto);
    
    private void configurarTituloEBotoes(String titulo){
        jlaTitulo.setText("Editar Informações de " + titulo);
        jlaObjetos.setText(titulo);
        jbuSalvar.getAccessibleContext().setAccessibleName("Salvar Informações de " + titulo);
        jbuFechar.getAccessibleContext().setAccessibleName("Fechar Editar Informaçôes de " + titulo);
    }
}
