package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaAtendimentoIndividualEditar;
import br.laramara.ti.sislaraclient.infra.PermissaoDeTelas;
import br.laramara.ti.sislaraclient.modelos.ModeloTabelaAtendimentoAcompanhante;
import br.laramara.ti.sislaraclient.modelos.ModeloTabelaAtendimentoProfissional;
import br.laramara.ti.sislaraclient.utilitarios.JOptionPanePersonalizado;
import br.laramara.ti.sislaraclient.utilitarios.WordUtils;
import br.laramara.ti.sislaracommons.dtos.atendimento.AtendimentoIndividualDTO;
import java.awt.Window;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

public class TelaAtendimentoIndividualEditar extends javax.swing.JDialog {

    public TelaAtendimentoIndividualEditar(JDialog parent, AtendimentoIndividualDTO atendimentoIndividualDTO) {
        this(parent, false, atendimentoIndividualDTO);
    }
    
    public TelaAtendimentoIndividualEditar(Window parent, boolean forcarCarregamentoAtendimentoIndividualDTO, AtendimentoIndividualDTO atendimentoIndividualDTO) {
        super(parent, ModalityType.APPLICATION_MODAL);
        initComponents();
        setLocationRelativeTo(parent);
        controlador = new ControladorTelaAtendimentoIndividualEditar(this, forcarCarregamentoAtendimentoIndividualDTO, atendimentoIndividualDTO, jbuUtilizarUsuario, jbuUtilizarPreCadastro, jftProntuario, jtfNomeUsuario, jtfNomePreCadastro, jftData, jftHoraInicio, jftHoraTermino, jcbTipoAtendimento, jcbDescricaoTipoAtendimento, jcbModuloAtividade, jcbPrimeiraVez, jcbSetor, jcbLocalAtendimento, jcbParticipacao, jatDescricao, jatInterdisciplinar, jtaProfissionais, jcbFrequencia, jatJustificativa, jtaAcompanhante, jliArquivos);
        controlador.inicializarCombosComDependencia();
        controlador.abrirSomenteSeHouverPermissao(PermissaoDeTelas.ATENDIMENTO_INDIVIDUAL_TELA_EDICAO_VISUALIZAR);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaEditarAtendimentoIndividual = new javax.swing.JPanel();
        jpaTitulo = new javax.swing.JPanel();
        jalTitulo = new javax.swing.JLabel();
        jbuFecharTitulo = new javax.swing.JButton();
        jtpIntegrante = new javax.swing.JTabbedPane();
        jpaUsuario = new javax.swing.JPanel();
        jlaProntuario = new javax.swing.JLabel();
        jlaNomeUsuario = new javax.swing.JLabel();
        jtfNomeUsuario = new javax.swing.JTextField();
        jbuUtilizarUsuario = new javax.swing.JButton();
        jftProntuario = new javax.swing.JFormattedTextField();
        jpaPreCadastro = new javax.swing.JPanel();
        jlaNomePreCadastro = new javax.swing.JLabel();
        jtfNomePreCadastro = new javax.swing.JTextField();
        jbuUtilizarPreCadastro = new javax.swing.JButton();
        jpaDataHora = new javax.swing.JPanel();
        jlaData = new javax.swing.JLabel();
        jftData = new javax.swing.JFormattedTextField();
        jbuSelecionarData = new javax.swing.JButton();
        jlaHoraInicio = new javax.swing.JLabel();
        jftHoraInicio = new javax.swing.JFormattedTextField();
        jlaHoraTermino = new javax.swing.JLabel();
        jftHoraTermino = new javax.swing.JFormattedTextField();
        jlaTipoAtendimento = new javax.swing.JLabel();
        jcbTipoAtendimento = new javax.swing.JComboBox();
        jlaDescricaoTipoAtendimento = new javax.swing.JLabel();
        jcbDescricaoTipoAtendimento = new javax.swing.JComboBox();
        jlaSetor = new javax.swing.JLabel();
        jcbSetor = new javax.swing.JComboBox();
        jlaModuloAtividade = new javax.swing.JLabel();
        jcbModuloAtividade = new javax.swing.JComboBox();
        jlaLocalAtendimento = new javax.swing.JLabel();
        jcbLocalAtendimento = new javax.swing.JComboBox();
        jtpRegistros = new javax.swing.JTabbedPane();
        jpaDescricaoAtendimento = new javax.swing.JPanel();
        jlaDescricao = new javax.swing.JLabel();
        jlaInterdisciplinar = new javax.swing.JLabel();
        jspDescricao = new javax.swing.JScrollPane();
        jatDescricao = new javax.swing.JTextArea();
        jspInterdisciplinar = new javax.swing.JScrollPane();
        jatInterdisciplinar = new javax.swing.JTextArea();
        jpaProfissionais = new javax.swing.JPanel();
        jlaProfissionais = new javax.swing.JLabel();
        jspProfissionais = new javax.swing.JScrollPane();
        jtaProfissionais = new javax.swing.JTable();
        jbuAdicionar = new javax.swing.JButton();
        jbuAlterar = new javax.swing.JButton();
        jbuRemover = new javax.swing.JButton();
        jpaFrequencia = new javax.swing.JPanel();
        jlaFrequencia = new javax.swing.JLabel();
        jcbFrequencia = new javax.swing.JComboBox();
        jlaJustificativa = new javax.swing.JLabel();
        jspJustificativa = new javax.swing.JScrollPane();
        jatJustificativa = new javax.swing.JTextArea();
        jpaAcompanhante = new javax.swing.JPanel();
        jlaAcompanhante = new javax.swing.JLabel();
        jspAcompanhante = new javax.swing.JScrollPane();
        jtaAcompanhante = new javax.swing.JTable();
        jbuAdicionarAcompanhante = new javax.swing.JButton();
        jbuAlterarAcompanhante = new javax.swing.JButton();
        jbuRemoverAcompanhante = new javax.swing.JButton();
        jpaArquivos = new javax.swing.JPanel();
        jspArquivos = new javax.swing.JScrollPane();
        jliArquivos = new javax.swing.JList();
        jlaArquivos = new javax.swing.JLabel();
        jbuAdicionarArquivo = new javax.swing.JButton();
        jbuAbrirAquivo = new javax.swing.JButton();
        jbuRemoverArquivo = new javax.swing.JButton();
        jbuSalvar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();
        jlaParticipacao = new javax.swing.JLabel();
        jcbParticipacao = new javax.swing.JComboBox();
        jlaPrimeiraVez = new javax.swing.JLabel();
        jcbPrimeiraVez = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(TelaAtendimentoIndividualEditar.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jpaEditarAtendimentoIndividual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpaEditarAtendimentoIndividual.setName("jpaEditarAtendimentoIndividual"); // NOI18N
        jpaEditarAtendimentoIndividual.setLayout(null);

        jpaTitulo.setBackground(resourceMap.getColor("jpaTitulo.background")); // NOI18N
        jpaTitulo.setName("jpaTitulo"); // NOI18N
        jpaTitulo.setLayout(null);

        jalTitulo.setFont(resourceMap.getFont("jalTitulo.font")); // NOI18N
        jalTitulo.setForeground(resourceMap.getColor("jalTitulo.foreground")); // NOI18N
        jalTitulo.setText(resourceMap.getString("jalTitulo.text")); // NOI18N
        jalTitulo.setName("jalTitulo"); // NOI18N
        jpaTitulo.add(jalTitulo);
        jalTitulo.setBounds(10, 0, 380, 26);

        jbuFecharTitulo.setBackground(resourceMap.getColor("jbuFecharTitulo.background")); // NOI18N
        jbuFecharTitulo.setIcon(resourceMap.getIcon("jbuFecharTitulo.icon")); // NOI18N
        jbuFecharTitulo.setText(resourceMap.getString("jbuFecharTitulo.text")); // NOI18N
        jbuFecharTitulo.setBorder(null);
        jbuFecharTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFecharTitulo.setFocusable(false);
        jbuFecharTitulo.setName("jbuFecharTitulo"); // NOI18N
        jbuFecharTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharTituloActionPerformed(evt);
            }
        });
        jpaTitulo.add(jbuFecharTitulo);
        jbuFecharTitulo.setBounds(1003, 0, 25, 25);

        jpaEditarAtendimentoIndividual.add(jpaTitulo);
        jpaTitulo.setBounds(1, 1, 1027, 26);

        jtpIntegrante.setFont(resourceMap.getFont("jtpIntegrante.font")); // NOI18N
        jtpIntegrante.setName("jtpIntegrante"); // NOI18N

        jpaUsuario.setName("jpaUsuario"); // NOI18N
        jpaUsuario.setLayout(null);

        jlaProntuario.setFont(resourceMap.getFont("jlaProntuario.font")); // NOI18N
        jlaProntuario.setText(resourceMap.getString("jlaProntuario.text")); // NOI18N
        jlaProntuario.setName("jlaProntuario"); // NOI18N
        jpaUsuario.add(jlaProntuario);
        jlaProntuario.setBounds(10, 11, 80, 17);

        jlaNomeUsuario.setFont(resourceMap.getFont("jlaProntuario.font")); // NOI18N
        jlaNomeUsuario.setText(resourceMap.getString("jlaNomeUsuario.text")); // NOI18N
        jlaNomeUsuario.setName("jlaNomeUsuario"); // NOI18N
        jpaUsuario.add(jlaNomeUsuario);
        jlaNomeUsuario.setBounds(99, 11, 42, 17);

        jtfNomeUsuario.setEditable(false);
        jtfNomeUsuario.setFont(resourceMap.getFont("jlaProntuario.font")); // NOI18N
        jtfNomeUsuario.setText(resourceMap.getString("jtfNomeUsuario.text")); // NOI18N
        jtfNomeUsuario.setName("jtfNomeUsuario"); // NOI18N
        jpaUsuario.add(jtfNomeUsuario);
        jtfNomeUsuario.setBounds(99, 31, 450, 23);
        jtfNomeUsuario.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfNomeUsuario.AccessibleContext.accessibleName")); // NOI18N

        jbuUtilizarUsuario.setFont(resourceMap.getFont("jbuUtilizarUsuario.font")); // NOI18N
        jbuUtilizarUsuario.setIcon(resourceMap.getIcon("jbuUtilizarUsuario.icon")); // NOI18N
        jbuUtilizarUsuario.setMnemonic('U');
        jbuUtilizarUsuario.setText(resourceMap.getString("jbuUtilizarUsuario.text")); // NOI18N
        jbuUtilizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuUtilizarUsuario.setName("jbuUtilizarUsuario"); // NOI18N
        jbuUtilizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuUtilizarUsuarioActionPerformed(evt);
            }
        });
        jpaUsuario.add(jbuUtilizarUsuario);
        jbuUtilizarUsuario.setBounds(555, 26, 120, 33);
        jbuUtilizarUsuario.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuUtilizarUsuario.AccessibleContext.accessibleName")); // NOI18N

        try {
            jftProntuario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftProntuario.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftProntuario.setFont(resourceMap.getFont("jftProntuario.font")); // NOI18N
        jftProntuario.setName("jftProntuario"); // NOI18N
        jftProntuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftProntuarioFocusLost(evt);
            }
        });
        jpaUsuario.add(jftProntuario);
        jftProntuario.setBounds(10, 31, 80, 23);
        jftProntuario.getAccessibleContext().setAccessibleName(resourceMap.getString("jftProntuario.AccessibleContext.accessibleName")); // NOI18N

        jtpIntegrante.addTab(resourceMap.getString("jpaUsuario.TabConstraints.tabTitle"), jpaUsuario); // NOI18N

        jpaPreCadastro.setName("jpaPreCadastro"); // NOI18N
        jpaPreCadastro.setLayout(null);

        jlaNomePreCadastro.setFont(resourceMap.getFont("jtfNomePreCadastro.font")); // NOI18N
        jlaNomePreCadastro.setText(resourceMap.getString("jlaNomePreCadastro.text")); // NOI18N
        jlaNomePreCadastro.setName("jlaNomePreCadastro"); // NOI18N
        jpaPreCadastro.add(jlaNomePreCadastro);
        jlaNomePreCadastro.setBounds(10, 11, 42, 17);

        jtfNomePreCadastro.setEditable(false);
        jtfNomePreCadastro.setFont(resourceMap.getFont("jtfNomePreCadastro.font")); // NOI18N
        jtfNomePreCadastro.setText(resourceMap.getString("jtfNomePreCadastro.text")); // NOI18N
        jtfNomePreCadastro.setName("jtfNomePreCadastro"); // NOI18N
        jpaPreCadastro.add(jtfNomePreCadastro);
        jtfNomePreCadastro.setBounds(10, 30, 540, 23);
        jtfNomePreCadastro.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfNomePreCadastro.AccessibleContext.accessibleName")); // NOI18N

        jbuUtilizarPreCadastro.setFont(resourceMap.getFont("jbuUtilizarPreCadastro.font")); // NOI18N
        jbuUtilizarPreCadastro.setIcon(resourceMap.getIcon("jbuUtilizarPreCadastro.icon")); // NOI18N
        jbuUtilizarPreCadastro.setMnemonic('U');
        jbuUtilizarPreCadastro.setText(resourceMap.getString("jbuUtilizarPreCadastro.text")); // NOI18N
        jbuUtilizarPreCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuUtilizarPreCadastro.setName("jbuUtilizarPreCadastro"); // NOI18N
        jbuUtilizarPreCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuUtilizarPreCadastroActionPerformed(evt);
            }
        });
        jpaPreCadastro.add(jbuUtilizarPreCadastro);
        jbuUtilizarPreCadastro.setBounds(555, 26, 120, 33);
        jbuUtilizarPreCadastro.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuUtilizarPreCadastro.AccessibleContext.accessibleName")); // NOI18N

        jtpIntegrante.addTab(resourceMap.getString("jpaPreCadastro.TabConstraints.tabTitle"), jpaPreCadastro); // NOI18N

        jpaEditarAtendimentoIndividual.add(jtpIntegrante);
        jtpIntegrante.setBounds(10, 40, 690, 120);

        jpaDataHora.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jpaDataHora.border.lineColor"))); // NOI18N
        jpaDataHora.setName("jpaDataHora"); // NOI18N
        jpaDataHora.setLayout(null);

        jlaData.setFont(resourceMap.getFont("jlaHoraTermino.font")); // NOI18N
        jlaData.setText(resourceMap.getString("jlaData.text")); // NOI18N
        jlaData.setName("jlaData"); // NOI18N
        jpaDataHora.add(jlaData);
        jlaData.setBounds(10, 5, 50, 17);

        try {
            jftData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftData.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftData.setFont(resourceMap.getFont("jftData.font")); // NOI18N
        jftData.setName("jftData"); // NOI18N
        jpaDataHora.add(jftData);
        jftData.setBounds(10, 25, 100, 23);
        jftData.getAccessibleContext().setAccessibleName(resourceMap.getString("jFormattedTextField1.AccessibleContext.accessibleName")); // NOI18N
        jftData.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jFormattedTextField1.AccessibleContext.accessibleDescription")); // NOI18N

        jbuSelecionarData.setIcon(resourceMap.getIcon("jbuSelecionarData.icon")); // NOI18N
        jbuSelecionarData.setText(resourceMap.getString("jbuSelecionarData.text")); // NOI18N
        jbuSelecionarData.setBorderPainted(false);
        jbuSelecionarData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSelecionarData.setName("jbuSelecionarData"); // NOI18N
        jbuSelecionarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSelecionarDataActionPerformed(evt);
            }
        });
        jpaDataHora.add(jbuSelecionarData);
        jbuSelecionarData.setBounds(114, 24, 25, 25);
        jbuSelecionarData.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuSelecionarData.AccessibleContext.accessibleName")); // NOI18N
        jbuSelecionarData.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jbuSelecionarData.AccessibleContext.accessibleDescription")); // NOI18N

        jlaHoraInicio.setFont(resourceMap.getFont("jlaHoraTermino.font")); // NOI18N
        jlaHoraInicio.setText(resourceMap.getString("jlaHoraInicio.text")); // NOI18N
        jlaHoraInicio.setName("jlaHoraInicio"); // NOI18N
        jpaDataHora.add(jlaHoraInicio);
        jlaHoraInicio.setBounds(10, 60, 80, 17);

        try {
            jftHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftHoraInicio.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftHoraInicio.setFont(resourceMap.getFont("jftHoraInicio.font")); // NOI18N
        jftHoraInicio.setName("jftHoraInicio"); // NOI18N
        jpaDataHora.add(jftHoraInicio);
        jftHoraInicio.setBounds(10, 80, 100, 23);
        jftHoraInicio.getAccessibleContext().setAccessibleName(resourceMap.getString("jFormattedTextField2.AccessibleContext.accessibleName")); // NOI18N
        jftHoraInicio.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jFormattedTextField2.AccessibleContext.accessibleDescription")); // NOI18N

        jlaHoraTermino.setFont(resourceMap.getFont("jlaHoraTermino.font")); // NOI18N
        jlaHoraTermino.setText(resourceMap.getString("jlaHoraTermino.text")); // NOI18N
        jlaHoraTermino.setName("jlaHoraTermino"); // NOI18N
        jpaDataHora.add(jlaHoraTermino);
        jlaHoraTermino.setBounds(10, 110, 100, 16);

        try {
            jftHoraTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftHoraTermino.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftHoraTermino.setFont(resourceMap.getFont("jftHoraTermino.font")); // NOI18N
        jftHoraTermino.setName("jftHoraTermino"); // NOI18N
        jpaDataHora.add(jftHoraTermino);
        jftHoraTermino.setBounds(10, 130, 100, 23);
        jftHoraTermino.getAccessibleContext().setAccessibleName(resourceMap.getString("jftHoraTermino.AccessibleContext.accessibleName")); // NOI18N
        jftHoraTermino.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jftHoraTermino.AccessibleContext.accessibleDescription")); // NOI18N

        jpaEditarAtendimentoIndividual.add(jpaDataHora);
        jpaDataHora.setBounds(710, 41, 155, 170);

        jlaTipoAtendimento.setFont(resourceMap.getFont("jlaTipoAtendimento.font")); // NOI18N
        jlaTipoAtendimento.setText(resourceMap.getString("jlaTipoAtendimento.text")); // NOI18N
        jlaTipoAtendimento.setName("jlaTipoAtendimento"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaTipoAtendimento);
        jlaTipoAtendimento.setBounds(10, 170, 290, 17);

        jcbTipoAtendimento.setFont(resourceMap.getFont("jcbTipoAtendimento.font")); // NOI18N
        jcbTipoAtendimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbTipoAtendimento.setName("jcbTipoAtendimento"); // NOI18N
        jcbTipoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoAtendimentoActionPerformed(evt);
            }
        });
        jpaEditarAtendimentoIndividual.add(jcbTipoAtendimento);
        jcbTipoAtendimento.setBounds(10, 190, 690, 25);
        jcbTipoAtendimento.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbTipoAtendimento.AccessibleContext.accessibleName")); // NOI18N

        jlaDescricaoTipoAtendimento.setFont(resourceMap.getFont("jlaDescricaoTipoAtendimento.font")); // NOI18N
        jlaDescricaoTipoAtendimento.setText(resourceMap.getString("jlaDescricaoTipoAtendimento.text")); // NOI18N
        jlaDescricaoTipoAtendimento.setName("jlaDescricaoTipoAtendimento"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaDescricaoTipoAtendimento);
        jlaDescricaoTipoAtendimento.setBounds(10, 220, 270, 17);

        jcbDescricaoTipoAtendimento.setFont(resourceMap.getFont("jcbDescricaoTipoAtendimento.font")); // NOI18N
        jcbDescricaoTipoAtendimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbDescricaoTipoAtendimento.setName("jcbDescricaoTipoAtendimento"); // NOI18N
        jcbDescricaoTipoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDescricaoTipoAtendimentoActionPerformed(evt);
            }
        });
        jpaEditarAtendimentoIndividual.add(jcbDescricaoTipoAtendimento);
        jcbDescricaoTipoAtendimento.setBounds(10, 240, 690, 25);
        jcbDescricaoTipoAtendimento.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbDescricaoTipoAtendimento.AccessibleContext.accessibleName")); // NOI18N

        jlaSetor.setFont(resourceMap.getFont("jlaSetor.font")); // NOI18N
        jlaSetor.setText(resourceMap.getString("jlaSetor.text")); // NOI18N
        jlaSetor.setName("jlaSetor"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaSetor);
        jlaSetor.setBounds(710, 220, 60, 17);

        jcbSetor.setFont(resourceMap.getFont("jcbSetor.font")); // NOI18N
        jcbSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbSetor.setName("jcbSetor"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jcbSetor);
        jcbSetor.setBounds(710, 240, 155, 25);
        jcbSetor.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbSetor.AccessibleContext.accessibleName")); // NOI18N

        jlaModuloAtividade.setFont(resourceMap.getFont("jlaModuloAtividade.font")); // NOI18N
        jlaModuloAtividade.setText(resourceMap.getString("jlaModuloAtividade.text")); // NOI18N
        jlaModuloAtividade.setName("jlaModuloAtividade"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaModuloAtividade);
        jlaModuloAtividade.setBounds(10, 270, 150, 17);

        jcbModuloAtividade.setFont(resourceMap.getFont("jcbModuloAtividade.font")); // NOI18N
        jcbModuloAtividade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbModuloAtividade.setName("jcbModuloAtividade"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jcbModuloAtividade);
        jcbModuloAtividade.setBounds(10, 290, 690, 25);
        jcbModuloAtividade.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbModuloAtividade.AccessibleContext.accessibleName")); // NOI18N

        jlaLocalAtendimento.setFont(resourceMap.getFont("jlaLocalAtendimento.font")); // NOI18N
        jlaLocalAtendimento.setText(resourceMap.getString("jlaLocalAtendimento.text")); // NOI18N
        jlaLocalAtendimento.setName("jlaLocalAtendimento"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaLocalAtendimento);
        jlaLocalAtendimento.setBounds(10, 320, 240, 17);

        jcbLocalAtendimento.setFont(resourceMap.getFont("jcbLocalAtendimento.font")); // NOI18N
        jcbLocalAtendimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbLocalAtendimento.setName("jcbLocalAtendimento"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jcbLocalAtendimento);
        jcbLocalAtendimento.setBounds(10, 340, 690, 25);
        jcbLocalAtendimento.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbLocalAtendimento.AccessibleContext.accessibleName")); // NOI18N

        jtpRegistros.setFont(resourceMap.getFont("jtpRegistros.font")); // NOI18N
        jtpRegistros.setName("jtpRegistros"); // NOI18N

        jpaDescricaoAtendimento.setName("jpaDescricaoAtendimento"); // NOI18N
        jpaDescricaoAtendimento.setLayout(null);

        jlaDescricao.setFont(resourceMap.getFont("jlaDescricao.font")); // NOI18N
        jlaDescricao.setText(resourceMap.getString("jlaDescricao.text")); // NOI18N
        jlaDescricao.setName("jlaDescricao"); // NOI18N
        jpaDescricaoAtendimento.add(jlaDescricao);
        jlaDescricao.setBounds(10, 10, 210, 17);

        jlaInterdisciplinar.setFont(resourceMap.getFont("jlaDescricao.font")); // NOI18N
        jlaInterdisciplinar.setText(resourceMap.getString("jlaInterdisciplinar.text")); // NOI18N
        jlaInterdisciplinar.setName("jlaInterdisciplinar"); // NOI18N
        jpaDescricaoAtendimento.add(jlaInterdisciplinar);
        jlaInterdisciplinar.setBounds(510, 10, 130, 17);

        jspDescricao.setName("jspDescricao"); // NOI18N

        jatDescricao.setColumns(20);
        jatDescricao.setFont(resourceMap.getFont("jatDescricao.font")); // NOI18N
        jatDescricao.setLineWrap(true);
        jatDescricao.setRows(5);
        jatDescricao.setWrapStyleWord(true);
        jatDescricao.setName("jatDescricao"); // NOI18N
        jatDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jatDescricaoKeyPressed(evt);
            }
        });
        jspDescricao.setViewportView(jatDescricao);
        jatDescricao.getAccessibleContext().setAccessibleName(resourceMap.getString("jatDescricao.AccessibleContext.accessibleName")); // NOI18N
        jatDescricao.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jatDescricao.AccessibleContext.accessibleDescription")); // NOI18N

        jpaDescricaoAtendimento.add(jspDescricao);
        jspDescricao.setBounds(10, 30, 490, 220);

        jspInterdisciplinar.setName("jspInterdisciplinar"); // NOI18N

        jatInterdisciplinar.setColumns(20);
        jatInterdisciplinar.setFont(resourceMap.getFont("jatInterdisciplinar.font")); // NOI18N
        jatInterdisciplinar.setLineWrap(true);
        jatInterdisciplinar.setRows(5);
        jatInterdisciplinar.setWrapStyleWord(true);
        jatInterdisciplinar.setName("jatInterdisciplinar"); // NOI18N
        jatInterdisciplinar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jatInterdisciplinarKeyPressed(evt);
            }
        });
        jspInterdisciplinar.setViewportView(jatInterdisciplinar);
        jatInterdisciplinar.getAccessibleContext().setAccessibleName(resourceMap.getString("jatInterdisciplinar.AccessibleContext.accessibleName")); // NOI18N
        jatInterdisciplinar.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jatInterdisciplinar.AccessibleContext.accessibleDescription")); // NOI18N

        jpaDescricaoAtendimento.add(jspInterdisciplinar);
        jspInterdisciplinar.setBounds(510, 30, 490, 220);

        jtpRegistros.addTab(resourceMap.getString("jpaDescricaoAtendimento.TabConstraints.tabTitle"), jpaDescricaoAtendimento); // NOI18N

        jpaProfissionais.setName("jpaProfissionais"); // NOI18N
        jpaProfissionais.setLayout(null);

        jlaProfissionais.setFont(resourceMap.getFont("jlaProfissionais.font")); // NOI18N
        jlaProfissionais.setText(resourceMap.getString("jlaProfissionais.text")); // NOI18N
        jlaProfissionais.setToolTipText(resourceMap.getString("jlaProfissionais.toolTipText")); // NOI18N
        jlaProfissionais.setName("jlaProfissionais"); // NOI18N
        jpaProfissionais.add(jlaProfissionais);
        jlaProfissionais.setBounds(10, 10, 180, 17);

        jspProfissionais.setName("jspProfissionais"); // NOI18N

        jtaProfissionais.setAutoCreateRowSorter(true);
        jtaProfissionais.setFont(resourceMap.getFont("jtaProfissionais.font")); // NOI18N
        jtaProfissionais.setModel(new ModeloTabelaAtendimentoProfissional());
        jtaProfissionais.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtaProfissionais.setName("jtaProfissionais"); // NOI18N
        jtaProfissionais.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtaProfissionais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaProfissionaisKeyPressed(evt);
            }
        });
        jspProfissionais.setViewportView(jtaProfissionais);
        jtaProfissionais.getAccessibleContext().setAccessibleName(resourceMap.getString("jtaProfissionais.AccessibleContext.accessibleName")); // NOI18N

        jpaProfissionais.add(jspProfissionais);
        jspProfissionais.setBounds(10, 30, 850, 220);

        jbuAdicionar.setFont(resourceMap.getFont("jbuAdicionar.font")); // NOI18N
        jbuAdicionar.setIcon(resourceMap.getIcon("jbuAdicionar.icon")); // NOI18N
        jbuAdicionar.setMnemonic('A');
        jbuAdicionar.setText(resourceMap.getString("jbuAdicionar.text")); // NOI18N
        jbuAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAdicionar.setName("jbuAdicionar"); // NOI18N
        jbuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarActionPerformed(evt);
            }
        });
        jpaProfissionais.add(jbuAdicionar);
        jbuAdicionar.setBounds(870, 30, 130, 33);
        jbuAdicionar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAdicionar.AccessibleContext.accessibleName")); // NOI18N

        jbuAlterar.setFont(resourceMap.getFont("jbuAlterar.font")); // NOI18N
        jbuAlterar.setIcon(resourceMap.getIcon("jbuAlterar.icon")); // NOI18N
        jbuAlterar.setMnemonic('e');
        jbuAlterar.setText(resourceMap.getString("jbuAlterar.text")); // NOI18N
        jbuAlterar.setToolTipText(resourceMap.getString("jbuAlterar.toolTipText")); // NOI18N
        jbuAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAlterar.setName("jbuAlterar"); // NOI18N
        jbuAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAlterarActionPerformed(evt);
            }
        });
        jpaProfissionais.add(jbuAlterar);
        jbuAlterar.setBounds(870, 70, 130, 33);
        jbuAlterar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAlterar.AccessibleContext.accessibleName")); // NOI18N

        jbuRemover.setFont(resourceMap.getFont("jbuRemover.font")); // NOI18N
        jbuRemover.setIcon(resourceMap.getIcon("jbuRemover.icon")); // NOI18N
        jbuRemover.setMnemonic('R');
        jbuRemover.setText(resourceMap.getString("jbuRemover.text")); // NOI18N
        jbuRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuRemover.setName("jbuRemover"); // NOI18N
        jbuRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverActionPerformed(evt);
            }
        });
        jpaProfissionais.add(jbuRemover);
        jbuRemover.setBounds(870, 110, 130, 33);
        jbuRemover.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuRemover.AccessibleContext.accessibleName")); // NOI18N

        jtpRegistros.addTab(resourceMap.getString("jpaProfissionais.TabConstraints.tabTitle"), jpaProfissionais); // NOI18N

        jpaFrequencia.setName("jpaFrequencia"); // NOI18N
        jpaFrequencia.setLayout(null);

        jlaFrequencia.setFont(resourceMap.getFont("jlaJustificativa.font")); // NOI18N
        jlaFrequencia.setText(resourceMap.getString("jlaFrequencia.text")); // NOI18N
        jlaFrequencia.setName("jlaFrequencia"); // NOI18N
        jpaFrequencia.add(jlaFrequencia);
        jlaFrequencia.setBounds(10, 10, 110, 17);

        jcbFrequencia.setFont(resourceMap.getFont("jcbFrequencia.font")); // NOI18N
        jcbFrequencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbFrequencia.setName("jcbFrequencia"); // NOI18N
        jpaFrequencia.add(jcbFrequencia);
        jcbFrequencia.setBounds(10, 30, 130, 25);
        jcbFrequencia.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbFrequencia.AccessibleContext.accessibleName")); // NOI18N

        jlaJustificativa.setFont(resourceMap.getFont("jlaJustificativa.font")); // NOI18N
        jlaJustificativa.setText(resourceMap.getString("jlaJustificativa.text")); // NOI18N
        jlaJustificativa.setName("jlaJustificativa"); // NOI18N
        jpaFrequencia.add(jlaJustificativa);
        jlaJustificativa.setBounds(10, 60, 150, 17);

        jspJustificativa.setName("jspJustificativa"); // NOI18N

        jatJustificativa.setFont(resourceMap.getFont("jatJustificativa.font")); // NOI18N
        jatJustificativa.setLineWrap(true);
        jatJustificativa.setRows(5);
        jatJustificativa.setWrapStyleWord(true);
        jatJustificativa.setName("jatJustificativa"); // NOI18N
        jatJustificativa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jatJustificativaKeyPressed(evt);
            }
        });
        jspJustificativa.setViewportView(jatJustificativa);

        jpaFrequencia.add(jspJustificativa);
        jspJustificativa.setBounds(10, 80, 990, 170);

        jtpRegistros.addTab(resourceMap.getString("jpaFrequencia.TabConstraints.tabTitle"), jpaFrequencia); // NOI18N

        jpaAcompanhante.setName("jpaAcompanhante"); // NOI18N

        jlaAcompanhante.setFont(resourceMap.getFont("jlaAcompanhante.font")); // NOI18N
        jlaAcompanhante.setText(resourceMap.getString("jlaAcompanhante.text")); // NOI18N
        jlaAcompanhante.setName("jlaAcompanhante"); // NOI18N

        jspAcompanhante.setName("jspAcompanhante"); // NOI18N

        jtaAcompanhante.setAutoCreateRowSorter(true);
        jtaAcompanhante.setFont(resourceMap.getFont("jtaAcompanhante.font")); // NOI18N
        jtaAcompanhante.setModel(new ModeloTabelaAtendimentoAcompanhante());
        jtaAcompanhante.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtaAcompanhante.setName("jtaAcompanhante"); // NOI18N
        jtaAcompanhante.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtaAcompanhante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaAcompanhanteKeyPressed(evt);
            }
        });
        jspAcompanhante.setViewportView(jtaAcompanhante);
        jtaAcompanhante.getAccessibleContext().setAccessibleName(resourceMap.getString("jtaAcompanhante.AccessibleContext.accessibleName")); // NOI18N

        jbuAdicionarAcompanhante.setFont(resourceMap.getFont("jbuAdicionarAcompanhante.font")); // NOI18N
        jbuAdicionarAcompanhante.setIcon(resourceMap.getIcon("jbuAdicionarAcompanhante.icon")); // NOI18N
        jbuAdicionarAcompanhante.setMnemonic('A');
        jbuAdicionarAcompanhante.setText(resourceMap.getString("jbuAdicionarAcompanhante.text")); // NOI18N
        jbuAdicionarAcompanhante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAdicionarAcompanhante.setName("jbuAdicionarAcompanhante"); // NOI18N
        jbuAdicionarAcompanhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarAcompanhanteActionPerformed(evt);
            }
        });

        jbuAlterarAcompanhante.setFont(resourceMap.getFont("jbuAlterarAcompanhante.font")); // NOI18N
        jbuAlterarAcompanhante.setIcon(resourceMap.getIcon("jbuAlterarAcompanhante.icon")); // NOI18N
        jbuAlterarAcompanhante.setMnemonic('e');
        jbuAlterarAcompanhante.setText(resourceMap.getString("jbuAlterarAcompanhante.text")); // NOI18N
        jbuAlterarAcompanhante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuAlterarAcompanhante.setName("jbuAlterarAcompanhante"); // NOI18N
        jbuAlterarAcompanhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAlterarAcompanhanteActionPerformed(evt);
            }
        });

        jbuRemoverAcompanhante.setFont(resourceMap.getFont("jbuRemoverAcompanhante.font")); // NOI18N
        jbuRemoverAcompanhante.setIcon(resourceMap.getIcon("jbuRemoverAcompanhante.icon")); // NOI18N
        jbuRemoverAcompanhante.setMnemonic('r');
        jbuRemoverAcompanhante.setText(resourceMap.getString("jbuRemoverAcompanhante.text")); // NOI18N
        jbuRemoverAcompanhante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuRemoverAcompanhante.setName("jbuRemoverAcompanhante"); // NOI18N
        jbuRemoverAcompanhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverAcompanhanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaAcompanhanteLayout = new javax.swing.GroupLayout(jpaAcompanhante);
        jpaAcompanhante.setLayout(jpaAcompanhanteLayout);
        jpaAcompanhanteLayout.setHorizontalGroup(
            jpaAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaAcompanhanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaAcompanhanteLayout.createSequentialGroup()
                        .addComponent(jlaAcompanhante)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpaAcompanhanteLayout.createSequentialGroup()
                        .addComponent(jspAcompanhante, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpaAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbuAlterarAcompanhante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuRemoverAcompanhante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuAdicionarAcompanhante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpaAcompanhanteLayout.setVerticalGroup(
            jpaAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaAcompanhanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlaAcompanhante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpaAcompanhanteLayout.createSequentialGroup()
                        .addComponent(jbuAdicionarAcompanhante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuAlterarAcompanhante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuRemoverAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbuAdicionarAcompanhante.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAdicionarAcompanhante.AccessibleContext.accessibleName")); // NOI18N
        jbuAlterarAcompanhante.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAlterarAcompanhante.AccessibleContext.accessibleName")); // NOI18N
        jbuRemoverAcompanhante.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuRemoverAcompanhante.AccessibleContext.accessibleName")); // NOI18N
        jbuRemoverAcompanhante.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jbuRemoverAcompanhante.AccessibleContext.accessibleDescription")); // NOI18N

        jtpRegistros.addTab(resourceMap.getString("jpaAcompanhante.TabConstraints.tabTitle"), jpaAcompanhante); // NOI18N

        jpaArquivos.setFont(resourceMap.getFont("jpaArquivos.font")); // NOI18N
        jpaArquivos.setName("jpaArquivos"); // NOI18N

        jspArquivos.setName("jspArquivos"); // NOI18N

        jliArquivos.setFont(resourceMap.getFont("jliArquivos.font")); // NOI18N
        jliArquivos.setModel(new DefaultListModel());
        jliArquivos.setName("jliArquivos"); // NOI18N
        jspArquivos.setViewportView(jliArquivos);
        jliArquivos.getAccessibleContext().setAccessibleName(resourceMap.getString("jliArquivos.AccessibleContext.accessibleName")); // NOI18N

        jlaArquivos.setFont(resourceMap.getFont("jlaArquivos.font")); // NOI18N
        jlaArquivos.setText(resourceMap.getString("jlaArquivos.text")); // NOI18N
        jlaArquivos.setName("jlaArquivos"); // NOI18N

        jbuAdicionarArquivo.setFont(resourceMap.getFont("jbuAdicionarArquivo.font")); // NOI18N
        jbuAdicionarArquivo.setIcon(resourceMap.getIcon("jbuAdicionarArquivo.icon")); // NOI18N
        jbuAdicionarArquivo.setMnemonic('d');
        jbuAdicionarArquivo.setText(resourceMap.getString("jbuAdicionarArquivo.text")); // NOI18N
        jbuAdicionarArquivo.setToolTipText(resourceMap.getString("jbuAdicionarArquivo.toolTipText")); // NOI18N
        jbuAdicionarArquivo.setName("jbuAdicionarArquivo"); // NOI18N
        jbuAdicionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarArquivoActionPerformed(evt);
            }
        });

        jbuAbrirAquivo.setFont(resourceMap.getFont("jbuAbrirAquivo.font")); // NOI18N
        jbuAbrirAquivo.setIcon(resourceMap.getIcon("jbuAbrirAquivo.icon")); // NOI18N
        jbuAbrirAquivo.setMnemonic('A');
        jbuAbrirAquivo.setText(resourceMap.getString("jbuAbrirAquivo.text")); // NOI18N
        jbuAbrirAquivo.setName("jbuAbrirAquivo"); // NOI18N
        jbuAbrirAquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAbrirAquivoActionPerformed(evt);
            }
        });

        jbuRemoverArquivo.setFont(resourceMap.getFont("jbuRemoverArquivo.font")); // NOI18N
        jbuRemoverArquivo.setIcon(resourceMap.getIcon("jbuRemoverArquivo.icon")); // NOI18N
        jbuRemoverArquivo.setMnemonic('R');
        jbuRemoverArquivo.setText(resourceMap.getString("jbuRemoverArquivo.text")); // NOI18N
        jbuRemoverArquivo.setName("jbuRemoverArquivo"); // NOI18N
        jbuRemoverArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaArquivosLayout = new javax.swing.GroupLayout(jpaArquivos);
        jpaArquivos.setLayout(jpaArquivosLayout);
        jpaArquivosLayout.setHorizontalGroup(
            jpaArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaArquivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlaArquivos)
                    .addGroup(jpaArquivosLayout.createSequentialGroup()
                        .addComponent(jspArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpaArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbuAdicionarArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuAbrirAquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuRemoverArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(474, Short.MAX_VALUE))
        );
        jpaArquivosLayout.setVerticalGroup(
            jpaArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaArquivosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlaArquivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaArquivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpaArquivosLayout.createSequentialGroup()
                        .addComponent(jbuAbrirAquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuAdicionarArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuRemoverArquivo)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jbuAdicionarArquivo.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAdicionarArquivo.AccessibleContext.accessibleName")); // NOI18N
        jbuAbrirAquivo.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuAbrirAquivo.AccessibleContext.accessibleName")); // NOI18N
        jbuRemoverArquivo.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuRemoverArquivo.AccessibleContext.accessibleName")); // NOI18N

        jtpRegistros.addTab(resourceMap.getString("jpaArquivos.TabConstraints.tabTitle"), jpaArquivos); // NOI18N

        jpaEditarAtendimentoIndividual.add(jtpRegistros);
        jtpRegistros.setBounds(9, 370, 1010, 290);

        jbuSalvar.setFont(resourceMap.getFont("jbuSalvar.font")); // NOI18N
        jbuSalvar.setIcon(resourceMap.getIcon("jbuSalvar.icon")); // NOI18N
        jbuSalvar.setMnemonic('S');
        jbuSalvar.setText(resourceMap.getString("jbuSalvar.text")); // NOI18N
        jbuSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSalvar.setName("jbuSalvar"); // NOI18N
        jbuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuSalvarActionPerformed(evt);
            }
        });
        jpaEditarAtendimentoIndividual.add(jbuSalvar);
        jbuSalvar.setBounds(10, 670, 120, 33);
        jbuSalvar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuSalvar.AccessibleContext.accessibleName")); // NOI18N

        jbuFechar.setFont(resourceMap.getFont("jbuFechar.font")); // NOI18N
        jbuFechar.setIcon(resourceMap.getIcon("jbuFechar.icon")); // NOI18N
        jbuFechar.setMnemonic('F');
        jbuFechar.setText(resourceMap.getString("jbuFechar.text")); // NOI18N
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });
        jpaEditarAtendimentoIndividual.add(jbuFechar);
        jbuFechar.setBounds(900, 670, 120, 33);
        jbuFechar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuFechar.AccessibleContext.accessibleName")); // NOI18N

        jlaParticipacao.setFont(resourceMap.getFont("jlaParticipacao.font")); // NOI18N
        jlaParticipacao.setText(resourceMap.getString("jlaParticipacao.text")); // NOI18N
        jlaParticipacao.setToolTipText(resourceMap.getString("jlaParticipacao.toolTipText")); // NOI18N
        jlaParticipacao.setName("jlaParticipacao"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaParticipacao);
        jlaParticipacao.setBounds(710, 320, 160, 17);

        jcbParticipacao.setFont(resourceMap.getFont("jcbParticipacao.font")); // NOI18N
        jcbParticipacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbParticipacao.setName("jcbParticipacao"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jcbParticipacao);
        jcbParticipacao.setBounds(710, 340, 310, 25);
        jcbParticipacao.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbParticipacao.AccessibleContext.accessibleName")); // NOI18N

        jlaPrimeiraVez.setFont(resourceMap.getFont("jlaPrimeiraVez.font")); // NOI18N
        jlaPrimeiraVez.setText(resourceMap.getString("jlaPrimeiraVez.text")); // NOI18N
        jlaPrimeiraVez.setName("jlaPrimeiraVez"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jlaPrimeiraVez);
        jlaPrimeiraVez.setBounds(710, 270, 190, 17);

        jcbPrimeiraVez.setFont(resourceMap.getFont("jcbPrimeiraVez.font")); // NOI18N
        jcbPrimeiraVez.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jcbPrimeiraVez.setName("jcbPrimeiraVez"); // NOI18N
        jpaEditarAtendimentoIndividual.add(jcbPrimeiraVez);
        jcbPrimeiraVez.setBounds(710, 290, 170, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarAtendimentoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarAtendimentoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoAtendimentoActionPerformed
        controlador.inicializarDescricaoTipoAtendimento();
}//GEN-LAST:event_jcbTipoAtendimentoActionPerformed

    private void jcbDescricaoTipoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDescricaoTipoAtendimentoActionPerformed
        controlador.inicializarModuloAtividadeESetor();
}//GEN-LAST:event_jcbDescricaoTipoAtendimentoActionPerformed

    private void jbuFecharTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharTituloActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharTituloActionPerformed

    private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
        controlador.fecharTela();
    }//GEN-LAST:event_jbuFecharActionPerformed

    private void jbuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSalvarActionPerformed
        controlador.salvar();
    }//GEN-LAST:event_jbuSalvarActionPerformed

    private void jbuUtilizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuUtilizarUsuarioActionPerformed
        controlador.abrirTelaUtilizarUsuario();
    }//GEN-LAST:event_jbuUtilizarUsuarioActionPerformed

    private void jbuUtilizarPreCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuUtilizarPreCadastroActionPerformed
        controlador.abrirTelaUtilizarPreCadastro();
    }//GEN-LAST:event_jbuUtilizarPreCadastroActionPerformed

    private void jbuSelecionarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuSelecionarDataActionPerformed
        JOptionPanePersonalizado.mostrarTelaSelecionarData(this, jftData);
    }//GEN-LAST:event_jbuSelecionarDataActionPerformed

    private void jbuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarActionPerformed
        controlador.adicionarDetalheProfissional();
    }//GEN-LAST:event_jbuAdicionarActionPerformed

    private void jbuAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAlterarActionPerformed
        controlador.editarAtendimentoProfissional();
    }//GEN-LAST:event_jbuAlterarActionPerformed

    private void jbuRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverActionPerformed
        controlador.removerAtendimentoProfissionalSelecionado();
    }//GEN-LAST:event_jbuRemoverActionPerformed

    private void jtaProfissionaisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaProfissionaisKeyPressed
        controlador.moverFocoOuAbrirTelaDeAlteracaoProfissional(evt);
    }//GEN-LAST:event_jtaProfissionaisKeyPressed

    private void jftProntuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftProntuarioFocusLost
        controlador.selecionarProntuario();
    }//GEN-LAST:event_jftProntuarioFocusLost

    private void jbuAdicionarAcompanhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarAcompanhanteActionPerformed
        controlador.adicionarAcompanhante();
    }//GEN-LAST:event_jbuAdicionarAcompanhanteActionPerformed

    private void jbuAlterarAcompanhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAlterarAcompanhanteActionPerformed
        controlador.editarAcompanhanteSelecionado();
    }//GEN-LAST:event_jbuAlterarAcompanhanteActionPerformed

    private void jbuRemoverAcompanhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverAcompanhanteActionPerformed
        controlador.removerAcompanhanteSelecionado();
    }//GEN-LAST:event_jbuRemoverAcompanhanteActionPerformed

    private void jtaAcompanhanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaAcompanhanteKeyPressed
        controlador.moverFocoOuAbrirTelaDeAlteracaoComunidade(evt);
    }//GEN-LAST:event_jtaAcompanhanteKeyPressed

    private void jatDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jatDescricaoKeyPressed
        WordUtils.abrirWord(evt, jatDescricao);
    }//GEN-LAST:event_jatDescricaoKeyPressed

    private void jatInterdisciplinarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jatInterdisciplinarKeyPressed
        WordUtils.abrirWord(evt, jatInterdisciplinar);
    }//GEN-LAST:event_jatInterdisciplinarKeyPressed

    private void jatJustificativaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jatJustificativaKeyPressed
        WordUtils.abrirWord(evt, jatJustificativa);
    }//GEN-LAST:event_jatJustificativaKeyPressed

    private void jbuAdicionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarArquivoActionPerformed
        controlador.adicionarArquivo();
    }//GEN-LAST:event_jbuAdicionarArquivoActionPerformed

    private void jbuAbrirAquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAbrirAquivoActionPerformed
        controlador.abrirArquivo();
    }//GEN-LAST:event_jbuAbrirAquivoActionPerformed

    private void jbuRemoverArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverArquivoActionPerformed
        controlador.removerArquivoSelecionado();
    }//GEN-LAST:event_jbuRemoverArquivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jalTitulo;
    private javax.swing.JTextArea jatDescricao;
    private javax.swing.JTextArea jatInterdisciplinar;
    private javax.swing.JTextArea jatJustificativa;
    private javax.swing.JButton jbuAbrirAquivo;
    private javax.swing.JButton jbuAdicionar;
    private javax.swing.JButton jbuAdicionarAcompanhante;
    private javax.swing.JButton jbuAdicionarArquivo;
    private javax.swing.JButton jbuAlterar;
    private javax.swing.JButton jbuAlterarAcompanhante;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuFecharTitulo;
    private javax.swing.JButton jbuRemover;
    private javax.swing.JButton jbuRemoverAcompanhante;
    private javax.swing.JButton jbuRemoverArquivo;
    private javax.swing.JButton jbuSalvar;
    private javax.swing.JButton jbuSelecionarData;
    private javax.swing.JButton jbuUtilizarPreCadastro;
    private javax.swing.JButton jbuUtilizarUsuario;
    protected javax.swing.JComboBox jcbDescricaoTipoAtendimento;
    protected javax.swing.JComboBox jcbFrequencia;
    protected javax.swing.JComboBox jcbLocalAtendimento;
    protected javax.swing.JComboBox jcbModuloAtividade;
    private javax.swing.JComboBox jcbParticipacao;
    private javax.swing.JComboBox jcbPrimeiraVez;
    protected javax.swing.JComboBox jcbSetor;
    protected javax.swing.JComboBox jcbTipoAtendimento;
    private javax.swing.JFormattedTextField jftData;
    private javax.swing.JFormattedTextField jftHoraInicio;
    private javax.swing.JFormattedTextField jftHoraTermino;
    private javax.swing.JFormattedTextField jftProntuario;
    private javax.swing.JLabel jlaAcompanhante;
    private javax.swing.JLabel jlaArquivos;
    private javax.swing.JLabel jlaData;
    private javax.swing.JLabel jlaDescricao;
    private javax.swing.JLabel jlaDescricaoTipoAtendimento;
    private javax.swing.JLabel jlaFrequencia;
    private javax.swing.JLabel jlaHoraInicio;
    private javax.swing.JLabel jlaHoraTermino;
    private javax.swing.JLabel jlaInterdisciplinar;
    private javax.swing.JLabel jlaJustificativa;
    private javax.swing.JLabel jlaLocalAtendimento;
    private javax.swing.JLabel jlaModuloAtividade;
    private javax.swing.JLabel jlaNomePreCadastro;
    private javax.swing.JLabel jlaNomeUsuario;
    private javax.swing.JLabel jlaParticipacao;
    private javax.swing.JLabel jlaPrimeiraVez;
    private javax.swing.JLabel jlaProfissionais;
    private javax.swing.JLabel jlaProntuario;
    private javax.swing.JLabel jlaSetor;
    private javax.swing.JLabel jlaTipoAtendimento;
    private javax.swing.JList jliArquivos;
    private javax.swing.JPanel jpaAcompanhante;
    private javax.swing.JPanel jpaArquivos;
    private javax.swing.JPanel jpaDataHora;
    private javax.swing.JPanel jpaDescricaoAtendimento;
    private javax.swing.JPanel jpaEditarAtendimentoIndividual;
    private javax.swing.JPanel jpaFrequencia;
    private javax.swing.JPanel jpaPreCadastro;
    private javax.swing.JPanel jpaProfissionais;
    private javax.swing.JPanel jpaTitulo;
    private javax.swing.JPanel jpaUsuario;
    private javax.swing.JScrollPane jspAcompanhante;
    private javax.swing.JScrollPane jspArquivos;
    private javax.swing.JScrollPane jspDescricao;
    private javax.swing.JScrollPane jspInterdisciplinar;
    private javax.swing.JScrollPane jspJustificativa;
    private javax.swing.JScrollPane jspProfissionais;
    private javax.swing.JTable jtaAcompanhante;
    private javax.swing.JTable jtaProfissionais;
    private javax.swing.JTextField jtfNomePreCadastro;
    private javax.swing.JTextField jtfNomeUsuario;
    private javax.swing.JTabbedPane jtpIntegrante;
    private javax.swing.JTabbedPane jtpRegistros;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaAtendimentoIndividualEditar controlador;
}
