package br.laramara.ti.sislaraclient.telas;

import javax.swing.JFrame;

public class TelaEditarCursosEntrevistaInicial extends javax.swing.JDialog {

    /** Creates new form TelaEditarCursosEntrevistaInicial */
    public TelaEditarCursosEntrevistaInicial(JFrame parent) {
        super(parent, true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaEditarCursoEntrevistaInicial = new javax.swing.JPanel();
        jpaTitulo = new javax.swing.JPanel();
        jlaTitulo = new javax.swing.JLabel();
        jbuFecharTitulo = new javax.swing.JButton();
        jchParticipaAtividadeOutroLugar = new javax.swing.JCheckBox();
        jlaCurso = new javax.swing.JLabel();
        jcbCurso = new javax.swing.JComboBox();
        jlaNivel = new javax.swing.JLabel();
        jcbNivel = new javax.swing.JComboBox();
        jlaLocal = new javax.swing.JLabel();
        jtfLocal = new javax.swing.JTextField();
        jlaConteudo = new javax.swing.JLabel();
        jtfConteudo = new javax.swing.JTextField();
        jlaDataCurso = new javax.swing.JLabel();
        jftDataCurso = new javax.swing.JFormattedTextField();
        jbuSelecionarDataCurso = new javax.swing.JButton();
        jlaHorario = new javax.swing.JLabel();
        jftHorario = new javax.swing.JFormattedTextField();
        jlaCargaHoraria = new javax.swing.JLabel();
        jftCargaHoraria = new javax.swing.JFormattedTextField();
        jlaHoras = new javax.swing.JLabel();
        jlaObservacoes = new javax.swing.JLabel();
        jspObservacoes = new javax.swing.JScrollPane();
        jepObservacoes = new javax.swing.JEditorPane();
        jbuSalvar = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(br.laramara.ti.sislaraclient.telas.SisLaraClient.class).getContext().getResourceMap(TelaEditarCursosEntrevistaInicial.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jpaEditarCursoEntrevistaInicial.setName("jpaEditarCursoEntrevistaInicial"); // NOI18N
        jpaEditarCursoEntrevistaInicial.setLayout(null);

        jpaTitulo.setBackground(resourceMap.getColor("jpaTitulo.background")); // NOI18N
        jpaTitulo.setName("jpaTitulo"); // NOI18N

        jlaTitulo.setFont(resourceMap.getFont("jlaTitulo.font")); // NOI18N
        jlaTitulo.setForeground(resourceMap.getColor("jlaTitulo.foreground")); // NOI18N
        jlaTitulo.setText(resourceMap.getString("jlaTitulo.text")); // NOI18N
        jlaTitulo.setName("jlaTitulo"); // NOI18N

        jbuFecharTitulo.setBackground(resourceMap.getColor("jbuFecharTitulo.background")); // NOI18N
        jbuFecharTitulo.setIcon(resourceMap.getIcon("jbuFecharTitulo.icon")); // NOI18N
        jbuFecharTitulo.setText(resourceMap.getString("jbuFecharTitulo.text")); // NOI18N
        jbuFecharTitulo.setBorder(null);
        jbuFecharTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFecharTitulo.setName("jbuFecharTitulo"); // NOI18N
        jbuFecharTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharTituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaTituloLayout = new javax.swing.GroupLayout(jpaTitulo);
        jpaTitulo.setLayout(jpaTituloLayout);
        jpaTituloLayout.setHorizontalGroup(
            jpaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 774, Short.MAX_VALUE)
                .addComponent(jbuFecharTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpaTituloLayout.setVerticalGroup(
            jpaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlaTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbuFecharTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpaEditarCursoEntrevistaInicial.add(jpaTitulo);
        jpaTitulo.setBounds(0, 0, 1024, 26);

        jchParticipaAtividadeOutroLugar.setFont(resourceMap.getFont("jchParticipaAtividadeOutroLugar.font")); // NOI18N
        jchParticipaAtividadeOutroLugar.setText(resourceMap.getString("jchParticipaAtividadeOutroLugar.text")); // NOI18N
        jchParticipaAtividadeOutroLugar.setName("jchParticipaAtividadeOutroLugar"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jchParticipaAtividadeOutroLugar);
        jchParticipaAtividadeOutroLugar.setBounds(10, 40, 320, 25);

        jlaCurso.setFont(resourceMap.getFont("jlaHorario.font")); // NOI18N
        jlaCurso.setText(resourceMap.getString("jlaCurso.text")); // NOI18N
        jlaCurso.setName("jlaCurso"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jlaCurso);
        jlaCurso.setBounds(10, 70, 50, 17);

        jcbCurso.setFont(resourceMap.getFont("jcbNivel.font")); // NOI18N
        jcbCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Artes Plasticas", "Massoterapia", "Informática" }));
        jcbCurso.setName("jcbCurso"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jcbCurso);
        jcbCurso.setBounds(10, 90, 170, 25);
        jcbCurso.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbCurso.AccessibleContext.accessibleName")); // NOI18N

        jlaNivel.setFont(resourceMap.getFont("jlaHorario.font")); // NOI18N
        jlaNivel.setText(resourceMap.getString("jlaNivel.text")); // NOI18N
        jlaNivel.setName("jlaNivel"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jlaNivel);
        jlaNivel.setBounds(190, 70, 36, 17);

        jcbNivel.setFont(resourceMap.getFont("jcbNivel.font")); // NOI18N
        jcbNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não Informado" }));
        jcbNivel.setName("jcbNivel"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jcbNivel);
        jcbNivel.setBounds(190, 90, 140, 25);
        jcbNivel.getAccessibleContext().setAccessibleName(resourceMap.getString("jcbNivel.AccessibleContext.accessibleName")); // NOI18N

        jlaLocal.setFont(resourceMap.getFont("jlaHorario.font")); // NOI18N
        jlaLocal.setText(resourceMap.getString("jlaLocal.text")); // NOI18N
        jlaLocal.setName("jlaLocal"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jlaLocal);
        jlaLocal.setBounds(10, 120, 90, 17);

        jtfLocal.setFont(resourceMap.getFont("jtfConteudo.font")); // NOI18N
        jtfLocal.setText(resourceMap.getString("jtfLocal.text")); // NOI18N
        jtfLocal.setName("jtfLocal"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jtfLocal);
        jtfLocal.setBounds(10, 140, 320, 23);
        jtfLocal.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfLocal.AccessibleContext.accessibleName")); // NOI18N

        jlaConteudo.setFont(resourceMap.getFont("jlaHorario.font")); // NOI18N
        jlaConteudo.setText(resourceMap.getString("jlaConteudo.text")); // NOI18N
        jlaConteudo.setName("jlaConteudo"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jlaConteudo);
        jlaConteudo.setBounds(10, 170, 110, 17);

        jtfConteudo.setFont(resourceMap.getFont("jtfConteudo.font")); // NOI18N
        jtfConteudo.setText(resourceMap.getString("jtfConteudo.text")); // NOI18N
        jtfConteudo.setName("jtfConteudo"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jtfConteudo);
        jtfConteudo.setBounds(10, 190, 320, 23);
        jtfConteudo.getAccessibleContext().setAccessibleName(resourceMap.getString("jtfConteudo.AccessibleContext.accessibleName")); // NOI18N

        jlaDataCurso.setFont(resourceMap.getFont("jlaHorario.font")); // NOI18N
        jlaDataCurso.setText(resourceMap.getString("jlaDataCurso.text")); // NOI18N
        jlaDataCurso.setName("jlaDataCurso"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jlaDataCurso);
        jlaDataCurso.setBounds(10, 220, 120, 17);

        try {
            jftDataCurso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataCurso.setFont(resourceMap.getFont("jftDataCurso.font")); // NOI18N
        jftDataCurso.setName("jftDataCurso"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jftDataCurso);
        jftDataCurso.setBounds(10, 240, 100, 23);
        jftDataCurso.getAccessibleContext().setAccessibleName(resourceMap.getString("jftDataCurso.AccessibleContext.accessibleName")); // NOI18N

        jbuSelecionarDataCurso.setIcon(resourceMap.getIcon("jbuSelecionarDataCurso.icon")); // NOI18N
        jbuSelecionarDataCurso.setText(resourceMap.getString("jbuSelecionarDataCurso.text")); // NOI18N
        jbuSelecionarDataCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSelecionarDataCurso.setName("jbuSelecionarDataCurso"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jbuSelecionarDataCurso);
        jbuSelecionarDataCurso.setBounds(113, 240, 25, 25);
        jbuSelecionarDataCurso.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuSelecionarDataCurso.AccessibleContext.accessibleName")); // NOI18N
        jbuSelecionarDataCurso.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jbuSelecionarDataCurso.AccessibleContext.accessibleDescription")); // NOI18N

        jlaHorario.setFont(resourceMap.getFont("jlaHorario.font")); // NOI18N
        jlaHorario.setText(resourceMap.getString("jlaHorario.text")); // NOI18N
        jlaHorario.setName("jlaHorario"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jlaHorario);
        jlaHorario.setBounds(150, 220, 60, 17);

        try {
            jftHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftHorario.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftHorario.setFont(resourceMap.getFont("jftDataCurso.font")); // NOI18N
        jftHorario.setName("jftHorario"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jftHorario);
        jftHorario.setBounds(150, 240, 60, 23);
        jftHorario.getAccessibleContext().setAccessibleName(resourceMap.getString("jftHorario.AccessibleContext.accessibleName")); // NOI18N

        jlaCargaHoraria.setFont(resourceMap.getFont("jlaHorario.font")); // NOI18N
        jlaCargaHoraria.setText(resourceMap.getString("jlaCargaHoraria.text")); // NOI18N
        jlaCargaHoraria.setName("jlaCargaHoraria"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jlaCargaHoraria);
        jlaCargaHoraria.setBounds(220, 220, 43, 17);

        try {
            jftCargaHoraria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCargaHoraria.setText(resourceMap.getString("jftCargaHoraria.text")); // NOI18N
        jftCargaHoraria.setFont(resourceMap.getFont("jftDataCurso.font")); // NOI18N
        jftCargaHoraria.setName("jftCargaHoraria"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jftCargaHoraria);
        jftCargaHoraria.setBounds(220, 240, 50, 23);
        jftCargaHoraria.getAccessibleContext().setAccessibleName(resourceMap.getString("jftCargaHoraria.AccessibleContext.accessibleName")); // NOI18N

        jlaHoras.setFont(resourceMap.getFont("jlaHoras.font")); // NOI18N
        jlaHoras.setText(resourceMap.getString("jlaHoras.text")); // NOI18N
        jlaHoras.setName("jlaHoras"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jlaHoras);
        jlaHoras.setBounds(275, 245, 60, 17);

        jlaObservacoes.setFont(resourceMap.getFont("jlaHorario.font")); // NOI18N
        jlaObservacoes.setText(resourceMap.getString("jlaObservacoes.text")); // NOI18N
        jlaObservacoes.setName("jlaObservacoes"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jlaObservacoes);
        jlaObservacoes.setBounds(10, 270, 100, 17);

        jspObservacoes.setName("jspObservacoes"); // NOI18N

        jepObservacoes.setFont(resourceMap.getFont("jepObservacoes.font")); // NOI18N
        jepObservacoes.setName("jepObservacoes"); // NOI18N
        jspObservacoes.setViewportView(jepObservacoes);
        jepObservacoes.getAccessibleContext().setAccessibleName(resourceMap.getString("jepObservacoes.AccessibleContext.accessibleName")); // NOI18N

        jpaEditarCursoEntrevistaInicial.add(jspObservacoes);
        jspObservacoes.setBounds(10, 290, 320, 200);

        jbuSalvar.setFont(resourceMap.getFont("jbuSalvar.font")); // NOI18N
        jbuSalvar.setIcon(resourceMap.getIcon("jbuSalvar.icon")); // NOI18N
        jbuSalvar.setMnemonic('s');
        jbuSalvar.setText(resourceMap.getString("jbuSalvar.text")); // NOI18N
        jbuSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuSalvar.setName("jbuSalvar"); // NOI18N
        jpaEditarCursoEntrevistaInicial.add(jbuSalvar);
        jbuSalvar.setBounds(10, 670, 120, 33);
        jbuSalvar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuSalvar.AccessibleContext.accessibleName")); // NOI18N

        jbuFechar.setFont(resourceMap.getFont("jbuSalvar.font")); // NOI18N
        jbuFechar.setIcon(resourceMap.getIcon("jbuFechar.icon")); // NOI18N
        jbuFechar.setMnemonic('f');
        jbuFechar.setText(resourceMap.getString("jbuFechar.text")); // NOI18N
        jbuFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });
        jpaEditarCursoEntrevistaInicial.add(jbuFechar);
        jbuFechar.setBounds(900, 670, 113, 33);
        jbuFechar.getAccessibleContext().setAccessibleName(resourceMap.getString("jbuFechar.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarCursoEntrevistaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaEditarCursoEntrevistaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbuFecharTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharTituloActionPerformed
    
}//GEN-LAST:event_jbuFecharTituloActionPerformed

private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
    
}//GEN-LAST:event_jbuFecharActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuFecharTitulo;
    private javax.swing.JButton jbuSalvar;
    private javax.swing.JButton jbuSelecionarDataCurso;
    private javax.swing.JComboBox jcbCurso;
    private javax.swing.JComboBox jcbNivel;
    private javax.swing.JCheckBox jchParticipaAtividadeOutroLugar;
    private javax.swing.JEditorPane jepObservacoes;
    private javax.swing.JFormattedTextField jftCargaHoraria;
    private javax.swing.JFormattedTextField jftDataCurso;
    private javax.swing.JFormattedTextField jftHorario;
    private javax.swing.JLabel jlaCargaHoraria;
    private javax.swing.JLabel jlaConteudo;
    private javax.swing.JLabel jlaCurso;
    private javax.swing.JLabel jlaDataCurso;
    private javax.swing.JLabel jlaHorario;
    private javax.swing.JLabel jlaHoras;
    private javax.swing.JLabel jlaLocal;
    private javax.swing.JLabel jlaNivel;
    private javax.swing.JLabel jlaObservacoes;
    private javax.swing.JLabel jlaTitulo;
    private javax.swing.JPanel jpaEditarCursoEntrevistaInicial;
    private javax.swing.JPanel jpaTitulo;
    private javax.swing.JScrollPane jspObservacoes;
    private javax.swing.JTextField jtfConteudo;
    private javax.swing.JTextField jtfLocal;
    // End of variables declaration//GEN-END:variables
}
