package br.laramara.ti.sislaraclient.telas;

import br.laramara.ti.sislaraclient.controladores.ControladorTelaMailing;
import br.laramara.ti.sislaraclient.utilitarios.JOptionPanePersonalizado;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

public class TelaMailing extends javax.swing.JDialog {

    /**
     * Creates new form TelaMailing
     */
    public TelaMailing(JFrame parent) {
        super(parent);
        initComponents();
        setLocationRelativeTo(parent);
        controladorTelaMailing = new ControladorTelaMailing(this, jftDataInicio, jftDataTermino, jbuCategoriasAAdicionar, jliCategorias);
        controladorTelaMailing.abrirTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaTelaMailing = new javax.swing.JPanel();
        jlaDataInicio = new javax.swing.JLabel();
        jftDataInicio = new javax.swing.JFormattedTextField();
        jbuDataInicio = new javax.swing.JButton();
        jlaDataTermino = new javax.swing.JLabel();
        jftDataTermino = new javax.swing.JFormattedTextField();
        jbuDataTermino = new javax.swing.JButton();
        jlaCategirioasAAdicionar = new javax.swing.JLabel();
        jbuCategoriasAAdicionar = new javax.swing.JComboBox<>();
        jlaCategorias = new javax.swing.JLabel();
        jspCategorias = new javax.swing.JScrollPane();
        jliCategorias = new javax.swing.JList<>();
        jbuAdicionarCategoria = new javax.swing.JButton();
        jbuRemoverCategoria = new javax.swing.JButton();
        jbuAbrir = new javax.swing.JButton();
        jbuFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mailing");
        setModal(true);
        setResizable(false);

        jpaTelaMailing.setName("jpaTelaMailing"); // NOI18N

        jlaDataInicio.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaDataInicio.setText("Data Incício");
        jlaDataInicio.setName("jlaDataInicio"); // NOI18N

        try {
            jftDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataInicio.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftDataInicio.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jftDataInicio.setName("jftDataInicio"); // NOI18N

        jbuDataInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Calendario.png"))); // NOI18N
        jbuDataInicio.setToolTipText("");
        jbuDataInicio.setBorder(null);
        jbuDataInicio.setName("jbuDataInicio"); // NOI18N
        jbuDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuDataInicioActionPerformed(evt);
            }
        });

        jlaDataTermino.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaDataTermino.setText("Data Término");
        jlaDataTermino.setName("jlaDataTermino"); // NOI18N

        try {
            jftDataTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataTermino.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jftDataTermino.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jftDataTermino.setName("jftDataTermino"); // NOI18N

        jbuDataTermino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Calendario.png"))); // NOI18N
        jbuDataTermino.setToolTipText("");
        jbuDataTermino.setBorder(null);
        jbuDataTermino.setName("jbuDataTermino"); // NOI18N
        jbuDataTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuDataTerminoActionPerformed(evt);
            }
        });

        jlaCategirioasAAdicionar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaCategirioasAAdicionar.setText("Categoria a adicionar");
        jlaCategirioasAAdicionar.setName("jlaCategirioasAAdicionar"); // NOI18N

        jbuCategoriasAAdicionar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuCategoriasAAdicionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jbuCategoriasAAdicionar.setName("jbuCategoriasAAdicionar"); // NOI18N

        jlaCategorias.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jlaCategorias.setText("Categorias adicionadas");
        jlaCategorias.setName("jlaCategorias"); // NOI18N

        jspCategorias.setName("jspCategorias"); // NOI18N

        jliCategorias.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jliCategorias.setModel(new DefaultListModel());
        jliCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jliCategorias.setName("jliCategorias"); // NOI18N
        jspCategorias.setViewportView(jliCategorias);

        jbuAdicionarCategoria.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuAdicionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Adicionar.png"))); // NOI18N
        jbuAdicionarCategoria.setText("Adicionar");
        jbuAdicionarCategoria.setName("jbuAdicionarCategoria"); // NOI18N
        jbuAdicionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAdicionarCategoriaActionPerformed(evt);
            }
        });

        jbuRemoverCategoria.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuRemoverCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Remover.png"))); // NOI18N
        jbuRemoverCategoria.setText("Remover");
        jbuRemoverCategoria.setName("jbuRemoverCategoria"); // NOI18N
        jbuRemoverCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRemoverCategoriaActionPerformed(evt);
            }
        });

        jbuAbrir.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Yes.png"))); // NOI18N
        jbuAbrir.setMnemonic('A');
        jbuAbrir.setText("Abrir");
        jbuAbrir.setName("jbuAbrir"); // NOI18N
        jbuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuAbrirActionPerformed(evt);
            }
        });

        jbuFechar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jbuFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/laramara/ti/sislaraclient/telas/resources/icones/Fechar.png"))); // NOI18N
        jbuFechar.setMnemonic('F');
        jbuFechar.setText("Fechar");
        jbuFechar.setName("jbuFechar"); // NOI18N
        jbuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaTelaMailingLayout = new javax.swing.GroupLayout(jpaTelaMailing);
        jpaTelaMailing.setLayout(jpaTelaMailingLayout);
        jpaTelaMailingLayout.setHorizontalGroup(
            jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaTelaMailingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaTelaMailingLayout.createSequentialGroup()
                        .addComponent(jbuAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuFechar))
                    .addGroup(jpaTelaMailingLayout.createSequentialGroup()
                        .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuCategoriasAAdicionar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jspCategorias, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpaTelaMailingLayout.createSequentialGroup()
                                .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlaCategirioasAAdicionar)
                                    .addComponent(jlaCategorias)
                                    .addGroup(jpaTelaMailingLayout.createSequentialGroup()
                                        .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlaDataInicio)
                                            .addComponent(jftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbuDataInicio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jlaDataTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jftDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbuDataTermino)))
                                .addGap(163, 163, 163)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuRemoverCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuAdicionarCategoria))))
                .addContainerGap())
        );
        jpaTelaMailingLayout.setVerticalGroup(
            jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaTelaMailingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpaTelaMailingLayout.createSequentialGroup()
                        .addComponent(jlaDataTermino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuDataTermino)
                            .addComponent(jbuDataInicio)))
                    .addGroup(jpaTelaMailingLayout.createSequentialGroup()
                        .addComponent(jlaDataInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(jlaCategirioasAAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaTelaMailingLayout.createSequentialGroup()
                        .addComponent(jbuCategoriasAAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlaCategorias))
                    .addComponent(jbuAdicionarCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaTelaMailingLayout.createSequentialGroup()
                        .addComponent(jspCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpaTelaMailingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbuAbrir)
                            .addComponent(jbuFechar)))
                    .addComponent(jbuRemoverCategoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpaTelaMailing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaTelaMailing, javax.swing.GroupLayout.PREFERRED_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuFecharActionPerformed
        controladorTelaMailing.fecharTela();
    }//GEN-LAST:event_jbuFecharActionPerformed

    private void jbuAdicionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAdicionarCategoriaActionPerformed
        controladorTelaMailing.adicionarTipoVinculoSelecionado();
    }//GEN-LAST:event_jbuAdicionarCategoriaActionPerformed

    private void jbuRemoverCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRemoverCategoriaActionPerformed
        controladorTelaMailing.removerTipoVinculoSelecionado();
    }//GEN-LAST:event_jbuRemoverCategoriaActionPerformed

    private void jbuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuAbrirActionPerformed
        controladorTelaMailing.abrirRelatorio();
    }//GEN-LAST:event_jbuAbrirActionPerformed

    private void jbuDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuDataInicioActionPerformed
        JOptionPanePersonalizado.mostrarTelaSelecionarData(this, jftDataInicio);
    }//GEN-LAST:event_jbuDataInicioActionPerformed

    private void jbuDataTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuDataTerminoActionPerformed
        JOptionPanePersonalizado.mostrarTelaSelecionarData(this, jftDataTermino);
    }//GEN-LAST:event_jbuDataTerminoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbuAbrir;
    private javax.swing.JButton jbuAdicionarCategoria;
    private javax.swing.JComboBox<String> jbuCategoriasAAdicionar;
    private javax.swing.JButton jbuDataInicio;
    private javax.swing.JButton jbuDataTermino;
    private javax.swing.JButton jbuFechar;
    private javax.swing.JButton jbuRemoverCategoria;
    private javax.swing.JFormattedTextField jftDataInicio;
    private javax.swing.JFormattedTextField jftDataTermino;
    private javax.swing.JLabel jlaCategirioasAAdicionar;
    private javax.swing.JLabel jlaCategorias;
    private javax.swing.JLabel jlaDataInicio;
    private javax.swing.JLabel jlaDataTermino;
    private javax.swing.JList<String> jliCategorias;
    private javax.swing.JPanel jpaTelaMailing;
    private javax.swing.JScrollPane jspCategorias;
    // End of variables declaration//GEN-END:variables
    private ControladorTelaMailing controladorTelaMailing;
}
