ALTER TABLE ATENDIMENTO_GRUPO ALTER COLUMN DESCRICAO TYPE VARCHAR(20000);
ALTER TABLE ATENDIMENTO_INDIVIDUAL ALTER COLUMN INTERDISCIPLINAR TYPE VARCHAR(20000);
ALTER TABLE INFORMACAO_ATENDIMENTO ALTER COLUMN DESCRICAO TYPE VARCHAR(20000);
ALTER TABLE INFORMACAO_ATENDIMENTO ALTER COLUMN JUSTIFICATIVA TYPE VARCHAR(20000);
ALTER TABLE PROGRAMACAO ALTER COLUMN TEMA_CONTEUDO TYPE VARCHAR(20000);
ALTER TABLE PROGRAMACAO ALTER COLUMN ESTRATEGIAS TYPE VARCHAR(20000);
ALTER TABLE PROGRAMACAO ALTER COLUMN RECADO_FAMILIA TYPE VARCHAR(20000);
ALTER TABLE USUARIO ALTER COLUMN OBS TYPE VARCHAR(20000);