ALTER TABLE GRUPO DROP COLUMN VERSAO;
ALTER TABLE USUARIO DROP COLUMN VERSAO;
ALTER TABLE USUARIO ADD COLUMN VERSAO VARCHAR(36) DEFAULT ' ';
ALTER TABLE atendimento_grupo ALTER COLUMN INTERDISCIPLINAR TYPE VARCHAR(20000);
