insert into cargo(nome) values('Advogado');
insert into cargo(nome) values('Arquiteto');
insert into cargo(nome) values('Artesão'); 
insert into cargo(nome) values('Artista (artes visuais)');
insert into cargo(nome) values('Assistente administrativo');
insert into cargo(nome) values('Assistente social');
insert into cargo(nome) values('Atleta profissional');
insert into cargo(nome) values('Auxiliar de radiologia (revelação fotográfica)');
insert into cargo(nome) values('Avaliador olfativo');
insert into cargo(nome) values('Babá');
insert into cargo(nome) values('Balconista');
insert into cargo(nome) values('Comerciante');
insert into cargo(nome) values('Economista');
insert into cargo(nome) values('Empregado doméstico');
insert into cargo(nome) values('Massoterapeuta');
insert into cargo(nome) values('Músico');
insert into cargo(nome) values('Office-boy');
insert into cargo(nome) values('Palhaço');
insert into cargo(nome) values('Pedagogo');
insert into cargo(nome) values('Professor');
insert into cargo(nome) values('Psicólogo');
insert into cargo(nome) values('Recepcionista');
insert into cargo(nome) values('Repositor');
insert into cargo(nome) values('Revisor de Braille');
insert into cargo(nome) values('Secretária');
insert into cargo(nome) values('Telefonista');
insert into cargo(nome) values('Vendedor');

insert into area_formacao(nome) values('Administração de Empresas');
insert into area_formacao(nome) values('Ciências Contábeis');
insert into area_formacao(nome) values('Ciências Sociais');
insert into area_formacao(nome) values('Direito');
insert into area_formacao(nome) values('Economia');
insert into area_formacao(nome) values('Educação Física');
insert into area_formacao(nome) values('Geografia');
insert into area_formacao(nome) values('Gestão em Recursos Humanos');
insert into area_formacao(nome) values('História');
insert into area_formacao(nome) values('Letras');
insert into area_formacao(nome) values('Massoterapia');
insert into area_formacao(nome) values('Música');
insert into area_formacao(nome) values('Musicoterapia');
insert into area_formacao(nome) values('Pedagogia');
insert into area_formacao(nome) values('Psicologia');
insert into area_formacao(nome) values('Serviço Social');
insert into area_formacao(nome) values('Tecnologia da Informação');
insert into area_formacao(nome) values('Turismo');

insert into local_trabalho(nome) values('AC Camargo Cancer Center');
insert into local_trabalho(nome) values('Accenture Brasil');
insert into local_trabalho(nome) values('Aché Laboratórios Farmacêuticos');
insert into local_trabalho(nome) values('Allianz');
insert into local_trabalho(nome) values('Associação Comercial de São Paulo');
insert into local_trabalho(nome) values('Banco Bradesco');
insert into local_trabalho(nome) values('Banco do Brasil');
insert into local_trabalho(nome) values('Banco Itaú-Unibanco');
insert into local_trabalho(nome) values('Carrefour');
insert into local_trabalho(nome) values('Citibank');
insert into local_trabalho(nome) values('Deloitte');
insert into local_trabalho(nome) values('Drogaria São Paulo');
insert into local_trabalho(nome) values('Drogasil');
insert into local_trabalho(nome) values('Fundação Dorina Nowill para Cegos');
insert into local_trabalho(nome) values('Gafor');
insert into local_trabalho(nome) values('Givaudan do Brasil');
insert into local_trabalho(nome) values('Hewlett Packard');
insert into local_trabalho(nome) values('IBM');
insert into local_trabalho(nome) values('Laramara'); 
insert into local_trabalho(nome) values('Natura');
insert into local_trabalho(nome) values('Serasa Experian');
insert into local_trabalho(nome) values('Siemens');
insert into local_trabalho(nome) values('Stefanini');
insert into local_trabalho(nome) values('TAM');
insert into local_trabalho(nome) values('Techint');
insert into local_trabalho(nome) values('Totvs');
insert into local_trabalho(nome) values('Unisantanna');
insert into local_trabalho(nome) values('Whirlpool');
insert into local_trabalho(nome) values('Yamaha Motor');


