insert into profissional(nome, habilitado, voluntario, profissional)values('WASHINGTON LUIS DE OLIVEIRA MESQUITA', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('MARLENE DAS CHAGAS', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('JACKSON DE ALMEIDA PEQUENO', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('SORAIA AP. CAMPIANI ZACARIAS', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('THEREZA POZOLLI', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('LAURA ROSSO', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('HAMILTON KIDA', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('ROSANA FERRAZ', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('ROBERTA PORTO', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('MARIA CECÍLIA CARDOSO', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('BRUNA DIEGUES', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('FERNANDA LIMA', true, true, true);