CREATE TABLE CONTRIBUINTE
(
	ID BIGSERIAL NOT NULL,
	DATA_CADASTRO TIMESTAMP,
	NOME_EMPRESA VARCHAR(100) NOT NULL,
	PRONTUARIO INT,
	ID_ENDERECO BIGINT NOT NULL,
	INDICADO_POR VARCHAR(100),
	FREQUENCIA_CONTRIBUICAO VARCHAR(50),
	VALOR_CONTRIBUICAO DECIMAL,
	ID_CONTATO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;
ALTER TABLE CONTRIBUINTE
	ADD FOREIGN KEY (ID_CONTATO)
	REFERENCES CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
ALTER TABLE INFORMACAO_ESSENCIAL_ENDERECO
	ADD FOREIGN KEY (ID_ENDERECO)
	REFERENCES ENDERECO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;