update recurso set cartela_de_selos = true, valor = '2500.00' where id in (3);
update recurso set cartela_de_selos = true, valor = '2100.00' where id in (9);
update recurso set valor = '80.00' where id in (1);
ALTER TABLE DEMANDA DROP COLUMN ID_PROJETO;
ALTER TABLE LOTE_RECURSO ADD COLUMN VALOR NUMERIC;
CREATE TABLE PROJETO_RESERVA
(
	ID_RESERVA BIGINT NOT NULL,
	ID_PROJETO BIGINT NOT NULL
) WITHOUT OIDS;

CREATE TABLE RESERVA
(
	ID BIGSERIAL NOT NULL,
	DATA TIMESTAMP NOT NULL,
	ID_DEMANDA BIGINT NOT NULL,
	VALOR DECIMAL NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


ALTER TABLE PROJETO_RESERVA
	ADD FOREIGN KEY (ID_PROJETO)
	REFERENCES PROJETO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE PROJETO_RESERVA
	ADD FOREIGN KEY (ID_RESERVA)
	REFERENCES RESERVA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
ALTER TABLE RESERVA
	ADD FOREIGN KEY (ID_DEMANDA)
	REFERENCES DEMANDA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;