insert into diretoria_ensino(nome)values('Região Avare');
insert into diretoria_ensino(nome)values('Região Penápolis');
insert into diretoria_ensino(nome)values('Região Santo  Anastácio');
insert into diretoria_ensino(nome)values('Região Santos');
insert into diretoria_ensino(nome)values('Região São Carlos');
insert into diretoria_ensino(nome)values('Região São João Da Boa Vista');
insert into diretoria_ensino(nome)values('Região São Joaquim Da  Barra');
insert into diretoria_ensino(nome)values('Região São José  Do Rio  Preto');
insert into diretoria_ensino(nome)values('Região São José  Dos Campos');
insert into diretoria_ensino(nome)values('Região São Roque');
insert into diretoria_ensino(nome)values('Região São Vicente');
insert into diretoria_ensino(nome)values('Região Sertãozinho');
insert into diretoria_ensino(nome)values('Região Sorocaba');
insert into diretoria_ensino(nome)values('Região Sumaré');
insert into diretoria_ensino(nome)values('Região Taquaritinga');
insert into diretoria_ensino(nome)values('Região Taubaté');
insert into diretoria_ensino(nome)values('Região Tupã');
insert into diretoria_ensino(nome)values('Região Votorantim');
insert into diretoria_ensino(nome)values('Região Votuporanga');
