DROP TABLE DEMANDA_CAPTACAO;
DROP TABLE CAPTACAO;
DROP TABLE PATROCINADOR;
DROP TABLE RECIBO;

CREATE TABLE FILIAL
(
	ID BIGINT NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	ENDERECO VARCHAR(60) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE RECIBO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CPF_CNPJ VARCHAR(14) NOT NULL,
	VALOR NUMERIC NOT NULL,
	DATA_DO_REGISTRO TIMESTAMP NOT NULL,
	DATA DATE NOT NULL,
	DESCRICAO VARCHAR(20000),
	MOTIVO_DO_CANCELAMENTO VARCHAR(20000),
	ID_FILIAL BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE RECIBO
	ADD FOREIGN KEY (ID_FILIAL)
	REFERENCES FILIAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

CREATE TABLE CAPTACAO
(
	ID BIGSERIAL NOT NULL,
	VALOR DECIMAL NOT NULL,
	ID_RECIBO BIGINT NOT NULL,
	DATA TIMESTAMP NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	CANCELADA BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE CAPTACAO
	ADD FOREIGN KEY (ID_RECIBO)
	REFERENCES RECIBO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE CAPTACAO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

CREATE TABLE DEMANDA_CAPTACAO
(
	ID_CAPTACAO BIGINT NOT NULL,
	ID_DEMANDA BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE DEMANDA_CAPTACAO
	ADD FOREIGN KEY (ID_CAPTACAO)
	REFERENCES CAPTACAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE DEMANDA_CAPTACAO
	ADD FOREIGN KEY (ID_DEMANDA)
	REFERENCES DEMANDA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

CREATE TABLE HISTORICO_STATUS_RECIBO
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25) NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE HISTORICO_STATUS_RECIBO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

CREATE TABLE RECIBO_HISTORICO_STATUS_RECIBO
(
	ID_RECIBO BIGINT NOT NULL,
	ID_HISTORICO_STATUS_RECIBO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE RECIBO_HISTORICO_STATUS_RECIBO
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_RECIBO)
	REFERENCES HISTORICO_STATUS_RECIBO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE RECIBO_HISTORICO_STATUS_RECIBO
	ADD FOREIGN KEY (ID_RECIBO)
	REFERENCES RECIBO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

update perfil_permissoes set permissao = 'RELATORIO_RECIBO' where permissao = 'RELATORIO_RECIBO_CAPTACAO_DOACAO_DEMANDA';
update conta_acesso_permissoes set permissao = 'RELATORIO_RECIBO' where permissao = 'RELATORIO_RECIBO_CAPTACAO_DOACAO_DEMANDA';

insert into filial(id, cnpj, endereco, cep) values(1, '67640441000129', 'Rua Conselheiro Brotero, 338 - Barra Funda - SÃO PAULO', '01154000');
insert into filial(id, cnpj, endereco, cep) values(5, '67640441000552', 'Rua Barra Funda, 16 - Barra Funda - SÃO PAULO', '01152000');
insert into filial(id, cnpj, endereco, cep) values(7, '67640441000714', 'Rua Conselheiro Brotero, 341 - Barra Funda - SÃO PAULO', '01154001');

ALTER SEQUENCE recibo_id_seq RESTART WITH 24999;
