ALTER TABLE ATENDIMENTO_INDIVIDUAL ADD COLUMN INTEGRACAO VARCHAR(5);
ALTER TABLE ATENDIMENTO_INDIVIDUAL ADD COLUMN MOTIVO_NAO_INTEGRACAO VARCHAR(20000);
ALTER TABLE ATENDIMENTO_INDIVIDUAL ADD COLUMN DISCUSSAO_CASO VARCHAR(5);