ALTER TABLE USUARIO ADD COLUMN HISTORICO VARCHAR(20000);
ALTER TABLE USUARIO ADD COLUMN FUNCIONALIDADE VARCHAR(20000);
ALTER TABLE USUARIO ADD COLUMN REACAO_FRENTE_A_DEFICIENCIA VARCHAR(20000);
ALTER TABLE USUARIO ADD COLUMN REACAO_FRENTE_A_DEFICIENCIA_FAMILIA VARCHAR(20000);
ALTER TABLE USUARIO ADD COLUMN REDE_DE_APOIO VARCHAR(20000);
ALTER TABLE USUARIO ADD COLUMN REDE_DE_AMIGOS VARCHAR(20000);
ALTER TABLE USUARIO ADD COLUMN NAMORO_CASAMENTO_SEXUALIDADE VARCHAR(20000);
ALTER TABLE USUARIO ADD COLUMN NECESSIDADES_EXPECTATIVAS_QUEIXAS VARCHAR(20000);
ALTER TABLE USUARIO ADD COLUMN EDUCACIONAL VARCHAR(20000);
ALTER TABLE USUARIO ADD COLUMN COMUNICACAO VARCHAR(20000);
ALTER TABLE USUARIO ADD COLUMN RELIGIAO_LAZER_CULTURA_ROTINA VARCHAR(20000);
	