CREATE TABLE FAMILIAR_PERIODO_BENEFICIO
(
	ID_FAMILIAR BIGINT NOT NULL,
	ID_PERIODO_BENEFICIO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE FAMILIAR_PERIODO_BENEFICIO
	ADD FOREIGN KEY (ID_FAMILIAR)
	REFERENCES FAMILIAR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE FAMILIAR_PERIODO_BENEFICIO
	ADD FOREIGN KEY (ID_PERIODO_BENEFICIO)
	REFERENCES PERIODO_BENEFICIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
