package br.laramara.sistelemarketingclient.utils;

public class ContextoGenerico {

	private static String textoGrande ="TESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTEST"
			+ "ETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTETESTESTESTESTE";
	public static String obterGrande() {
		return textoGrande;
	}

}
