CREATE TABLE SOLICITACAO_RELATORIO_FINALIDADE_RELATORIO
(
	ID_SOLICITACAO_RELATORIO BIGINT NOT NULL,
	FINALIDADE_RELATORIO VARCHAR(50) NOT NULL
) WITHOUT OIDS;

CREATE TABLE HISTORICO_STATUS_SOLICITACAO_RELATORIO
(
	ID BIGSERIAL NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS_SOLICITACAO_RELATORIO VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE SOLICITACAO_RELATORIO
(
	ID BIGSERIAL NOT NULL,
	NOME_SOLICITANTE VARCHAR(100),
	RG_SOLICITANTE VARCHAR(15),
	ID_USUARIO BIGINT NOT NULL,
	QUANTIDADE_RELATORIOS_EMITIDOS INT,
	QUANTIDADE_RELATORIOS_ENTREGUES INT,
	OBS VARCHAR(20000),
	ELABORADOR VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE SOLICITACAO_RELATORIO_HISTORICO_STATUS_SOLICITACAO_RELATORIO
(
	ID_SOLICITACAO_RELATORIO BIGINT NOT NULL,
	ID_HISTORICO_STATUS_SOLICITACAO_RELATORIO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE HISTORICO_STATUS_SOLICITACAO_RELATORIO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SOLICITACAO_RELATORIO_HISTORICO_STATUS_SOLICITACAO_RELATORIO
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_SOLICITACAO_RELATORIO)
	REFERENCES HISTORICO_STATUS_SOLICITACAO_RELATORIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SOLICITACAO_RELATORIO_HISTORICO_STATUS_SOLICITACAO_RELATORIO
	ADD FOREIGN KEY (ID_SOLICITACAO_RELATORIO)
	REFERENCES SOLICITACAO_RELATORIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE SOLICITACAO_RELATORIO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
