CREATE TABLE CAPTACAO
(
	ID BIGSERIAL NOT NULL,
	ID_PATROCINADOR BIGINT NOT NULL,
	VALOR DECIMAL NOT NULL,
	DATA TIMESTAMP NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	CANCELADA BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE DEMANDA_CAPTACAO
(
	ID_CAPTACAO BIGINT NOT NULL,
	ID_DEMANDA BIGINT NOT NULL
) WITHOUT OIDS;

CREATE TABLE PATROCINADOR
(
	ID BIGSERIAL NOT NULL,
	CPF_CNPJ VARCHAR(14) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE DEMANDA_CAPTACAO
	ADD FOREIGN KEY (ID_CAPTACAO)
	REFERENCES CAPTACAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE CAPTACAO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE DEMANDA_CAPTACAO
	ADD FOREIGN KEY (ID_DEMANDA)
	REFERENCES DEMANDA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE CAPTACAO
	ADD FOREIGN KEY (ID_PATROCINADOR)
	REFERENCES PATROCINADOR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

CREATE TABLE DOACOES_LEGADO
(
	CPF VARCHAR(14) NOT NULL,
	TIPO VARCHAR(255) NOT NULL,
	PRIMARY KEY (CPF)
) WITHOUT OIDS;

ALTER TABLE DEMANDA ADD COLUMN VALOR DECIMAL;

ALTER TABLE RECURSO ADD COLUMN VALOR DECIMAL;