ALTER TABLE FAMILIAR ADD COLUMN RESPONSAVEL_PELA_AVALIACAO_SOCIAL BOOLEAN DEFAULT 'false';
ALTER TABLE FAMILIAR ADD COLUMN ACOMPANHANTE BOOLEAN DEFAULT 'false';
ALTER TABLE FAMILIAR ADD COLUMN CUIDA_DO_USUARIO BOOLEAN DEFAULT 'false';
ALTER TABLE FAMILIAR ADD COLUMN PARADEIRO_IGNORADO BOOLEAN DEFAULT 'false';