CREATE TABLE PARTICIPACAO_DETALHADA
(
	ID BIGSERIAL NOT NULL,
	PARTICIPACAO VARCHAR(50) NOT NULL,
	QUANTIDADE BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE INFORMACAO_ATENDIMENTO_PARTICIPACAO_DETALHADA
(
	ID_INFORMACAO_ATENDIMENTO BIGINT NOT NULL,
	ID_PARTICIPACAO_DETALHADA BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE INFORMACAO_ATENDIMENTO_PARTICIPACAO_DETALHADA
	ADD FOREIGN KEY (ID_INFORMACAO_ATENDIMENTO)
	REFERENCES INFORMACAO_ATENDIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE INFORMACAO_ATENDIMENTO_PARTICIPACAO_DETALHADA
	ADD FOREIGN KEY (ID_PARTICIPACAO_DETALHADA)
	REFERENCES PARTICIPACAO_DETALHADA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

select 'insert into PARTICIPACAO_DETALHADA(participacao, quantidade) values (''', infate.participacao,''', 1);', 'insert into INFORMACAO_ATENDIMENTO_PARTICIPACAO_DETALHADA(ID_INFORMACAO_ATENDIMENTO, ID_PARTICIPACAO_DETALHADA)values(', infate.id, ',', 'currval(''participacao_detalhada_id_seq'')', ');'  from informacao_atendimento infate where infate.participacao in ('APENAS_FAMILIA', 'COM_FAMILIA');