ALTER TABLE DEMANDA RENAME data TO data_prazo_captacao; 
ALTER TABLE DEMANDA ADD COLUMN CARTELA_DE_SELOS BOOLEAN DEFAULT 'false';
ALTER TABLE RECURSO ADD COLUMN CARTELA_DE_SELOS BOOLEAN DEFAULT 'false';