ALTER TABLE CAPTACAO ADD COLUMN ID_RECIBO BIGINT NOT NULL;

CREATE TABLE RECIBO
(
	ID BIGINT NOT NULL,
	VALOR NUMERIC NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE CAPTACAO
	ADD FOREIGN KEY (ID_RECIBO)
	REFERENCES RECIBO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;