ALTER TABLE FAMILIAR ADD COLUMN MORA_NA_CASA BOOLEAN DEFAULT 'false';
ALTER TABLE FAMILIAR ADD COLUMN GENERO VARCHAR(20);
ALTER TABLE INFORMACAO_TRABALHO ADD COLUMN ID_CARGO BIGINT;
ALTER TABLE INFORMACAO_TRABALHO
	ADD FOREIGN KEY (ID_CARGO)
	REFERENCES CARGO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
