CREATE TABLE PROJETO_ARQUIVO
(
	ID_ARQUIVO BIGINT NOT NULL,
	ID_PROJETO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE PROJETO_ARQUIVO
	ADD FOREIGN KEY (ID_ARQUIVO)
	REFERENCES ARQUIVO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE PROJETO_ARQUIVO
	ADD FOREIGN KEY (ID_PROJETO)
	REFERENCES PROJETO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;