CREATE TABLE ENCAMINHAMENTO
(
	ID BIGSERIAL NOT NULL,
	ID_ORIGEM_ENCAMINHAMENTO BIGINT,
	ID_REDE_ENCAMINHAMENTO BIGINT,
	PROFISSIONAL_LIBERAL VARCHAR(100),
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE ORIGEM_ENCAMINHAMENTO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE REDE_ENCAMINHAMENTO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE USUARIO_ENCAMINHAMENTO
(
	ID_USUARIO BIGINT NOT NULL,
	ID_ENCAMINHAMENTO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE USUARIO_ENCAMINHAMENTO
	ADD FOREIGN KEY (ID_ENCAMINHAMENTO)
	REFERENCES ENCAMINHAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ENCAMINHAMENTO
	ADD FOREIGN KEY (ID_ORIGEM_ENCAMINHAMENTO)
	REFERENCES ORIGEM_ENCAMINHAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ENCAMINHAMENTO
	ADD FOREIGN KEY (ID_REDE_ENCAMINHAMENTO)
	REFERENCES REDE_ENCAMINHAMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE USUARIO_ENCAMINHAMENTO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

insert into origem_encaminhamento(descricao)values('Hospital');
insert into rede_encaminhamento(descricao)values('SUAS');

