CREATE TABLE ACAO_CONDUTA
(
	ID BIGSERIAL NOT NULL,
	TIPO_ACAO_CONDUTA VARCHAR(50) NOT NULL,
	ID_GRUPO BIGINT,
	ID_USUARIO BIGINT NOT NULL,
	DATA_PROCESSAMENTO TIMESTAMP,
	OBS VARCHAR(20000),
	CANCELADA BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE ATENDIMENTO_INDIVIDUAL_ACAO_CONDUTA
(
	ID_ACAO_CONDUTA BIGINT NOT NULL,
	ID_ATENDIMENTO_INDIVIDUAL BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE ATENDIMENTO_INDIVIDUAL_ACAO_CONDUTA
	ADD FOREIGN KEY (ID_ACAO_CONDUTA)
	REFERENCES ACAO_CONDUTA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ATENDIMENTO_INDIVIDUAL_ACAO_CONDUTA
	ADD FOREIGN KEY (ID_ATENDIMENTO_INDIVIDUAL)
	REFERENCES ATENDIMENTO_INDIVIDUAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ACAO_CONDUTA
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE ACAO_CONDUTA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;