ALTER TABLE ATENDIMENTO_INDIVIDUAL ADD COLUMN RELATORIO_AVFUN_NAO_CONFECCIONADO BOOLEAN DEFAULT 'false';
ALTER TABLE ATENDIMENTO_INDIVIDUAL ADD COLUMN MOTIVO_NAO_CONFECCAO_RELATORIO_AVFUN VARCHAR(20000);
