CREATE TABLE DESCRICAO_RECURSO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE RECURSO_DESCRICAO_RECURSO
(
	ID_RECURSO BIGINT NOT NULL,
	ID_DESCRICAO_RECURSO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE DEMANDA ADD COLUMN ID_DESCRICAO_RECURSO BIGINT;
ALTER TABLE DEMANDA ADD COLUMN DATA_EXPECTATIVA DATE;

ALTER TABLE DEMANDA
	ADD FOREIGN KEY (ID_DESCRICAO_RECURSO)
	REFERENCES DESCRICAO_RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE DEMANDA
	ADD FOREIGN KEY (ID_DESCRICAO_RECURSO)
	REFERENCES DESCRICAO_RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE RECURSO_DESCRICAO_RECURSO
	ADD FOREIGN KEY (ID_DESCRICAO_RECURSO)
	REFERENCES DESCRICAO_RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE RECURSO_DESCRICAO_RECURSO
	ADD FOREIGN KEY (ID_RECURSO)
	REFERENCES RECURSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;