ALTER TABLE descricao_recurso ALTER COLUMN descricao TYPE VARCHAR(100);
insert into descricao_recurso(id, descricao)values(29,'Avaliação Educacional de Alunos com Baixa Visão e Múltipla Deficiência');
insert into descricao_recurso(id, descricao)values(30,'CD Brincar Para Todos');
insert into descricao_recurso(id, descricao)values(31,'DVD Brincar Para Todos');
insert into descricao_recurso(id, descricao)values(32,'A Deficiência Visual Associada à Deficiência Múltipla e o Atendimento Educacional Especializado');
insert into descricao_recurso(id, descricao)values(33,'A Esperança do Sucesso em Matemática está na Semente');
insert into descricao_recurso(id, descricao)values(34,'A Liberdade Cria Asas');
insert into descricao_recurso(id, descricao)values(35,'Aprendendo junto com Papai e Mamãe');
insert into descricao_recurso(id, descricao)values(36,'Auxílios Para Baixa Visão');
insert into descricao_recurso(id, descricao)values(37,'Baixa Visão na Infância');
insert into descricao_recurso(id, descricao)values(38,'Baixa Visão na Infância – Guia Prático de Atenção Oftalmoloógica');
insert into descricao_recurso(id, descricao)values(39,'Baixa Visão: Conhecendo Mais para Ajudar Melhor');
insert into descricao_recurso(id, descricao)values(40,'Brincar Juntinhos');
insert into descricao_recurso(id, descricao)values(41,'Brincar Para Todos');
insert into descricao_recurso(id, descricao)values(42,'Caderno de Pauta Ampliada');
insert into descricao_recurso(id, descricao)values(43,'Caminhado Juntos');
insert into descricao_recurso(id, descricao)values(44,'CDs Revista Contato – kit com 8 CDs – versão áudio');
insert into descricao_recurso(id, descricao)values(45,'Deficiência Visual – Reflexão sobre a Prática Pedagógica');
insert into descricao_recurso(id, descricao)values(46,'DVD - Aprendizagem e Desenvolvimento da Criança com Deficiência');
insert into descricao_recurso(id, descricao)values(47,'DVD - Ganma Laramara');
insert into descricao_recurso(id, descricao)values(48,'GANMA Laramara');
insert into descricao_recurso(id, descricao)values(49,'Kit Auxílios para Baixa Visão');
insert into descricao_recurso(id, descricao)values(50,'Kit Baixa Visão lll - KIT III. 2 MANUAIS + 1 CD ROM + 1 FITA DE VÍDEO VHS');
insert into descricao_recurso(id, descricao)values(51,'Ler e Escrever em Braille');
insert into descricao_recurso(id, descricao)values(52,'Manual Ilustrado para uso do Braille');
insert into descricao_recurso(id, descricao)values(53,'Manual para Creches');
insert into descricao_recurso(id, descricao)values(54,'Mercenário ou Missionário?');
insert into descricao_recurso(id, descricao)values(55,'O Desenvolvimento Integral do Portador de Deficiência Visual');
insert into descricao_recurso(id, descricao)values(56,'Orientação aos Professores na Integração Escolar da Criança com Baixa Visão');
insert into descricao_recurso(id, descricao)values(57,'Orientação e Mobilidade');
insert into descricao_recurso(id, descricao)values(58,'Papai e Mamãe, Vamos Brincar');
insert into descricao_recurso(id, descricao)values(59,'Papai, Mamãe - Ajudem-me Por Favor');
insert into descricao_recurso(id, descricao)values(60,'Revista Contato n.8');
insert into descricao_recurso(id, descricao)values(61,'Toque o Bebê');

insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,29);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,30);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,31);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,32);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,33);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,34);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,35);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,36);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,37);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,38);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,39);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,40);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,41);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,42);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,43);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,44);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,45);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,46);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,47);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,48);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,49);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,50);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,51);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,52);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,53);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,54);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,55);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,56);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,57);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,58);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,59);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,60);
insert into  recurso_descricao_recurso(id_recurso, id_descricao_recurso)values(10,61);