alter table grupo add column INVESTIMENTO DECIMAL;
alter table grupo add column VALOR_TOTAL_ALMOCO DECIMAL;
alter table grupo add column NOME_CURSO VARCHAR(100);
alter table grupo add column DATA_INICIO_PRE_INSCRICAO DATE;
alter table grupo add column DATA_TERMINO_PRE_INSCRICAO DATE;
alter table grupo add column PUBLICADO BOOLEAN DEFAULT 'FALSE';

CREATE TABLE DESCRICAO_EVENTO
(
	ID BIGSERIAL NOT NULL,
	TIPO_DESCRICAO_EVENTO VARCHAR(100) DEFAULT 'FALSE',
	TITULO VARCHAR(100),
	CONTEUDO VARCHAR(20000),
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE GRUPO_DESCRICAO_EVENTO
(
	ID_GRUPO BIGINT NOT NULL,
	ID_DESCRICAO_EVENTO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE GRUPO_DESCRICAO_EVENTO
	ADD FOREIGN KEY (ID_DESCRICAO_EVENTO)
	REFERENCES DESCRICAO_EVENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE GRUPO_DESCRICAO_EVENTO
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES GRUPO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE GRUPO_DESCRICAO_EVENTO
	ADD FOREIGN KEY (ID_DESCRICAO_EVENTO)
	REFERENCES DESCRICAO_EVENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE USUARIO_EXTERNO ADD COLUMN NOME_COMPLETO VARCHAR(100) NOT NULL;
ALTER TABLE USUARIO_EXTERNO ADD COLUMN AUTORIZO_RECEBIMENTO_INFORMATIVO BOOLEAN;
ALTER TABLE USUARIO_EXTERNO ADD COLUMN DDD VARCHAR(2) NOT NULL;
ALTER TABLE USUARIO_EXTERNO ADD COLUMN TELEFONE_CELULAR VARCHAR(9) NOT NULL;