CREATE TABLE COMPROMETIMENTO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE PERIODO_COMPROMETIMENTO
(
	ID BIGSERIAL NOT NULL,
	ID_COMPROMETIMENTO BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	EPOCA_INCIDENCIA VARCHAR(25),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE USUARIO_PERIODO_COMPROMETIMENTO
(
	ID_PERIODO_COMPROMETIMENTO BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE PERIODO_COMPROMETIMENTO
	ADD FOREIGN KEY (ID_COMPROMETIMENTO)
	REFERENCES COMPROMETIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE USUARIO_PERIODO_COMPROMETIMENTO
	ADD FOREIGN KEY (ID_PERIODO_COMPROMETIMENTO)
	REFERENCES PERIODO_COMPROMETIMENTO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE USUARIO_PERIODO_COMPROMETIMENTO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;