CREATE TABLE PROJETO_RESPONSAVEL_TECNICO
(
	ID_PROJETO BIGINT NOT NULL,
	ID_RESPONSAVEL_TECNICO BIGINT NOT NULL
) WITHOUT OIDS;

CREATE TABLE RESPONSAVEL_TECNICO
(
	ID BIGSERIAL NOT NULL,
	ID_PROFISSIONAL BIGINT NOT NULL,
	PRINCIPAL BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE RESPONSAVEL_TECNICO
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE PROJETO_RESPONSAVEL_TECNICO
	ADD FOREIGN KEY (ID_PROJETO)
	REFERENCES PROJETO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE PROJETO_RESPONSAVEL_TECNICO
	ADD FOREIGN KEY (ID_RESPONSAVEL_TECNICO)
	REFERENCES RESPONSAVEL_TECNICO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
