CREATE TABLE FAMILIAR_VULNERABILIDADE
(
	ID_FAMILIAR BIGINT NOT NULL,
	ID_VULNERABILIDADE BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE FAMILIAR_VULNERABILIDADE
	ADD FOREIGN KEY (ID_FAMILIAR)
	REFERENCES FAMILIAR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE FAMILIAR_VULNERABILIDADE
	ADD FOREIGN KEY (ID_VULNERABILIDADE)
	REFERENCES VULNERABILIDADE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;