CREATE TABLE INSCRICAO
(
	ID BIGSERIAL NOT NULL,
	ID_USUARIO_EXTERNO BIGINT NOT NULL,
	ID_ENDERECO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE INSCRICAO ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID);
ALTER TABLE INSCRICAO ADD FOREIGN KEY (ID_USUARIO_EXTERNO) REFERENCES USUARIO_EXTERNO (ID);