insert into estado(id, descricao) values(1,'Acre');
insert into estado(id, descricao) values(2,'Alagoas');
insert into estado(id, descricao) values(3,'Amazonas');
insert into estado(id, descricao) values(4,'Amapá');
insert into estado(id, descricao) values(5,'Bahia');
insert into estado(id, descricao) values(6,'Ceara');
insert into estado(id, descricao) values(7,'Distrito Federal');
insert into estado(id, descricao) values(8,'Espirito Santo');
insert into estado(id, descricao) values(9,'Goiás');
insert into estado(id, descricao) values(10,'Maranhão');
insert into estado(id, descricao) values(11,'Minas Gerais');
insert into estado(id, descricao) values(12,'Mato Grosso do Sul');
insert into estado(id, descricao) values(13,'Mato Grosso');
insert into estado(id, descricao) values(14,'Pará');
insert into estado(id, descricao) values(15,'Paraíba');
insert into estado(id, descricao) values(16,'Pernambuco');
insert into estado(id, descricao) values(17,'Piauí');
insert into estado(id, descricao) values(18,'Paraná');
insert into estado(id, descricao) values(19,'Rio de Janeiro');
insert into estado(id, descricao) values(20,'Rio Grande do Norte');
insert into estado(id, descricao) values(21,'Rondônia');
insert into estado(id, descricao) values(22,'Roraima');
insert into estado(id, descricao) values(23,'Rio Grande do Sul');
insert into estado(id, descricao) values(24,'Santa Catarina');
insert into estado(id, descricao) values(25,'Sergipe');
insert into estado(id, descricao) values(26,'São Paulo');
insert into estado(id, descricao) values(27,'Tocantins');
