CREATE TABLE HISTORICO_INSTITUICAO
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	ID_INSTITUICAO BIGINT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE USUARIO_HISTORICO_INSTITUICAO_SAAI
(
	ID_USUARIO BIGINT NOT NULL,
	ID_HISTORICO_INSTITUICAO BIGINT NOT NULL
) WITHOUT OIDS;

CREATE TABLE USUARIO_HISTORICO_INSTITUICAO_SALA_RECURSO
(
	ID_USUARIO BIGINT NOT NULL,
	ID_HISTORICO_INSTITUICAO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_SAAI
	ADD FOREIGN KEY (ID_HISTORICO_INSTITUICAO)
	REFERENCES HISTORICO_INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_SALA_RECURSO
	ADD FOREIGN KEY (ID_HISTORICO_INSTITUICAO)
	REFERENCES HISTORICO_INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE HISTORICO_INSTITUICAO
	ADD FOREIGN KEY (ID_INSTITUICAO)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_SAAI
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_SALA_RECURSO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;