ALTER TABLE MODULO_PRE_CADASTRO ADD COLUMN ID_INSTITUICAO_COM_SAAI BIGINT;
ALTER TABLE MODULO_PRE_CADASTRO ADD COLUMN ID_INSTITUICAO_COM_SALA_RECURSO BIGINT;
ALTER TABLE MODULO_PRE_CADASTRO ADD COLUMN ID_INSTITUICAO_COM_OUTROS_AEE BIGINT;

ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_INSTITUICAO_COM_SAAI)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_INSTITUICAO_COM_SALA_RECURSO)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE MODULO_PRE_CADASTRO
	ADD FOREIGN KEY (ID_INSTITUICAO_COM_OUTROS_AEE)
	REFERENCES INSTITUICAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;