insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(4515, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 18);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(717, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7453, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(9452, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(3148, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 22);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(3330, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 22);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(9745, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 22);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7100, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 11);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7958, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 11);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8379, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 11);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8855, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 11);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(9715, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 11);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(5458, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 8);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(6477, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 8);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8594, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 8);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(1863, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 10);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(5446, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 10);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7197, '2013-02-01', 19, 1, 'CTO', 20, 'LC', 17);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(9424, '2013-03-01', 19, 1, 'CTO', 20, 'LC', 33);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7927, '2013-03-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7949, '2013-03-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8304, '2013-03-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8444, '2013-03-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(188, '2013-04-013', 19, 1, 'CTO', 20, 'LC', 6);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(6378, '2013-04-013', 19, 1, 'CTO', 20, 'LC', 8);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(9441, '2013-04-013', 19, 1, 'CTO', 20, 'LC', 8);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8168, '2013-05-01', 19, 1, 'CTO', 20, 'LC', 5);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8258, '2013-06-01', 19, 1, 'CTO', 20, 'LC', 20);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8124, '2013-06-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(9113, '2013-06-01', 19, 1, 'CTO', 20, 'LC', 8);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(6679, '2013-07-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(6680, '2013-07-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(9148, '2013-08-01', 19, 1, 'CTO', 20, 'LC', 33);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(6362, '2013-08-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7840, '2013-08-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8136, '2013-08-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(9003, '2013-08-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7062, '2013-09-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8241, '2013-09-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8300, '2013-09-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(4987, '2013-10-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7369, '2013-10-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7968, '2013-10-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(8483, '2013-10-01', 19, 1, 'CTO', 20, 'LC', 35);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7425, '2013-10-01', 19, 1, 'CTO', 20, 'LC', 2);
insert into espera (id_usuario, data, id_descricao_tipo_atendimento, id_modulo, id_setor, id_nome_grupo, tipo_espera, id_profissional_solicitado_por)values(7612, '2013-11-01', 19, 1, 'CTO', 20, 'LC', 2);

insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');
insert into historico_status_espera (id_conta_acesso, data_inicial_vigencia, status)values(8, '"2013-03-25 10:00:00.000"', 'AGUARDANDO');

insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(640, 686);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(641, 687);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(642, 688);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(643, 689);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(644, 690);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(645, 691);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(646, 692);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(647, 693);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(648, 694);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(649, 695);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(650, 696);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(651, 697);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(652, 698);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(653, 699);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(654, 700);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(655, 701);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(656, 702);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(657, 703);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(658, 704);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(659, 705);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(660, 706);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(661, 707);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(662, 708);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(663, 709);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(664, 710);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(665, 711);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(666, 712);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(667, 713);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(668, 714);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(669, 715);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(670, 716);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(671, 717);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(672, 718);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(673, 719);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(674, 720);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(675, 721);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(676, 722);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(677, 723);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(678, 724);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(679, 725);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(680, 726);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(681, 727);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(682, 728);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(683, 729);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(684, 730);
insert into espera_historico_status_espera (id_espera, id_historico_status_espera)values(685, 731);