ALTER TABLE INFORMACAO_EDUCACIONAL ADD COLUMN DATA_REFERENCIA TIMESTAMP NOT NULL DEFAULT '01/01/2013';
ALTER TABLE USUARIO ADD COLUMN RENDA INT;
ALTER TABLE INFORMACAO_EDUCACIONAL ALTER COLUMN DATA_REFERENCIA DROP DEFAULT;