ALTER TABLE PERIODO_DEFICIENCIA ADD COLUMN CID VARCHAR(4);
ALTER TABLE PERIODO_DEFICIENCIA ADD COLUMN EPOCA_INCIDENCIA VARCHAR(25);
ALTER TABLE PERIODO_DEFICIENCIA ADD COLUMN EXCLUIDO BOOLEAN DEFAULT 'FALSE';
