CREATE TABLE CERTIDAO
(
	ID BIGSERIAL NOT NULL,
	TIPO_CERTIDAO VARCHAR(25) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	LIVRO VARCHAR(10) NOT NULL,
	FOLHA VARCHAR(10) NOT NULL,
	DISTRITO VARCHAR(100) NOT NULL,
	UF VARCHAR(10) NOT NULL,
	ID_MUNICIPIO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE USUARIO_CERTIDAO
(
	ID_CERTIDAO BIGINT NOT NULL,
	ID_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE USUARIO_CERTIDAO
	ADD FOREIGN KEY (ID_CERTIDAO)
	REFERENCES CERTIDAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE CERTIDAO
	ADD FOREIGN KEY (ID_MUNICIPIO)
	REFERENCES MUNICIPIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE USUARIO_CERTIDAO
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;
