CREATE TABLE PENDENCIA
(
	ID BIGSERIAL NOT NULL,
	TIPO VARCHAR(50) NOT NULL,
	PRONTUARIO BIGINT,
	RESOLVIDA BOOLEAN DEFAULT 'false' NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE PENDENCIA_PROFISSIONAL
(
	ID_PENDENCIA BIGINT NOT NULL,
	ID_PROFISSIONAL BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE PENDENCIA_PROFISSIONAL
	ADD FOREIGN KEY (ID_PENDENCIA)
	REFERENCES PENDENCIA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE PENDENCIA_PROFISSIONAL
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;