ALTER TABLE solicitacao_relatorio ALTER COLUMN nome_solicitante SET NOT NULL;
ALTER TABLE solicitacao_relatorio ALTER COLUMN rg_solicitante SET NOT NULL;
ALTER TABLE CONTRIBUINTE ALTER COLUMN DATA_CADASTRO SET NOT NULL;