CREATE TABLE MOTIVO_DESATIVACAO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

ALTER TABLE CONTRIBUINTE ADD COLUMN ID_MOTIVO_DESATIVACAO BIGINT;

ALTER TABLE CONTRIBUINTE
	ADD FOREIGN KEY (ID_MOTIVO_DESATIVACAO)
	REFERENCES MOTIVO_DESATIVACAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE ESPERA ADD COLUMN LM_LIGOU BOOLEAN DEFAULT 'false';
