CREATE TABLE HISTORICO_STATUS_USUARIO
(
	ID BIGSERIAL NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE USUARIO_HISTORICO_STATUS_USUARIO
(
	ID_USUARIO BIGINT NOT NULL,
	ID_HISTORICO_STATUS_USUARIO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE USUARIO_HISTORICO_STATUS_USUARIO
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_USUARIO)
	REFERENCES HISTORICO_STATUS_USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE USUARIO_PERIODO_DOENCA
	ADD FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
