ALTER TABLE INFORMACAO_EDUCACIONAL ALTER COLUMN	ID_INSTITUICAO DROP NOT NULL;
ALTER TABLE INFORMACAO_EDUCACIONAL ALTER COLUMN	SITUACAO DROP NOT NULL;
ALTER TABLE INFORMACAO_EDUCACIONAL ALTER COLUMN	PERIODO DROP NOT NULL;
ALTER TABLE INFORMACAO_EDUCACIONAL ALTER COLUMN	ID_SERIE DROP NOT NULL;
ALTER TABLE INFORMACAO_EDUCACIONAL ALTER COLUMN	ID_ESCOLARIDADE DROP NOT NULL;