ALTER SEQUENCE profissional_id_seq RESTART WITH 146;
insert into profissional(nome, habilitado, voluntario, profissional)values('Cláudia Regina Piauilino dos  Santos', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('Jefferson Pena', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('Gerusa Fabiani Silva', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('Cleiton Barbosa Jesus', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('Fabio Henrique Brunharo', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('Daniela Danielenco', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('Fernanda Aparecida Quintilhano', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('Edinalva Rosa dos Anjos', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('Gisele Aparecida de Oliveira Santos', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('Waldir Alexandre', true, true, true);
insert into profissional(nome, habilitado, voluntario, profissional)values('Solange Nunes', true, true, true);