CREATE TABLE CONTA_ACESSO_PROFISSIONAL_EQUIVALENTE
(
	ID_PROFISSIONAL BIGINT NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL
) WITHOUT OIDS;

ALTER TABLE CONTA_ACESSO_PROFISSIONAL_EQUIVALENTE
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;
	
ALTER TABLE CONTA_ACESSO_PROFISSIONAL_EQUIVALENTE
	ADD FOREIGN KEY (ID_PROFISSIONAL)
	REFERENCES PROFISSIONAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;