update instituicao set tipo_apoio = 'SRMs' where tipo_apoio = 'SAAI';
ALTER TABLE MODULO_PRE_CADASTRO RENAME ID_INSTITUICAO_COM_SAAI TO ID_INSTITUICAO_COM_SRMS;
ALTER TABLE USUARIO_HISTORICO_INSTITUICAO_SAAI RENAME TO USUARIO_HISTORICO_INSTITUICAO_SRMS;