
/* Drop Tables */

DROP TABLE IF EXISTS CAMPANHA_ALOCACAO_OPERADOR;
DROP TABLE IF EXISTS ALOCACAO_OPERADOR;
DROP TABLE IF EXISTS CAMPANHA_CRITERIO;
DROP TABLE IF EXISTS DISTRIBUICAO_CONTATO_EVENTO_DISTRIBUICAO_CONTATO;
DROP TABLE IF EXISTS DISTRIBUICAO_CONTATO_EVENTO_TELEFONIA;
DROP TABLE IF EXISTS DOACAO_VALOR_DETALHADO;
DROP TABLE IF EXISTS DOACAO;
DROP TABLE IF EXISTS DISTRIBUICAO_CONTATO;
DROP TABLE IF EXISTS CAMPANHA;
DROP TABLE IF EXISTS CONTATO_HISTORICO_STATUS_CONTATO;
DROP TABLE IF EXISTS CONTATO_TELEFONE;
DROP TABLE IF EXISTS CONTATO;
DROP TABLE IF EXISTS EVENTO_DISTRIBUICAO_CONTATO;
DROP TABLE IF EXISTS HISTORICO_STATUS_CONTATO;
DROP TABLE IF EXISTS CONTA_ACESSO;
DROP TABLE IF EXISTS CRITERIO;
DROP TABLE IF EXISTS LOGRADOURO;
DROP TABLE IF EXISTS MUNICIPIO;
DROP TABLE IF EXISTS ESTADO;
DROP TABLE IF EXISTS EVENTO_TELEFONIA;
DROP TABLE IF EXISTS NIVEL_PERMISSAO;
DROP TABLE IF EXISTS NIVEL;
DROP TABLE IF EXISTS PERMISSAO;
DROP TABLE IF EXISTS TELEFONE;
DROP TABLE IF EXISTS VALOR_DETALHADO;




/* Create Tables */

CREATE TABLE ALOCACAO_OPERADOR
(
	ID BIGSERIAL NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	META_FINANCEIRA DECIMAL,
	META_QUANTIDADE_LIGACOES INT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CAMPANHA
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(20000),
	DATA_INICIO DATE NOT NULL,
	DATA_TERMINO DATE,
	META_FINANCEIRA DECIMAL,
	META_QUANTIDADE_LIGACOES INT,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CAMPANHA_ALOCACAO_OPERADOR
(
	ID_CAMPANHA BIGINT NOT NULL,
	ID_ALOCACAO_OPERADOR BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE CAMPANHA_CRITERIO
(
	ID_CAMPANHA BIGINT NOT NULL,
	ID_CRITERIO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE CONTATO
(
	ID BIGSERIAL NOT NULL,
	CPF VARCHAR(11),
	NOME VARCHAR(100) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	NUMERO VARCHAR(50),
	COMPLEMENTO VARCHAR(50),
	EMAIL VARCHAR(50),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CONTATO_HISTORICO_STATUS_CONTATO
(
	ID_CONTATO BIGINT NOT NULL,
	ID_HISTORICO_STATUS_CONTATO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE CONTATO_TELEFONE
(
	ID_CONTATO BIGINT NOT NULL,
	ID_TELEFONE BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE CONTA_ACESSO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	ATIVO BOOLEAN NOT NULL,
	TOKEN VARCHAR(36),
	ID_NIVEL BIGINT NOT NULL,
	TURNO VARCHAR(50),
	RAMAL VARCHAR(10),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE CRITERIO
(
	ID BIGSERIAL NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	ID_MUNICIPIO BIGINT NOT NULL,
	QUANTIDADE_DISTRIBUIR INT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DISTRIBUICAO_CONTATO
(
	ID BIGSERIAL NOT NULL,
	ID_CAMPANHA BIGINT NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	ID_CONTATO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DISTRIBUICAO_CONTATO_EVENTO_DISTRIBUICAO_CONTATO
(
	ID_DISTRIBUICAO_CONTATO BIGINT NOT NULL,
	ID_EVENTO_DISTRIBUICAO_CONTATO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE DISTRIBUICAO_CONTATO_EVENTO_TELEFONIA
(
	ID_DISTRIBUICAO_CONTATO BIGINT NOT NULL,
	ID_EVENTO_TELEFONIA BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE DOACAO
(
	ID BIGSERIAL NOT NULL,
	ID_DISTRIBUICAO_CONTATO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE DOACAO_VALOR_DETALHADO
(
	ID_DOACAO BIGINT NOT NULL,
	ID_VALOR_DETALHADO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE ESTADO
(
	ID BIGINT NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE EVENTO_DISTRIBUICAO_CONTATO
(
	ID BIGSERIAL NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	EVENTO VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE EVENTO_TELEFONIA
(
	ID BIGSERIAL NOT NULL,
	TIPO_EVENTO VARCHAR(50) NOT NULL,
	RAMAL VARCHAR(10) NOT NULL,
	DDD VARCHAR(2) NOT NULL,
	TELEFONE VARCHAR(9) NOT NULL,
	UNIQUEID VARCHAR(32) NOT NULL,
	DURACAO_LIGACAO INT NOT NULL,
	DATA_OCORRENCIA TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE HISTORICO_STATUS_CONTATO
(
	ID BIGSERIAL NOT NULL,
	ID_CONTA_ACESSO BIGINT NOT NULL,
	DATA_INICIAL_VIGENCIA TIMESTAMP NOT NULL,
	DATA_FINAL_VIGENCIA TIMESTAMP,
	STATUS VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE LOGRADOURO
(
	CEP VARCHAR(8) NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	ID_MUNICIPIO BIGINT NOT NULL,
	PRIMARY KEY (CEP)
) WITHOUT OIDS;


CREATE TABLE MUNICIPIO
(
	ID BIGINT NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	ID_ESTADO BIGINT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE NIVEL
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE NIVEL_PERMISSAO
(
	ID_NIVEL BIGINT NOT NULL,
	ID_PERMISSAO BIGINT NOT NULL
) WITHOUT OIDS;


CREATE TABLE PERMISSAO
(
	ID BIGSERIAL NOT NULL,
	DESCRICAO VARCHAR(100),
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE TELEFONE
(
	ID BIGSERIAL NOT NULL,
	DDD VARCHAR(2) NOT NULL,
	TELEFONE VARCHAR(9) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


CREATE TABLE VALOR_DETALHADO
(
	ID BIGSERIAL NOT NULL,
	METODO VARCHAR(50) NOT NULL,
	TIPO_RETIRADA VARCHAR(50) NOT NULL,
	VALOR DECIMAL NOT NULL,
	DATA_HORA_EFETUACAO TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE CAMPANHA_ALOCACAO_OPERADOR
	ADD FOREIGN KEY (ID_ALOCACAO_OPERADOR)
	REFERENCES ALOCACAO_OPERADOR (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CAMPANHA_ALOCACAO_OPERADOR
	ADD FOREIGN KEY (ID_CAMPANHA)
	REFERENCES CAMPANHA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CAMPANHA_CRITERIO
	ADD FOREIGN KEY (ID_CAMPANHA)
	REFERENCES CAMPANHA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DISTRIBUICAO_CONTATO
	ADD FOREIGN KEY (ID_CAMPANHA)
	REFERENCES CAMPANHA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTATO_HISTORICO_STATUS_CONTATO
	ADD FOREIGN KEY (ID_CONTATO)
	REFERENCES CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTATO_TELEFONE
	ADD FOREIGN KEY (ID_CONTATO)
	REFERENCES CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DISTRIBUICAO_CONTATO
	ADD FOREIGN KEY (ID_CONTATO)
	REFERENCES CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ALOCACAO_OPERADOR
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DISTRIBUICAO_CONTATO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EVENTO_DISTRIBUICAO_CONTATO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HISTORICO_STATUS_CONTATO
	ADD FOREIGN KEY (ID_CONTA_ACESSO)
	REFERENCES CONTA_ACESSO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CAMPANHA_CRITERIO
	ADD FOREIGN KEY (ID_CRITERIO)
	REFERENCES CRITERIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DISTRIBUICAO_CONTATO_EVENTO_DISTRIBUICAO_CONTATO
	ADD FOREIGN KEY (ID_DISTRIBUICAO_CONTATO)
	REFERENCES DISTRIBUICAO_CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DISTRIBUICAO_CONTATO_EVENTO_TELEFONIA
	ADD FOREIGN KEY (ID_DISTRIBUICAO_CONTATO)
	REFERENCES DISTRIBUICAO_CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DOACAO
	ADD FOREIGN KEY (ID_DISTRIBUICAO_CONTATO)
	REFERENCES DISTRIBUICAO_CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DOACAO_VALOR_DETALHADO
	ADD FOREIGN KEY (ID_DOACAO)
	REFERENCES DOACAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MUNICIPIO
	ADD FOREIGN KEY (ID_ESTADO)
	REFERENCES ESTADO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DISTRIBUICAO_CONTATO_EVENTO_DISTRIBUICAO_CONTATO
	ADD FOREIGN KEY (ID_EVENTO_DISTRIBUICAO_CONTATO)
	REFERENCES EVENTO_DISTRIBUICAO_CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DISTRIBUICAO_CONTATO_EVENTO_TELEFONIA
	ADD FOREIGN KEY (ID_EVENTO_TELEFONIA)
	REFERENCES EVENTO_TELEFONIA (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTATO_HISTORICO_STATUS_CONTATO
	ADD FOREIGN KEY (ID_HISTORICO_STATUS_CONTATO)
	REFERENCES HISTORICO_STATUS_CONTATO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTATO
	ADD FOREIGN KEY (CEP)
	REFERENCES LOGRADOURO (CEP)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CRITERIO
	ADD FOREIGN KEY (ID_MUNICIPIO)
	REFERENCES MUNICIPIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOGRADOURO
	ADD FOREIGN KEY (ID_MUNICIPIO)
	REFERENCES MUNICIPIO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTA_ACESSO
	ADD FOREIGN KEY (ID_NIVEL)
	REFERENCES NIVEL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE NIVEL_PERMISSAO
	ADD FOREIGN KEY (ID_NIVEL)
	REFERENCES NIVEL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE NIVEL_PERMISSAO
	ADD FOREIGN KEY (ID_PERMISSAO)
	REFERENCES PERMISSAO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONTATO_TELEFONE
	ADD FOREIGN KEY (ID_TELEFONE)
	REFERENCES TELEFONE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DOACAO_VALOR_DETALHADO
	ADD FOREIGN KEY (ID_VALOR_DETALHADO)
	REFERENCES VALOR_DETALHADO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



