insert into parentesco(descricao)values('Pai');
insert into parentesco(descricao)values('Mãe');
insert into parentesco(descricao)values('Pai Adotivo');
insert into parentesco(descricao)values('Mãe Adotiva');
insert into parentesco(descricao)values('Irmão');
insert into parentesco(descricao)values('Irmã');
insert into parentesco(descricao)values('Avô');
insert into parentesco(descricao)values('Avó');
insert into parentesco(descricao)values('Tio');
insert into parentesco(descricao)values('Tia');
insert into parentesco(descricao)values('Primo');
insert into parentesco(descricao)values('Prima');
insert into parentesco(descricao)values('Cônjuge');
insert into parentesco(descricao)values('Filho');
insert into parentesco(descricao)values('Filha');
insert into parentesco(descricao)values('Outro');