insert into diretoria_ensino(nome)values('Região Centro');
insert into diretoria_ensino(nome)values('Região Centro Oeste');
insert into diretoria_ensino(nome)values('Região Centro Sul');
insert into diretoria_ensino(nome)values('Região Leste 1'); 
insert into diretoria_ensino(nome)values('Região Leste 2'); 
insert into diretoria_ensino(nome)values('Região Leste 3'); 
insert into diretoria_ensino(nome)values('Região Leste 4'); 
insert into diretoria_ensino(nome)values('Região Leste 5'); 
insert into diretoria_ensino(nome)values('Região Norte 1'); 
insert into diretoria_ensino(nome)values('Região Norte 2'); 
insert into diretoria_ensino(nome)values('Região Sul 1'); 
insert into diretoria_ensino(nome)values('Região Sul 2'); 
insert into diretoria_ensino(nome)values('Região Sul 3'); 
insert into diretoria_ensino(nome)values('Região Caieiras'); 
insert into diretoria_ensino(nome)values('Região Carapicuíba'); 
insert into diretoria_ensino(nome)values('Região Diadema'); 
insert into diretoria_ensino(nome)values('Região Guarulhos Norte'); 
insert into diretoria_ensino(nome)values('Região Guarulhos Sul'); 
insert into diretoria_ensino(nome)values('Região Itapecerica Da Serra'); 
insert into diretoria_ensino(nome)values('Região Itapevi'); 
insert into diretoria_ensino(nome)values('Região Itaquaquecetuba'); 
insert into diretoria_ensino(nome)values('Região Mauá'); 
insert into diretoria_ensino(nome)values('Região Mogi Das Cruzes'); 
insert into diretoria_ensino(nome)values('Região Osasco'); 
insert into diretoria_ensino(nome)values('Região Santo André'); 
insert into diretoria_ensino(nome)values('Região São Bernardo Do Campo');
insert into diretoria_ensino(nome)values('Região Suzano'); 
insert into diretoria_ensino(nome)values('Região Taboão Da Serra'); 
insert into diretoria_ensino(nome)values('Região Adamantina'); 
insert into diretoria_ensino(nome)values('Região Americana'); 
insert into diretoria_ensino(nome)values('Região Andradina'); 
insert into diretoria_ensino(nome)values('Região Apiaí'); 
insert into diretoria_ensino(nome)values('Região Araçatuba'); 
insert into diretoria_ensino(nome)values('Região Araraquara'); 
insert into diretoria_ensino(nome)values('Região Assis'); 
insert into diretoria_ensino(nome)values('Região Barretos'); 
insert into diretoria_ensino(nome)values('Região Bauru'); 
insert into diretoria_ensino(nome)values('Região Birigui'); 
insert into diretoria_ensino(nome)values('Região Botucatu'); 
insert into diretoria_ensino(nome)values('Região Bragança'); 
insert into diretoria_ensino(nome)values('Região Campinas Leste'); 
insert into diretoria_ensino(nome)values('Região Campinas'); 
insert into diretoria_ensino(nome)values('Região Capivari'); 
insert into diretoria_ensino(nome)values('Região Caraguatatuba');
insert into diretoria_ensino(nome)values('Região Catanduva'); 
insert into diretoria_ensino(nome)values('Região Fernandópolis'); 
insert into diretoria_ensino(nome)values('Região Franca'); 
insert into diretoria_ensino(nome)values('Região Guaratinguetá'); 
insert into diretoria_ensino(nome)values('Região Itapetininga'); 
insert into diretoria_ensino(nome)values('Região Itapeva'); 
insert into diretoria_ensino(nome)values('Região Itararé'); 
insert into diretoria_ensino(nome)values('Região Itu'); 
insert into diretoria_ensino(nome)values('Região Jaboticabal'); 
insert into diretoria_ensino(nome)values('Região Jacareí'); 
insert into diretoria_ensino(nome)values('Região Jales'); 
insert into diretoria_ensino(nome)values('Região Jaú'); 
insert into diretoria_ensino(nome)values('Região José Bonifácio'); 
insert into diretoria_ensino(nome)values('Região Jundiaí'); 
insert into diretoria_ensino(nome)values('Região Limeira'); 
insert into diretoria_ensino(nome)values('Região Lins'); 
insert into diretoria_ensino(nome)values('Região Marília'); 
insert into diretoria_ensino(nome)values('Região Miracatu'); 
insert into diretoria_ensino(nome)values('Região Mirante Do Paranapanema'); 
insert into diretoria_ensino(nome)values('Região Mogi Mirim'); 
insert into diretoria_ensino(nome)values('Região Ourinhos'); 
insert into diretoria_ensino(nome)values('Região Pindamonhangaba'); 
insert into diretoria_ensino(nome)values('Região Piracicaba'); 
insert into diretoria_ensino(nome)values('Região Piraju'); 
insert into diretoria_ensino(nome)values('Região Pirassununga'); 
insert into diretoria_ensino(nome)values('Região Presidente Prudente'); 
insert into diretoria_ensino(nome)values('Região Registro'); 
insert into diretoria_ensino(nome)values('Região Ribeirão Preto');