insert into nome_grupo(id, nome)values(1, 'G00');
insert into nome_grupo(id, nome)values(2, 'G02');
insert into nome_grupo(id, nome)values(3, 'G04');
insert into nome_grupo(id, nome)values(4, 'G07');
insert into nome_grupo(id, nome)values(5, 'G10');
insert into nome_grupo(id, nome)values(6, 'GJ01');
insert into nome_grupo(id, nome)values(7, 'GJ02');
insert into nome_grupo(id, nome)values(8, 'BV');
insert into nome_grupo(id, nome)values(9, 'BR');
insert into nome_grupo(id, nome)values(10,'INFO');
insert into nome_grupo(id, nome)values(11,'CR');
insert into nome_grupo(id, nome)values(12,'MBR');
insert into nome_grupo(id, nome)values(13,'OM');
insert into nome_grupo(id, nome)values(14,'SOR');
insert into nome_grupo(id, nome)values(15,'ART');
insert into nome_grupo(id, nome)values(16,'CORP');
insert into nome_grupo(id, nome)values(17,'OE');
insert into nome_grupo(id, nome)values(18,'AVFUN');
insert into nome_grupo(id, nome)values(19,'AVI');
insert into nome_grupo(id, nome)values(20,'AVOM');
insert into nome_grupo(id, nome)values(21,'AVPSS');
insert into nome_grupo(id, nome)values(22,'CAMT');
insert into nome_grupo(id, nome)values(23,'MASS');
insert into nome_grupo(id, nome)values(24,'TLMKT');
insert into nome_grupo(id, nome)values(25,'CL');
insert into nome_grupo(id, nome)values(26,'AEEF');
insert into nome_grupo(id, nome)values(27,'BVF');
insert into nome_grupo(id, nome)values(28,'BRF');
insert into nome_grupo(id, nome)values(29,'OMF');
insert into nome_grupo(id, nome)values(30,'SORF');
insert into nome_grupo(id, nome)values(31,'SSF');
insert into nome_grupo(id, nome)values(32,'PSSF');
insert into nome_grupo(id, nome)values(33,'PSCF');
insert into nome_grupo(id, nome)values(34,'CLF');
insert into nome_grupo(id, nome)values(35,'ARTF');
insert into nome_grupo(id, nome)values(36,'CORPF');
insert into nome_grupo(id, nome)values(37,'FAM');
insert into nome_grupo(id, nome)values(38,'SS');
insert into nome_grupo(id, nome)values(39,'PSS');
insert into nome_grupo(id, nome)values(40,'PSC');
insert into nome_grupo(id, nome)values(41,'AVOFT');
insert into nome_grupo(id, nome)values(42,'OFT');
insert into nome_grupo(id, nome)values(43,'AVORT');
insert into nome_grupo(id, nome)values(44,'ORT');


insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(1, 1);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(1, 2);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(1, 3);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(1, 4);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(1, 5);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(1, 6);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(1, 7);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(2, 8);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(3, 9);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(4, 10);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(5, 11);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(6, 12);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(7, 13);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(8, 14);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(9, 15);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(15, 16);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(16, 17);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(17, 18);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(18, 19);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(19, 20);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(20, 21);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(21, 22);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(22, 23);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(23, 24);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(24, 25);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(25, 26);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(26, 27);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(27, 28);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(28, 29);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(29, 30);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(30, 31);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(31, 32);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(32, 33);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(33, 34);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(34, 35);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(35, 36);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(36, 37);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(37, 38);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(38, 39);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(39, 40);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(40, 41);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(41, 42);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(42, 43);
insert into descricao_tipo_atendimento_nome_grupo(id_descricao_tipo_atendimento, id_nome_grupo)values(43, 44);