insert into local_atendimento(nome)values('AEE Arte e Cultura I');
insert into local_atendimento(nome)values('AEE Arte e Cultura II');
insert into local_atendimento(nome)values('AEE Braille e Soroban');
insert into local_atendimento(nome)values('AEE I');
insert into local_atendimento(nome)values('AEE II');
insert into local_atendimento(nome)values('AEE III');
insert into local_atendimento(nome)values('AEE Informática I');
insert into local_atendimento(nome)values('AEE Informática II');
insert into local_atendimento(nome)values('AEE IV');
insert into local_atendimento(nome)values('AEE OM I');
insert into local_atendimento(nome)values('AEE OM II');
insert into local_atendimento(nome)values('AEE OM III');
insert into local_atendimento(nome)values('AEE V');
insert into local_atendimento(nome)values('AEE VI');
insert into local_atendimento(nome)values('Ateliê de Artes Plásticas');
insert into local_atendimento(nome)values('Auditório');
insert into local_atendimento(nome)values('Avaliação I');
insert into local_atendimento(nome)values('Avaliação II');
insert into local_atendimento(nome)values('Brinquedoteca');
insert into local_atendimento(nome)values('Cantinho da Leitura');
insert into local_atendimento(nome)values('Casinha de AVA');
insert into local_atendimento(nome)values('Centro de Estudos');
insert into local_atendimento(nome)values('Centro de Recursos');
insert into local_atendimento(nome)values('Cinema');
insert into local_atendimento(nome)values('Coordenação Proceja');
insert into local_atendimento(nome)values('CTA');
insert into local_atendimento(nome)values('Espaço de Convivência');
insert into local_atendimento(nome)values('Externo');
insert into local_atendimento(nome)values('Laraparque');
insert into local_atendimento(nome)values('Metrô');
insert into local_atendimento(nome)values('Oftalmologia I');
insert into local_atendimento(nome)values('Oftalmologia II');
insert into local_atendimento(nome)values('Ortoptica I');
insert into local_atendimento(nome)values('Ortoptica II');
insert into local_atendimento(nome)values('Outros');
insert into local_atendimento(nome)values('Parque');
insert into local_atendimento(nome)values('Piscina');
insert into local_atendimento(nome)values('Psicologia I');
insert into local_atendimento(nome)values('Psicologia II');
insert into local_atendimento(nome)values('Sala de Apoio I');
insert into local_atendimento(nome)values('Sala de Apoio II');
insert into local_atendimento(nome)values('Sala de apoio III');
insert into local_atendimento(nome)values('Sala de Apoio IV');
insert into local_atendimento(nome)values('Sala de Apoio VI');
insert into local_atendimento(nome)values('Sala de aula');
insert into local_atendimento(nome)values('Sala de reunião 3º andar');
insert into local_atendimento(nome)values('Sala de reunião Proceja');
insert into local_atendimento(nome)values('Secretaria');
insert into local_atendimento(nome)values('Serviço Social I');
insert into local_atendimento(nome)values('Serviço Social II');
insert into local_atendimento(nome)values('Teatro');
insert into local_atendimento(nome)values('Trilha sensorial');