package br.laramara.ti.sislaraserver.dominio.solicitacao;

public enum FinalidadeRelatorio {
	ISENCAO_DE_IPI_NA_COMPRA_DE_CARRO,
	LIBERACAO_DE_FGTS_PARA_COMPRA_DE_RECURSOS,
	PRESTACAO_DE_SERVICO_MILITAR, 
	TITULO_DE_ELEITOR,
	INTERDICAO,
	VESTIBULAR,
	ESCOLA, 
	ATESTADO, 
	INSS, 
	LOAS, 
	CRAS,
	OUTRA_FINALIDADE, 
	OUTRO_PROFISSIONAL, 
	CONCURSOS_E_COTAS, 
	PROCESSO_SELETIVO_E_TRABALHO,
	CET, 
	EMTU, 
	RODIZIO, 
	SPTRANS
}
